### ISSUE TITLE
获取黑名单失败，执行异常，已清空黑名单

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#1]
个人—设置—屏蔽设置—管理黑名单

知乎 6.52.0(2548)
surge 4.10.0(Build 1797)

**Comment by blackmatrix7** [comment]
> 个人—设置—屏蔽设置—管理黑名单
> 
> 知乎 6.52.0(2548)
> surge 4.10.0(Build 1797)

方便提供下运行日志吗？看看出错信息。

**Comment by fiiir** [comment]
> > 个人—设置—屏蔽设置—管理黑名单
> > 
> > 知乎 6.52.0(2548)
> > surge 4.10.0(Build 1797)
> 
> 方便提供下运行日志吗？看看出错信息。


2020-08-18 22:17:24.029710 <NOTIFY> [SGJSVM] [知乎_获取黑名单]
22:17:24.020160 [INFO] [知乎增强]
获取黑名单失败，异常信息：TypeError: null is not an object (evaluating 'data[session] = val')

**Comment by blackmatrix7** [comment]
> > > 个人—设置—屏蔽设置—管理黑名单
> > > 知乎 6.52.0(2548)
> > > surge 4.10.0(Build 1797)
> > 
> > 
> > 方便提供下运行日志吗？看看出错信息。
> 
> 2020-08-18 22:17:24.029710 [SGJSVM] [知乎_获取黑名单]
> 22:17:24.020160 [INFO] [知乎增强]
> 获取黑名单失败，异常信息：TypeError: null is not an object (evaluating 'data[session] = val')

已更新，你再试试。如果没问题麻烦告知一下。

**Comment by fiiir** [comment]
更新脚本后，“获取脚本黑名单结束，当前黑名单共6人”
推荐里翻了大概一百行找不到“知乎盐选会员”的回答，脚本应该是正常工作

**Comment by blackmatrix7** [comment]
> 更新脚本后，“获取脚本黑名单结束，当前黑名单共6人”
> 推荐里翻了大概一百行找不到“知乎盐选会员”的回答，脚本应该是正常工作

那就好，感谢反馈。
