### ISSUE TITLE
请问知乎回答中的购物链接，有意向去掉吗？

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#10]
苹果开完发布会，还有ios 14正式版推送。
导致这几天苹果很多问题下面的回答，各种塞购物链接！
更离谱的是：刚才刷到一个美队漏鸟相关的问题，回答里居然有推荐内裤的……

https://www.zhihu.com/question/421207063/answer/1477248974

**Comment by blackmatrix7** [comment]
这种都是作者自行加入的推广链接，如果直接去掉的话，可能会造成上下文衔接不畅。
