### ISSUE TITLE
发现AdvertisingTest存在的一些问题

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#100]
1、AdvertisingTest_MITM.sgmodule
这个模块中存在大量相同重复的域名，猜测是因为没去重？

2、AdvertisingTest.list
URL-REGEX,^https?:\/\/yxyapi\d\.drcuiyutao\.com\/yxy-api-gateway\/api\/json\/advert\/
上面这条规则在AdvertisingTest_MITM.sgmodule中对应的域名是yxyapi.drcuiyutao.com，没有考虑到URL-REGEX中“\d”的匹配
这条是无意间发现的，不确定list中的其他URL-REGEX是否存在相同情况

**Comment by blackmatrix7** [comment]
感谢帮忙找问题。
第一个的确是忘了去重。
第二个这个纯属是程序算法推导的，没仔细看过，的确是会有些错误，需要人工再去校验，目前已经手动介入修复。
上面两个都处理完了，现在已经完全托管在服务器上定时生成，大概明天凌晨3点半左右重新生成一次应该就没问题了。
