### ISSUE TITLE
ChinaMax.list 和 Proxy.list 文件内的一些错误

### ISSUE THREAD

**Issue by DustinWin** [blackmatrix7/ios_rule_script#1001]
# [ChinaMax.list](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/ChinaMax/ChinaMax.list) 错误：
## 原内容：
`DOMAIN-KEYWORD,.tmall.com`  
## 需修改为：
`DOMAIN-KEYWORD,tmall`  

# [Proxy.list](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Proxy/Proxy.list) 错误：
## 原内容：
```
DOMAIN-SUFFIX,14.102.250.18
DOMAIN-SUFFIX,14.102.250.19
DOMAIN-SUFFIX,174.142.105.153
DOMAIN-SUFFIX,67.220.91.15
DOMAIN-SUFFIX,67.220.91.18
DOMAIN-SUFFIX,67.220.91.23
DOMAIN-SUFFIX,69.65.19.160
DOMAIN-SUFFIX,72.52.81.22
```
## 需修改为：
```
IP-CIDR,14.102.250.18,no-resolve
IP-CIDR,14.102.250.19,no-resolve
IP-CIDR,174.142.105.153,no-resolve
IP-CIDR,67.220.91.15,no-resolve
IP-CIDR,67.220.91.18,no-resolve
IP-CIDR,67.220.91.23,no-resolve
IP-CIDR,69.65.19.160,no-resolve
IP-CIDR,72.52.81.22,no-resolve
```

**Comment by blackmatrix7** [comment]
DOMAIN-KEYWORD,.tmall.com 没有修改，因为DOMAIN-KEYWORD,tmall范围太大了，容易误判。

IP-CIDR类型的规则已处理。

**Comment by DustinWin** [comment]
> DOMAIN-KEYWORD,.tmall.com 没有修改，因为DOMAIN-KEYWORD,tmall范围太大了，容易误判。
> 
> IP-CIDR类型的规则已处理。

感谢，一直用您的规则！
