### ISSUE TITLE
Jetbrains AI 规则添加 

### ISSUE THREAD

**Issue by ryan961** [blackmatrix7/ios_rule_script#1005]
- DOMAIN-SUFFIX,grazie.ai

![image](https://github.com/blackmatrix7/ios_rule_script/assets/32825698/f4e5928d-b73f-4d12-b27c-b18cf7b9f0fb)

**Comment by blackmatrix7** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Jetbrains/Jetbrains.list


已加入
