### ISSUE TITLE
添加宜家中国域名至China规则解决访问缓慢问题

### ISSUE THREAD

**Issue by Xm798** [blackmatrix7/ios_rule_script#1007]
规则名称：
- ChinaMaxNoIP
- ChinaMaxNoMedia 
- ChinaNoMedia 
- ChinaMax 
- China_Domain

问题描述：
宜家中国访问缓慢/失败

调整方案：(你希望规则做哪些调整，及其原因。)
添加宜家中国域名 `ikea.cn` 至大陆域名规则中，解决访问缓慢问题。

**Comment by blackmatrix7** [comment]
谢谢补充，已添加，预计明天凌晨更新。
