### ISSUE TITLE
求更新下联通的，我客服端已经升级好几次了，获取不到cookie

### ISSUE THREAD

**Issue by 1ninty2** [blackmatrix7/ios_rule_script#101]
天天抽奖链接点进去空白页面

**Comment by blackmatrix7** [comment]
你试试从配置文件中将联通签到的相关脚本去除，看看是不是还是空白页面？
如果还是空白页面，可能被你的去广告规则给拦截了。

**Comment by blackmatrix7** [comment]
![image](https://user-images.githubusercontent.com/27717518/101886897-1fa75700-3bd7-11eb-8674-8d828a6a5013.jpeg)

我试了下是可以获取到cookie的，你看下是不是被去广告规则拦截了。

**Comment by 1ninty2** [comment]
好像并不是，我把重写禁用之后就能打开了

**Comment by blackmatrix7** [comment]
你把你使用的App和版本，还有联通的App版本，及无法打开时的日志发上来看下吧。

**Comment by 1ninty2** [comment]
用的是quanx V1.0.17-build452，联通的版本是V8.0.3应该是最新版。我quanx的日志只能看到task的运行

**Comment by blackmatrix7** [comment]
![image](https://user-images.githubusercontent.com/27717518/101891497-13be9380-3bdd-11eb-95a5-fad0a7fa57b3.jpeg)

![image](https://user-images.githubusercontent.com/27717518/101891535-22a54600-3bdd-11eb-80d3-ff68530f2819.jpeg)

QuanX试了下，搭配手机营业厅最新版，也是可以获取到Cookie的，并且有对应日志。

如果你复写成功触发，即使出错也应有异常体质，你再仔细看看，否则难判断问题。

**Comment by blackmatrix7** [comment]
我看了下代码，这个是我比较早写的，没有异常捕获，晚些我加个try catch，把异常输出出来，你再看看日志。

**Comment by 1ninty2** [comment]
页面空白应该不会触发重写吧，我看日志没东西更新。

**Comment by blackmatrix7** [comment]
> 页面空白应该不会触发重写吧，我看日志没东西更新。

增加了异常日志记录，你再试试吧。

**Comment by 1ninty2** [comment]
还是获取不了，[ERROR] [中国联通]
获取联通手机营业厅Cookie出现异常，异常信息：TypeError: null is not an object (evaluating '/c_mobile=([0-9]{11})/.exec(cookie)[1]')
我是直接在主页搜索的天天抽奖

**Comment by blackmatrix7** [comment]
这个事情比较奇怪，我更新到最新版的手机营业厅，抓了几次包，都是能够正常匹配正则的。

不知道会不会和手机号码归属地有关系，你如果方便的话，自己抓个包，把请求头的内容【脱敏】之后发给我看看。

**Comment by r0ckmifan** [comment]
我也出现了，前几天的时候已经获取了cookie但是运行脚本到时候显示签到异常，后面重新获取一次cookie就好了，今天task运行了又出现签到异常，然后尝试重新获取cookie后就出现下面日志了。

[ERROR] [中国联通]
获取联通手机营业厅Cookie出现异常，异常信息：TypeError: null is not an object (evaluating '/c_mobile=([0-9]{11})/.exec(cookie)[1]')

**Comment by blackmatrix7** [comment]
现在的情况是，不同地区的手机号码可能Cookie不太一样，比如对我来说c_mobile就是存在的。
不清楚这种情况的范围有多大，我更新了一个版本，增加一些获取手机号码的正则匹配，你试试。

**Comment by r0ckmifan** [comment]
我更新试了，还是一样，不知道有没有办法手动清除这个cookie，然后再获取试试。

**Comment by blackmatrix7** [comment]
> 我更新试了，还是一样，不知道有没有办法手动清除这个cookie，然后再获取试试。

异常日志发我看下

**Comment by r0ckmifan** [comment]
> > 我更新试了，还是一样，不知道有没有办法手动清除这个cookie，然后再获取试试。
> 
> 
> 
> 异常日志发我看下

[ERROR] [中国联通]
获取联通手机营业厅Cookie出现异常，异常信息：TypeError: null is not an object (evaluating '/c_mobile=([0-9]{11})/.exec(cookie)[1]')

**Comment by blackmatrix7** [comment]
> > > 我更新试了，还是一样，不知道有没有办法手动清除这个cookie，然后再获取试试。
> > 
> > 
> > 异常日志发我看下
> 
> 还是一样
> [ERROR] [中国联通]
> 获取联通手机营业厅Cookie出现异常，异常信息：TypeError: null is not an object (evaluating '/c_mobile=([0-9]{11})/.exec(cookie)[1]')

你没更新成功，这段代码已经不存在了……

  // 获取手机号
  let mobile01 = /c_mobile=(\d{11})/.exec(cookie);
  let mobile02 = /u_account=(\d{11})/.exec(cookie);
  let mobile03 = /desmobile==(\d{11})/.exec(magicJS.request.headers['Referer']);

你看下脚本中获取手机号的部分应该是这样的

**Comment by r0ckmifan** [comment]
![image](https://user-images.githubusercontent.com/74949306/102371376-15cb8c80-3ff9-11eb-8ee7-46d9d94e9e67.jpeg)
可以了，谢谢大佬😃

**Comment by r0ckmifan** [comment]
不知道为什么还是出现了异常
[INFO] [中国联通]
签到与抽奖执行完毕！
2020/12/17 00:15:23:392  <console>    [JS Console]: [NOTIFY] [中国联通]
title:中国联通 签到异常，连续签到?天
subTitle:
body:美团外卖优惠券：领取成功
第1次抽奖：10MB流量
第2次抽奖：谢谢参与~
第3次抽奖：谢谢参与~
第4次抽奖：2MB
options:{"open-url":""}
2020/12/17 00:15:23:393  <error>      [QTXNotificationManager] <media> Unsupported URL for option open-url.

**Comment by r0ckmifan** [comment]
零点签到已经，原来的系统在升级。
