### ISSUE TITLE
Advertising规则补充

### ISSUE THREAD

**Issue by svngxr** [blackmatrix7/ios_rule_script#1011]
PotPlayer数据收集的域名补充
  - DOMAIN, p1-play.edge4k.com, REJECT
  - DOMAIN, p1-play.kgslb.com, REJECT
  - DOMAIN, p2-play.edge4k.com, REJECT
  - DOMAIN, play.kakao.com, REJECT

启动和关闭PotPlayer时可以复现
[https://gist.githubusercontent.com/avin/66fc4cd337e35647cfa842e2b8d40700/raw/756a9f15f14d2dd59d390d67b1ec25dac46ea435/pot-player-block-ads.txt](https://gist.githubusercontent.com/avin/66fc4cd337e35647cfa842e2b8d40700/raw/756a9f15f14d2dd59d390d67b1ec25dac46ea435/pot-player-block-ads.txt)

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
