### ISSUE TITLE
gw.alicdn reject 后导致饿了么图片无法加载

### ISSUE THREAD

**Issue by CY-Christin** [blackmatrix7/ios_rule_script#1012]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：
AllInOne_Mock.sgmodule
APP版本：
饿了么 11.2.8
客户端名称：
Surge
客户端版本：
5.6.0
问题描述：
饿了么图片地址如下
https://gw.alicdn.com/imgextra/i4/2214693827757/O1CN01A14IwC27Al8pJNLd3_!!2214693827757-2-koubei.png
https://gw.alicdn.com/imgextra/i1/O1CN012FqkbR23g7jvrJjwX_!!6000000007284-2-tps-60-60.png_90x90q90.jpg_.webp
开启 AllInOne surgemodule 后图片无法加载，日志中显示会一直显示活跃，有的会直接显示失败，有的会持续连接 2 分钟以上还无法请求成功，关闭次模块后即可正常加载图片。
复现方式：

1. 切换到空白配置文件
2. 安装并应用此模块
3. 打开饿了么，清空图片缓存后再次打开即可看到图片一直无法加载，在 surge 最近请求中也能看到图片请求的情况。
4. 关闭此模块再次重复步骤 3 即可看到图片能正常请求。

已使用空白配置文件验证：是，已经试用空白文件做对照实验。

**Comment by CY-Christin** [comment]
不好意思应该不是正则的问题，才想明白如果是正则的原因的话会直接显示 reject，但是确实是这个模块里面的问题。我目前的解决方法是在 mitm 中再写一个 gw.alicdn.com，并禁用掉，此时再应用模块也可以正常加载图片。

**Comment by blackmatrix7** [comment]
我更新到饿了么最新版本，用空白文件，只加载这个模块，在两台手机上都没有复现这个问题。

通过浏览器直接打开上方的链接也是正常的。

因为饿了么我自己也在用，长期使用一直没发现有问题。

如果还存在问题，可以提供进一步的资料方便排查，谢谢。
