### ISSUE TITLE
花小猪打车价格导致显示网络错误

### ISSUE THREAD

**Issue by MittWillson** [blackmatrix7/ios_rule_script#1013]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：All-In-One 和 Advertising

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/14b523e8d79d7a993138d540a7515e54084be713/rewrite/Shadowrocket/AllInOne/AllInOne.sgmodule#L54

异常规则：^https:\/\/api\.hongyibo\.com\.cn - reject-dict

问题描述：花小猪打车时价格查询走了这个API地址，导致显示(网络错误/价格获取失败)而无法打车，微信小程序

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

去除该规则/优化规则细节匹配

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
