### ISSUE TITLE
surge domain-set是不支持eTLD suffix的

### ISSUE THREAD

**Issue by kid-oh** [blackmatrix7/ios_rule_script#1015]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：ChinaMaxNoIP_Domain

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/ChinaMaxNoIP/ChinaMaxNoIP_Domain.list

异常规则：.cn

问题描述：进行规则测试时发现sinaimg.cn不能匹配

抓包截图：(相关抓包工具的截图。)

调整方案：修改至rule-set部分中

**Comment by kid-oh** [comment]
查了一下surge官方文档，似乎是.cn不支持DOMAIN-SET，可能需要使用RULE-SET。官方文档说明如下：

DOMAIN-SET

Designed for a large number of domain names, supports fast search for thousands of records. Each line in the file is a domain name if a line begins with . matches all sub-domains and the domain name itself. This can be used for ad filtering.

The DOMAIN-SET rule doesn't support including an eTLD suffix due to performance optimization.

For example: .github.io won't match example.github.io

Here is the full eTLD list: https://publicsuffix.org/list/

Please use RULE-SET instead if you want to use eTLD as a suffix.

**Comment by blackmatrix7** [comment]
谢谢反馈，针对Surge部分已调整，稍后会进行更新。

其他客户端尚未修改。
