### ISSUE TITLE
Game Riot 规则中缺少相关域名

### ISSUE THREAD

**Issue by ingoosey** [blackmatrix7/ios_rule_script#1017]
规则名称：Riot.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Riot/Riot.list

异常规则：riotgames.zendesk.com 未包含在 Roit.list 规则中

问题描述：Roit.list 中未包含 riotgames.zendesk.com 域名

抓包截图：(相关抓包工具的截图。)
<img width="893" alt="截屏2023-09-11 10 20 05" src="https://github.com/blackmatrix7/ios_rule_script/assets/48196021/5a311307-15f2-4afc-9094-4515f62958f0">

调整方案：在 Riot、Game等相关规则中添加 riotgames.zendesk.com 域名

**Comment by blackmatrix7** [comment]
谢谢反馈，已补充，稍后更新。
