### ISSUE TITLE
Proxy规则中缺少了steam的数据

### ISSUE THREAD

**Issue by EndDream** [blackmatrix7/ios_rule_script#1019]
规则名称：Proxy

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Proxy

异常规则：

问题描述：来自数据上游之一的acl4ssr的ProxyGFWlist规则内包含了steam的部分被墙规则，但是本项目并未收录

抓包截图：(相关抓包工具的截图。)
# Steam
DOMAIN-SUFFIX,fanatical.com
DOMAIN-SUFFIX,humblebundle.com
DOMAIN-SUFFIX,underlords.com
DOMAIN-SUFFIX,valvesoftware.com
DOMAIN-SUFFIX,playartifact.com
DOMAIN-SUFFIX,steam-chat.com
DOMAIN-SUFFIX,steamcommunity.com
DOMAIN-SUFFIX,steamgames.com
DOMAIN-SUFFIX,steampowered.com
DOMAIN-SUFFIX,steamserver.net
DOMAIN-SUFFIX,steamstatic.com
DOMAIN-SUFFIX,steamstat.us
DOMAIN,steambroadcast.akamaized.net
DOMAIN,steamcommunity-a.akamaihd.net
DOMAIN,steamstore-a.akamaihd.net
DOMAIN,steamusercontent-a.akamaihd.net
DOMAIN,steamuserimages-a.akamaihd.net
DOMAIN,steampipe.akamaized.net

调整方案：希望可以收录进Proxy列表中

**Comment by blackmatrix7** [comment]
这是有意进行移除的，建议搭配steam规则使用
