### ISSUE TITLE
webnovel 的归类

### ISSUE THREAD

**Issue by ChellyL** [blackmatrix7/ios_rule_script#1021]
规则名称：China_Domain.txt 、Tencent.list 等

异常规则：webnovel.com

问题描述：webnovel.com 不为中国ip提供服务，将之归为China domain是不是有点不恰当？

抓包截图：暂无

调整方案：是否应该将其移到global media之类的分类中？

**Comment by blackmatrix7** [comment]
谢谢反馈，已调整，稍后更新。
