### ISSUE TITLE
+.easebar.com包含的一些子域名用在了暴雪的战网国际服

### ISSUE THREAD

**Issue by malagebidi** [blackmatrix7/ios_rule_script#1023]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

脚本名称：ChinaMax_Domain_For_Clash.txt

客户端名称：ClashMetaForAndroid 2.8.9

问题描述：+.easebar.com默认走了GeoSite(cn)这条规则，导致暗黑破坏神不朽安卓版本无法登录，

抓包内容：
```
Info: [TCP] 127.0.0.1:41830 --> unisdk.proxima.nie.easebar.com:443 match GeoSite(cn) using DIRECT
Info: [TCP] 127.0.0.1:41836 --> who.nie.easebar.com:443 match GeoSite(cn) using DIRECT
Info: [TCP] 127.0.0.1:41832 --> g0.gsf.easebar.com:443 match GeoSite(cn) using DIRECT
Info: [TCP] 127.0.0.1:41838 --> data-detect.nie.easebar.com:443 match GeoSite(cn) using DIRECT
```

截图：
![微信图片_20230915004438](https://github.com/blackmatrix7/ios_rule_script/assets/726456/b5a432cb-7668-4d4c-b409-11063d98f1eb)

调整方案：移除。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后进行更新。
