### ISSUE TITLE
高德地图无法搜索

### ISSUE THREAD

**Issue by orochislm10** [blackmatrix7/ios_rule_script#1024]
脚本名称：Advertising, AdvertisingLite,allinone

APP版本：13.01.0.2026

客户端名称：Quantumult X

客户端版本：Quantumult X 1.4.0-809

问题描述：
搜索地址无法搜索

![image](https://github.com/blackmatrix7/ios_rule_script/assets/70789060/2fa04aee-3a12-40dc-9d8b-2f11f1ad2a27)

**Comment by orochislm10** [comment]
三个重写#out=amap就可以搜索了，不知道具体哪个重写出问题

**Comment by orochislm10** [comment]
^https?://m\d\.amap\.com/ws/shield/(scene/recommend|search/new_hotword)? url reject-dict
排除本重写可以解决搜索不了的问题

**Comment by morooi** [comment]
遇到了+1，暂时通过 #out=amap 解决（QX）

**Comment by killsting** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf

高德同无法搜索，一度以为自己手机坏了。希望可以删除高德地图的规则。

**Comment by killsting** [comment]
> 遇到了+1，暂时通过 #out=amap 解决（QX）

谢谢，可行。

**Comment by blackmatrix7** [comment]
测试了几个版本，包含当前的最新版本，都无法复现此问题。

**Comment by lichenxxx** [comment]
> 测试了几个版本，包含当前的最新版本，都无法复现此问题。

Surge使用Advertising规则时，也会碰到高德地图无网络或者无法搜送的情况；开关surge后就正常了

**Comment by killsting** [comment]
> 测试了几个版本，包含当前的最新版本，都无法复现此问题。

试试搜索不是当前位置的地址，其他省份或者未曾到达过的地方。这个问题依旧还存在的。

**Comment by blackmatrix7** [comment]
尝试搜索其他城市依旧未复现问题。

不过鉴于多人反馈，还是将这条规则移除了。
