### ISSUE TITLE
rule/Surge/Advertising/Advertising.list 数据量过于庞大导致Surge爆内存重启

### ISSUE THREAD

**Issue by chouchoui** [blackmatrix7/ios_rule_script#1036]
规则名称：Advertising

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising.list

问题描述：9月28日的更新（Git SHA: da9a0be282415a538fee839a1ed41f805e92d398）导致Advertising.list加载了全部11万条规则，Surge更新引用后导致NE超过内存限制无限重启

<img width="1830" alt="Snipaste_2023-10-01_01-18-06" src="https://github.com/blackmatrix7/ios_rule_script/assets/14866249/240c89c5-05b4-47fb-b62b-9a26e79f8121">

**Comment by fovecifer** [comment]
遇到了同样的问题

**Comment by blackmatrix7** [comment]
应该是个Bug导致的，稍后会更新。

**Comment by blackmatrix7** [comment]
已修复
