### ISSUE TITLE
分流调整

### ISSUE THREAD

**Issue by xxb5656** [blackmatrix7/ios_rule_script#1037]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Global
规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Shadowrocket/Global
异常规则：
DOMAIN-SUFFIX,tesla.cn
问题描述：
目前特斯拉cn所有cdn都是国内ip，需要在Global中去除DOMAIN-SUFFIX,tesla.cn
，否则打开tesla app，tesla.cn会走代理导致加载延迟。
抓包截图：(相关抓包工具的截图。)
调整方案：(你希望规则做哪些调整，及其原因。)
去除DOMAIN-SUFFIX,tesla.cn

规则名称：
Global
规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Shadowrocket/Global
异常规则：
DOMAIN-KEYWORD,duolingo
问题描述：
DOMAIN-KEYWORD,duolingo
会导致duolingo.cn走代理，该域名所有cdn均在国内，导致走代理

抓包截图：(相关抓包工具的截图。)
调整方案：(你希望规则做哪些调整，及其原因。)
去除DOMAIN-KEYWORD,duolingo

**Comment by blackmatrix7** [comment]
谢谢反馈，已调整。
