### ISSUE TITLE
line通话规则缺失

### ISSUE THREAD

**Issue by FosterHan** [blackmatrix7/ios_rule_script#1039]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Line

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Line/Line.list

异常规则：125.209.252.208:27560

问题描述：这个是line 里面语音通话连接的相关IP，通过ipapi查询是韩国navor，目前的分流规则里面没有

抓包截图：
![image](https://github.com/blackmatrix7/ios_rule_script/assets/57893160/134f644f-791b-4e97-bb67-88e334d90fe6)
(相关抓包工具的截图。)

调整方案：理解这种ip类的经常改变不好抓，麻烦加上相关规则，谢谢(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入。

**Comment by FosterHan** [comment]
加错了呢，应该是125.209.252.0/32   这样才会更全一点，现在通话ip变成125.209.252.103了
