### ISSUE TITLE
能否考虑取消对m.yap.yahoo.com的拦截

### ISSUE THREAD

**Issue by elonj** [blackmatrix7/ios_rule_script#104]
请问能否考虑取消对m.yap.yahoo.com的拦截。因为拦截m.yap.yahoo.com之后，Yahoo Finance这个app不能正常使用。
与m.yap.yahoo.com相关的有两个位置：
rewrite中Advertising的^https?:\/\/m\.yap\.yahoo\.com\/v\d{2}\/getAds\.do
和rule中Advertising的m.yap.yahoo.com

希望可以去掉这两条，非常感谢对规则的维护！

**Comment by blackmatrix7** [comment]
已经去掉了，等明天半夜自动更新后你再看看。

**Comment by elonj** [comment]
非常感谢
