### ISSUE TITLE
Adobe的分流似乎有一处错误

### ISSUE THREAD

**Issue by Flora-air** [blackmatrix7/ios_rule_script#1040]
规则名称：Adobe.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Adobe/Adobe.list

异常规则：DOMAIN-SUFFIX,digicert.com

问题描述：把SSL证书颁发机构的域名给写到Adobe的连接里去了
虽然暂时没有遇到使用上的问题，但是我个人认为这一条不太妥当

抓包截图： 
<img width="850" alt="image" src="https://github.com/blackmatrix7/ios_rule_script/assets/62434508/35a85eb9-e6d5-4769-8f5b-33ef6adab589">

调整方案：(你希望规则做哪些调整，及其原因。)
DOMAIN-SUFFIX,digicert.com
很容易查证digicert.com的官网身份，这似乎是一个比较明显的错误，可以考虑把这一行删掉

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
