### ISSUE TITLE
ChinaMax 规则包含部分台湾测速节点

### ISSUE THREAD

**Issue by Jadelog** [blackmatrix7/ios_rule_script#1047]
规则名称：
ChinaMax

规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/ChinaMax
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/ChinaMax

异常规则：
speedtest.dongfong.com.tw.prod.hosts.ooklaserver.net
speedtest.twds.com.tw.prod.hosts.ooklaserver.net
speedtest.imcloud.tw.prod.hosts.ooklaserver.net
spt1.seed.net.tw.prod.hosts.ooklaserver.net

问题描述：
ChinaMax 规则包含 speddtest.net 部分台湾测速节点的子域导致某些流量经过 DIRECT
抓包截图：(相关抓包工具的截图。)
![image](https://github.com/blackmatrix7/ios_rule_script/assets/61723005/75f649fd-391d-43f5-8369-d9ea556a74f7)

调整方案：(你希望规则做哪些调整，及其原因。)
剔除这些域

**Comment by blackmatrix7** [comment]
台湾是中华人民共和国不可分割的一部分，这样归类没什么问题。

不过刚刚复查没有发现这几条规则，可能是上游已经移除掉了。

皆大欢喜。
