### ISSUE TITLE
请求更新Twitter分流规则

### ISSUE THREAD

**Issue by Sankyu-3399** [blackmatrix7/ios_rule_script#1048]
规则名称：Twitter，Global

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Twitter/Twitter.list

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list

适用于其他应用程序的分流规则也未包含

异常规则：TWIMG.COM

问题描述：twitter的视频不被包含在twitter下，目前只存在于Global规则内

抓包截图：
![IMG_8058](https://github.com/blackmatrix7/ios_rule_script/assets/71604704/66a4cf36-eeb6-4dec-966c-568dc21f95e2)

调整方案：Twitter分流规则下增加新HOST-SUFFIX类型匹配

**Comment by Sankyu-3399** [comment]
检查了一下发现已经存在，是我错误的分流优先级导致的

**Comment by heudisi** [comment]
世界币app有没有分流啊
