### ISSUE TITLE
联通签到无法获取cookie，surge报错

### ISSUE THREAD

**Issue by fangpidedongsun** [blackmatrix7/ios_rule_script#105]
10:58:43.854209 HTTP request script found: 联通_获取cookie
10:58:44.106919 [ERROR] [中国联通]
获取联通手机营业厅Cookie出现异常，异常信息：TypeError: null is not an object (evaluating '/c_mobile=([0-9]{11})/.exec(cookie)[1]')

**Comment by blackmatrix7** [comment]
手机营业厅版本号，及获取Cookie的步骤是什么？

**Comment by blackmatrix7** [comment]
这个事情比较奇怪，我更新到最新版的手机营业厅，抓了几次包，都是能够正常匹配正则的。

不知道会不会和手机号码归属地有关系，你如果方便的话，自己抓个包，把请求头的内容【脱敏】之后发给我看看。

**Comment by fangpidedongsun** [comment]
还请大神检查,敏感部分已用(******************) 代替

GET /dailylottery/static/doubleball/firstpage?encryptmobile=(******************) HTTP/1.1
Host: m.client.10010.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: keep-alive
Cookie: JSESSIONID=CD3317922F8(******************) 22BBEFDDD2C; c_version=iphone_c@8.0004; channel=GGPD; city=011|110; cw_mutual=(******************) 69e430ecf3d64a00ad11e7e1f9c80a856fe8f938241dfad3234fcdd950fce4284b2ad2e6e3a6b22e80f0a415aaad6e9772d2bf78cfe788; devicedId=9CF95E90-762F-44CE-876C-A6469F34C46B; ecs_token=(******************) jZDhiYmJhZTEwYWQ1NDMzYjIyNDJkODc2M2Q4ZWU2M2U4ZjAxYTk5OGEzNTQ2NDcwMDFmNzI3NDhlYjE5YWZjMWU2NDY3NDliYjE3YjllZmJiOWNmMTdmYzBmNzAyNGIzNmIxYmFmNj(******************) mNlNmJiYTk2Y2RmNTE4MDkyZmU4YTEwMTNkM2M1YTY3NjNjZmU4MGRmOTg2Y2QzNjE2YTc1M2JmMzNlYmM5IiwidmVyc2lvbiI6IjAwIn0=; jwt=(******************) cCI6IkpXVCJ9.eyJtb2JpbGUiOiIxMzI2MTc4NjQwNyIsInBybyI6IjAxMSIsImNpdHkiOiIxMTAiLCJpZCI6IjllMGM0YzFiYjhkZDU0Mzc2NjJlZmJmOTk0ZjNiZjE0In0._HyOKgNgUcDaW06bAL7UIV1fpYfIp-haIRsLq3H1YVc; login_type=06; u_account=(******************) ; ecs_acc=(******************) D9hIq3YUKXGh5I6iGlSEAeTI88pWQEIufwr2HOsDeCf1+bNX4qhQHwR1WyLyz5NSno+/7mueHlziKKiCvhC1W0XJkaHVnVyoyPtcNm+yFzJr/3pVB1xhyakL0Fnc0eSuFCy0esHuFx9UcuRbAeI=; dailyltoute=(******************) bbab1cba3bf914d51bd82496014; route=(******************) 58c135afafcff51e20971; ecs_acc=(******************) M6S5ce6E/+3NhYUL1YU9yrKuM4zua76u4VO7Hz00PATvm798W8tW73RI3k64RrdASxpH/EREmZL3hZa7YwYzVAoyw17Zc3D1ty59e8yhXVr/aVK5B7x3q1ZNgAvsp5KbsLcn93iW88MZxU5DnEiqQ=; clientid=11|110; on_info=(******************) 91ad2f844a90b2dc06c5; mobileServiceAll=(******************) d57498fdf7b6
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148     unicom{version:iphone_c@8.0004}{systemVersion:dis}{yw_code:}
Accept-Language: zh-cn
Referer: https://m.client.10010.com/dailylottery/static/textdl/userLogin?version=iphone_c@8.0004&desmobile=(******************) &yw_code=&time=1608077309
Accept-Encoding: gzip, deflate, br

**Comment by blackmatrix7** [comment]
我把你的删掉了，cookie本身就非常敏感，不要在公共场合泄漏，你打星号的部分是手机号码吗？

**Comment by fangpidedongsun** [comment]
> 我把你的删掉了，cookie本身就非常敏感，不要在公共场合泄漏，你打星号的部分是手机号码吗？

对的

**Comment by blackmatrix7** [comment]
mobileServiceAll=(****************)

这个括号是自带的吗？

**Comment by fangpidedongsun** [comment]
不是 是我加的 这个位置显示的是手机号

**Comment by blackmatrix7** [comment]
你登录账号的方式是什么？密码登录？验证码登录？

**Comment by fangpidedongsun** [comment]
> 验证码登录
验证码登录的

**Comment by blackmatrix7** [comment]
你方便再重新发一下请求头吗？不要把内容删掉，只要把部分内容替换成错的就可以了。之前发的删掉了一些东西，不太好分析。

**Comment by fangpidedongsun** [comment]
GET /dailylottery/static/doubleball/firstpage?encryptmobile= 12345678900 HTTP/1.1
Host: m.client.10010.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: keep-alive
Cookie: JSESSIONID=ABC; c_version=iphone_c@8.0004; channel=GGPD; city=011|110; cw_mutual=12345678900; devicedId=12345678900-12345678900; ecs_token= ABC; jwt= ABC; login_type=06; u_account=12345678900; ecs_acc=ABC; dailyltoute=12345678900; route=ABC; clientid=11|110
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148   unicom{version:iphone_c@8.0004}{systemVersion:dis}{yw_code:}
Accept-Language: zh-cn
Referer: https://m.client.10010.com/dailylottery/static/textdl/userLogin?version=iphone_c@8.0004&desmobile=12345678900&yw_code=&time=1608098705
Accept-Encoding: gzip, deflate, br

**Comment by fangpidedongsun** [comment]
> 你方便再重新发一下请求头吗？不要把内容删掉，只要把部分内容替换成错的就可以了。之前发的删掉了一些东西，不太好分析。

大神，我找到问题了。修改了一下主函数就成功了，不知道我的是不是个例。
客户端版本：8.0.3
请大神参考我的修改。
最后，感谢大神的回复，谢谢！

async function Main() 下面
        let mobile = /**u_account**=([0-9]{11})/.exec(cookie)[1]; //我抓包看的话cookie里面没有c_mobile，我的是u_account是手机号
        let hisMobile = magicJS.read(mobileKey, 'default');
        // 获取加密手机号
        let encryptMobile = /encryptmobile=([a-zA-Z0-9]*)/.exec(magicJS.request.url)**[4];**//我抓包看的话cookie里面encryptMobile是4开头的，所以我改成4

**Comment by blackmatrix7** [comment]
现在的情况是，不同地区的手机号码可能Cookie不太一样，比如对我来说c_mobile就是存在的。
不清楚这种情况的范围有多大，我更新了一个版本，增加一些获取手机号码的正则匹配，你试试。

**Comment by fangpidedongsun** [comment]
> 现在的情况是，不同地区的手机号码可能Cookie不太一样，比如对我来说c_mobile就是存在的。
> 
> 不清楚这种情况的范围有多大，我更新了一个版本，增加一些获取手机号码的正则匹配，你试试。

好的👌
