### ISSUE TITLE
百度贴吧签到问题反馈

### ISSUE THREAD

**Issue by maliouu** [blackmatrix7/ios_rule_script#1050]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：百度贴吧

APP版本：12.49.3

客户端名称：百度贴吧

客户端版本：12.49.3

问题描述：boxjs填入了cookie签到失败

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
支持多账户签到，不能直接填入Cookie，必须使用脚本自动获取。
