### ISSUE TITLE
误杀反馈

### ISSUE THREAD

**Issue by ashurinn** [blackmatrix7/ios_rule_script#106]
Surge/AdvertisingLite/Domain.list会拦截flickr.com
![5E29D4AD-1D4D-4168-9F35-9BBDC2C374E8](https://user-images.githubusercontent.com/54405882/102153495-4bb22900-3eb2-11eb-929a-02bcd202857a.jpeg)

**Comment by blackmatrix7** [comment]
已经把这条规则加入过滤器，等明天早上你更新一下应该就好了。
