### ISSUE TITLE
请求优化 Clash 的规则命名逻辑

### ISSUE THREAD

**Issue by ghost** [blackmatrix7/ios_rule_script#1060]
你好作者大大

从逻辑上以及别的库命名规则来讲，以`ChinaMax`为例`ChinaMax_Classical.yaml`、`ChinaMax_Domain.yaml`、`ChinaMax_IP.yaml`这三份规则应该属于`ChinaMax.yaml`的特殊加载方式版

但实际上`ChinaMax.yaml`却是`ChinaMax_Classical.yaml`的特殊加载方式版，这很不逻辑

比如`115`，如果按照`ChinaMax`的命名方式，应该是`115_Classical.yaml`

所以希望能调整为`ChinaMax.yaml`是最完整的版本；而`ChinaMax_Classical.yaml`、`ChinaMax_Domain.yaml`、`ChinaMax_IP.yaml`这三份规则应该属于`ChinaMax.yaml`的特殊加载方式版

别的规则也有类似情况，只是用`ChinaMax`举例

希望实现，谢谢

**Comment by blackmatrix7** [comment]
你好，这个是因为历史原因导致的。

早期并没有这么多文件，随着不断提出新的需求，为了和之前的文件做区分，不得不增加新的文件名。

多次需求的增加，最终成为这样的情况。

而目前直接去修改文件名，会导致原先其他人在使用的链接变成404。
