### ISSUE TITLE
Global分流规则导致访问威联通ddns服务异常

### ISSUE THREAD

**Issue by Gensei-Makise** [blackmatrix7/ios_rule_script#1062]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Global

规则链接： https://cdn.jsdelivr.net/gh/
blackmatrix7/ios_rule_script@master/rule/ QuantumultX/Global/Global.list

异常规则：HOST-SUFFIX     myqnapcloud.cn

问题描述：myqnapcloud.cn属于威联通大陆区域ddns转发域名，不应该错误归类在global规则下，如该域名走代理访问，将无法连接威联通的ddns服务

抓包截图：似乎无需截图

调整方案：*.cn域名个人建议无需放在global规则下，一般来说cn顶级域名下的网站都应该采取直连的方式连接，在global规则下可能导致不必要的麻烦

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除了。
