### ISSUE TITLE
希望能单独开一个DOMAIN-SET规则的栏目

### ISSUE THREAD

**Issue by easonnnone** [blackmatrix7/ios_rule_script#1066]
因为现在规则一般用的是RULE-SET，但做DOMAIN-SET规则的就很少
希望能单独开一个DOMAIN-SET规则的栏目，谢谢啦。

**Comment by blackmatrix7** [comment]
目前超过1000条会自动拆分DOMAIN-SET。

1000条以内不会拆分，以减少规则配置的复杂性。

根据Surge的更新日志，1000条以内性能影响微乎其微：

一般情况下，绝大多数用户的需求都可以在 1000 条规则内满足（或者更少），此时每次进行规则匹配的开销应该在 1ms 以内，完全不必在意。
但是部分巨量的规则集（主要是去广告的规则），可能内含上万条规则。这将产生严重的性能影响，我们测试在 iPhone 15 Pro 上，七万条规则的 RULE-SET 匹配耗时约 100ms，造成严重的性能下降。
所以如果需要使用巨量的规则，请使用 DOMAIN-SET 类型规则集，该类型专为巨量规则所设计，不仅内存占用极小，匹配速度也极快，七万条规则也只需要个位数 ms 即可完成匹配。

**Comment by easonnnone** [comment]
那是不是去广告规则 用DOMAIN-SET就行了，其他还是用RULE-SET，对吧

**Comment by OUZYcn** [comment]
> 那是不是去广告规则 用DOMAIN-SET就行了，其他还是用RULE-SET，对吧


https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Advertising
注意看 使用说明

> Advertising.list，请使用RULE-SET。
> Advertising_Resolve.list，请使用RULE-SET。
> Advertising_Domain.list，请使用DOMAIN-SET。

配置建议

> Advertising.list、Advertising_Domain.list 共同使用。
> Advertising_Resolve.list、Advertising_Domain.list 共同使用。
