### ISSUE TITLE
去广告项目

### ISSUE THREAD

**Issue by shaGuar-svg** [blackmatrix7/ios_rule_script#107]
能否适配毒奶去广告项目，实测优秀。但因surge不能直接修改响应体无法使用。项目地址：https://github.com/limbopro/Adblock4limbo
[如图效果](https://limbopro.xyz/usr/uploads/2020/11/3077832229.jpg)

**Comment by blackmatrix7** [comment]
分流规则已加入了，至于复写，我随便贴几条里面的内容：

^https:/?.*\.trwl1\b.* url 302 https://limbopro.xyz/865.html
^https:/?.*\.trwl1\b.*?\SC$ url 302 https://limbopro.xyz/865.html
^a.\bo333o\b.*\=1$ url 302 https://limbopro.xyz
^<a\sclass\b.*uu-ads\b.*\</a>$ url 302 https://limbopro.xyz

http code 302 是重定向的作用，上面这几条的作用是将某个地址重定向到自己网站上，以增加网站访问量。

这个实际上就是一种流量劫持的行为，所以没办法加入这个。
