### ISSUE TITLE
OpenAI.list解决网页端报错和静态资源加载问题 需要补充分流 oaistatic.com和oaiusercontent.com

### ISSUE THREAD

**Issue by Flora-air** [blackmatrix7/ios_rule_script#1072]
规则名称：OpenAI.list
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list
异常规则：
问题描述：OpenAI的分流需要进行补充

抓包截图：(相关抓包工具的截图。)
![IMG_2940](https://github.com/blackmatrix7/ios_rule_script/assets/62434508/6a5085fe-bf84-4b2b-a3d6-317c87a24153)
![IMG_2941](https://github.com/blackmatrix7/ios_rule_script/assets/62434508/15ab7e77-b800-40e1-94a1-2537be04438b)
![IMG_2942](https://github.com/blackmatrix7/ios_rule_script/assets/62434508/ce9362ce-1b29-4fac-9d7b-7465df77b075)

调整方案：(你希望规则做哪些调整，及其原因。) 
增加规则 host-suffix, oaistatic.com //domain-suffix, oaistatic.com 视客户端情况而定

**Comment by Flora-air** [comment]
![IMG_2948](https://github.com/blackmatrix7/ios_rule_script/assets/62434508/3fee8b63-9981-4e0e-ae8b-99a9ab91833c)
补充：cdn的限制 cdn.oaistatic.com files.oaiusercontent.com

DOMAIN-SUFFIX,oaistatic.com
DOMAIN-SUFFIX,oaiusercontent.com

**Comment by eavan5** [comment]
https://github.com/blackmatrix7/ios_rule_script/pull/1071 等待作者合并

**Comment by OUZYcn** [comment]
rule/Surge/OpenAI/OpenAI.list

1. 现有list有重复项
2. 且还需要加入：
```
DOMAIN-KEYWORD,openaicom-api
DOMAIN-SUFFIX,openaiapi-site.azureedge.net
DOMAIN-SUFFIX,launchdarkly.com
DOMAIN-SUFFIX,segment.io
DOMAIN-SUFFIX,googleapis.com
```
3. 另外， 要将openai.list 放在 下边两个之前， 因为“api.statsig.com”被加入到下边的list了。 
```
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.lis
```

**Comment by gotoplaycode** [comment]
> rule/Surge/OpenAI/OpenAI.list
> 
> 1. 现有list有重复项
> 2. 且还需要加入：
> 
> ```
> DOMAIN-KEYWORD,openaicom-api
> DOMAIN-SUFFIX,openaiapi-site.azureedge.net
> DOMAIN-SUFFIX,launchdarkly.com
> DOMAIN-SUFFIX,segment.io
> DOMAIN-SUFFIX,googleapis.com
> ```
> 
> 3. 另外， 要将openai.list 放在 下边这个之前， 因为“.statsigapi.net”被加入到下边的list了，记忆中会出问题。
> 
> ```
> https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list
> ```
确实，重复的也太明显了哈，新加的俩网址居然重复了三遍，改的也太不用心了。。。

**Comment by RexLee0929** [comment]
补充一点,移动端还有额外的域名需要分流
`api.statsig.com`
这个也得分流 不然会无法登录

**Comment by gotoplaycode** [comment]
大佬能不能把clash分支下的yaml也增加一下？电脑上也要用，cfw好像不支持list格式，只能用yaml

**Comment by OUZYcn** [comment]
# --2023-11-17--
DOMAIN,static.cloudflareinsights.com
DOMAIN-SUFFIX,observeit.net
DOMAIN-SUFFIX,algolia.net
# --2023-11-18--
DOMAIN,openai-api.arkoselabs.com

观察中，，，

**Comment by OUZYcn** [comment]
# --2023-11-17--
DOMAIN,static.cloudflareinsights.com
DOMAIN-SUFFIX,observeit.net
DOMAIN-SUFFIX,algolia.net
# --2023-11-18--
DOMAIN,openai-api.arkoselabs.com

观察中，，，

**Comment by laobanbiefangcu** [comment]
clash的分支能不能加一下，感谢

https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/OpenAI

**Comment by MalikWilliams1greher** [comment]
> # --2023-11-17--
> DOMAIN,static.cloudflareinsights.com DOMAIN-SUFFIX,observeit.net DOMAIN-SUFFIX,algolia.net
> 
> # --2023-11-18--
> DOMAIN,openai-api.arkoselabs.com
> 
> 观察中，，，

这是干啥的 规则

**Comment by Flora-air** [comment]
> clash的分支能不能加一下，感谢
> 
> https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/OpenAI


#1083 已提交 待审核

**Comment by blackmatrix7** [comment]
已经全部更新了。

重复规则问题是因为接受多人的PR，其实规则都不需要PR，它是根据上游的规则源自动更新合并的。考虑到各方面的原因，一般提PR都会接受。

接受PR后，正好上游规则没有更新，所以没有触发它的自动更新，导致部分客户端缺失规则和部分规则重复。

现在做了一个强制更新，所有的规则都正常了。
