### ISSUE TITLE
JOOX规则补充

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#1077]
规则名称：JOOX

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/JOOX

异常规则：IP-CIDR,203.205.234.0/23,no-resolve // Added for: 203.205.234.136:443 (api.joox.com)
IP-CIDR,119.28.182.0/23,no-resolve // Added for: 119.28.183.94:443 (api-jooxtt.sanook.com)
DOMAIN-SUFFIX,i-joox.com
DOMAIN-SUFFIX,sanook.com

问题描述：

抓包截图：
![IMG_8391](https://github.com/blackmatrix7/ios_rule_script/assets/57618347/37ba9f4b-81b8-47de-99dc-0ee9644b5358)

调整方案：补充规则

**Comment by tkzc11** [comment]
补充：DOMAIN-SUFFIX,i-joox.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
