### ISSUE TITLE
百度走代理分流？

### ISSUE THREAD

**Issue by dcty** [blackmatrix7/ios_rule_script#108]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Proxy/Domain.list

包含了 .baidu.com

**Comment by blackmatrix7** [comment]
这个是同步数据源的，某个时候某个数据源出现问题就会同步到规则里，这种情况只能缓解无法解决，毕竟数据源不受我的控制。
