### ISSUE TITLE
希望加入copilot.microsoft.com的规则

### ISSUE THREAD

**Issue by easonnnone** [blackmatrix7/ios_rule_script#1081]
copilot.microsoft.com不用全局代理就进不去了，希望能新增copilot相关的规则，谢谢啦

**Comment by wang93wei** [comment]
我目前也是这样

**Comment by Giant-Li** [comment]
Copilot相关配置
edgeservices.bing.com
d.docs.live.net
edge.microsoft.com
proteus-assetstore.azurewebsites.net
nexusrules.officeapps.live.com
functional.events.data.microsoft.com
browser.events.data.msn.cn
services.bingapis.com
