### ISSUE TITLE
OpenAI iOS端登录异常，应把 api.statsig.com 加入规则

### ISSUE THREAD

**Issue by smilingpoplar** [blackmatrix7/ios_rule_script#1082]
规则名称：OpenAI

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/OpenAI/OpenAI.yaml

问题描述：iOS端chatgpt登录时，"Checking System Health" 后 "Sign In Failed"

调整方案：把 `api.statsig.com` 加入代理规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
