### ISSUE TITLE
Discovery+规则补充

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#1084]
规则名称：DiscoveryPlus

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/DiscoveryPlus

规则：DOMAIN,dplus-northamerica-cloudfront-gcs.prod-vod.h264.io

调整方案：添加规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
