### ISSUE TITLE
genshin impact无法检查更新、进入游戏

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#1086]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

规则链接：

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/HoYoverse/HoYoverse.list

异常规则：

问题描述：
请添加yuanshen.com suffix domain
否则 此域名与genshinimpact其他域名节点可能不走同一个节点，导致检查更新出错，无法进入游戏
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
