### ISSUE TITLE
关于知乎黑名单功能的一些建议

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#109]
以下是我日常添加黑名单的全过程步骤，相信符合大多数人的使用场景：
1、浏览“精选”
2、发现一篇不感兴趣的推荐（从题目和回答摘要中推断是：卖假鞋、羊毛群、职场鸡汤、淘宝店推荐之类），于是想将该用户加入黑名单
3，点进去这个回答
4、点进用户头像，将其加入黑名单
但是后来发现这类不感兴趣的回答反而变多了，猜测是第3、4这两步浏览行为改变了我的用户画像，使知乎给我推送了更多“同样用户画像用户”浏览过的回答。

是否能提供一种不用点开回答就能添加黑名单的办法，我妄想出来的解决方案是这样的：
除了知乎自带的黑名单，再加一个外挂的黑名单，黑名单链接文件固定为a.com/black.txt
我按照黑名单格式在本地增删黑名单人员，上传到b.net/black.txt
然后在surge中将a.com/black.txt这个链接rewrite到b.net/black.txt
最后通过知乎中的“设置—屏蔽设置—管理黑名单”，下拉刷新更新block.txt中的黑名单人员

**Comment by blackmatrix7** [comment]
如果是在推荐列表中屏蔽用户，建议用知乎自带的屏蔽功能，在列表里点击右边横着的三个圆点， 选择屏蔽这个问题，屏蔽作者或者相关话题。

虽然脚本的黑名单屏蔽经过优化，黑名单数量几乎不影响执行效率，但是在知乎服务端的屏蔽执行效率仍要远高于本地脚本的屏蔽。

**Comment by fiiir** [comment]
> 如果是在推荐列表中屏蔽用户，建议用知乎自带的屏蔽功能，在列表里点击右边横着的三个圆点， 选择屏蔽这个问题，屏蔽作者或者相关话题。
> 
> 虽然脚本的黑名单屏蔽经过优化，黑名单数量几乎不影响执行效率，但是在知乎服务端的屏蔽执行效率仍要远高于本地脚本的屏蔽。

刚发现“屏蔽这个问题”点进去还有二级菜单，以前没发现不敢乱点
那就不用让事情变麻烦了，自带的就挺好用了已经

**Comment by blackmatrix7** [comment]
好的，能解决就好。
