### ISSUE TITLE
关于什么值得买签到接口失效问题

### ISSUE THREAD

**Issue by FosterHan** [blackmatrix7/ios_rule_script#1095]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：什么值得买每日签到

APP版本：ALL

客户端名称：使用Loon插件

客户端版本：Loon 3.1.3

问题描述：签到脚本反馈安卓接口不合法，是我的个例还是安卓接口挂了，麻烦帮忙看一下，谢谢

复现方式：每日自动化签到，插件log见图
![IMG_0716](https://github.com/blackmatrix7/ios_rule_script/assets/57893160/b637940a-bb56-4427-951b-0e4ae9fe422b)

自动化签到失败

已使用空白配置文件验证：否

**Comment by FosterHan** [comment]
![photo_2023-11-26_10-16-13](https://github.com/blackmatrix7/ios_rule_script/assets/57893160/e99bd44d-9ff7-4b0e-ad35-9fd1ed388e4d)
lolog显示获取cookie正常，所以怀疑安卓接口问题

**Comment by FosterHan** [comment]
loon脚本缓存数据问题，已自行解决

**Comment by godmiracle** [comment]
> loon脚本缓存数据问题，已自行解决

怎么清除缓存的啊，我用的圈x试过重装app，脚本清空重装都还是获取不到cookies

**Comment by nelvko** [comment]
> > loon脚本缓存数据问题，已自行解决
> 
> 
> 
> 怎么清除缓存的啊，我用的圈x试过重装app，脚本清空重装都还是获取不到cookies

boxjs 或 qx 内的定时任务页面均可删除缓存的数据
