### ISSUE TITLE
GlobalMedia“当前分流规则，未包含其他子规则。”表述不准确

### ISSUE THREAD

**Issue by jochne** [blackmatrix7/ios_rule_script#1098]
规则名称：GlobalMedia

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/GlobalMedia

问题描述：“当前分流规则，未包含其他子规则。”表述不准确

调整方案：该规则有包含Youtube、YouTubeMusic等子规则，建议增加说明。

**Comment by blackmatrix7** [comment]
谢谢反馈，已调整。
