### ISSUE TITLE
118.89.204.198这个ip被reject后有时会加载错误

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_script#11]
118.89.204.198这个ip被reject后有时会加载错误

**Comment by blackmatrix7** [comment]
提供下详细的日志。如果是想法加载失败，属于正常情况。

**Comment by LuzMasonj** [comment]
@yfue 
[QuantumultX用户知乎APP加载失败原因定位](https://github.com/blackmatrix7/ios_rule_script/issues/268#issue-836760611) 
根据这个issue试试 看看究竟是不是这个的原因
