### ISSUE TITLE
使用知乎助手 提示没有获取到当前登录用户信息

### ISSUE THREAD

**Issue by jongkhurunn** [blackmatrix7/ios_rule_script#110]
使用qx的知乎助手plus，已经登录了，但在日志中大量出现
` [JS Console]: [WARNING] [知乎助手]没有获取到当前登录用户信息，已设置为默认用户配置。如果未登录知乎请忽略此日志。`

**Comment by blackmatrix7** [comment]
可能是某些异常导致没有获取到用户信息，你看下 

# 知乎处理用户信息
^https?:\/\/api\.zhihu\.com\/people\/ url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.js 
这条复写是不是正常工作，还有对应的MITM是不是存在，尽量不要再复写中重复引入相同的MITM

**Comment by jongkhurunn** [comment]
看了下请求记录发现脚本正常运行，这个报错只有点进自己的主页/people/self/时才会出现，进入别人的主页不会出现

**Comment by blackmatrix7** [comment]
这个主要是用来在不同知乎账户间切换黑名单，如果你只有一个账户，可以忽略这个问题。具体什么原因暂时没时间去查。

**Comment by jongkhurunn** [comment]
好的 感谢
