### ISSUE TITLE
App端没法签到啊

### ISSUE THREAD

**Issue by sxx520** [blackmatrix7/ios_rule_script#111]
测试使用app端的签到  返回code为0  但是登陆app客户端  显示并没有进行签到  什么值得买的签到

**Comment by blackmatrix7** [comment]
需要提供一下完整的日志

**Comment by Jessire** [comment]
> 测试使用app端的签到 返回code为0 但是登陆app客户端 显示并没有进行签到 什么值得买的签到

只是客户端显示有问题，实际已经签上了

**Comment by sxx520** [comment]
我用接口测试的  返回如下   {"error_code":"0","error_msg":"","smzdm_id":"0","s":"5fdc211c9a6ee541797","data":null}

**Comment by sxx520** [comment]
是用C#  进行接口请求的

**Comment by blackmatrix7** [comment]
这应该只是获取到token，你需要再调用接口签到。

**Comment by sxx520** [comment]
var content2 = new System.Net.Http.StringContent($"token={appToken}&f=win", Encoding.UTF8, "application/x-www-form-urlencoded");

                using var response2 = await http.PostAsync("https://api.smzdm.com/v1/user/checkin", content2);

返回的就是这个{"error_code":"0","error_msg":"","smzdm_id":"0","s":"5fdc211c9a6ee541797","data":null}

**Comment by blackmatrix7** [comment]
> var content2 = new System.Net.Http.StringContent($"token={appToken}&f=win", Encoding.UTF8, "application/x-www-form-urlencoded");
> 
> ```
>             using var response2 = await http.PostAsync("https://api.smzdm.com/v1/user/checkin", content2);
> ```
> 
> 返回的就是这个{"error_code":"0","error_msg":"","smzdm_id":"0","s":"5fdc211c9a6ee541797","data":null}

看起来调用的接口应该没什么问题，error_code为0就是签到成功了。不过这个接口很老，实际上没什么收益，APP也不会显示已签到，没办法。
