### ISSUE TITLE
Google规则中未排除YouTube规则，反而是囊括了YouTube规则

### ISSUE THREAD

**Issue by Rysiwv** [blackmatrix7/ios_rule_script#1114]
规则名称：Google

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Google

异常规则：DOMAIN-KEYWORD,google

问题描述：YouTube视频连接的 URL 长这样 `rr4---sn-abcabc.googlevideo.com:443` ，使用 Google 规则后会将此连接归为 Google 规则，与 YouTube.list 冲突，且 YouTube.list 未达到匹配效果。

**Comment by blackmatrix7** [comment]
DOMAIN-KEYWORD,google 类型的规则的确容易引起误判

但是如果直接把它移除，担心会影响请求的分流

你可以试试把YouTube的规则置于Google规则之前试试，如果有问题，你可以重新打开issue再沟通。

**Comment by Rysiwv** [comment]
把 `YouTube 规则` 移到更靠前的位置确实可以解决 YouTube 视频流量被 `Google 规则` 匹配的问题，我提 issue 的初衷可能未表述清楚。
在 `Google 规则` 的 README.md 中（下图）描述已排除 YouTube 规则，但实际上该规则会匹配到 YouTube 视频流量，可能会对使用者造成些许困扰，或许可以添加一段说明之类的以作提醒。
<img width="932" alt="image" src="https://github.com/blackmatrix7/ios_rule_script/assets/76012915/1f85e96f-9b51-42f6-843b-f37ef7887b18">
