### ISSUE TITLE
去广告规则导致向日葵客户端不能登录 

### ISSUE THREAD

**Issue by phoenix-cn** [blackmatrix7/ios_rule_script#1115]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
去广告
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rewrite/QuantumultX/Advertising/Advertising.conf
异常规则：
^https?:\/\/slapi.oray.net/client/ad url reject
^https?:\/\/slapi\.oray\.net\/adver url reject
^https?:\/\/slapi\.oray\.net\/client\/ad url reject
还有另外两条
问题描述：
导致向日葵客户端不能登录
抓包截图：(相关抓包工具的截图。)
<img width="1049" alt="截屏2023-12-11 20 45 14" src="https://github.com/blackmatrix7/ios_rule_script/assets/60874520/77663440-8e86-4e8d-8f3e-d13075b0e4e2">
<img width="472" alt="截屏2023-12-11 21 28 59" src="https://github.com/blackmatrix7/ios_rule_script/assets/60874520/b380ad2e-e351-4205-8e79-457b97185f76">

调整方案：(你希望规则做哪些调整，及其原因。)
调整规则

**Comment by blackmatrix7** [comment]
主分支已移除。
