### ISSUE TITLE
请问ChinaMax_Domain.txt这个文件怎么没有更新了？

### ISSUE THREAD

**Issue by mx4994** [blackmatrix7/ios_rule_script#1116]
[ChinaMax_Domain.txt](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/ChinaMax/ChinaMax_Domain.txt) 这个文件自从10月26日之后再也没更新过了，是自动脚本故障了还是停更了呢？

![image](https://github.com/blackmatrix7/ios_rule_script/assets/52325833/c258cdf0-e468-4b22-88a3-45891343c570)

**Comment by blackmatrix7** [comment]
谢谢反馈，这是个Bug，已修复。
