### ISSUE TITLE
请求一下规则不同的详情

### ISSUE THREAD

**Issue by DreamsCat** [blackmatrix7/ios_rule_script#1121]
想问一下有些规则的具体不同，就拿去广告规则来说：
我看到有
[Advertising.list](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising.list)

和[Advertising_All.list](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising_All.list)

请问一下这两者有什么区别吗？

**Comment by blackmatrix7** [comment]
ALL是后来Surge不再需要区分DOMAIN-SET和RULE-SET后添加的。

如果你的Surge是最新版，直接使用带ALL的文件即可。
