### ISSUE TITLE
global list的一些问题

### ISSUE THREAD

**Issue by 2583538** [blackmatrix7/ios_rule_script#1135]
QX规则资源的Global里面有一些（特斯拉）tesla的链接。

因为这个规则的名称是境外网站，那么分流的时候就设置的是非DIRECT。

我使用下来认为会导致无法连接到tesla app查看车辆信息。

谢谢。

--

另外遇到个问题可能和您这无关。

就是通过朴朴买菜app跳转到alipay付款的时候，会超时。

**Comment by blackmatrix7** [comment]
谢谢反馈，已调整。
