### ISSUE TITLE
请求添加iOS的copilot规则

### ISSUE THREAD

**Issue by li2282231** [blackmatrix7/ios_rule_script#1137]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：copilot

规则链接：无

异常规则：无

问题描述：目前没有copilot规则，请更新，谢谢！

抓包截图：无

调整方案：微软copilot在AppStore上推出好几天了，目前网上相关的copilot规则都不完善，使用有各种各样的问题，遂请更新，谢谢

**Comment by blackmatrix7** [comment]
临时加了一个https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Copilot

如果有缺失或错误再修改
