### ISSUE TITLE
反馈Copilot规则不全面，目前的规则无法正常使用，我已通过抓包工具loon解析到还需将以下域名设置代理分流，请更新，谢谢1

### ISSUE THREAD

**Issue by li2282231** [blackmatrix7/ios_rule_script#1147]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：copilot

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Loon/Copilot/Copilot.list

异常规则：copilot

问题描述：规则不全面，目前使用该规则无法正常登陆使用copilot

抓包截图：
![IMG_0006](https://github.com/blackmatrix7/ios_rule_script/assets/8499645/aa1356c9-6a9b-4760-a302-2ffd48a452f8)

调整方案：希望添加以下域名到分流规则copilot里面，这样我就不用在自定义规则里面一个一个手动添加了，谢谢！
DOMAIN,services.bingapis.com
DOMAIN,location.microsoft.com
DOMAIN,gateway.bingviz.microsoftapp.net
DOMAIN,assets.msn.com
DOMAIN,www.bing.com
DOMAIN,api.msn.com
DOMAIN,in.appcenter.ms

**Comment by young1023x2** [comment]
补充
DOMAIN-SUFFIX,edgeservices.bing.com

**Comment by AnYiEE** [comment]
> 补充 DOMAIN-SUFFIX,edgeservices.bing.com

确实，没这个Windows上的Copilot会提示服务在当前地区不可用。

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后更新。
