### ISSUE TITLE
请问微软相关的域名(microsoft outlook ondrive sharepoint等)出现在chinamax中，但子规则中没写有microsoft，是哪边写错了？

### ISSUE THREAD

**Issue by ghost** [blackmatrix7/ios_rule_script#1148]
请问微软相关的域名(microsoft outlook ondrive sharepoint等)出现在chinamax中，但子规则中没写有microsoft，是哪边写错了？

copilot好像也受到影响了。要把微软的相关规则加到chinamax前面才能生效

issue disscuss 中没搜到原因，disscuss的回复率不高就发到Issue了，见谅

**Comment by blackmatrix7** [comment]
可能是某个数据源包含了对应的规则，已对微软的规则做了排除，晚些时候更新。
