### ISSUE TITLE
RevenueCat被错误分流到Netflix规则集

### ISSUE THREAD

**Issue by dnomd343** [blackmatrix7/ios_rule_script#1150]
规则名称：Netflix

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/Netflix/Netflix.list

异常规则：`IP-CIDR,52.0.0.0/15,Netflix`

问题描述：
RevenueCat服务（APP内购使用）的API接口，DNS解析到 `52.0.43.155` ，错误地匹配到Netflix规则。

该IP段目前已经不是奈飞专用，其他公司的AWS服务器均有可能使用该地址。

抓包截图：

![IMG_0572](https://github.com/blackmatrix7/ios_rule_script/assets/54678581/b6d9bde3-7111-4202-80c9-1b86634a20c3)

![IMG_0573](https://github.com/blackmatrix7/ios_rule_script/assets/54678581/3ad4aeb3-8afe-4f14-bea1-546009c995a4)

调整方案：移除异常规则。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
