### ISSUE TITLE
Advertising_All_No_Resolve.list的master分支报错remote resource is too large

### ISSUE THREAD

**Issue by abingx** [blackmatrix7/ios_rule_script#1158]
规则名称：
Advertising_All_No_Resolve.list

规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_All_No_Resolve.list

问题描述：
在surge5.8.3中更新，提示remote resource is too large

**Comment by blackmatrix7** [comment]
之前有个数据源，约29万条数据，所以导致数据量剧增，现在暂时把对应的上游数据源去除，你可以再试试。
