### ISSUE TITLE
Advertising for clash的规则太大导致stash启动后宕机

### ISSUE THREAD

**Issue by wuhyapc** [blackmatrix7/ios_rule_script#1159]
规则名称：Advertising_Domain.txt

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.txt

异常规则：Advertising_Domain 的规则，从7天前的10万多笔暴增到30多万笔，规则太大导致stash下载的时候直接崩溃

问题描述：Advertising_Domain 的规则，从7天前的10万多笔暴增到30多万笔，规则太大导致stash下载的时候直接崩溃，实际测试倒回7天前的规则，stash可以正常运行

调整方案：希望去除近日增加的20多万笔的规则，倒回7天前的记录

**Comment by wuhyapc** [comment]
希望倒回7天前的记录，去除近日增加的20多万的规则，或者合并规则或者优化规则也行，现在自己这边的临时解决方案是fork一个库自己做了一个分支

**Comment by blackmatrix7** [comment]
之前有个数据源，约29万条数据，所以导致数据量剧增，现在暂时把对应的上游数据源去除，你可以再试试。
