### ISSUE TITLE
关于您在github上侵权中信银行的问题沟通，请配合处理 

### ISSUE THREAD

**Issue by yeeton111** [blackmatrix7/ios_rule_script#1160]
您好，
我们是为中信银行股份有限公司提供安全服务的厂商-北京亿盾互联科技有限公司。受中信银行委托，跟您沟通有关您发布存储库里涉及中信银行的问题。您在github上发布的以下1个链接中的内容涉及中信银行信息，因中信银行现在进行护网行动需要删除银行关键信息并且具有不定因素可能给中信银行及其用户带来了安全风险，请帮忙删掉此信息。谢谢配合！

内容链接：    
https://github.com/blackmatrix7/ios_rule_script/blob/a98f2723493f491180dbc9d0fa35f5aed306e787/rule/Loon/CITIC/CITIC.list#L11

**Comment by blackmatrix7** [comment]
您好，已删除相关的域名。
