### ISSUE TITLE
增加一个wetv的域名

### ISSUE THREAD

**Issue by malagebidi** [blackmatrix7/ios_rule_script#1161]
规则名称：WETV

规则链接：很多

问题描述：该域名解析在国外，桌面端做跳转用

抓包截图：
![132244](https://github.com/blackmatrix7/ios_rule_script/assets/726456/5af4322a-42fa-494f-a9b5-17ff086e388a)

调整方案：把`wetv.qq.com`添加到相关规则中

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，晚些时候更新。
