### ISSUE TITLE
vk.com 不应存在于Advertising/Advertising_Domain中

### ISSUE THREAD

**Issue by 1x2y3z4** [blackmatrix7/ios_rule_script#1162]
规则名称：
Advertising/Advertising_Domain.list

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising_Domain.list
异常规则：
vk.com
问题描述：
vk.com是俄罗斯版Facebook，不应该被认为是广告域名
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
删除该条

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加到过滤器，稍后更新。
