### ISSUE TITLE
广告规则可能存在误伤

### ISSUE THREAD

**Issue by Karitsuki** [blackmatrix7/ios_rule_script#1163]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_All_No_Resolve.list

异常规则：DOMAIN-SUFFIX,is1-ssl.mzstatic.com

问题描述：此域名reject之后可能导致itune商店部分内容无法加载，手动改为direct之后恢复正常。

抓包截图：(相关抓包工具的截图。)
![IMG_4855](https://github.com/blackmatrix7/ios_rule_script/assets/118410829/5905cea6-d215-4a80-8ea4-787ca238760d)
![IMG_4854](https://github.com/blackmatrix7/ios_rule_script/assets/118410829/ec261e3d-d5f6-49ed-89f1-7073e38f5d38)

调整方案：由于是最近才发生的问题，所以希望能帮忙验证一下，如果可能的话放行此域名。

**Comment by usrnb** [comment]
遇到相同问题，暂时通过本地规则解决
DOMAIN-KEYWORD,mzstatic.com,DIRECT

**Comment by yesanshao007** [comment]
确实有同样的问题
is1-ssl.mzstatic.com:443

**Comment by Karitsuki** [comment]
问题已解决
