### ISSUE TITLE
Twitter规则匹配错误

### ISSUE THREAD

**Issue by eli-yip** [blackmatrix7/ios_rule_script#1169]
规则名称：twitter.list

规则链接：[https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list)

异常规则：IP-CIDR 199.16.156.0/22

问题描述：错误匹配了`www.google.com`的规则

抓包截图：(相关抓包工具的截图。)

```

16:35:27.185203 [Connection] Incoming proxy protocol: HTTP
16:35:27.185251 [TLS] TLS Client Hello SNI: www.google.com
16:35:27.185352 [Rule] Rule evaluating requires DNS lookup for rule: RULE-SET LAN
16:35:27.185415 [Rule] DNS completed in 0.05ms, IPv4 address for matching: 199.16.158.8, IPv6 address for matching: N/A
16:35:27.185581 [Rule] Sub-rule matched: IP-CIDR 199.16.156.0/22(Twitter.list)
16:35:27.185591 [Rule] Rule matched: RULE-SET Twitter.list
```

调整方案：(你希望规则做哪些调整，及其原因。)

调整这个规则。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
