### ISSUE TITLE
BardAI缺失域名

### ISSUE THREAD

**Issue by toyo2333** [blackmatrix7/ios_rule_script#1172]
gemini.google.com

现在需要这个了。不知道除了这个还有没有其他需要的。

**Comment by young1023x2** [comment]
bard正式改名了，现在是gemini，域名也换了

**Comment by lwore** [comment]
Hi，我是该库的 BardAI 来源作者，我已经重新抓包修改域名了，安卓实测可用。等 Blackmatrix 7 脚本自动重新获取就可以了。

**Comment by lwore** [comment]
等他脚本自动更新。

**Comment by habbiedev** [comment]
目前貌似还没更

**Comment by blackmatrix7** [comment]
感谢提供，稍后更新。
