### ISSUE TITLE
zhihuads页面的空链接

### ISSUE THREAD

**Issue by 2583538** [blackmatrix7/ios_rule_script#1173]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：zhihuads

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/ZhihuAds

异常规则：

问题描述：此页面提示“本分流规则，需要搭配 https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu 使用。” 但是以上链接点开是空的

抓包截图：(无)

调整方案：(无)

**Comment by 2583538** [comment]
另外大佬，萤石云视频和keep的开屏去广告失效了，可否在您有空的时候修正一下呀，全网找不到好用的。

**Comment by blackmatrix7** [comment]
谢谢反馈，已修改。另外两个APP，目前没精力进行处理，不好意思。
