### ISSUE TITLE
高德导航的网络异常

### ISSUE THREAD

**Issue by 2583538** [blackmatrix7/ios_rule_script#1176]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：高德导航

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/GaoDe

异常规则：

问题描述：开启高德导航规则的话，会比较频繁出现网络不畅的情况。关闭则消失，检查发现大陆网站里面存在amap.com, 不知道是互相冲突还是什么？

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
目前高德长期使用未发现问题，需要进一步提供一些日志。issue我先关闭，提供完日志再打开。
