### ISSUE TITLE
哔哩哔哩去开屏广告时在某些网络状态下失效

### ISSUE THREAD

**Issue by KANGNAMEMEDA** [blackmatrix7/ios_rule_script#118]
iPhone使用联通4g没问题
iPad使用移动wifi开屏广告必定有
iPhone使用移动Wi-Fi必定有
配置一样 软件quantumult x

**Comment by blackmatrix7** [comment]
我没有移动卡，也没有移动WIFI，没办法帮你验证这个问题……
除非B站针对移动网络有什么特别的响应，否则不应该会出这种问题。
你可以把抓包的响应体发我看下。

**Comment by lzr52o** [comment]
哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效

**Comment by lzr52o** [comment]
> iPhone使用联通4g没问题
> iPad使用移动wifi开屏广告必定有
> iPhone使用移动Wi-Fi必定有
> 配置一样 软件quantumult x
——————————————————————
•iPhone11 网络Wi-Fi
•联通宽带
•软件 （Quantumult X）

**Comment by blackmatrix7** [comment]
> 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效

什么版本的？

**Comment by lzr52o** [comment]
> > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> 
> 什么版本的？

哔哩哔哩App Store最新版本
QuantumultX App Store最新版本

**Comment by blackmatrix7** [comment]
> > > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> > 
> > 
> > 什么版本的？
> 
> 哔哩哔哩App Store最新版本
> QuantumultX App Store最新版本

提供一下出现异常的日志吧，我这里复现不了这个问题。

**Comment by lzr52o** [comment]
> > > > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> > > 
> > > 
> > > 什么版本的？
> > 
> > 
> > 哔哩哔哩App Store最新版本
> > QuantumultX App Store最新版本
> 
> 提供一下出现异常的日志吧，我这里复现不了这个问题。

我把重写的去广告规则都关掉就失效了，打开也是失效的甚至打开获取Cookie也能掉登陆 登陆提示API校验密钥错误
2020/12/21 11:45:12:915  <error>      [JS Console]: undefined is not an object (evaluating 'obj["data"]["vip"]').
2020/12/21 11:45:12:918  <error>      [JS Console]: Exception undefined is not an object (evaluating 'obj["data"]["vip"]'), https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilifj.js

**Comment by blackmatrix7** [comment]
https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilifj.js

这个不是我的脚本啊……

**Comment by blackmatrix7** [comment]
> > > > > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> > > > 
> > > > 
> > > > 什么版本的？
> > > 
> > > 
> > > 哔哩哔哩App Store最新版本
> > > QuantumultX App Store最新版本
> > 
> > 
> > 提供一下出现异常的日志吧，我这里复现不了这个问题。
> 
> 我把重写的去广告规则都关掉就失效了，打开也是失效的甚至打开获取Cookie也能掉登陆 登陆提示API校验密钥错误
> 2020/12/21 11:45:12:915 [JS Console]: undefined is not an object (evaluating 'obj["data"]["vip"]').
> 2020/12/21 11:45:12:918 [JS Console]: Exception undefined is not an object (evaluating 'obj["data"]["vip"]'), https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilifj.js

这个不是我的脚本……

**Comment by lzr52o** [comment]
> > > > > > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> > > > > 
> > > > > 
> > > > > 什么版本的？
> > > > 
> > > > 
> > > > 哔哩哔哩App Store最新版本
> > > > QuantumultX App Store最新版本
> > > 
> > > 
> > > 提供一下出现异常的日志吧，我这里复现不了这个问题。
> > 
> > 
> > 我把重写的去广告规则都关掉就失效了，打开也是失效的甚至打开获取Cookie也能掉登陆 登陆提示API校验密钥错误
> > 2020/12/21 11:45:12:915 [JS Console]: undefined is not an object (evaluating 'obj["data"]["vip"]').
> > 2020/12/21 11:45:12:918 [JS Console]: Exception undefined is not an object (evaluating 'obj["data"]["vip"]'), https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilifj.js
> 
> 这个不是我的脚本……

大佬你的脚本给一下

**Comment by blackmatrix7** [comment]
> > > > > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> > > > 
> > > > 
> > > > 什么版本的？
> > > 
> > > 
> > > 哔哩哔哩App Store最新版本
> > > QuantumultX App Store最新版本
> > 
> > 
> > 提供一下出现异常的日志吧，我这里复现不了这个问题。
> 
> 我把重写的去广告规则都关掉就失效了，打开也是失效的甚至打开获取Cookie也能掉登陆 登陆提示API校验密钥错误
> 2020/12/21 11:45:12:915 [JS Console]: undefined is not an object (evaluating 'obj["data"]["vip"]').
> 2020/12/21 11:45:12:918 [JS Console]: Exception undefined is not an object (evaluating 'obj["data"]["vip"]'), https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilifj.js

看了下，两个脚本的复写冲突了，没办法共存。

https:\/\/ap(p|i)\.bilibili\.com\/((pgc\/player\/api\/playurl)|(x\/v2\/account\/myinfo\?)|(x\/v2\/account/mine\?)) url script-response-body BiliHD.js

这个暂时没什么办法，只能我把他的脚本集成进来，但是近期没有这个计划。

**Comment by lzr52o** [comment]
> > > > > > 哔哩哔哩去广告，开启1080+失效一周了，大神求修复，现在重写开启去广告就会掉登陆哔哩哔哩提示API失效
> > > > > 
> > > > > 
> > > > > 什么版本的？
> > > > 
> > > > 
> > > > 哔哩哔哩App Store最新版本
> > > > QuantumultX App Store最新版本
> > > 
> > > 
> > > 提供一下出现异常的日志吧，我这里复现不了这个问题。
> > 
> > 
> > 我把重写的去广告规则都关掉就失效了，打开也是失效的甚至打开获取Cookie也能掉登陆 登陆提示API校验密钥错误
> > 2020/12/21 11:45:12:915 [JS Console]: undefined is not an object (evaluating 'obj["data"]["vip"]').
> > 2020/12/21 11:45:12:918 [JS Console]: Exception undefined is not an object (evaluating 'obj["data"]["vip"]'), https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilifj.js
> 
> 看了下，两个脚本的复写冲突了，没办法共存。
> 
> https://ap(p|i).bilibili.com/((pgc/player/api/playurl)|(x/v2/account/myinfo?)|(x/v2/account/mine?)) url script-response-body BiliHD.js
> 
> 这个暂时没什么办法，只能我把他的脚本集成进来，但是近期没有这个计划。

谢谢🙏

**Comment by ICan1DO** [comment]
联通签到脚本的loon配置链接好像写错了，文件格式不对

**Comment by blackmatrix7** [comment]
> 联通签到脚本的loon配置链接好像写错了，文件格式不对
Loon这个是远程脚本，不是插件。

**Comment by blackmatrix7** [comment]
修复了一处去除开屏广告的Bug，你再试试，如果有问题再反馈。
