### ISSUE TITLE
hamreus.com域名整体非国内IP 

### ISSUE THREAD

**Issue by guangmingLQ** [blackmatrix7/ios_rule_script#1180]
规则名称：所有chinaMAX规则

异常规则：DOMAIN-SUFFIX,hamreus.com

问题描述：此规则已经失效 IPIP查询为广播国外IP

调整方案：移除出所有chinamax系列规则列表

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，晚些时候更新。
