### ISSUE TITLE
clash去广告m.ctrip.com连接阻断

### ISSUE THREAD

**Issue by weijingcheng4** [blackmatrix7/ios_rule_script#1191]
规则名称：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/AdvertisingTest

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingTest/AdvertisingTest_Classical.yaml

异常规则：携程app m.ctrip.com

问题描述：连接阻断

**Comment by weijingcheng4** [comment]
![Uploading 截屏2024-03-07 21.29.09.png…]()

**Comment by weijingcheng4** [comment]
账户和登录等相关信息会被阻断

**Comment by weijingcheng4** [comment]
现在已经不维护规则了吗

**Comment by blackmatrix7** [comment]
现在看已经移除了，规则还在维护，但是目前工作比较繁忙，只能抽空来调整一下。

**Comment by weijingcheng4** [comment]
![截屏2024-05-25 07 23 59](https://github.com/blackmatrix7/ios_rule_script/assets/49937971/e557803c-c836-4239-b0d1-3488ed0ce656)
又有了，呜呜呜
