### ISSUE TITLE
Roblox 2#

### ISSUE THREAD

**Issue by hamugua** [blackmatrix7/ios_rule_script#1193]
规则名称：Roblox

异常规则：无

问题描述：增加

调整方案：建议增加：- IP-CIDR,128.116.55.33/16,no-resolve

**Comment by blackmatrix7** [comment]
这是个错误的IP-CIDR规则，所以没办法正常添加进去。

网络前缀设置了16，但是设置了主机位，互相冲突了。

不知道是否需要设置为128.116.0.0/16？

**Comment by hamugua** [comment]
是的，等价于这个
