### ISSUE TITLE
OpenAI新增了一个域名，如果分流错误，会导致IOS客户端无法登录。

### ISSUE THREAD

**Issue by lin1123** [blackmatrix7/ios_rule_script#1194]
```
ab.chatgpt.com
```

GPT又增加了一个检测域名，要是这个域名分流不对就会导致登录不上账号。我主要在IOS上复现

**Comment by yesanshao007** [comment]
同样的问题，报错如图所示
![IMG_3024](https://github.com/blackmatrix7/ios_rule_script/assets/42309868/408bbbb4-22ae-4b69-8820-ad30b78e54ab)

**Comment by Jetive** [comment]
确实有一个新域名
ab.chatgpt.com:443
用Quantumult X时分分流错误。

**Comment by blackmatrix7** [comment]
DOMAIN-SUFFIX,chatgpt.com 可以覆盖 ab.chatgpt.com

QuanX需要看下规则的优先级
