### ISSUE TITLE
Clash去广告规则有误判，请处理一下

### ISSUE THREAD

**Issue by maplestory** [blackmatrix7/ios_rule_script#1197]
Clash去广告规则有误判，请处理一下

------

规则名称：Clash去广告规则（路径如下）

> rule/Clash/Advertising

规则链接：

> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising.list
> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising.yaml
> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Classical.yaml
> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Classical_No_Resolve.yaml
> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Domain.txt
> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Domain.yaml
> https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Domain_For_Clash.txt

异常规则：

问题描述：

1. 在电脑端打开“得到”官网（[www.dedao.cn](https://www.dedao.cn/)）时，网页始终是一片空白，今天刚好有空，就仔细检查了一下，发现和umiwi.com域名相关的资源都是无法访问，但我用手机测试了一下，这些资源是正常的js脚本，并非广告；
2. 我想到了把dedao作为独立的RuleSet，但Clash重启后，仍然不能正常访问“得到”官网；
3. 我把后台的广告规则改为直连，此时访问umiwi.com主页，发现这是“得到”电子书的官网，见【抓包截图1】；
4. 我检查了clash的后台日志，原来它真的被劫持到广告规则里了，见【抓包截图2】；
5. 我搜索了"去广告"里每个文件，发现都有一条和umiwi.com相关的记录，但dedao的规则里却没有这一条记录

抓包截图：(相关抓包工具的截图。)
![企业微信截图_17101458758282](https://github.com/blackmatrix7/ios_rule_script/assets/2831978/bfb21f31-a794-461a-aca5-30458e3cebbe)
![企业微信截图_17101463382336](https://github.com/blackmatrix7/ios_rule_script/assets/2831978/8cc0d1a7-fd5b-4d41-ab2e-a3b7d139660d)

调整方案：(你希望规则做哪些调整，及其原因。) 
首先感谢作者们的辛勤付出，虽然我可以在放行规则里增加修正，但仍希望能将umiwi.com这条记录从去广告规则中移除，因为我希望在继续使用去广告规则的前提下，也能在电脑上看“得到”电子书。
再次感谢各位作者大佬！

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
