### ISSUE TITLE
张大妈APP获取

### ISSUE THREAD

**Issue by shaGuar-svg** [blackmatrix7/ios_rule_script#12]
2020-09-28 13:31:29.718590 <NOTIFY> [SGJSVM] [什么值得买_获取账号密码]
13:31:29.708965 [WARNING] [什么值得买]
获取账号密码时请求数据不合法 。
请求数据：undefined

最新版张大妈app获取账号密码日志会报非法导致账户被锁

**Comment by blackmatrix7** [comment]
#9 
我猜你用的是Surge，参考上面的试试。

**Comment by shaGuar-svg** [comment]
Okey
