### ISSUE TITLE
钉钉误杀

### ISSUE THREAD

**Issue by BaileyZyp** [blackmatrix7/ios_rule_script#120]
retcode.taobao.com
请放行此条域名，拦截此域名会导致钉钉加班申请页面加载不完全，不能正常填写加班时间

**Comment by blackmatrix7** [comment]
我全局搜索没搜出这个规则
https://github.com/blackmatrix7/ios_rule_script/search?q=retcode
能否详细说下是在哪个文件里找到的？
如果是稳定版，在实时版新增的这些功能稳定前暂时没办法更新。

**Comment by BaileyZyp** [comment]
![036D8C50-9279-4A62-88B0-C1FD3A9B22FC](https://user-images.githubusercontent.com/16634459/102830592-9852b280-4424-11eb-84e6-9ddef5856427.png)
要么在Advertising要么在Privacy里，我就这俩Domain-SET

**Comment by blackmatrix7** [comment]
已经加入过滤器，明天更新一下就好了。

**Comment by BaileyZyp** [comment]
@blackmatrix7 这条域名还是未放行

**Comment by BaileyZyp** [comment]
Advertising_Domain 在这个文件里面

**Comment by blackmatrix7** [comment]
之前重构了规则之间的父子关系，Privacy没有加入过滤器，所以会把规则再带入到Advertising，现在已经加到过滤器中了，晚些时候会做个更新。

**Comment by blackmatrix7** [comment]
已更新
