### ISSUE TITLE
如何制定规则对应的区域

### ISSUE THREAD

**Issue by NiuCoder** [blackmatrix7/ios_rule_script#1201]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
必应
规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Shadowrocket/Bing
异常规则：

问题描述：
在shadowsocket中设置该规则， 如何指定规则对应的区域，因为copilot应用需要制定国外的区域才能用。我尝试指定了策略为TW，发现不行。
抓包截图：(相关抓包工具的截图。)
![421ac31d150537a607e2f2619944def](https://github.com/blackmatrix7/ios_rule_script/assets/13538998/bf30b50b-b215-4bc6-8179-af527aa77f33)
![c20ac7b61c343242d3d38bee4570f15](https://github.com/blackmatrix7/ios_rule_script/assets/13538998/48d5c53b-8123-45c6-9e52-8b732af5e968)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
这个需要搜索对应的服务，分流规则只是把域名和IP等进行分类。
