### ISSUE TITLE
圈X的allinone故障

### ISSUE THREAD

**Issue by Sagittarius16th** [blackmatrix7/ios_rule_script#1205]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：

APP版本：

客户端名称：

客户端版本：

问题描述：

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

路径如下：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/QuantumultX/AllInOne
打开只有几条去知乎广告的重写。

**Comment by blackmatrix7** [comment]
现在看是正常的
