### ISSUE TITLE
什么值得买签到脚本未能结束运行

### ISSUE THREAD

**Issue by Wo1framalpha** [blackmatrix7/ios_rule_script#121]
问题：什么值得买脚本（smzdm_checkin.js）在输出账户信息后无法正常结束

运行环境：Quantumult X

日志：
2020/12/23 10:04:33:422  <console>    [JS Console]: [ERROR] [什么值得买] 获取用户信息失败，异常信息：TypeError: null is not an object (evaluating 'pointTimeList.length')
2020/12/23 10:04:33:679  <console>    [JS Console]: [INFO] [什么值得买]
昵称：xxxxx
Web端签到状态：true
签到前等级5，积分3300，经验null，金币114，碎银子278，威望null, 未读消息0

问题出现时间：2020.12.23

**Comment by jiegto** [comment]
同样报上述错误：获取用户信息失败，异常信息：TypeError: Cannot read property 'length' of null

 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
16
    at Main (/smzdm_checkin.js:869:30)

**Comment by blackmatrix7** [comment]
已知问题，什么值得买的html改了，目前我自己测试的版本已修复，再测试个一两天没问题就会更新上来。

不过没办法再像以前获取那么多经验了，部分任务改为只能在APP中完成。

**Comment by jiegto** [comment]
即使如此还是非常的赞，期待更新

**Comment by Wo1framalpha** [comment]
> 已知问题，什么值得买的html改了，目前我自己测试的版本已修复，再测试个一两天没问题就会更新上来。
> 
> 不过没办法再像以前获取那么多经验了，部分任务改为只能在APP中完成。

感谢大佬修正！！！

其实获得的经验够保级就满足了，主要还是图个签到

**Comment by blackmatrix7** [comment]
已更新
