### ISSUE TITLE
Apple.yaml规则缺失严重，Apple.list却没问题

### ISSUE THREAD

**Issue by makaspacex** [blackmatrix7/ios_rule_script#1210]
规则名称：rule/Clash/Apple/Apple.yaml

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml

异常规则：整个规则异常

问题描述：缺少了很多规则

抓包截图：
<img width="1149" alt="image" src="https://github.com/blackmatrix7/ios_rule_script/assets/16874796/ca4ba09a-4eb8-4612-8982-4fcbfb987ee4">

调整方案：盲猜是转换脚本出了问题，导致生成的规则文件出错

**Comment by PingZi-Wing** [comment]
注意看该页面下的配置建议，你引用错了

**Comment by makaspacex** [comment]
> 注意看该页面下的配置建议，你引用错了

好的 我的锅🤦
