### ISSUE TITLE
请求更新copilot规则，添加域名 DOMAIN,sydney.bing.com

### ISSUE THREAD

**Issue by Thresh-Frazier** [blackmatrix7/ios_rule_script#1211]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
rule/Clash/Copilot/Copilot.list

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Copilot/Copilot.list

异常规则：
无

问题描述：
经测试，Clash中使用该规则可以调出Copilot，但回答时提示正在尝试重新连接。后经自己抓包，发现域名 sydney.bing.com  不在规则中，加入规则后Copilot可正常回复，故申请更新。

抓包截图：(相关抓包工具的截图。)
![屏幕截图 2024-03-25 124541](https://github.com/blackmatrix7/ios_rule_script/assets/21073721/1d8620a1-40f8-49e6-bda8-73156801908d)

调整方案：
规则中补充 DOMAIN,sydney.bing.com

Tips:
新版Edge中无法添加搜索引擎bing源的可以F12控制台中删除disabled，修改URL后保存，确保bing的位置不被锁定
![Tips](https://github.com/blackmatrix7/ios_rule_script/assets/21073721/5c9b0f55-4499-4bfa-bb5b-ff7a9ed8af63)

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后会进行更新。
