### ISSUE TITLE
广告规则可能有些问题，容易误杀

### ISSUE THREAD

**Issue by qinyq** [blackmatrix7/ios_rule_script#1213]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：HOST-KEYWORD,volc,Advertising

问题描述：
这个关键字太容易误杀了，比如火山引擎https://www.volcengine.com，包含这个关键字，就会被直接拒绝

还有一些其它的问题，暂时没找到是哪条规则导致的，就是无法接入飞书会议，等查到之后再更新。

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

去掉这行规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，对于上游增加的DOMAIN-KEYWORD，的确很容易出现误差。

稍后会进行更新。
