### ISSUE TITLE
AdvertisingLite导致Soul异常

### ISSUE THREAD

**Issue by LecherousMan** [blackmatrix7/ios_rule_script#1218]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite

规则链接：

异常规则：ssp.soulapp.cn

问题描述：网络异常

抓包截图：![image](https://github.com/blackmatrix7/ios_rule_script/assets/121013939/0e554999-fcf8-4022-86a0-8a260fbdf002)
![image](https://github.com/blackmatrix7/ios_rule_script/assets/121013939/e15ad6b1-2034-4163-9a0c-dca1de1e55a8)
调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by LecherousMan** [comment]
规则链接：https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list

**Comment by blackmatrix7** [comment]
目前没有在文件里找到这个规则，可能是上游已移除。
