### ISSUE TITLE
Surge/Alibaba规则

### ISSUE THREAD

**Issue by sydneygao** [blackmatrix7/ios_rule_script#1221]
规则名称：Alibaba （Surge）
规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Alibaba/Alibaba.list
问题描述：域名忘记写“.com”
DOMAIN-SUFFIX,alibaba
DOMAIN-SUFFIX,taobao
DOMAIN-SUFFIX,tmall

**Comment by sydneygao** [comment]
规则名称：Alibaba （Surge）
规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Alibaba/Alibaba.list
问题描述：域名忘记写“.com”
DOMAIN-SUFFIX,alibaba
DOMAIN-SUFFIX,taobao
DOMAIN-SUFFIX,tmall

**Comment by blackmatrix7** [comment]
DOMAIN-SUFFIX,alibaba
DOMAIN-SUFFIX,taobao
DOMAIN-SUFFIX,tmall 

都是顶级域名，所以规则没有问题。

可以存在例如 qq.taobao这样的域名
