### ISSUE TITLE
哲也模块去广告部分

### ISSUE THREAD

**Issue by Meonthb** [blackmatrix7/ios_rule_script#1222]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：哲也同学

APP版本：知乎 10.0.0 (18018)

客户端名称：Surge

客户端版本：5.10.0 (Build 3086, SDK17.0)

问题描述：回答页面下方出现广告，推荐页面也出现广告文章。

复现方式：

每次打开知乎都会这样，开屏广告等可以正常屏蔽，但上诉广告已经无法屏蔽。

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
更新到最新版，未能复现此问题，希望能进一步提供日志。
