### ISSUE TITLE
claude.ai域名重复

### ISSUE THREAD

**Issue by yaaisinile** [blackmatrix7/ios_rule_script#1224]
规则名称：ProxyLite

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/ProxyLite/ProxyLite.list

异常规则：claude.ai

问题描述：claude.ai已经存在于claude规则里会跟proxylite冲突

**Comment by blackmatrix7** [comment]
谢谢反馈，已经做了移除，稍后更新。
