### ISSUE TITLE
MITM“frodo.douban.com”会导致豆瓣APP影视作品详情无法打开

### ISSUE THREAD

**Issue by noobsora** [blackmatrix7/ios_rule_script#1225]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：复写去广告（严格版）

APP版本：豆瓣

客户端名称：quantumultx

客户端版本：1.5.0-828

问题描述：MITM“frodo.douban.com”会导致豆瓣APP影视作品详情无法打开

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
谢谢反馈，已经移除，稍后更新。
