### ISSUE TITLE
AdvertisingLite 导致bytedance 误杀

### ISSUE THREAD

**Issue by pujiaxun** [blackmatrix7/ios_rule_script#1226]
规则名称：
AdvertisingLite.list

规则链接：
rule/QuantumultX/AdvertisingLite/AdvertisingLite.list

异常规则：
```
HOST-SUFFIX,bytedance.com,AdvertisingLite
HOST-SUFFIX,bytegoofy.com,AdvertisingLite
HOST-SUFFIX,byteimg.com,AdvertisingLite
HOST-SUFFIX,byteorge.com,AdvertisingLite
```

问题描述：
这只是一个 ad block *lite* 规则呀，怎么可以直接屏蔽二级域名bytedance.com呀？
这直接导致无法使用飞书会议，应该还有不少其他影响。

抓包截图：(相关抓包工具的截图。)
RTC 相关域名的请求都被拦截，导致音视频通话失败。

![image](https://github.com/blackmatrix7/ios_rule_script/assets/13177974/38632ba8-3fe2-4708-90c7-86eaabc723e6)

调整方案：(你希望规则做哪些调整，及其原因。)

可以针对 bytedance 子域名细化规则，不要直接屏蔽二级域名

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。因为规则是采集自上游的，对于这类上游的规则问题，目前无法做到事前预防，只能时候发现再进行移除。

你可以尝试使用release分支下的文档版本，不会自动更新。
