### ISSUE TITLE
TikTok 规则 需要手动修订

### ISSUE THREAD

**Issue by Accademia** [blackmatrix7/ios_rule_script#1228]
规则名称：
TikTok

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/TikTok/TikTok_No_Resolve.yaml

异常规则：
bytegecko.com

问题描述：
会拦截大量的懂车帝链接

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

 - DOMAIN-KEYWORD, cdn-tos-ncdn.bytegecko.com          , DIRECT 
 - DOMAIN-KEYWORD, dcd-cdn-tos.bytegecko.com           , DIRECT 
 - DOMAIN-KEYWORD, webcast-cdn-tos.bytegecko.com       , DIRECT 
 - DOMAIN-KEYWORD, webcast-cdn-tos-ncdn.bytegecko.com  , DIRECT 

按尚书调整后则暂时无拦截情况。

我怀疑Tiktok和抖音分家后，bytegecko.com很大概率已经不再被Tiktok所使用。

**Comment by blackmatrix7** [comment]
谢谢反馈，已处理。
