### ISSUE TITLE
Steam规则覆盖不全，有漏网之鱼，导致无法下载

### ISSUE THREAD

**Issue by Accademia** [blackmatrix7/ios_rule_script#1230]
规则名称：
Steam

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Steam/Steam_No_Resolve.yaml

异常规则：

问题描述：
规则覆盖不全，有漏网之鱼，导致无法下载

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
- DOMAIN-SUFFIX  , steamserver.net      
需要添加如上规则

**Comment by blackmatrix7** [comment]
steamserver.net 在SteamCN中，因为在Steam排除了SteamCN，建议两个搭配使用。
