### ISSUE TITLE
广告拦截规则，会导致抖音web、抖音app搜索表情加载不出来

### ISSUE THREAD

**Issue by ChenYueC** [blackmatrix7/ios_rule_script#1232]
规则名称：
    广告拦截精简版

规则链接：
    https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml（包括但不限于精简版及Clash规则）

异常规则及问题描述：
    - DOMAIN-SUFFIX,bytegoofy.com （会导致抖音网页版，页面加载失败。lf3-cdn-tos.bytegoofy.com 放行后正常加载）
    - DOMAIN-SUFFIX,byteimg.com    （会导致抖音app加载异常。1、包括但不限于，p3-piu或p6-piu、p9-piu、p26-piu、p3-ecop-image等前缀的导致抖音商城，商品图片加载不出来。2、搜索的表情包加载失败。p3-heycan-dy-sign.byteimg.com，p9-heycan-dy-sign.byteimg.com 放行后正常加载）

抓包截图：(相关抓包工具的截图。)
     抖音网页版  
![image](https://github.com/blackmatrix7/ios_rule_script/assets/82785993/bac46e63-0296-40ad-b9d2-33c6e6da84b6)
    分流规则走向
![image](https://github.com/blackmatrix7/ios_rule_script/assets/82785993/6806b708-fbd4-4595-a3a6-803c7cfc76b4)

    抖音app
![13d212a8b221e1d74c1859ed9cde5eb](https://github.com/blackmatrix7/ios_rule_script/assets/82785993/d8de7303-0f21-4412-a6db-52cb460d714d)
   分流规则走向
![9f647d8ce061cf7567215f0bff586c1](https://github.com/blackmatrix7/ios_rule_script/assets/82785993/be9082a6-2e84-487b-b3e2-8857067142cf)

调整方案：(你希望规则做哪些调整，及其原因。)
   直连修正规则中加入如上地址

**Comment by blackmatrix7** [comment]
感谢反馈，已移除，稍后更新。
