### ISSUE TITLE
联通签到异常

### ISSUE THREAD

**Issue by r0ckmifan** [blackmatrix7/ios_rule_script#124]
cookie前两天刚获取的，今天显示签到异常。

[INFO] [中国联通]
新版签到异常，接口返回数据不合法。{"msg":"您还没有登录，快去登录吧","status":"0001"}

[ERROR] [中国联通]
签到异常

[ERROR] [中国联通]
签到异常

[INFO] [中国联通]
获取连续签到次数失败，接口响应不合法。{"toLogin":"https://act.10010.com/SigninApp/signin/querySigninActivity.htm"}

[INFO] [中国联通]
获取用户信息异常，接口响应不合法：{"timestamp":"2020-12-25T00:33:38.334+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/mobileserviceimportant/home/queryUserInfoSeven"}

[ERROR] [中国联通]
获取用户信息接口响应异常

**Comment by blackmatrix7** [comment]
Cookie过期时间是联通在服务器上设置的，非脚本可以控制，没办法。
