### ISSUE TITLE
clash 规则问题

### ISSUE THREAD

**Issue by lonecale** [blackmatrix7/ios_rule_script#1241]
规则名称：
Telegram
规则链接：
[Telegram](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Telegram/Telegram.list)

问题描述：
缺少IP-ASN规则 但是QX的规则是有的，clash的规则类型能否增加IP-ASN 规则，clash 是支持 IP-ASN类型匹配的

**Comment by snachx** [comment]
Facebook 规则也是，clash 规则里面 IP-ASN 条目被忽略掉了
原版 clash 删库之后 现在通行的 clashmeta (mihomo) 已经支持 IP-ASN 了
希望可以把 IP-ASN 条目保留下来

**Comment by blackmatrix7** [comment]
已经支持，晚些时候会更新。

**Comment by FAST0888** [comment]
Clash 原版库 CFA 不支持IP-ASN 规则更新直接报错呀？如何解决

**Comment by FAST0888** [comment]
> 已经支持，晚些时候会更新。

Clash 原版库 CFA 不支持IP-ASN 规则更新直接报错呀？如何解决

**Comment by snachx** [comment]
换成 clash meta for android？

**Comment by FAST0888** [comment]
> 换成 clash meta for android？

这个太麻烦了，因为CFA 3.03版本可以在Root环境下 直接使用Transport Proxy

**Comment by lonecale** [comment]
> > 换成 clash meta for android？
> 
> 这个太麻烦了，因为CFA 3.03版本可以在Root环境下 直接使用Transport Proxy

可以尝试使用在线订阅转换，如果支持订阅链接，现在大多数订阅默认过滤了IP-ASN，当然更建议使用clash meta for android

**Comment by FAST0888** [comment]
> 已经支持，晚些时候会更新。

可否多生成一个Clash 原版 不含IP-ASN 规则配置？

**Comment by FAST0888** [comment]
> 可是原版都已经删库不会再维护了，不能就此止步吧？你说的功能clash meta for android 不行吗？

CMFA 做不到使用Transport Proxy

**Comment by FAST0888** [comment]
> 已经支持，晚些时候会更新。

可否不需要IP-ASN 照顾一下Clash源库群体规则正常更新（每天涉及到这样规则的天天报错），CFW也不支持这个
