### ISSUE TITLE
QuantumultX 规则组：Proxy

### ISSUE THREAD

**Issue by bowzhung** [blackmatrix7/ios_rule_script#1243]
规则名称： Proxy

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Proxy/Proxy.list

异常规则：

问题描述：因为规则组使用名称是Proxy，且每条规则后面指向Proxy，导致这个规则组无法在QuantumultX使用节点分组，我默认走一个固定的节点。

抓包截图：
![Uploading 截屏2024-04-18 23.58.33.png…]()

调整方案：这个策略组非常好用，建议能否换成其他的名称，如：output ?!

**Comment by bowzhung** [comment]
![Uploading 截屏2024-04-18 23.58.33.png…]()

**Comment by luoweihua7** [comment]
QuantumutX使用规则集的时候，不是可以使用force-policy指定规则的么？你试试指定一个自己的节点分组

**Comment by bowzhung** [comment]
> QuantumutX使用规则集的时候，不是可以使用force-policy指定规则的么？你试试指定一个自己的节点分组



> QuantumutX使用规则集的时候，不是可以使用force-policy指定规则的么？你试试指定一个自己的节点分组

确实是可以指定规则的，但是 Qx 的 bug 还是怎样，指定会无效，因为这个规则集里面每一条后面都指向Proxy

**Comment by blackmatrix7** [comment]
> > QuantumutX使用规则集的时候，不是可以使用force-policy指定规则的么？你试试指定一个自己的节点分组
> 
> > QuantumutX使用规则集的时候，不是可以使用force-policy指定规则的么？你试试指定一个自己的节点分组
> 
> 确实是可以指定规则的，但是 Qx 的 bug 还是怎样，指定会无效，因为这个规则集里面每一条后面都指向Proxy

目前这么配置是有效的，我长期这么使用，可能需要再找找其他原因。
