### ISSUE TITLE
rule/Loon/LinkedIn/LinkedIn.list

### ISSUE THREAD

**Issue by QinSisuo** [blackmatrix7/ios_rule_script#1249]
应新增www.linkedin.com方可正常访问

**Comment by blackmatrix7** [comment]
DOMAIN-SUFFIX,linkedin.com 已经包括 www.linkedin.com了

**Comment by QinSisuo** [comment]
> DOMAIN-SUFFIX,linkedin.com 已经包括 www.linkedin.com了

谢谢，当时是我的其他原因导致无法访问，已解决，谢谢，辛苦
