### ISSUE TITLE
Clash 不支持IP-ASN最新规则里例如telegram有IP-ASN导致无法使用

### ISSUE THREAD

**Issue by Kai4real** [blackmatrix7/ios_rule_script#1252]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Telegram

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml

异常规则：  - IP-ASN,211157
  - IP-ASN,44907
  - IP-ASN,59930
  - IP-ASN,62014
  - IP-ASN,62041

问题描述：Clash 不支持IP-ASN,Facebook规则下也有这个问题

抓包截图：(相关抓包工具的截图。)

调整方案：删除IP-ASN相关规则

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/issues/1241

根据上述反馈，现在已经支持ASN了。

你可以更新下内核，或者使用release分支下的，目前尚未添加对ASN的支持。
