### ISSUE TITLE
OpenAI 规则可否单独有过滤掉ip-asn的版本?

### ISSUE THREAD

**Issue by lovitus** [blackmatrix7/ios_rule_script#1253]
作者你好.
一直使用你的OpenAI规则
    `ios_rule_script/rule/Clash/OpenAI/`
但是昨天的更新加入了 `ip-asn`, 这个只有meta内核才支持.
请问能否在这个目录内单独有一个  OpenAI-noipasn.yaml的版本 去兼容非meta内核?
谢谢你.

**Comment by blackmatrix7** [comment]
因为这个内核已经不更新了，所以肯定是向最新的版本兼容，目前没有创建单独剔除IP-ASN规则的计划。

你可以从之前的提交记录里找一个不带IP-ASN的。
