### ISSUE TITLE
Privacy.list  Surge  分流规则 只有3条记录？

### ISSUE THREAD

**Issue by FAST0888** [blackmatrix7/ios_rule_script#126]

**Comment by blackmatrix7** [comment]
超过1000条会移动到Domain.list

**Comment by FAST0888** [comment]
请问我怎么使用？

**Comment by blackmatrix7** [comment]
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Privacy/Domain.list
