### ISSUE TITLE
sub web 订阅转换有一个远程配置，需要ini后缀名的。一直不明白怎么在订阅转换用这个？

### ISSUE THREAD

**Issue by gygy** [blackmatrix7/ios_rule_script#1269]
sub web 订阅转换有一个远程配置，需要ini后缀名的。一直不明白怎么在订阅转换用这个？ 还有有一个总的链接不？

**Comment by keay250** [comment]
这个仓库主要不是给规则转换用的,规则转换基本上要用到acl4ssr的仓库,那边有现成的ini格式,但是没有这边那么全
比较好的解决方法是你自己爬取surge的规则集并转换成ini提交到你自己仓库去用
一劳永逸的方法是抛弃订阅转换的方案,改用手写配置

**Comment by gygy** [comment]
> 这个仓库主要不是给规则转换用的,规则转换基本上要用到acl4ssr的仓库,那边有现成的ini格式,但是没有这边那么全
> 
> 比较好的解决方法是你自己爬取surge的规则集并转换成ini提交到你自己仓库去用
> 
> 一劳永逸的方法是抛弃订阅转换的方案,改用手写配置

手写配置，surge下面这么多子文件夹和规则，需要自己一条一条写？后面这里更新了规则，手工那套要怎么更新

**Comment by keay250** [comment]
> surge下面这么多子文件夹和规则，需要自己一条一条写？

不需要,根据自己需求选择相应的规则即可,例如如果你需要youtube,twitter,google的分流,那就只需要选择对应的规则文件就行了

> 后面这里更新了规则，手工那套要怎么更新

无论是surge,clash,qx之类的工具,都支持"引用规则集"的操作,也就是所谓的"外部资源".将你需要的使用的规则文件地址根据分流需求写入配置文件里,首次启动或配置文件变动时会自动更新规则,后续也可以通过手动更新外部资源来批量更新你引用的规则集

**Comment by gygy** [comment]
> > surge下面这么多子文件夹和规则，需要自己一条一条写？
> 
> 
> 
> 不需要,根据自己需求选择相应的规则即可,例如如果你需要youtube,twitter,google的分流,那就只需要选择对应的规则文件就行了
> 
> 
> 
> > 后面这里更新了规则，手工那套要怎么更新
> 
> 
> 
> 无论是surge,clash,qx之类的工具,都支持"引用规则集"的操作,也就是所谓的"外部资源".将你需要的使用的规则文件地址根据分流需求写入配置文件里,首次启动或配置文件变动时会自动更新规则,后续也可以通过手动更新外部资源来批量更新你引用的规则集

我试试。主要这个规则比较全，更新及时
