### ISSUE TITLE
小红书app评论区无法显示

### ISSUE THREAD

**Issue by VeetaCrush** [blackmatrix7/ios_rule_script#1287]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/AdvertisingLite

异常规则：小红书相关规则

问题描述：在surge中开启advertising lite模块后，小红书的评论无法显示。查看surge中的最近请求后，发现来自小红书的含有/comment的请求被修改。关闭advertising lite模块之后可恢复评论区。

抓包截图：
![27AC55B59AC5E264C6FBB0E61D31C285](https://github.com/blackmatrix7/ios_rule_script/assets/40906391/0b903713-12b7-4517-95e4-9f2d72130d40)

调整方案：(你希望规则做哪些调整，及其原因。)本人对该方面技术了解甚少，不知如何调整，若能修复该问题不胜感激

**Comment by blackmatrix7** [comment]
能提供下具体哪条规则吗？

目前看重写规则里的正则，没有可以匹配请求的。
