### ISSUE TITLE
quanx尝试仅知乎规则，依然出现加载失败，且无日志报告

### ISSUE THREAD

**Issue by shangguanhongxin** [blackmatrix7/ios_rule_script#129]
[仅知乎规则.zip](https://github.com/blackmatrix7/ios_rule_script/files/5746900/default.zip)

**Comment by shangguanhongxin** [comment]
证书我删掉了，就用的quanx自己生成的证书

**Comment by blackmatrix7** [comment]
QuanX偶尔加载失败原因不明，暂时没有解决办法。

**Comment by shangguanhongxin** [comment]
surge没问题 真离谱

**Comment by blackmatrix7** [comment]
之前我自己的也会，把QuanX中拦截预加载的复写注释掉后，没再遇到过。不知道你的是什么原因，也有可能是我QuanX只在备用机上使用，使用时间不长，没有发现。

**Comment by blackmatrix7** [comment]
试试打开温和策略机制，猜的。

**Comment by shangguanhongxin** [comment]
> 试试打开温和策略机制，猜的。

好，我试试

**Comment by shangguanhongxin** [comment]
还是有，算了换surge

**Comment by blackmatrix7** [comment]
我是TF版本的QuanX，不知道你是什么版本，你是一直都加载失败，还是偶尔加载失败？？

**Comment by shangguanhongxin** [comment]
商店版的，偶尔吧

**Comment by blackmatrix7** [comment]
商店版很久不用了，有空我试试吧，你也可以等等商店版更新看看。

**Comment by Paris0-0** [comment]
我也遇到了，频繁加载失败，热榜里的问题偶尔失败，但推荐的问题有时候点一个失败一个，开调试也看不出来问题在哪，不过日志里有时会报[QTXDataParser] MitM error for api.zhihu.com with optional ssl code -9836，最新Quantumult X tf 知乎最新商店

**Comment by blackmatrix7** [comment]
> 我也遇到了，频繁加载失败，有时候往下划一个回答失败一个，开调试也看不出来问题在哪，不过日志里偶尔会报[QTXDataParser] MitM error for api.zhihu.com with optional ssl code -9836，出现问题的时候没报，最新Quantumult X tf 知乎最新商店

TF也这样的话，麻烦把配置文件脱敏发一份我试试，我这里复现不了。

**Comment by Paris0-0** [comment]
[1.txt](https://github.com/blackmatrix7/ios_rule_script/files/5752885/1.txt)

基本就这些，温和策略开关都一样

**Comment by blackmatrix7** [comment]
> [1.txt](https://github.com/blackmatrix7/ios_rule_script/files/5752885/1.txt)
> 
> 基本就这些，温和策略开关都一样

看了下你的配置，这几条规则有单独加上吗？？？

[filter_local]
# 知乎去广告
HOST,118.89.204.198,REJECT
IP-CIDR,118.89.204.198/32,REJECT
DOMAIN,appcloud2.in.zhihu.com,REJECT
USER-AGENT,AVOS*,REJECT

**Comment by Paris0-0** [comment]
这几条在https://github.com/DivineEngine/Profiles/blob/master/Quantumult/Filter/Guard/Advertising.list有，IP-CIDR,118.89.204.198/32包含了118.89.204.198也不用单独列

**Comment by blackmatrix7** [comment]
测试了一天，发现蜂窝数据的时候不会加载失败，Wi-Fi下有一定概率加载失败，看不出来什么问题…

**Comment by Paris0-0** [comment]
唉凑乎用吧，看来是玄学😂

**Comment by LuzMasonj** [comment]
@shangguanhongxin @Paris0-0 
[QuantumultX用户知乎APP加载失败原因定位](https://github.com/blackmatrix7/ios_rule_script/issues/268#issue-836760611) 
两位老哥根据这个issue试试 看看究竟是不是这个的原因
