### ISSUE TITLE
booking.com错误归入China规则

### ISSUE THREAD

**Issue by simonsmh** [blackmatrix7/ios_rule_script#1291]
规则名称：China_Domain.txt

规则链接：[China_Domain.txt](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/China/China.list)

异常规则：booking.com

问题描述：booking.com域名不向国内提供服务，国内服务由booking.cn域名提供

抓包截图：ipip

调整方案：将规则booking.com改为booking.cn

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
