### ISSUE TITLE
本地局域网地址应排除 cp.cloudflare.com 等公网服务

### ISSUE THREAD

**Issue by xream** [blackmatrix7/ios_rule_script#1295]
规则名称：本地局域网地址

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Lan

异常规则：`cp.cloudflare.com`, `msftconnecttest.com` 等公网服务

问题描述：本地局域网地址应排除 cp.cloudflare.com 等公网服务

抓包截图：无

调整方案：排除 `cp.cloudflare.com` 等公网服务

**Comment by blackmatrix7** [comment]
谢谢反馈，移除掉了引起问题的数据源，稍后更新。
