### ISSUE TITLE
【规则补充】增加Emby分流规则

### ISSUE THREAD

**Issue by zhuty0010** [blackmatrix7/ios_rule_script#1299]
规则名称：Emby

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Emby/Emby.yaml

问题描述：增加一个emby分流规则

调整方案：DOMAIN-SUFFIX,embymv.tk

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后更新。
