### ISSUE TITLE
首页无法刷出内容

### ISSUE THREAD

**Issue by aiiibolo** [blackmatrix7/ios_rule_script#13]
如果我清空缓存以后，首页的内容无法刷出来，如果关闭助手刷出内容以后再开助手，则可以刷新内容 surgetf4.10 知乎6.58.0（6724） 有时候会提示 似乎断开互联网连接，复写里无任何与知乎相关的内容

**Comment by blackmatrix7** [comment]
清空知乎缓存后，无法加载数据，我试着更新了一下Surge模块，你试试是否正常。如果还是不正常，清理知乎缓存后，不需要关闭插件，重启一次知乎可以解决。
”似乎断开互联网连接“ ，这个问题我只复现过一次，可能清理缓存后，某个脚本执行时资源占用过大，导致Surge的VPN重启，具体还要再排查下。如果你频繁出现这个问题，建议使用Lite版本，资源占用较小。

**Comment by aiiibolo** [comment]
谢谢回复-我刚刚一直在寻找复写或者其他的问题，一直无法解决，然后我尝试了一下lite，发现热榜无法刷出来，你是否有其他的联系方式我可以把我用的配置文件发给你，你来试试

**Comment by blackmatrix7** [comment]
> 谢谢回复-我刚刚一直在寻找复写或者其他的问题，一直无法解决，然后我尝试了一下lite，发现热榜无法刷出来，你是否有其他的联系方式我可以把我用的配置文件发给你，你来试试

我没有对热榜的数据做过处理，应该不会导致热榜无法加载，我试着用一个空的配置文件，使用Lite版本，无法复现热榜无法加载的情况。

你留个TG号，我加你吧。

**Comment by aiiibolo** [comment]
https://t.me/wotule
