### ISSUE TITLE
OpenAi规则部分缺失

### ISSUE THREAD

**Issue by R99day** [blackmatrix7/ios_rule_script#1300]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：openai

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/OpenAI/OpenAI.list

异常规则：chat.openai.com，ios.chat.openai.com

问题描述：缺少以上网址，导致iOS chatgpt app无法正确分流，无法使用

抓包截图：Qx
![B80043A2-CB79-47ED-9D64-43AC870E5C7C](https://github.com/blackmatrix7/ios_rule_script/assets/162714794/64d42e83-b54b-476b-a142-b64ef10987de)
(相关抓包工具的截图。)

调整方案：加上就可以了

**Comment by EAlyce** [comment]
规则中已有HOST-KEYWORD,openai,OpenAI

**Comment by RichardHaoShen** [comment]
感谢！！！

**Comment by R99day** [comment]
❤️

**Comment by blackmatrix7** [comment]
DOMAIN-SUFFIX,openai.com 应该足够覆盖上述的规则了

我把DOMAIN-KEY和DOMAIN与DOMAIN-SUFFIX的合并去掉了。

记得QuanX有个规则优先级之类的设置，看下是不是这个原因导致的。
