### ISSUE TITLE
大陆爱奇艺无法正常播放

### ISSUE THREAD

**Issue by Rabbit-Spec** [blackmatrix7/ios_rule_script#1302]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：GlobalMedia

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/GlobalMedia

异常规则：cache.video.iqiyi.com

问题描述：大陆爱奇艺也会使用这个域名检测区域
![2024-06-12 16 44 44](https://github.com/blackmatrix7/ios_rule_script/assets/59154499/9414c05e-c189-4022-afb0-51886598f5af)

抓包截图：
![2024-06-12 16 44 48](https://github.com/blackmatrix7/ios_rule_script/assets/59154499/49fd1889-ead0-49c6-837a-6b54045080b7)

调整方案：移除 cache.video.iqiyi.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
