### ISSUE TITLE
中信银行APP中的图片无法载入

### ISSUE THREAD

**Issue by Apocalypsor** [blackmatrix7/ios_rule_script#1307]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite.sgmodule

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule

异常规则：
https://github.com/blackmatrix7/ios_rule_script/blob/6aed25a4eec2479ad5c685c2b0bce4b917e72044/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule#L57

问题描述：中信银行APP

抓包截图：(相关抓包工具的截图。)
![IMG_2463](https://github.com/blackmatrix7/ios_rule_script/assets/37431235/26f885b6-4a00-4ad9-bd50-22a4d6c5cfe4)
![IMG_2462](https://github.com/blackmatrix7/ios_rule_script/assets/37431235/bcf19a33-6445-407a-88fc-f0a83c61f618)
![IMG_2464](https://github.com/blackmatrix7/ios_rule_script/assets/37431235/6bcc768f-ebc5-433a-8cf1-3cc9561da575)

调整方案：(你希望规则做哪些调整，及其原因。)
删除此规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
