### ISSUE TITLE
epic规则问题

### ISSUE THREAD

**Issue by Yzaams** [blackmatrix7/ios_rule_script#1308]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Game_No_Resolve
GameDownload_No_Resolve.yaml

规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game_No_Resolve.yaml
https://[raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload_No_Resolve.yaml]

异常规则：
无规则
 - DOMAIN-KEYWORD,epicgames
问题描述：
cloudflare.epicgamescdn.com，epic会通过这个域名下载，这个域名是可以通过直连下载的，我现在的情况是gamedownload和gamedownloadcn在game规则前面，漏掉之后会直接走game的规则， - DOMAIN-KEYWORD,epicgames会匹配到这个域名，变成走代理下载了

抓包截图：(相关抓包工具的截图。)
![image](https://github.com/blackmatrix7/ios_rule_script/assets/125407415/1f269994-6499-4f00-9b00-23c398722377)

调整方案：(你希望规则做哪些调整，及其原因。)
第一次写issues，哪里表达不好的地方还请大佬谅解，感谢大佬提供的规则
如果我是对的，希望能加上这条规则，如果有更好的解决方案，也希望大家帮帮我哈哈

**Comment by blackmatrix7** [comment]
KEYWORD类型的规则，我个人倾向于去除，比较容易引起问题，所以目前的解决方案是先去掉DOMAIN-KEYWORD,epicgames
