### ISSUE TITLE
BlockHTTPDNS 貌似没有和源同步

### ISSUE THREAD

**Issue by yt1988** [blackmatrix7/ios_rule_script#1312]
BlockHTTPDNS

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/BlockHTTPDNS/BlockHTTPDNS.sgmodule

选择每日更新分支，貌似并未与源进行同步更新。至少缺少以下规则：

DOMAIN,httpdns.yunxindns.com,REJECT,extended-matching

再次感谢辛苦付出

**Comment by zqq-nuli** [comment]
这仓库已经很久没更新了 估计作者太忙了 几十个pr都没合

**Comment by blackmatrix7** [comment]
> 这仓库已经很久没更新了 估计作者太忙了 几十个pr都没合

还在维护，只是的确挺忙的， 看情况是没有触发这个重写规则的更新，先手动触发一下，晚些再看下是什么问题。
