### ISSUE TITLE
ex.qq.com 误封

### ISSUE THREAD

**Issue by chenyiping1995** [blackmatrix7/ios_rule_script#133]
## 关于 ex.qq.com
第三方邮箱客户端通过 Exchange ActiveSync 协议连接到 `ex.qq.com` 来获取邮件、通讯录和日历。

关于该域名的配置，请参阅 [QQ 邮箱的文档](https://service.mail.qq.com/cgi-bin/help?subtype=1&&id=20019&&no=1000707)。

## 涉及到的拦截规则
blackmatrix7/ios_rule_script/master/rule/\*/Advertising/Advertising.list
blackmatrix7/ios_rule_script/master/rule/\*/AdvertisingTest/AdvertisingTest.list
blackmatrix7/ios_rule_script/release/rule/\*/Advertising/Advertising.list
blackmatrix7/ios_rule_script/release/rule/\*/AdvertisingTest/AdvertisingTest.list

**Comment by blackmatrix7** [comment]
很详细的反馈，十分感谢，实时版已经更新去除了，稳定版暂未更新。
