### ISSUE TITLE
akamaized.net 不应位于 China 规则里

### ISSUE THREAD

**Issue by chenyiping1995** [blackmatrix7/ios_rule_script#134]
## 关于 akamaized.net

此为 Akamai CDN 的域名。

## 为何 akamaized.net 不应该在 China 规则里

并非所有套上 Akamai CDN 的域名都适合直连。举例来说，位于 SteamCN 规则里的 `steamcommunity-a.akamaihd.net` 就可以直接访问，而 `assets-priconne-redive-us.akamaized.net` 就无法使用大陆 IP 访问。

针对此域名，更为建议的是使用 `DOMAIN` 匹配特定子域，而不是 `DOMAIN-SUFFIX` 整体匹配。

## 涉及到的规则

blackmatrix7/ios_rule_script/master/rule/\*/China/China.list
blackmatrix7/ios_rule_script/release/rule/\*/China/China.list
blackmatrix7/ios_rule_script/master/rule/\*/ChinaTest/ChinaTest.list
blackmatrix7/ios_rule_script/release/rule/\*/ChinaTest/ChinaTest.list

**Comment by blackmatrix7** [comment]
谢谢这么详细的反馈，分流规则已更新。

**Comment by KeyZM** [comment]
- 'DOMAIN,manga.bilibili.com,哔哩哔哩'
