### ISSUE TITLE
api.sec.miui.com 误封

### ISSUE THREAD

**Issue by chenyiping1995** [blackmatrix7/ios_rule_script#136]
## 关于 api.sec.miui.com
该域名负责 MIUI 下的骚扰拦截相关更新。

## 上游信息
https://github.com/privacy-protection-tools/anti-AD/issues/59

## 涉及到的规则
blackmatrix7/ios_rule_script/master/rule/\*/AdvertisingLite/AdvertisingLite.list
blackmatrix7/ios_rule_script/master/rule/\*/Advertising/Advertising.list
blackmatrix7/ios_rule_script/master/rule/\*/AdvertisingTest/AdvertisingTest.list
blackmatrix7/ios_rule_script/release/rule/\*/AdvertisingLite/AdvertisingLite.list
blackmatrix7/ios_rule_script/release/rule/\*/Advertising/Advertising.list
blackmatrix7/ios_rule_script/release/rule/\*/AdvertisingTest/AdvertisingTest.list

**Comment by blackmatrix7** [comment]
还是这么详细的反馈，十分感谢，已经更新了。
