### ISSUE TITLE
去广告规则源 希望添加

### ISSUE THREAD

**Issue by ICU2Vmile** [blackmatrix7/ios_rule_script#138]
https://github.com/ddgksf2013/Cuttlefish/blob/master/Applet/Quan.conf

**Comment by blackmatrix7** [comment]
暂缓添加脚本去广告规则，一方面脚本的规则仅通过转换后能否支持3个不同的客户端，我不太清楚；另外一方面第三方脚本的安全性我也没办法保证。如果加入的话，也会是处理出一个第三方脚本的复写，不会加入到现有的去广告复写中。

还是很感谢你提供数据源，如果后面有添加，我再回复你。
