### ISSUE TITLE
关于js正则的询问

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_script#14]
你好，我现在在使用zhihu_plus模块；非常感谢🙏我看了一下7个js用的好像是一个文件；如果是的话能不能用一个正则表示？当然这只是强迫症而已，不行就算了

**Comment by blackmatrix7** [comment]
> 你好，我现在在使用zhihu_plus模块；非常感谢🙏我看了一下7个js用的好像是一个文件；如果是的话能不能用一个正则表示？当然这只是强迫症而已，不行就算了

理论上可以，但是正则可读性和可维护性会变得很差。

**Comment by zjcfynn** [comment]
那就算了，不增加你的麻烦
