### ISSUE TITLE
去广告规则误杀

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#142]
相关list：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/Advertising/Advertising.sgmodule
相关规则：^https?:\/\/p\d\.pstatp\.com\/origin

有漫画网站的图片使用这个地址
例图：https://p3.pstatp.com/origin/pgc-image/c87fdaf9cd744cf7852e27be4f7b774c

**Comment by blackmatrix7** [comment]
已更新去除
