### ISSUE TITLE
关于部分数据来源需要更新的提醒

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#143]
发现Hijacking.list的数据来源是：
https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Hijacking.list

然而ConnersHua的list 已经不再更新，现还在维护Hijacking.list地址为：
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list

ConnersHua的相关list，应该全面转为新项目DivineEngine的同名list，两个项目是同一个作者

**Comment by blackmatrix7** [comment]
已经加入了，等半夜自动更新下就好，旧的也不需要删，如果原作者把库删了，我这里会使用本地的备份，影响不大。

另外Hijacking已经包含在Advertising中了
