### ISSUE TITLE
China.list导致Quantumult X开启失败

### ISSUE THREAD

**Issue by IvorkChan** [blackmatrix7/ios_rule_script#144]
关闭Quantumult X并试图重新开启时，启用China.list规则订阅会导致“大量重复的分流规则”错误。
如果先禁用该list，开启QuanX后再启用是能正常运行的。
 ![image](https://user-images.githubusercontent.com/19368630/103661669-f1385400-4fa9-11eb-9fc1-d6a4b5137906.png)

**Comment by blackmatrix7** [comment]
你用了其他的分流规则的，和China重复了，排查下。

**Comment by IvorkChan** [comment]
Well…
是因为Proxy.list，这组规则和China.list同时订阅会导致QuanX不能开启。
我一个❓

**Comment by blackmatrix7** [comment]
China一共才607条，不可能有1097条重复的情况。应该还有其他的规则重复，只是你禁用China后，重复的数量正好减少到不提醒错误的阈值。

**Comment by IvorkChan** [comment]
谢谢解答，可以关闭了，我会自己排除。

**Comment by blackmatrix7** [comment]
你看下README，China与Proxy的重复数量为107条，不会高达1000多条的警告，所以China肯定不会是主因。

完全没重复不太现实，因为本身就是抓取不同作者的数据源，某个作者认为这个域名应该走Proxy，另外一个作者认为这个域名应该走Direct，那么就会造成重复。而程序本身没办法理解上游数据源作者的意图，没办法决定是走Direct或Proxy，就会出现重复。

README中的重复数量表格就是为了缓解这种情况，便于搭配使用的。
