### ISSUE TITLE
大佬，我看你quanx的google.list分流已经更新了HOST-SUFFIX,voice.telephony.goog,Google.但是打gv的时候还是走之后的outside策略组，outside里面写的是HOST,voice.telephony.goog,outside.HOST和HOST-SUFFIX是有什么区别吗？不太懂，麻烦看一下

### ISSUE THREAD

**Issue by HEARTPHILIANS** [blackmatrix7/ios_rule_script#146]
![image](https://user-images.githubusercontent.com/69738186/103834109-86783d00-50bd-11eb-8884-ab7577a17016.jpeg)
![image](https://user-images.githubusercontent.com/69738186/103834118-8e37e180-50bd-11eb-9abd-78bdda1f3856.jpeg)

https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Outside.list

**Comment by HEARTPHILIANS** [comment]
大佬，我觉得应该要完整域名匹配，用HOST，不知道对不对

**Comment by HEARTPHILIANS** [comment]
google.list里面还有HOST-SUFFIX,telephony.goog,Google

这条域名后缀匹配也没匹配到，不知道为啥

**Comment by blackmatrix7** [comment]
这个跟你规则的优先级是有关系的，你检查下配置文件中规则的优先级关系。

**Comment by HEARTPHILIANS** [comment]
![image](https://user-images.githubusercontent.com/69738186/103839741-0e187880-50cb-11eb-8c34-448b94e495e3.jpeg)
![image](https://user-images.githubusercontent.com/69738186/103839760-1670b380-50cb-11eb-8d33-629fe10db3b4.jpeg)

**Comment by HEARTPHILIANS** [comment]
我这个顺序应该对的，google放在ouside之前

**Comment by blackmatrix7** [comment]
原先的规则就包含了HOST-SUFFIX,telephony.goog，而你的这个规则里包含了HOST,voice.telephony.goog,Outside

HOST的优先级高于HOST-SUFFIX，所以无论什么顺序，只要HOST,voice.telephony.goog,Outside存在，HOST-SUFFIX,telephony.goog都不会生效。

而我的程序在生成规则时，如果发现HOST-SUFFIX,telephony.goog存在，会把HOST,voice.telephony.goog去除，因为HOST-SUFFIX,telephony.goog已经包含了HOST,voice.telephony.goog。

这是一个很好的问题，我需要再重新评估一下在QuantumultX中进行DOMAIN-SUFFIX的合并。

现在临时的解决方案是你在本地写HOST,voice.telephony.goog这条规则。

**Comment by HEARTPHILIANS** [comment]
非常感谢

我以为你先把现在的HOST-SUFFIX,voice.telephony.goog和HOST-SUFFIX,telephony.goog删除，再把HOST,voice.telephony.goog添加上就可以了

原来你是用什么程序生成规则的

**Comment by blackmatrix7** [comment]
> 非常感谢
> 
> 我以为你先把现在的HOST-SUFFIX,voice.telephony.goog和HOST-SUFFIX,telephony.goog删除，再把HOST,voice.telephony.goog添加上就可以了
> 
> 原来你是用什么程序生成规则的

是程序自动生成的，所以直接改现有的文件解决不了问题，明天半夜重新生成又会恢复到之前的样子。

QuanX除了文件顺序间有优先级，不同规则类型间也有优先级，目前还没有考虑清楚如何改动，暂时保持原样了。
