### ISSUE TITLE
知乎最新版，好像无法去广告和增强功能

### ISSUE THREAD

**Issue by pukarziu** [blackmatrix7/ios_rule_script#147]
个人操作问题，已经可以用上了，不过黑名单上明明只有一个人，通知却是三个人
![6F141462-3FFC-423D-8193-AFAEC784596C](https://user-images.githubusercontent.com/30079779/103977078-6a56c780-51b3-11eb-919c-a6b1ac675d2e.jpeg)

**Comment by blackmatrix7** [comment]
启用黑名单后，会加入两个默认的账户名，用于拦截知乎的推广，这两个用户属于特殊用户，没办法手动加入黑名单。
