### ISSUE TITLE
关于China规则的bug

### ISSUE THREAD

**Issue by yfue** [blackmatrix7/ios_rule_script#148]
麻烦你了，感谢你的付出🙏surge规则China.list中的GEOIP,cn行会导致触发dns查询，失去了no-resolve的意义，建议删除。只在China_Resolve.list中保留即可，这样排布规则时逻辑更顺一些。

**Comment by blackmatrix7** [comment]
GEOIP的存在属于意料之外的情况，已去除，你试试，后续如果有问题可以再反馈给我。
