### ISSUE TITLE
IP-CIDR,118.89.204.198/32,no-resolve,REJECT触发不必要的dns查询

### ISSUE THREAD

**Issue by m1a1y1u1e1** [blackmatrix7/ios_rule_script#149]
surge网络诊断的时候提示IP-CIDR,118.89.204.198/32,no-resolve,REJECT触发不必要的dns查询
用UI添加,格式是这个样子的,IP-CIDR,118.89.204.198/32,REJECT,no-resolve,不再提示,猜测应该是格式错了

涉及到的规则:
ios_rule_script/rewrite/loon/AdvertisingScript/AdvertisingScript.sgmodule,没有loon不知道有没有影响
ios_rule_script/script/zhihu/zhihu_lite.lnplugin,没有loon不知道有没有影响
ios_rule_script/rewrite/Surge/AdvertisingScript/AdvertisingScript.sgmodule

**Comment by blackmatrix7** [comment]
谢谢，很详细的反馈，已修复，你试试，后续如果有问题可以再反馈给我。
