### ISSUE TITLE
您好 饿了么复写 url 错误 无法获取 cookie 

### ISSUE THREAD

**Issue by HotKids** [blackmatrix7/ios_rule_script#15]
应为 ^https?:\/\/h5\.ele\.me\/restapi\/svip_biz\/v1\/supervip\/query_mission_list?.*longitude=([^&]*).*latitude=([^&]*)

**Comment by blackmatrix7** [comment]
我看了下，新版已经把奖励金改成吃货豆，全部不一样了，看起来不是正则不对的问题，而是活动完全变了。找个时间再改改。我用的是9.0.10 13216362，目前还是领取奖励金的任务。

**Comment by blackmatrix7** [comment]
已经更新适配最新版吃货豆任务

**Comment by HotKids** [comment]
感谢！再请教一个问题，这个任务是默认领取第一个还是其他

**Comment by blackmatrix7** [comment]
> 感谢！再请教一个问题，这个任务是默认领取第一个还是其他

代码是领取全部任务，但是一直只有一个任务，所以现阶段就是领取一个任务。如果你那里有多个任务的响应体，可以发我看下能不能用。

**Comment by HotKids** [comment]
好 我研究下
