### ISSUE TITLE
网易云音乐的规则把网易系的规则都加进去了

### ISSUE THREAD

**Issue by Edger** [blackmatrix7/ios_rule_script#150]
RT，网易云音乐的规则把网易系的规则都加进去，这样在指定网易云音乐的策略时，会导致有道等这些服务不可用。

**Comment by blackmatrix7** [comment]
谢谢反馈，已修复，你试试，后续如果有问题可以再反馈给我。

**Comment by Edger** [comment]
> 谢谢反馈，已修复，你试试，后续如果有问题可以再反馈给我。

还是有问题，指定节点后无法播放音乐了。

用 https://github.com/nzw9314/QuantumultX/blob/master/NeteaseMusic.list 这个才正常

**Comment by blackmatrix7** [comment]
> > 谢谢反馈，已修复，你试试，后续如果有问题可以再反馈给我。
> 
> 还是有问题，指定节点后无法播放音乐了。
> 
> 用 https://github.com/nzw9314/QuantumultX/blob/master/NeteaseMusic.list 这个才正常

排查了下，我这边的处理逻辑是
host-suffix,music.163.com,🎸解锁网易云音乐
host-suffix,interface.music.163.com,🎸解锁网易云音乐
host-suffix,interface3.music.163.com,🎸解锁网易云音乐
host-suffix,apm.music.163.com,🎸解锁网易云音乐
host-suffix,apm3.music.163.com,🎸解锁网易云音乐

当host-suffix,music.163.com存在时，我认为已经包含了interface.music.163.com等等后续的规则，会将后面4条去除。

不清楚是否这个处理在QuanX中不行，暂时取消网易云音乐这个分流规则的Domain合并，重新生成了一次，麻烦你再试试。

**Comment by Edger** [comment]
> > > 谢谢反馈，已修复，你试试，后续如果有问题可以再反馈给我。
> > 
> > 
> > 还是有问题，指定节点后无法播放音乐了。
> > 用 https://github.com/nzw9314/QuantumultX/blob/master/NeteaseMusic.list 这个才正常
> 
> 排查了下，我这边的处理逻辑是
> host-suffix,music.163.com,🎸解锁网易云音乐
> host-suffix,interface.music.163.com,🎸解锁网易云音乐
> host-suffix,interface3.music.163.com,🎸解锁网易云音乐
> host-suffix,apm.music.163.com,🎸解锁网易云音乐
> host-suffix,apm3.music.163.com,🎸解锁网易云音乐
> 
> 当host-suffix,music.163.com存在时，我认为已经包含了interface.music.163.com等等后续的规则，会将后面4条去除。
> 
> 不清楚是否这个处理在QuanX中不行，暂时取消网易云音乐这个分流规则的Domain合并，重新生成了一次，麻烦你再试试。

还是有问题，我在手机上用这个：https://github.com/nzw9314/QuantumultX/blob/master/NeteaseMusic.list
电脑上用这个：https://github.com/nzw9314/QuantumultX/blob/master/NeteaseMusic.list
都是正常的，用了这个合并之后的就不行

**Comment by blackmatrix7** [comment]
谢谢，很重要的反馈。我排查了下，发现是在处理User-Agent类型的规则时，将对应的参数转换为小写导致的，现在又更了一次，实测在QuanX中没有问题，灰色歌曲可以正常播放了。
如果还是不行，你看下日志中相关请求走的是哪条规则。或者把你的配置文件脱敏后，留个网易云音乐的节点和相关证书我试试。
