### ISSUE TITLE
AllInOne中有影响youtube去广告的重写

### ISSUE THREAD

**Issue by notaganin** [blackmatrix7/ios_rule_script#152]
这一条不能去除片头广告
https://github.com/blackmatrix7/ios_rule_script/blob/813cdd3e049e91b19df39f5abe9a17ce2ac7b21f/rewrite/QuantumultX/AllInOne/AllInOne.conf#L177
这一条既不能去除片头广告，也不能播放片头广告
https://github.com/blackmatrix7/ios_rule_script/blob/813cdd3e049e91b19df39f5abe9a17ce2ac7b21f/rewrite/QuantumultX/AllInOne/AllInOne.conf#L186

可以参照作者DivineEngine的[youtube去广告](https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/YouTubeAds.conf)重写，将第一条改为`(^https?:\/\/[\w-]+\.googlevideo\.com\/.+)(ctier=L)(&.+) url 302 $1$3`，第二条改为`^https?:\/\/[\w-]+\.googlevideo\.com\/.+&(oad|ctier) url reject`，即可达到去除片头广告的效果。

**Comment by blackmatrix7** [comment]
晚些更新以下会把它去掉

**Comment by blackmatrix7** [comment]
已经去除了，目前过滤器没办法支持到文件级别的过滤，所以暂时没办法加入其他的Youtube规则，后续会更新支持。
