### ISSUE TITLE
rewrite中对招商银行-掌上生活屏蔽广告失效

### ISSUE THREAD

**Issue by fangpidedongsun** [blackmatrix7/ios_rule_script#153]
hostname添加mlife.cmbchina.com会导致银行APP MITM FAILD
rewrite 中 关于mlife.cmbchina.com的重写已无效
建议去除。
不知道还有无其他办法去除掌上生活广告。

**Comment by fangpidedongsun** [comment]
另外还有京东金融开屏广告，我在库中没找到，自己抓了一个，看看能不能加到库里
#京东金融
URL-REGEX,^https:\/\/ms\.jr\.jd\.com\/gw\/generic\/aladdin\/newna\/m\/getLoadingPicture$,REJECT

**Comment by blackmatrix7** [comment]
京东金融加进去了，掌上生活这个复写实测的确会导致APP提示网络异常，已经去掉了。MITM Failed就没什么太好的办法，放弃吧。
