### ISSUE TITLE
规则路径大小写字母变化导致 Surge 引用外部资源失败

### ISSUE THREAD

**Issue by iarchean** [blackmatrix7/ios_rule_script#155]
作者你好，感谢你维护这些规则，非常有用。

最近发现一些问题，我个人的 Surge 规则中引用了几个媒体服务的地址，如

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/BiliBili/BiliBili.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/iQIYI/iQIYI.list

最近发现「BiliBili」和「iQIYI」目录及其中的文件大小写发生了变化导致规则下载失败，比如前几天 iQiyi 的路径是 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/iQiyi/iQiyi.list，现在已经404了。

我理解可能是地址更新时把文件名也修改了？希望目录名及文件名是固定的，这样至少个人规则可以不用再去维护，只进行引用即可。

谢谢！

**Comment by blackmatrix7** [comment]
为了适配程序更新，手动修改了部分分流规则的名称，并非程序自动修改。这种情况不会很常见，我在更新程序的过程中，会尽量避免对原有路径的变动。
