### ISSUE TITLE
知乎助手，用loon的情况下关注列表和推荐列表中还是会出现广告

### ISSUE THREAD

**Issue by doherty88** [blackmatrix7/ios_rule_script#156]
Loon版本2.1.6（244） TF版
知乎版本7.0.0（3522）

在关注列表和推荐列表下拉，会出现广告内容，切换成quanx之后就没了

**Comment by blackmatrix7** [comment]
麻烦你抓个包，把118.89.204.198:443的请求结果发我看下，看看走的是哪条规则。

**Comment by blackmatrix7** [comment]
如果你用的是我的China.list，并且设置为DIRECT的话，重新更新下规则文件就可以了。

**Comment by doherty88** [comment]
我确实用的China.list,更新之后还是有广告。
但是我现在在知乎助手之外又同时加了另外两个去广告订阅之后，好像loon再看知乎就没广告了
https://raw.githubusercontent.com/eHpo1/Rules/master/QuantumultX/Filter/Liby.txt
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Guard/Advertising.list

**Comment by blackmatrix7** [comment]
知乎的广告拦截，依赖于拦截118.89.204.198:443这个地址的请求，迫使知乎APP回退到以api.zhihu.com请求数据，才能进行MTIM清理广告内容。

拦截失效通常情况都是118.89.204.198:443被某条优先级更高的规则意外放行导致。你如果有兴趣，可以抓包看下118.89.204.198:443这个地址的请求，如果不是REJECT，那拦截广告功能一定会失效，就得手动找出放行此地址的规则，将它去掉。
