### ISSUE TITLE
滴滴出行福利金抽奖每天都报错

### ISSUE THREAD

**Issue by Paris0-0** [blackmatrix7/ios_rule_script#157]
福利金签到失败，执行异常：TypeError: undefined is not an object (evaluating 'obj.data.notification.reverse')，接口返回：{"errno":0,"errmsg":"","traceid"

后面还有一大堆，每天都要手动抽一次奖更新那个什么id以后才能正常执行，第二天就又失效了

**Comment by blackmatrix7** [comment]
谢谢反馈，我调试看下。

**Comment by blackmatrix7** [comment]
福利金已修改好，抽奖需要再观察几天，没问题会更新上来。

**Comment by Paris0-0** [comment]
好的

**Comment by blackmatrix7** [comment]
已更新。
