### ISSUE TITLE
什么值得买有账户异常吗？

### ISSUE THREAD

**Issue by r0ckrise** [blackmatrix7/ios_rule_script#162]
具体可以去幸运屋抽奖试试，我的是被检测到了。
![image](https://user-images.githubusercontent.com/76696224/104860892-602d8980-5968-11eb-8b21-88642197da5d.png)![image](https://user-images.githubusercontent.com/76696224/104860895-64f23d80-5968-11eb-94e6-08da3a0e650d.png)

**Comment by blackmatrix7** [comment]
的确会造成账号异常，现在暂时下线几个功能：

APP端签到，这个接口老旧且没有任何收益，纯粹增加风险。
去除生活频道抽奖，现在这个情况，抽到碎银子也用不出去，不如去掉。

其他功能只能获取经验，不涉及到金币和碎银子，所以暂时保留。

你申请解封的情况怎么样？麻烦反馈给我下，我两个账号都沦陷了。

**Comment by r0ckrise** [comment]
还在申请中，有结果反馈。

**Comment by blackmatrix7** [comment]
> 还在申请中，有结果反馈。

期待你的反馈，建议先暂停脚本使用吧，如果做任务什么的会导致账号异常，后续可能考虑只保留一个Web端签到的功能，然后增加个随机时间签到试试。毕竟服务端要检测这种自动签到太容易了。

**Comment by r0ckrise** [comment]
好的，大佬费心了。

**Comment by r0ckrise** [comment]
已经解封了![image](https://user-images.githubusercontent.com/76696224/105064004-58c8c600-5ab7-11eb-98fa-ed66ce9b1be5.png)

**Comment by blackmatrix7** [comment]
> 已经解封了![image](https://user-images.githubusercontent.com/76696224/105064004-58c8c600-5ab7-11eb-98fa-ed66ce9b1be5.png)

你的金币、碎银子有被扣掉吗？

现在还是不知道是签到、做任务还是抽奖导致的账户异常，建议先手动签到吧。

**Comment by r0ckrise** [comment]
没有被扣掉，现在已经停掉了，先手动着。

**Comment by blackmatrix7** [comment]
> 没有被扣掉，现在已经停掉了，先手动着。

我对抽奖没什么兴趣，打算继续签到着，等累计多点再去申请解除封禁。

**Comment by r0ckrise** [comment]
> 我对抽奖没什么兴趣，打算继续签到着，等累计多点再去申请解除封禁。

同，只要不断签就好了，只需要一个简单的签到功能。

**Comment by blackmatrix7** [comment]
> > 我对抽奖没什么兴趣，打算继续签到着，等累计多点再去申请解除封禁。
> 
> 同，只要不断签就好了，只需要一个简单的签到功能。

后面独立出来吧，不过要春节后了，最近事情太多。

**Comment by r0ckrise** [comment]
感谢大佬，先手动签着。

**Comment by blackmatrix7** [comment]
> 感谢大佬，先手动签着。

你现在手动在APP里点赞点值会有经验吗？我的账号点赞点值都没有经验，只有收藏有经验。

但是看官方成长值介绍，手动点击应该也是有经验的，不知道是不是我账号异常的原因。

如果确认没有经验，打算把这几个功能去掉了。。。

**Comment by r0ckrise** [comment]
我试了下评论点赞没有经验

**Comment by blackmatrix7** [comment]
> 我试了下评论点赞没有经验

那可能真的没有了，目前只有收藏有经验，打算把其他任务去掉

**Comment by r0ckrise** [comment]
我很简单，需求就是不断签就好了😂

**Comment by blackmatrix7** [comment]
> 我很简单，需求就是不断签就好了😂

 现在已拆分开了，签到和任务是两个脚本，测试几天会更新上来。任务部分我还在看到底保留几个。
