### ISSUE TITLE
知乎首页板块的问题

### ISSUE THREAD

**Issue by yfue** [blackmatrix7/ios_rule_script#163]
知乎首页的板块在编辑后重新打开又回到原来的了，能不能通过js处理

**Comment by blackmatrix7** [comment]
不太明白你说的意思，仔细说下操作步骤。

**Comment by yfue** [comment]
![867E1F22-30BB-4DF1-A38E-B62E83F5DFCE](https://user-images.githubusercontent.com/58805062/104980547-c1755b80-5a41-11eb-9a56-dcb3edd20614.jpeg)
就是圈出来的这个，可以通过编辑删除，但是重启后就会恢复

**Comment by blackmatrix7** [comment]
这个可以编辑删除？是新版的功能吗？我很少更新APP，不太清楚。麻烦把知乎版本和编辑步骤仔细说下，我看看什么问题。之前有处理过这个顶部的tab。

**Comment by fiiir** [comment]
我的知乎是商店最新版，翻遍设置没有找到编辑功能，用了JS只显示4个板块，和更新前一致
