### ISSUE TITLE
Surge复写规则All In One出现问题

### ISSUE THREAD

**Issue by Meonthb** [blackmatrix7/ios_rule_script#164]
All In One规则包含Redirect，但是Rediredt里很多规则无效且有问题，比如^https?:\/\/(www.)?jd\.com\/ https://yhd.com/ 302行，会导致京东无法打开，希望能有不含Redirect的All In One规则。

**Comment by blackmatrix7** [comment]
我也不赞同由客户端去实现HTTP重定向到HTTPS的行为，所以对部分的数据源进行了修改， 现在只保留了google.cn的重定向。

这是一个临时的解决方案，春节后如果有时间会修改代码，让程序支持数据源级别的过滤器，这样才能精确过滤掉某个数据源中不想要的重定向。
