### ISSUE TITLE
Apple.list 中 Map 服务走代理的问题

### ISSUE THREAD

**Issue by mintyfrankie** [blackmatrix7/ios_rule_script#165]
在大陆的语境下用户应该大多都希望是类似 iCloud 和 iTunes 等服务走代理加速，而地图则保留国内高德的服务吧（Tomtom 在国内几乎处于不可用状态）我看了 Divine Engine 等几大配置的 Apple.list 中对地图的处理都是走直连/不包括在规则里的。

作者能考虑剔除关于 Map 服务的规则，或另外设置单独的 list 吗？谢谢！

**Comment by blackmatrix7** [comment]
你可以试试高德的规则 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GaoDe/GaoDe.list

**Comment by blackmatrix7** [comment]
触发的规则是USER-AGENT,geod*,Apple
来自
https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Apple.list
现在暂时不太清楚geod这个UA覆盖的范围，建议暂时将高德的规则置于Apple规则之前，geod我需要再查下作用是什么。

**Comment by mintyfrankie** [comment]
你好，感谢答复。我这边测试了一下，iPhone 已经恢复正常，但 iPad 和 M1 Mac（也使用 QX 代理）仍旧是 TOMTOM。

我尝试在 config 里排除了 Apple.list 的规则，似乎没有效果。

我这边看到 https://www.v2ex.com/t/174134 这个讨论里有人提到类似的问题，请问作者这边有什么建议吗？

谢谢！
