### ISSUE TITLE
多有打扰，关于重复分流规则问题

### ISSUE THREAD

**Issue by KMJ-2020** [blackmatrix7/ios_rule_script#166]
部分分流规则重复，感谢提供这么多的分流规则，我引用的分流规则包括：China，apple等分流，global，globalmedia，油管奈非等，Google，还有Chinamedia（刚刚删除），Asianmedia，hiJacking，去广告，基本是这些吧，本人用的圈X软件，今日手动更新了一下全部规则，然后关闭圈x的主开关，打开时提示部分分流规则重复，最后把中国媒体删除了才能正常打开，查找了去广告里面的重复规则，中国媒体没有太多和去广告的重复吧，或者我把hiJacking关掉（没删除中国媒体的时候），圈x也没有提示大量重复规则，就是希望大佬能够腾出一些时间把这些重复的规则能精简就精简一下吧，麻烦了，谢谢！打扰，望见谅！！！

**Comment by blackmatrix7** [comment]
Advertising 完全包含 Hijacking，China 包含 部分 ChinaMedia，这个属于没办法的事情，如果把ChinaMedia从China中剔除，那对于只使用China，不使用ChinaMedia的人又不合理。

**Comment by KMJ-2020** [comment]
那我大概了解了，想我这样既使用Advertising又使用HiJacking的就可以完全抛弃HiJacking了，谢谢！
