### ISSUE TITLE
login.sina.com.cn 应该不算 Advertising 吧

### ISSUE THREAD

**Issue by lucifer9** [blackmatrix7/ios_rule_script#168]
RT
出现在 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list 里面

**Comment by blackmatrix7** [comment]
来自于
https://raw.githubusercontent.com/NobyDa/ND-AD/master/Surge/AD_Block_Plus.txt
目前尚不清楚为什么会加入到广告拦截中，明天凌晨更新会去掉，你可以明天早上睡醒再更新一下。

**Comment by chenyiping1995** [comment]
似乎这个域名又出现在 Advertising_Domain 里面了。

**Comment by blackmatrix7** [comment]
> 似乎这个域名又出现在 Advertising_Domain 里面了。

之前重构遗漏了一些过滤器，现在重新加回去，已经更新去掉了。
