### ISSUE TITLE
Global.list 缺少 DOMAIN-SUFFIX 类规则

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#169]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global.list

其中的
DOMAIN-SUFFIX: 1128
一条都没有

**Comment by blackmatrix7** [comment]
超过1000条，会自动生成到Domain.list中

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_Domain.list
