### ISSUE TITLE
知乎想法的规则貌似没有匹配到^https?:\/\/api\.zhihu\.com\/(moments|topstory)(\/|\?)?(recommend|action=|feed_type=)，为什么会错误呢

### ISSUE THREAD

**Issue by czmecho** [blackmatrix7/ios_rule_script#17]
把^https?:\/\/api\.zhihu\.com\/(moments|topstory)(\/|\?)?(recommend|action=|feed_type=) url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.js 注释掉，想法不存在的问题就解决了。
但这个正则和脚本貌似没有匹配到https://api.zhihu.com/pins/1297608506535374800/reactions 这个，不知道是什么原因呢。

**Comment by blackmatrix7** [comment]
对响应体进行修改后，1297608506535374800这个想法的Id会变，绝大多数情况下会变成不存在的另外一个Id，少数情况下保持正常。更具体的原因还没往下查。

**Comment by blackmatrix7** [comment]
1297608506535374800，这个是在响应的JSON中为target_id，为number类型。而它的值超出JavaScript number类型的最大值9007199254740992，在JSON.parse时，会出现精度丢失问题。
所以在JSON.parse修改响应体，再进行JSON.stringify后，target_id由于精度问题，变成另外一个不存在的target_id，体现到知乎的App中就是想法不存在。
只有极少数target_id小于9007199254740992的想法不会出现此问题。

**Comment by blackmatrix7** [comment]
想法不存在的问题已解决
