### ISSUE TITLE
ip类hostname缺失

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#170]
去广告模块中的[MITM]部分
都缺失ip类的hostname
包括：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/Advertising
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Advertising
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/AdvertisingLite
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/AdvertisingTest

**Comment by blackmatrix7** [comment]
分流规则中的IP-CIDR不需要MITM，复写中的可能是在校验合法性中被误去掉了，近期没时间处理，要过几天看下。

**Comment by blackmatrix7** [comment]
已经修复，等明天早上更新一下就好了。
