### ISSUE TITLE
HBO和Hulu规则问题

### ISSUE THREAD

**Issue by xaver985** [blackmatrix7/ios_rule_script#173]
你好，
仓库内的HBO规则包含了HBO Max和香港的HBO GO，而HBO Max则只在美国提供服务，希望作者可以拆分下
Hulu同理，包含了Hulu和Hulu Japan，后者只在日本提供服务，前者也是美国限定

**Comment by xaver985** [comment]
另外HBO规则中还有Now-E的分流？
这是两回事，只是Now-E订阅会附带HBO GO，这两者是香港限定，和规则中的HBO MAX冲突

**Comment by blackmatrix7** [comment]
这两个APP我都没用过，只是顺手看到就加入进来，目前上游数据源只有一个，拆分的话需要我也不太清楚那些是美国的，那些是在日本提供服务的。
如果你能提供一下相关的IP，我可以根据规则把这几条拆分成独立的分流规则。

**Comment by xaver985** [comment]
HBO规则中hk后缀和包含HBOASIA是香港限定
Hulu中hulu.jp和其他jp后缀则是日本限定

**Comment by xaver985** [comment]
HBOGO、HBOGOASIA和带有now的这些都是只在香港提供服务

**Comment by xaver985** [comment]
不过HBO GO和Nowe的服务范围不一样，前者除了香港外还在菲律宾有服务，后者则只是香港限定

**Comment by blackmatrix7** [comment]
谢谢反馈，现在程序只能实现多规则合并为一条，晚些会增加一条数据源拆分为多项规则的功能，到时候会更新拆分。

**Comment by xaver985** [comment]
> 谢谢反馈，现在程序只能实现多规则合并为一条，晚些会增加一条数据源拆分为多项规则的功能，到时候会更新拆分。

另外GlobalMedia规则下的USER-AGENT,News*会使新闻类的Widget走代理，可否优化下？

**Comment by blackmatrix7** [comment]
> > 谢谢反馈，现在程序只能实现多规则合并为一条，晚些会增加一条数据源拆分为多项规则的功能，到时候会更新拆分。
> 
> 另外GlobalMedia规则下的USER-AGENT,News*会使新闻类的Widget走代理，可否优化下？

已经去掉了

**Comment by xaver985** [comment]
> > > 谢谢反馈，现在程序只能实现多规则合并为一条，晚些会增加一条数据源拆分为多项规则的功能，到时候会更新拆分。
> > 
> > 另外GlobalMedia规则下的USER-AGENT,News*会使新闻类的Widget走代理，可否优化下？
> 
> 已经去掉了

这条规则又出现在GlobalMedia里了

**Comment by blackmatrix7** [comment]
已经重写发布去掉了

**Comment by xaver985** [comment]
> 已经重新发布去掉了

这条一直还在GlobalMedia里

**Comment by blackmatrix7** [comment]
再次去掉了，之前做重构的时候忘了把过滤器再加进去导致又出现。

HBO和Hulu也做了拆分，麻烦帮忙看下是不是正确。

**Comment by xaver985** [comment]
> 再次去掉了，之前做重构的时候忘了把过滤器再加进去导致又出现。
> 
> HBO和Hulu也做了拆分，麻烦帮忙看下是不是正确。

hbonow.com应该放在HBO USA里头，其余都正确
最后辛苦了

**Comment by blackmatrix7** [comment]
谢谢反馈，已修改。
