### ISSUE TITLE
去广告规则数据

### ISSUE THREAD

**Issue by Wangsc1** [blackmatrix7/ios_rule_script#174]
麻烦大佬看下https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/base-filter.txt

https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/adaway.txt

https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt

https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt(rule-set)

https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt(domain-set)

**Comment by blackmatrix7** [comment]
这些都是已有的数据源，你可以仔细看下，部分可能是在Test中。
