### ISSUE TITLE
Edge 浏览器同步和WNS被当成 Advertising 了

### ISSUE THREAD

**Issue by lucifer9** [blackmatrix7/ios_rule_script#176]
https://edge-enterprise.activity.windows.com
https://edge.activity.windows.com
按照[微软的文档](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync)，这俩是edge同步的
另外还有[WNS](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/firewall-allowlist-config)用到的一些域名也在Advertising里
```
*.notify.windows.com
*.wns.windows.com
*.notify.live.net
login.microsoftonline.com
login.live.com
```
当然对于不需要用到微软消息推送的估计也就无感了。估计主要是edge同步会影响到的人比较多。

**Comment by blackmatrix7** [comment]
谢谢反馈，已去除。

**Comment by chenyiping1995** [comment]
edge.activity.windows.com 和 edge-enterprise.activity.windows.com 又回到 Advertising_Domain 了。

**Comment by blackmatrix7** [comment]
> edge.activity.windows.com 和 edge-enterprise.activity.windows.com 又回到 Advertising_Domain 了。

刚刚更新后，搜索了下内容，应该是去掉了，你再看看。

**Comment by chouchoui** [comment]
> > edge.activity.windows.com 和 edge-enterprise.activity.windows.com 又回到 Advertising_Domain 了。
> 
> 刚刚更新后，搜索了下内容，应该是去掉了，你再看看。

Advertising_Domain 中还存在 .activity.windows.com

**Comment by blackmatrix7** [comment]
> > > edge.activity.windows.com 和 edge-enterprise.activity.windows.com 又回到 Advertising_Domain 了。
> > 
> > 
> > 刚刚更新后，搜索了下内容，应该是去掉了，你再看看。
> 
> Advertising和Advertising_Domain中还存在 activity.windows.com

之前没有过滤 activity.windows.com，现在把它加到过滤器里了。
