### ISSUE TITLE
不同App对RULE-SET DOMAIN-SET优先级处理不同

### ISSUE THREAD

**Issue by lucifer9** [blackmatrix7/ios_rule_script#177]
目前观察到的：
- 对Surge来说，每个set是独立的，匹配规则时候先按照set来，所以如果两个set有相同元素是按照全局从上到下匹配，比较符合直觉
- 对shadowrocket来说，是把set拆开了一条一条导入规则，所以如果有相同元素，后面规则会覆盖前面的。这个比较反直觉，如果写规则时候不注意挺坑的。比如最前面是Advertising的reject，以为会都阻止，其实后面proxy或者China里面有相同元素的，就还是会去连接了。或者前面有个dl.google.com走direct，后面引用了Google走Proxy，很可能该直连的就消耗流量了

这个问题也像小火箭作者反馈了，也许以后会修改，所以在修改前，可否在小火箭相关规则里面加个提示呢，提醒用户有重复的是以后面的规则为准

**Comment by blackmatrix7** [comment]
目前没有计划提供对客户端配置的帮助，一方面是我自己对客户端配置了解也不是很深，另外一方面是众所周知的原因。
