### ISSUE TITLE
百度贴吧死循环

### ISSUE THREAD

**Issue by L1cardo** [blackmatrix7/ios_rule_script#178]
这条规则造成了死循环
![image](https://user-images.githubusercontent.com/33802186/105811448-9e215200-5fe7-11eb-9ed7-811e61c03807.png)![image](https://user-images.githubusercontent.com/33802186/105811453-a11c4280-5fe7-11eb-828d-7610058f914a.png)![image](https://user-images.githubusercontent.com/33802186/105811461-a2e60600-5fe7-11eb-8537-dd99916050cf.jpeg)

**Comment by blackmatrix7** [comment]
Reject的规则应该不会造成死循环，更多的可能是贴吧在请求被拦截后，触发大量重试引起请求风暴。你可以尝试把策略改为REJECT-DROP。

**Comment by L1cardo** [comment]
这又是 surge 的隐藏策略？  服了。。。。。

**Comment by blackmatrix7** [comment]
> 这又是 surge 的隐藏策略？ 服了。。。。。

REJECT-DROP：拒绝该请求，与 REJECT 不同的是，该策略将静默抛弃请求。因为部分程序有着十分暴力的重试逻辑，连接失败后会立刻进行重试，导致请求风暴。
