### ISSUE TITLE
Global_Domain.list规则无法匹配

### ISSUE THREAD

**Issue by LisonChan** [blackmatrix7/ios_rule_script#179]
Global_Domain.list中的
.google
无法被匹配，查询surge手册后发现DOMAIN-SET只能识别DOMAIN 和 DOMAIN-SUFFIX 两种形式的内容，而.google属于DOMAIN-KEYWORD规则所以无法被DOMAIN-SET匹配
DOMAIN-SET匹配Google需要改为DOMAIN-SUFFIX规则
即 .google.com等等

**Comment by blackmatrix7** [comment]
这条规则是来自 https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list的
DOMAIN-SUFFIX,google
DOMAIN-SUFFIX类型的规则，在转换成DOMIAN-SET时，会将其转换为.google，并不是由DOMAIN-KEYWORD转换的。
晚些会加到过滤器把它去掉。

**Comment by LisonChan** [comment]
经过测试，DOMAIN-SUFFIX,google也不会被匹配到，谢谢

**Comment by blackmatrix7** [comment]
> 经过测试，DOMAIN-SUFFIX,google也不会被匹配到，谢谢

这条规则本来就是错的，我的程序是对上游数据源做整合，上游数据源错了就会反应到整合生成后到规则，这时只能手动维护过滤器将错误的规则去掉。

**Comment by LisonChan** [comment]
> > 经过测试，DOMAIN-SUFFIX,google也不会被匹配到，谢谢
> 
> 这条规则本来就是错的，我的程序是对上游数据源做整合，上游数据源错了就会反应到整合生成后的规则，这时只能手动维护过滤器将错误的规则去掉。

已经向上游提交了错误报告

**Comment by blackmatrix7** [comment]
> > > 经过测试，DOMAIN-SUFFIX,google也不会被匹配到，谢谢
> > 
> > 
> > 这条规则本来就是错的，我的程序是对上游数据源做整合，上游数据源错了就会反应到整合生成后的规则，这时只能手动维护过滤器将错误的规则去掉。
> 
> 已经向上游提交了错误报告，辛苦作者了

谢谢反馈，已经更新去除这条规则。

**Comment by blackmatrix7** [comment]
DOMAIN-SUFFIX,google 是正确的，因为存在如dns.google的域名，所以这条规则在明天更新会重新加回来。
