### ISSUE TITLE
请求从Advertising中移除 chtbl.com 

### ISSUE THREAD

**Issue by lucifer9** [blackmatrix7/ios_rule_script#183]
因为很多博客订阅会用这个来track下载...例如 https://podcastrepublic.net/podcast/1460475182
下载连接是 https://chtbl.com/track/6AGABB/r.typlog.com/eyJzIjozNTIsImUiOjUxMTcsInAiOjIsInUiOiIxODAxLm1wMyJ9.BUu1N-bD9GrzKAdmMHL_PJgle_E/pythonhunter/8389736406_21801.mp3

**Comment by blackmatrix7** [comment]
已更新去除。
