### ISSUE TITLE
quantumltx分流规则中advertising相关存在报错

### ISSUE THREAD

**Issue by LucaLin233** [blackmatrix7/ios_rule_script#186]
萌新不太会用issue，只能简单反馈
quantumltx分流规则中的advertising规则里存在报错项目，导致无法更新，为最后一条
![73F63AA8-4D4F-4F1E-B801-F86519813F3D](https://user-images.githubusercontent.com/78164141/106167539-42fa8580-61c8-11eb-8b58-f514b596c363.png)
 IP6-CIDR, ,Advertising

**Comment by blackmatrix7** [comment]
谢谢反馈，暂时把IPV6去掉了，过个10分钟更新一下试试，具体问题等有空再排查下。

**Comment by LucaLin233** [comment]
感谢及时修复，稍后我更新看看

> 谢谢反馈，暂时把IPV6去掉了，过个10分钟更新一下试试，具体问题等有空再排查下。

**Comment by blackmatrix7** [comment]
已修复了。
