### ISSUE TITLE
Apple 地图 Host 被错误🙅分类

### ISSUE THREAD

**Issue by shadowdogy** [blackmatrix7/ios_rule_script#188]
如下图：
![image](https://user-images.githubusercontent.com/77425913/106267013-0aa88500-6264-11eb-8b37-b69dbaf9590a.jpeg)

该 Host 被错误分配到了 GlobalMedia 中。这可能造成 Apple Map 中的地图提供商从国内的高德地图变更到 TomTom 等国外提供商。

**Comment by blackmatrix7** [comment]
gspe1-ssl.ls.apple.com 不仅用于国内高德地图，在Apple News等其他服务中都会使用到，所以直接去掉不是很合适。

建议在GlobalMedia前加一条规则进行放行。
