### ISSUE TITLE
https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/QuantumultX/Advertising#quantumultx

### ISSUE THREAD

**Issue by czmecho** [blackmatrix7/ios_rule_script#19]
链接地址错了，
原文是
实时版： https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf

稳定版： https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/master/rewrite/QuantumultX/Advertising/Advertising.conf

**Comment by blackmatrix7** [comment]
谢谢提醒，已修复。
