### ISSUE TITLE
mac无法检测更新

### ISSUE THREAD

**Issue by L1cardo** [blackmatrix7/ios_rule_script#191]
应该是 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list
这个中的某一个阻止了mac系统的更新检测
<img width="146" alt="image" src="https://user-images.githubusercontent.com/33802186/106541730-7c6f2000-653d-11eb-82ac-886267b23544.png">

**Comment by blackmatrix7** [comment]
我的Macbook用的是老版本的Surge，不支持RULE-SET，只能你抓包告诉我哪条规则，我再去掉。
