### ISSUE TITLE
loon下知乎助手插件无论plus还是lite无法在推荐页面自动播放视频

### ISSUE THREAD

**Issue by yzxj3180** [blackmatrix7/ios_rule_script#192]
RTRTRT，关闭知乎助手插件后恢复正常。

**Comment by blackmatrix7** [comment]
不太清楚你说的自动播放是指什么，是刷到视频自动开始播放，还是点击视频后自动开始播放?

**Comment by yzxj3180** [comment]
刷到视频自动播放，和app设置无关，因为关闭插件后就会恢复正常，而且不是无法播放，是一直加载不播放，而不是暂停。

另外点击视频后下滑到其他相关推荐视频时候，出现以下信息。
json:invalid use of ,string struct tag,trying to unmarshal ""into int64 
不知道与该问题有没有关系。

**Comment by blackmatrix7** [comment]
我在知乎 6.62.0 (2824) 和 Loon 2.1.6 (252) TF 版本测试是正常的。

Loon再往上升级，会导致我连不上代理服务器，原因不明，所以暂时没再往上升级。

**Comment by yzxj3180** [comment]
我得loon和你版本一样，知乎是7.3 3820版本的。。。。差的有点多吧。。。


198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:198  [Debug]  [385] api.zhihu.com match policy:DIRECT match rule:DOMAIN-SUFFIX,zhihu.com,DIRECT
2021/02/05 14:07:12:208  [Debug]  [393] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:211  [Debug]  [394] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:213  [Debug]  [395] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:244  [Debug]  [396] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:248  [Debug]  [397] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:251  [Debug]  [398] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:289  [Debug]  Featch dns cache for:api.zhihu.com (ip:198.18.5.225)
2021/02/05 14:07:12:301  [Debug]  [399] api.zhihu.com match policy:DIRECT match rule:DOMAIN-SUFFIX,zhihu.com,DIRECT
2021/02/05 14:07:12:480  [Debug]  Match script:知乎_信息流去广告 url:https://api.zhihu.com/topstory/recommend?session_token=da63ef9315a3c3e0b666e43ae1ff1beb&page_number=4&limit=6&action=down&after_id=18&ad_interval=0&action_feed=true&feed_card_exp=card_corner%7C1&reverse_order=0&scroll=down&tsp_ios_cardredesign=0&v_serial=2 [body]
2021/02/05 14:07:12:487  [Debug]  [382] Start http-response(need response body) script
2021/02/05 14:07:12:490  [Info]  Start execute http-response script:知乎_信息流去广告
2021/02/05 14:07:12:506  [Debug]  LNJSContext release
2021/02/05 14:07:12:508  [Debug]  script response length:26561
2021/02/05 14:07:12:515  [Debug]  [400] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:520  [Debug]  [401] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:528  [Debug]  [402] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:545  [Debug]  [403] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:547  [Debug]  [405] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:549  [Debug]  [406] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:574  [Debug]  Featch dns cache for:api.zhihu.com (ip:198.18.5.225)
2021/02/05 14:07:12:584  [Debug]  [408] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:585  [Debug]  [409] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:586  [Debug]  [404] api.zhihu.com match policy:DIRECT match rule:DOMAIN-SUFFIX,zhihu.com,DIRECT
2021/02/05 14:07:12:586  [Debug]  TTL timeout:api.zhihu.com (ip:198.18.5.225)
2021/02/05 14:07:12:586  [Debug]  start query for:api.zhihu.com designated Server:(null)
2021/02/05 14:07:12:586  [Debug]  Featch dns cache for:lens.zhihu.com (ip:198.18.18.232)
2021/02/05 14:07:12:588  [Debug]  [410] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:591  [Debug]  [412] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:593  [Debug]  [414] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:594  [Debug]  [416] 118.89.204.198 match policy:REJECT match rule:IP-CIDR,118.89.204.198/32,REJECT
2021/02/05 14:07:12:598  [Debug]  [407] lens.zhihu.com match policy:DIRECT match rule:DOMAIN-SUFFIX,zhihu.com,DIRECT
2021/02/05 14:07:12:598  [Debug]  TTL timeout:lens.zhihu.com (ip:198.18.18.232)
2021/02/05 14:07:12:598  [Debug]  start query for:lens.zhihu.com designated Server:(null)
2021/02/05 14:07:12:599  [Debug]  Query dns for:api.zhihu.com - 198.18.5.225 from:2408:8207:c96:99e0::1
2021/02/05 14:07:12:602  [Debug]  Query dns for:lens.zhihu.com - 198.18.18.232 from:192.168.5.1

**Comment by blackmatrix7** [comment]
确认脚本不兼容知乎7.x版，原因还需要排查，近期没时间维护脚本，如果很在意这个问题建议先降级知乎App版本使用。

**Comment by yzxj3180** [comment]
没关系，大神的广告屏蔽功能已经很爽了，忙完了年后再说吧
