### ISSUE TITLE
大佬可以给famijia加上多账号吗，类似boxjs的

### ISSUE THREAD

**Issue by windforclouds** [blackmatrix7/ios_rule_script#193]

**Comment by blackmatrix7** [comment]
京东之所以能多账号，是因为它通过网页端登录，可以使用不同浏览器或无痕模式来登录不同账号，并且保证Cookie不过期。

而Fa米家是通过App登录，当你在App中退出登录时，Cookie就已经失效，所以无法在同个设备中保持两个Cookie不过期。

除非你有两台手机，分别将两个Cookie填入，不过既然都有两台手机了，多账号也没什么实际意义……

等什么时候Fa米家有微信小程序等其他登录途径，能同时保证多个Cookie不过期，才能实现。
