### ISSUE TITLE
非常不错的白名单列表

### ISSUE THREAD

**Issue by Angelalisa-x** [blackmatrix7/ios_rule_script#197]
https://raw.githubusercontent.com/Potterli20/filtering/master/filtering.txt

**Comment by blackmatrix7** [comment]
谢谢反馈，不过目前暂时没办法支持这样的格式，后续可以支持我再回复你。

**Comment by Angelalisa-x** [comment]
简单转换一下就好了呀

**Comment by blackmatrix7** [comment]
虽然这个文件的内容都是域名，但是Adblock的例外规则，并不是域名，而是通配符或正则。

由于上游数据源内容对规则生成程序来说不可控，所以不能简单地把它们当成域名来处理，否则一旦出现域名之外的规则，就可能生成意外结果。

增加一种新的数据源类型支持，需要重新编写一套转换器去解析和转换此类型的所有规则。这个工作量不小，但是收益很小。

不过可以弄个折中的办法，将这个文件的现有内容手动做下文本替换，作为规则的本地数据源，但是没办法同步上游数据源更新。
