### ISSUE TITLE
网易云音乐普通歌曲无法播放

### ISSUE THREAD

**Issue by weijingcheng4** [blackmatrix7/ios_rule_script#199]
HOST-SUFFIX,music.126.net,NetEaseMusic
这条规则导致网易云音乐普通歌曲无法播放

**Comment by blackmatrix7** [comment]
music.126.net 也是网易云音乐所使用的域名，无法播放是因为使用的节点没有处理music.126.net域名的请求。

建议手动增加一条规则对music.126.net进行方向。
