### ISSUE TITLE
关于规则的一点建议

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#2]
IP-CIDR, 118.89.204.198/32, REJECT
以上这条规则在surge中是会触发dns查询的（所有域名请求经过这条规则都会触发）
如果有人将教程中的去广告规则置于最前，那么会产生大量不必要的dns查询

建议改成以下这样，不影响去广告效果，不会触发dns查询
IP-CIDR, 118.89.204.198/32, REJECT,no-resolve

**Comment by blackmatrix7** [comment]
> IP-CIDR, 118.89.204.198/32, REJECT
> 以上这条规则在surge中是会触发dns查询的（所有域名请求经过这条规则都会触发）
> 如果有人将教程中的去广告规则置于最前，那么会产生大量不必要的dns查询
> 
> 建议改成以下这样，不影响去广告效果，不会触发dns查询
> IP-CIDR, 118.89.204.198/32, REJECT,no-resolve

感谢提醒，因为我自己没用模块，没有注意到，已更正。
