### ISSUE TITLE
[smzdm]多了两条通知

### ISSUE THREAD

**Issue by EchoChan314** [blackmatrix7/ios_rule_script#20]
![微信图片_20201011114210.png](https://i.loli.net/2020/10/11/VJ3mD5O79S8Ncb2.png)
按理标红的两条通知应该不用出现的吧?

**Comment by blackmatrix7** [comment]
Cookie写入成功这个不是我这边的通知，你可能引用了其他的签到脚本。
没有获取到App端账号密码，因为脚本没有读取到有效的登录账号密码，所以有这个通知，只影响App端签到，不影响Web端签到。
