### ISSUE TITLE
China.list和ChinaIP.list能否考虑添加一个直接以DIRECT结尾的版本

### ISSUE THREAD

**Issue by LeoJeson** [blackmatrix7/ios_rule_script#200]
例如：
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/China.list
和
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Extra/ChinaIP.list
其中的每一条规则直接以DIRECT结尾，可以省去在quanx中的一个策略组

**Comment by blackmatrix7** [comment]
试试force-policy=DIRECT
