### ISSUE TITLE
IQIYI

### ISSUE THREAD

**Issue by MyGoodbye** [blackmatrix7/ios_rule_script#201]
安卓手机让iqiyi走台湾代理，网页可以看，但是手机app仍然地区限制无法观看，有办法解决吗？

**Comment by blackmatrix7** [comment]
可能是分流规则内的域名、IP不够齐全导致，你可以抓包一下看看哪些流量没有走代理导致。

**Comment by MyGoodbye** [comment]
> 可能是分流规则内的域名、IP不够齐全导致，你可以抓包一下看看哪些流量没有走代理导致。

已解决，谢谢，加了一部分 
  - DOMAIN-KEYWORD,events.appsflyer.com
  - IP-CIDR,159.138.102.146/32
  - IP-CIDR,159.138.107.90/32
  - IP-CIDR,52.77.62.30/32
  - IP-CIDR,3.0.121.41/32
  - IP-CIDR,3.1.161.42/32
  - IP-CIDR,8.138.94.6/32
  - IP-CIDR,203.74.95.137/32
  - IP-CIDR,106.75.84.152/32
  具体是哪一些起作用不确定，懒得尝试。
最后：谢谢！
