### ISSUE TITLE
网易云音乐分流导致平安京无法进入游戏

### ISSUE THREAD

**Issue by idgenusomne** [blackmatrix7/ios_rule_script#202]
IP-CIDR,59.111.128.0/17,NetEaseMusic
网易云的这条规则，会导致无法进入决战平安京，服务器超时。改成direct就可以进，不知道会不会影响网易云的解锁。

**Comment by LeoJeson** [comment]
类似的问题，现在的qx网易云音乐规则过于严格，导致网易旗下的其他app，包括但不限于中国大学mooc，以及个别网易游戏无法使用

**Comment by blackmatrix7** [comment]
可能是某些域名、IP并不只用于网易云音乐，而节点又配置为仅允许用过网易云音乐的请求。

建议手动设置放心规则，或者自建节点，在配置中允许通过网易云音乐外的其他请求。

不过以上仅是猜测。
