### ISSUE TITLE
新增REJECT知乎IPv6解析請求

### ISSUE THREAD

**Issue by Mr-Sheep** [blackmatrix7/ios_rule_script#203]
https://github.com/blackmatrix7/ios_rule_script/blob/2724c2f76ae65d9915745b805bc27e34ece3b840/rule/Surge/ZhihuAds/ZhihuAds.list

在開啓IPv6後，知乎會用請求`118.89.204.198/resolv?host=zhihu-web-analytics.zhihu.com`的方式向
`2402:4e00:1200:ed00:0:9089:6dac:96b6`發起連結

可以新增對`2402:4e00:1200:ed00:0:9089:6dac:96b6/128`的屏蔽

附上具體請求內容
```
curl 'http://[2402:4e00:1200:ed00:0:9089:6dac:96b6]/resolv?host=zhihu-web-analytics.zhihu.com&os_type=iOS&udid=&uid=&version=7.3.1' -H 'Host: [2402:4e00:1200:ed00:0:9089:6dac:96b6]' -H 'Accept: */*' -H 'User-Agent: osee2unifiedRelease/7.3.1 (iPhone; iOS 14.4; Scale/3.00)' -H 'Accept-Language: en-US;q=1, zh-Hant-US;q=0.9, zh-Hans-US;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' --compressed
```

**Comment by blackmatrix7** [comment]
拦截118.89.204.198的请求，阻止知乎进行解析应该就够了。解析结果不一定的服务器的真实地址，可能是CDN的地址，如果把它们直接REJECT，担心会影响其他APP工作。
