### ISSUE TITLE
您好，我无法获取饿了么Cookie

### ISSUE THREAD

**Issue by WowYiJiu** [blackmatrix7/ios_rule_script#204]
设备: 苹果12
饿了么版本: v9.8.5
远程订阅，按说明进入饿了么超级吃货卡无反应
不会用日志调试。。。

**Comment by WowYiJiu** [comment]
抱歉，忘了说了我用的是圈x最新版，日志里我发现有饿了么cookie啊，但是脚本没有获取到

**Comment by blackmatrix7** [comment]
把获取Cookie的日志，和脚本执行的日志复制上来我看下。
Cookie内容做下处理

**Comment by WowYiJiu** [comment]
![elm2](https://user-images.githubusercontent.com/63225855/108986556-3a18a900-76cd-11eb-8b2a-f77443c8af43.png)
![elm](https://user-images.githubusercontent.com/63225855/108986568-3be26c80-76cd-11eb-921e-42baff1a1847.jpg)
实在不好意思，不知道这两张图片有用没，cookie重写和gallery都是直接用的您的，cookie是在我开启调试时找到的，无脚本执行记录
