### ISSUE TITLE
直接把白名单放到去广告的规则里面去过滤会不会好点

### ISSUE THREAD

**Issue by Angelalisa-x** [blackmatrix7/ios_rule_script#205]
去广告的规则数量会少一点，误杀率也低一点

**Comment by blackmatrix7** [comment]
去广告规则和白名单不是简单的互斥关系。

假设 *.ad.demo.net 是需要过滤的广告域名，而 user.ad.demo.net 是需要排除的白名单，此时把user.ad.demo.net加入到过滤器中，对 *.ad.demo.net这条规则实际没有任何效果。
