### ISSUE TITLE
分流规则中 TikTok.list 域名分流问题

### ISSUE THREAD

**Issue by harveyhuangw** [blackmatrix7/ios_rule_script#206]
TikTok.list  若设置走代理，,snssdk.com ，该域名，会导致国内字节跳动系软件，例如 头条，西瓜视频，加载访问缓慢，反之设置direct，则正常，而tiktok访问对该域名不走代理貌似没什么影响

**Comment by blackmatrix7** [comment]
我很久不用TikTok，记得TikTok并不需要代理。snssdk.com国内的抖音和国外的TikTok都在用，对于这种一个域名多个APP使用的，没什么很好的办法。因为snssdk.com的确是TikTok的使用的域名，直接去掉也不合适。
建议手动处理下进行DIRECT。
