### ISSUE TITLE
quantumultx重写的allinone部分出现单个地址404

### ISSUE THREAD

**Issue by LucaLin233** [blackmatrix7/ios_rule_script#207]
看缩写是什么值得买的js出现库404，如图
![79E24C38-0EE2-473F-BBE7-FCE164E3DE19](https://user-images.githubusercontent.com/78164141/109034310-7c101200-7702-11eb-90e8-2759ab947e1a.jpeg)
![2BE249BB-2FEF-4CF4-BB31-C0811867DF47](https://user-images.githubusercontent.com/78164141/109034317-7e726c00-7702-11eb-9e25-d97d3f9f3444.jpeg)

**Comment by blackmatrix7** [comment]
什么值得买拆分为签到和任务两个脚本，需要修改地址。

如果希望使用旧文件，在smzdm/backup目录下，不过旧文件不会再进行更新。
