### ISSUE TITLE
force-http-engine-hosts缺失

### ISSUE THREAD

**Issue by ashurinn** [blackmatrix7/ios_rule_script#208]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rewrite/Surge/Advertising/Advertising.sgmodule
此模块中缺失force-http-engine-hosts = %APPEND% *.cp31.ott.cibntv.net，导致^https?:\/\/vali\.cp31\.ott\.cibntv\.net\/youku - reject不生效，无法去除优酷片头广告。
关于该参数参见https://manual.nssurge.com/book/understanding-surge/cn/#%E5%8C%BA%E5%88%86%E8%AF%B7%E6%B1%82

**Comment by blackmatrix7** [comment]
Advertising.sgmodule 是由程序自动生成的，所以没办法直接修改文件来实现，否则下次生成时还是会被覆盖掉。

需要修改生成程序，来支持force-http-engine-hosts参数，临时的解决方案建议先手动在配置文件中加上。

后续可以支持此参数时，我再回复你。

**Comment by blackmatrix7** [comment]
已经支持几天了，忘了回复不好意思。
