### ISSUE TITLE
clash chianips 的分流规则 404了 

### ISSUE THREAD

**Issue by ZoreAir** [blackmatrix7/ios_rule_script#209]

**Comment by ZoreAir** [comment]
如果恢复的话 请通知一声

**Comment by blackmatrix7** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml

**Comment by YUUKIASUNA233** [comment]
取消订阅





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: blackmatrix7 <notifications@github.com&gt;
发送时间: 2021年2月25日 22:32
收件人: blackmatrix7/ios_rule_script <ios_rule_script@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[blackmatrix7/ios_rule_script] clash chianips 的分流规则 404了  (#209)






Closed #209.
