### ISSUE TITLE
望增加# 知乎网页版去广告&推荐列表这个qx重写

### ISSUE THREAD

**Issue by MisterGlasses** [blackmatrix7/ios_rule_script#21]
# 知乎网页去广告&推荐列表
https://www\.zhihu\.com/api/v4/questions/\d+/related-readings url reject-200
https://www\.zhihu\.com/api/v4/answers/\d+/related-readings url reject-200
https://www\.zhihu\.com/api/v4/hot_recommendation url reject-200
https://www\.zhihu\.com/commercial_api/banners_v3/mobile_banner url reject-200
https://zhuanlan\.zhihu\.com/api/articles/\d+/recommendation url reject-200

[mitm]
hostname = www.zhihu.com, zhuanlan.zhihu.com

**Comment by blackmatrix7** [comment]
我网页版用得很少，请问下这些是屏蔽什么内容的？

**Comment by MisterGlasses** [comment]
> 我网页版用得很少，请问下这些是屏蔽什么内容的？

网页版知乎的广告 推荐等

**Comment by blackmatrix7** [comment]
> > 我网页版用得很少，请问下这些是屏蔽什么内容的？
> 
> 网页版知乎的广告 推荐等

最近事情比较多，稍晚我测一下。

**Comment by MisterGlasses** [comment]
> > > 我网页版用得很少，请问下这些是屏蔽什么内容的？
> > 
> > 网页版知乎的广告 推荐等
> 
> 最近事情比较多，稍晚我测一下。

麻烦了
