### ISSUE TITLE
本条已404

### ISSUE THREAD

**Issue by tengyuankoo** [blackmatrix7/ios_rule_script#210]
https://github.com/blackmatrix7/ios_rule_script/blob/89c6c770f925adb83aa065468f375664ee0718a1/rewrite/QuantumultX/AllInOne/AllInOne.conf#L847

**Comment by WowYiJiu** [comment]
更改下脚本地址就可以了

**Comment by blackmatrix7** [comment]
旧版的JS已移动到smzdm/backup目录下，你可以使用新版的AllInOne，或者手动修改使用旧版的文件。
