### ISSUE TITLE
clash里  Chinatest的分流规则有问题

### ISSUE THREAD

**Issue by ZoreAir** [blackmatrix7/ios_rule_script#212]

**Comment by ZoreAir** [comment]
Chinatest-domain 订阅链接 显示格式错误
Chinatest的里分流规则数量和统计数量不同

**Comment by blackmatrix7** [comment]
当DOMAINL类型的规则数量过多时，会自动拆分出ChinaTest_Domain.yaml。所以ChinaTest.yaml 和 ChinaTest_Domain.yaml 共同使用才是完整的规则，规则数量统计是按两个文件的总数。

ChinaTest_Classical.yaml 则一个文件可以包含上面两个文件全部内容。

具体的区别，我用Clash很少，不太清楚。

ChinaTest_Domain.yaml 正常情况下不应该会出现格式错误，因为都是通过同一个模板生成的，我在OpenClash使用Proxy_Domain.yaml时，可以正常读取内容。这个需要你进一步提供一些信息。

**Comment by ZoreAir** [comment]
懂了
