### ISSUE TITLE
qx重写All in one中去广告重写导致网易云mv无法加载

### ISSUE THREAD

**Issue by idgenusomne** [blackmatrix7/ios_rule_script#213]
通过分析qx网络活动与自行测试，^https?:\/\/interface3?\.music\.163\.com/eapi/(ad|abtest|sp|hot|store|mlog|search/(specialkeyword|defaultkeyword|hot)) url reject-img
这条重写导致主页顶部滚动栏mv类无法正常播放，以及歌曲mv按钮界面无法正常进入t与播放。
禁用该条后，mv类播放正常。

**Comment by blackmatrix7** [comment]
我试了下没发现有不能加载的问题，能否给个MV链接我试试？

**Comment by idgenusomne** [comment]
就现在主页滚动栏那个tfboys七周年演唱会纪录片。

**Comment by blackmatrix7** [comment]
昨天把两个MV、Surge、QuantumultX都测试了下，没办法复现这个问题。方便给下抓包记录吗？

**Comment by idgenusomne** [comment]
![7A166B95-E95A-498A-8C26-7AE934AB47EE](https://user-images.githubusercontent.com/70569089/109446075-f54d9300-7a7b-11eb-9f84-9e1d8b5ebfb2.png)
![FA42A420-990F-4CB4-A044-F1BEB7F7DBD8](https://user-images.githubusercontent.com/70569089/109446080-f8e11a00-7a7b-11eb-8e41-89f181cc3c4e.png)
![832E9F31-BFDC-4F0A-AD76-258EB53B3750](https://user-images.githubusercontent.com/70569089/109446082-f979b080-7a7b-11eb-9bf9-815e67808323.png)

**Comment by blackmatrix7** [comment]
你网易云音乐的版本是？可能是版本不一样，我抓不到这个请求。

**Comment by idgenusomne** [comment]
8.1.30

**Comment by blackmatrix7** [comment]
已经更新去除了。
