### ISSUE TITLE
什么值得买和中国联通获取不到cookie

### ISSUE THREAD

**Issue by r0ckrise** [blackmatrix7/ios_rule_script#214]
重新恢复了手机，直接用的您的合集的复写获取不到了。![image](https://user-images.githubusercontent.com/76696224/109373324-103bce00-78e9-11eb-8771-5846b8e994d1.png)![image](https://user-images.githubusercontent.com/76696224/109373331-1467eb80-78e9-11eb-8018-a0e8cdf390e6.png)

**Comment by blackmatrix7** [comment]
什么值得买的js文件更换了，不知道你那里更新了没。

联通你试试在App里搜索天天抽奖。

**Comment by r0ckrise** [comment]
奇怪的是，用合集getcookie获取不到联通的cookie，用单个订阅的就可以，是冲突还是什么原因不知道，张大妈的单个也还是不行。

**Comment by blackmatrix7** [comment]
> 取不到联通的cookie，用单个订阅的就可以，是冲突还是什么原因不知道，张大妈的单个也还是不行。

GetCookie是自动生成的，我自己也没试过，因为其他的模块也带获取Cookie的脚本，是由可能冲突的，你可以先用单个模块，后面我再试试。

**Comment by r0ckrise** [comment]
好的，辛苦大佬了，联通OK，就是什么值得买获取不到了

**Comment by blackmatrix7** [comment]
> 好的，辛苦大佬了，联通OK，就是什么值得买获取不到了

什么值得买单个模块也获取不到Cookie吗？

**Comment by r0ckrise** [comment]
> > 好的，辛苦大佬了，联通OK，就是什么值得买获取不到了
> 
> 什么值得买单个模块也获取不到Cookie吗？

获取不到

**Comment by blackmatrix7** [comment]
> > 
> 
> 今天又试了下，可以了，集合的不行，应该是重写冲突了。

GetCookie集合主要是给QuanX使用的，如果是其他客户端，不建议使用，因为每个模块或插件已经带有获取Cookie的复写，目前尚不清楚多个重复的复写会有什么问题。

**Comment by r0ckrise** [comment]
👌🏻，我是圈x。
