### ISSUE TITLE
surge module 可否不限制 platform

### ISSUE THREAD

**Issue by puuuudding** [blackmatrix7/ios_rule_script#216]
因为 mac surge 可以作为家里网关来用，此时我会临时停用 iOS 的 surge，所有代理都走 mac surge，此时 iOS 的 module 就不起效果了，又由于 module 的 platform 限制，我无法将这些 module 装到我的 mac surge 上。是否可以取消 module 中 platform 的限制？

**Comment by blackmatrix7** [comment]
方便说下哪个模块吗？

**Comment by puuuudding** [comment]
我现在有用到知乎去广告脚本

**Comment by blackmatrix7** [comment]
已经去除了
