### ISSUE TITLE
Rewrite下all in one集合希望不加入cookies获取脚本

### ISSUE THREAD

**Issue by Qbo218** [blackmatrix7/ios_rule_script#217]
最新的master分支下面的Rewrite下的all in one集合加入了cookies获取脚本。但用Rewrite主要作用是去广告，cookies加入后会造成使用不方便。现在release分支尚未加入，希望保持不加入或后期master也取消加入，cookies脚本自行选择是否单独添加模块。望考虑，谢谢。

**Comment by blackmatrix7** [comment]
有去掉的计划，加入GetCookie的确不合理，今天会去掉，明天更新下就可以。

**Comment by Qbo218** [comment]
好的，非常感谢！

**Comment by blackmatrix7** [comment]
已经去掉了，你更新一下吧。
