### ISSUE TITLE
B站开屏广告处理出现异常

### ISSUE THREAD

**Issue by chouchoui** [blackmatrix7/ios_rule_script#218]
错误信息：`TypeError: undefined is not an object (evaluating 'obj["data"]["show"].length')`

https://github.com/blackmatrix7/ios_rule_script/blob/f5f3d70035e7bfa736a21bf0aa99515a3c3835bd/script/bilibili/bilibili_plus.js#L50

Surge 与 Quantumult X抓包结果对象
```json
{
  "code" : 0,
  "message" : "0",
  "ttl" : 1,
  "data" : {
    "max_time" : 4,
    "min_interval" : 14400,
    "list" : [
        ……
    ],
    "pull_interval" : 900
  }
}

```

**Comment by blackmatrix7** [comment]
已知问题，等待修复。

**Comment by blackmatrix7** [comment]
已修复
