### ISSUE TITLE
复写去广告怎么用

### ISSUE THREAD

**Issue by wanch1ng** [blackmatrix7/ios_rule_script#219]
在复写里面订阅了，也开启了mitm，但是开屏广告还是有。

**Comment by blackmatrix7** [comment]
复写只是对网上其他大佬的规则做一个集合去重，并不能保证去除所有APP的启动广告。

你可以提供下APP的版本，我有空可以试着验证下。

**Comment by wanch1ng** [comment]
[Image.jpeg]
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: blackmatrix7 <notifications@github.com>
发送时间: Monday, March 1, 2021 5:38:52 PM
收件人: blackmatrix7/ios_rule_script <ios_rule_script@noreply.github.com>
抄送: wanch1ng <wncg05@outlook.com>; Author <author@noreply.github.com>
主题: Re: [blackmatrix7/ios_rule_script] 复写去广告怎么用 (#219)


复写只是对网上其他大佬的规则做一个集合去重，并不能保证去除所有APP的启动广告。

你可以提供下APP的版本，我有空可以试着验证下。

―
