### ISSUE TITLE
TikTok无法登录和查看个人页面。

### ISSUE THREAD

**Issue by LevineWoo** [blackmatrix7/ios_rule_script#221]
在引用ios_rule_script/rewrite/QuantumultX/AllInOne的https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf
后
TikTok无法登录和查看个人页面

**Comment by blackmatrix7** [comment]
排查了下，复写中只有针对ad类型的规则，应该不会误杀。
建议更换个解锁的脚本试试，我用的是https://github.com/Semporia/TikTok-Unlock，测试正常。
