### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dashmett** [blackmatrix7/ios_rule_script#222]
Bilibili App 下方栏只会出现”我的“
![2C4CDFE7-F9DE-47D1-95D1-6A3AA35E8FFF](https://user-images.githubusercontent.com/79370026/109681072-0f8c8b80-7bb8-11eb-8d4f-d028b04683ed.jpeg)

**Comment by blackmatrix7** [comment]
无法复现此问题，也未收到其他人的反馈，建议检查下是否有复写的冲突。
