### ISSUE TITLE
关于油管观看记录的问题

### ISSUE THREAD

**Issue by LucaLin233** [blackmatrix7/ios_rule_script#224]
在引用 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list 该规则后，油管播放记录不能被记录，导致无法使用历史观看功能。
初步定位为：HOST,s.youtub.com,Advertising 和 HOST-SUFFIX,ads.youtube.com,Advertising 二者其一，极大概率为前者。
希望作者修复，万分谢谢。

**Comment by blackmatrix7** [comment]
s.youtube.com 已经加入过滤器，等待明天凌晨自动更新即可。

**Comment by blackmatrix7** [comment]
已更新
