### ISSUE TITLE
关于QX m.douban.com 分流错误的问题

### ISSUE THREAD

**Issue by mintyfrankie** [blackmatrix7/ios_rule_script#225]
这个域名被自动纳入了 Global.list 中，这个规则会导致 iOS App 无法正常刷新。

![image](https://user-images.githubusercontent.com/77310871/109931733-29d38000-7d04-11eb-87c0-c3a1170e563b.png)

麻烦查看处理一下，谢谢。

**Comment by blackmatrix7** [comment]
谢谢反馈，已经加到过滤器中，请等待明天凌晨自动更新。

**Comment by blackmatrix7** [comment]
已更新

**Comment by mintyfrankie** [comment]
已确认，谢谢！
