### ISSUE TITLE
百度网盘头像误杀

### ISSUE THREAD

**Issue by BaileyZyp** [blackmatrix7/ios_rule_script#228]
![A60EF45F-8DDC-42D6-A4D7-474229D9D3B8](https://user-images.githubusercontent.com/16634459/110046777-9f346480-7d87-11eb-8928-1dd5cff794d5.jpeg)
![87F8E634-D47D-4CF1-BC61-8947355CF3E4](https://user-images.githubusercontent.com/16634459/110046784-a0fe2800-7d87-11eb-8537-189960dc3a1c.jpeg)

个人头像，群组头像，按钮图标都被误杀了😂

**Comment by blackmatrix7** [comment]
头像的地址是dss0.bdstatic.com，很不幸APP启动广告也是这个地址，如果放行，头像是正常的，但是APP启动广告也随之出现。

**Comment by blackmatrix7** [comment]
如果你是会员没有启动广告，可以手动加一条规则 DOMAIN,dss0.bdstatic.com  将它设置到最前面方向。
