### ISSUE TITLE
b站复写规则问题

### ISSUE THREAD

**Issue by LucaLin233** [blackmatrix7/ios_rule_script#229]
在引用https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf  复写规则后，b站深色模式无法跟随系统深色模式，打开即日间模式，去广告相关部分运作正常，关闭复写后能够跟随系统夜间模式。
客户端版本6.19.0

**Comment by blackmatrix7** [comment]
暂时把处理B站皮肤的复写去掉了，你再试试。

**Comment by blackmatrix7** [comment]
如果还有问题你再打开这个issue

**Comment by LucaLin233** [comment]
> 如果还有问题你再打开这个issue

更新规则后问题依旧

**Comment by blackmatrix7** [comment]
对复写做了彻底的删除，如果还有问题，提供下APP的版本，还有客户端的版本，比如Surge或Loon，是什么版本的。

我这里一直是正常的。

**Comment by LucaLin233** [comment]
> 对复写做了彻底的删除，如果还有问题，提供下APP的版本，还有客户端的版本，比如Surge或Loon，是什么版本的。
> 
> 我这里一直是正常的。

目前正常了，更新规则后，反复切换模式也不会恢复成日间模式了，我过段时间再测试一下，目前我使用的B站版本是6.19.0，QX版本是1.0.19

**Comment by blackmatrix7** [comment]
> > 对复写做了彻底的删除，如果还有问题，提供下APP的版本，还有客户端的版本，比如Surge或Loon，是什么版本的。
> > 我这里一直是正常的。
> 
> 目前正常了，更新规则后，反复切换模式也不会恢复成日间模式了，我过段时间再测试一下，目前我使用的B站版本是6.19.0，QX版本是1.0.19

看来是对皮肤的处理会引发一些异常，这个功能暂时不上了。
