### ISSUE TITLE
ChinaIPs.list里应该去掉no-resolve

### ISSUE THREAD

**Issue by ftnice** [blackmatrix7/ios_rule_script#23]
当一个使用域名的请求遇到IP-CIDR规则时，Surge需要进行DNS查询才能确定是否应该执行规则。如果启用该选项将会使域名请求跳过该规则。

**Comment by blackmatrix7** [comment]
因为数据源本身有，去掉需要改下程序，稍晚些实现。

**Comment by fiiir** [comment]
> 因为数据源本身有，去掉需要改下程序，稍晚些实现。

不需要去掉no-resolve 

在Chinaip.list规则前面，添加下面这条规则触发一次dns查询（相当从这一步开始，把域名规则变成ip规则），执行到Chinaip.list的时候就不会跳过了
IP-CIDR,0.0.0.0/32,REJECT

个人还是倾向于保留no-resolve，因为这样放在配置文件任何一行都不会触发dns查询，配置文件写起来比较灵活，需要dns查询的地方加上那条规则就行了

**Comment by blackmatrix7** [comment]
分流规则默认带有no-resolve，如果不需要，请使用ChinaIPs_Resolve.list。
各取所需吧。

**Comment by ftnice** [comment]
感谢
2020年10月17日 +0800 PM10:47 blackmatrix7 <notifications@github.com>，写道：

**Comment by Wrandz** [comment]
@fiiir 我发现只要触发一次dns解析，后面的no-resolve参数都失效了，感觉no-resolve没起到该有的作用。
