### ISSUE TITLE
美团买菜在手机端运行长时间活跃的问题

### ISSUE THREAD

**Issue by ArthurKwok0320** [blackmatrix7/ios_rule_script#235]
客户端qx 运行一直活跃

**Comment by blackmatrix7** [comment]
无法复现此问题，请提供下客户端版本和脚本执行日志。

**Comment by ArthurKwok0320** [comment]
客户端版本是商店最新版1.0.19-build501，每天第一次运行会长时间active。日志
State:  Released
Request: 1
Description:   
➤ 美团买菜
➤ https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/meituan/maicai_checkin.js
Logs:    
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_unified_push_url](object)
null
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_unified_push_url](object)
null
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_cookie](string)
"_lxsdk_s=1773dc13afe-68e-ebf-98e%7C%7C15; _lx_utm=utm_term%3D5.14.10%26utm_medium%3Diphone%26utm_content%3D00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020%26utm_source%3DAppStore%26utm_campaign%3DAimaicai_cBimaicai_cD200H0; _utm_campaign=Aimaicai_cBimaicai_cD200H0; _utm_content=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020; _utm_medium=iphone; _utm_source=AppStore; _utm_term=5.14.10; cityid=2; dpid=; latlng=36.66631%2C116.98530%2C1611648818084; network=wifi; token=M9umCqUOtDt-ROftteuE0TMWC3gAAAAAiQwAALEEIyHIcK07vIaFGz24RjvZ0NZs55FVcpKVld6SC8sIey5MqFfKM_g7e8Ko_jZnZg; uuid=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020; logan_session_token=m1ld72hri0tvsfhk8lyr; _lxsdk=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020; _lxsdk_cuid=1773dc13afbb8-0ae461689ebe688-3f50252d-4a574-1773dc13afc5c; _lxsdk_unoinid=9a03c0a17aa04f298021a58aa0508499a161168500385756020; latlon=36.66631%2C116.98530%2C1611648808039"
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_t](string)
"M9umCqUOtDt-ROftteuE0TMWC3gAAAAAiQwAALEEIyHIcK07vIaFGz24RjvZ0NZs55FVcpKVld6SC8sIey5MqFfKM_g7e8Ko_jZnZg"
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_querystring](string)
"app_tag=union&bizId=2&channel=1&poi=292&poiId=292&stockPois=292&tenantId=1&userId=123403585&utm_medium=iphone&utm_term=5.14.10&uuid=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020"
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_userid](number)
123403585
❚ [DEBUG] [美团买菜]
READ DATA [meituan_mall_uuid](string)
"00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020"
❚ [DEBUG] [美团买菜]
HTTP POST: {"url":"https://mall.meituan.com/api/c/mallcoin/checkIn/userCheckInNew?app_tag=union&bizId=2&channel=1&poi=292&poiId=292&stockPois=292&tenantId=1&userId=123403585&utm_medium=iphone&utm_term=5.14.10&uuid=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020","headers":{"Accept":"*/*","Accept-Encoding":"gzip, deflate, br","Accept-Language":"zh-cn","Connection":"keep-alive","Content-Type":"application/json","Cookie":"_lxsdk_s=1773dc13afe-68e-ebf-98e%7C%7C15; _lx_utm=utm_term%3D5.14.10%26utm_medium%3Diphone%26utm_content%3D00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020%26utm_source%3DAppStore%26utm_campaign%3DAimaicai_cBimaicai_cD200H0; _utm_campaign=Aimaicai_cBimaicai_cD200H0; _utm_content=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020; _utm_medium=iphone; _utm_source=AppStore; _utm_term=5.14.10; cityid=2; dpid=; latlng=36.66631%2C116.98530%2C1611648818084; network=wifi; token=M9umCqUOtDt-ROftteuE0TMWC3gAAAAAiQwAALEEIyHIcK07vIaFGz24RjvZ0NZs55FVcpKVld6SC8sIey5MqFfKM_g7e8Ko_jZnZg; uuid=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020; logan_session_token=m1ld72hri0tvsfhk8lyr; _lxsdk=00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020; _lxsdk_cuid=1773dc13afbb8-0ae461689ebe688-3f50252d-4a574-1773dc13afc5c; _lxsdk_unoinid=9a03c0a17aa04f298021a58aa0508499a161168500385756020; latlon=36.66631%2C116.98530%2C1611648808039","Host":"mall.meituan.com","Origin":"https://mall.meituan.com","User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/6.5.7 miniprogram MMP/1.10.0.9.8","t":"M9umCqUOtDt-ROftteuE0TMWC3gAAAAAiQwAALEEIyHIcK07vIaFGz24RjvZ0NZs55FVcpKVld6SC8sIey5MqFfKM_g7e8Ko_jZnZg"},"body":"{\"userId\":123403585,\"riskMap\":{\"platform\":13,\"app\":95,\"utm_term\":\"5.12.3\",\"uuid\":\"00000000000009A03C0A17AA04F298021A58AA0508499A161168500385756020\",\"utm_medium\":\"tuanApp\",\"fingerprint\":\"\"}}","opts":{"hints":false},"method":"POST"}
❚ [DEBUG] [美团买菜]
美团买菜签到响应结果：{"code":0,"data":{"result":true,"rewardValue":"0.50","checkinCard":{"text":"好好休息，好好吃饭，平平安安。","picUrl":"https://p1.meituan.net/mallimages/62dc829fc19dcae442ccbfeda5111744438096.jpg","week":"周二","timestamp":1615221000737,"type":1}}}
❚ [NOTIFY] [美团买菜]
title:美团买菜
subTitle:周二签到成功，获得买菜钱0.50元。
body:好好休息，好好吃饭，平平安安。
options:{"open-url":""}
