### ISSUE TITLE
hbomax新域名,不加入无法播放影院同步的那些电影

### ISSUE THREAD

**Issue by ShadowsSide** [blackmatrix7/ios_rule_script#236]
cmaf.cf.us.hbomaxcdn.com
cmaf.lv3.us.hbomaxcdn.com

**Comment by ShadowsSide** [comment]
![image](https://user-images.githubusercontent.com/61958350/110232542-33095a80-7f59-11eb-90b2-beb88c7241ab.png)
hui
会报类似这样的错误.

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入。
