### ISSUE TITLE
广告list源的建议

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#24]
这位大佬爬取了Adguard 的规则，都是DOMAIN-SET格式，有意向整合进广告list吗？
https://github.com/geekdada/surge-list/tree/master/domain-set

**Comment by blackmatrix7** [comment]
只是担心加入的越多，误拦截的也会越多，考虑加个测试版的去广告规则，把所有的都往里加……

**Comment by blackmatrix7** [comment]
增加了AdvertisingTest，你可以试试。

**Comment by fiiir** [comment]
> 增加了AdvertisingTest，你可以试试。

来了来了，小白鼠来了🐁
