### ISSUE TITLE
china.list完善

### ISSUE THREAD

**Issue by bigchalizi** [blackmatrix7/ios_rule_script#242]
大佬您好，由于china.list里的speedtest.net的分流规则相较于speetest.list中的speedtest更为明确。即使speedtest分流规则放在chinalist的上面，打开speedtest依旧命中chinalist的规则，故建议将chinalist中的speedtest.net这条删去。

**Comment by blackmatrix7** [comment]
已加入到过滤器中，最迟明天凌晨会统一更新，如果今天累积的调整多，可能会临时手动更新。
