### ISSUE TITLE
b站动态里面的推荐广告

### ISSUE THREAD

**Issue by violesea** [blackmatrix7/ios_rule_script#247]
昨天晚上开始有的，不知道是我没设置好的问题还是b站新出的。![image](https://user-images.githubusercontent.com/43993281/110704351-cf6c7f00-822f-11eb-8f59-08d8e78e023e.png)

https://i0.hdslb.com/bfs/sycp/creative_img/202103/d8b1e5a40c9a92e7a04085060e33532b.jpg@780w_440h_1e_1c.webp 这是我抓到的图片地址

**Comment by blackmatrix7** [comment]
已修复
