### ISSUE TITLE
百度搜索建议被拦截，且主页收藏项目无法正常显示

### ISSUE THREAD

**Issue by mwhds97** [blackmatrix7/ios_rule_script#249]
![image](https://user-images.githubusercontent.com/32876945/110924146-aa295f00-835c-11eb-8aa2-83676c92d527.png)
![image](https://user-images.githubusercontent.com/32876945/110924212-bd3c2f00-835c-11eb-8277-8695eb727bb3.png)

**Comment by blackmatrix7** [comment]
你这个是PC上的浏览器吗？

**Comment by mwhds97** [comment]
> 你这个是PC上的浏览器吗？

是的， Chrome 84.0.4147.135

**Comment by blackmatrix7** [comment]
> > 你这个是PC上的浏览器吗？
> 
> 
> 
> 是的， Chrome 84.0.4147.135

F12 开发者模式看下网络请求的执行情况

**Comment by mwhds97** [comment]
> > > 你这个是PC上的浏览器吗？
> > 
> > 
> > 是的， Chrome 84.0.4147.135
> 
> F12 开发者模式看下网络请求的执行情况

![image](https://user-images.githubusercontent.com/32876945/110927624-d8a93900-8360-11eb-9980-871643f73c08.png)

**Comment by mwhds97** [comment]
失败的请求地址都是 dss0.bdstatic.com

**Comment by blackmatrix7** [comment]
已经把dss0.bdstatic.com加入到过滤器，等待明天凌晨统一更新。
