### ISSUE TITLE
圈x去广告复写，腾讯视频部分广告消除不了，爱奇艺有部分出现版权限制

### ISSUE THREAD

**Issue by shawn121212** [blackmatrix7/ios_rule_script#25]
请大师检查检查

**Comment by blackmatrix7** [comment]
我本身不是去广告规则的维护者，这个项目只是对现有去广告规则做整合去重。如果数据源的去广告规则去不了的广告，这个项目中的去广告规则也无能为力。
爱奇艺出现版权限制一般是分流规则配置错误导致，通常和去广告无关。
