### ISSUE TITLE
关于知乎助手在 Quantumult X 失效初步排查

### ISSUE THREAD

**Issue by chouchoui** [blackmatrix7/ios_rule_script#253]
相关Issues
#129 
#110 

知乎助手 Quantumult X 段落使用说明需要调整
https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu#quantumult-x

编辑配置，必须将`ip-cidr,118.89.204.198/32,reject`添加至`[filter_local]`模块内`geoip, cn, direct`的上方
```ini
[filter_local]
...以上略
ip-cidr,118.89.204.198/32,reject
geoip, cn, direct
...以下略
```

其他条目在`[filter_local]`顺序随意
```
host,118.89.204.198,reject
host,appcloud2.in.zhihu.com,reject
host,mqtt.zhihu.com,reject
host,sugar.zhihu.com,reject
user-agent,AVOS*,reject
ip6-cidr,2402:4e00:1200:ed00:0:9089:6dac:96b6/128,reject
```
或直接订阅分流
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ZhihuAds/ZhihuAds.list

**Comment by blackmatrix7** [comment]
谢谢反馈，已经更新README。
