### ISSUE TITLE
知乎助手“精简顶部标签页”如何判断是否生效？

### ISSUE THREAD

**Issue by LuzMasonj** [blackmatrix7/ios_rule_script#254]
知乎助手的“精简顶部标签页”没有提供效果图，不确定自己的是否生效。
我在用的知乎版本为6.67.0,相关域名已经放行。翻看以前的issue得知视频标签在6.62.0时就内置了，可是我现在用的版本还是多了一个圈子，如下图所示，还请作者帮忙看一下。
![A95E4B72-2EA1-4C45-92F9-FBF6914C9CF4](https://user-images.githubusercontent.com/27768847/111089793-59865180-8568-11eb-9767-bf68ca390209.png)

**Comment by blackmatrix7** [comment]
你把复写去掉看看是否有变化，可能需要多重启几次APP才会生效。

**Comment by LuzMasonj** [comment]
> 你把复写去掉看看是否有变化，可能需要多重启几次APP才会生效。

我是抓包下载6.67.0 现在评论区的推荐跟广告又出来了 还会提示失败 如图所示
![F91C61CA-D46A-4E82-85C2-FCDCA7F3811B](https://user-images.githubusercontent.com/27768847/111279439-aad03700-8675-11eb-8316-4830af8bfd07.png)
![182C4749-4B82-4990-9AE6-311BA6733097](https://user-images.githubusercontent.com/27768847/111279090-48773680-8675-11eb-9faa-54315fa3e419.png)
![D2A633BD-FE8D-42C6-A0AE-4F8B517AA9E4](https://user-images.githubusercontent.com/27768847/111279122-4f9e4480-8675-11eb-8ce3-63d22e55ad1c.png)
![A2147401-53EC-4DE5-AE89-14CCF7D6E8A6](https://user-images.githubusercontent.com/27768847/111279297-84aa9700-8675-11eb-94bf-4a069f52d4f4.png)

**Comment by LuzMasonj** [comment]
`^https?:\/\/www\.zhihu\.com url request-header (\r\n)User-Agent: Mozilla.+iPhone.+(\r\n) request-header $1User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 SearchCraft/2.6.3 (Baidu; P1 8.0.0)$2 `
1.目前经过排查 推荐 广告失效是由如上规则导致 请问如何处理以解决冲突？
2.通过排查规则 仍然无法找到提示加载失败的原因。

**Comment by blackmatrix7** [comment]
^https?:\/\/www\.zhihu\.com 这个正则匹配范围太大，很有可能会覆盖其他的复写导致去广告失效，建议吧这条复写的位置往后放试试。

QuanX加载失败属于已知问题，只会在QuanX出现，暂时不知道什么原因，无法解决。

**Comment by LuzMasonj** [comment]
> ^https?://www.zhihu.com 这个正则匹配范围太大，很有可能会覆盖其他的复写导致去广告失效，建议吧这条复写的位置往后放试试。
> 
> QuanX加载失败属于已知问题，只会在QuanX出现，暂时不知道什么原因，无法解决。

已屏蔽上述规则

**Comment by LuzMasonj** [comment]
> ^https?://www.zhihu.com 这个正则匹配范围太大，很有可能会覆盖其他的复写导致去广告失效，建议吧这条复写的位置往后放试试。
> 
> QuanX加载失败属于已知问题，只会在QuanX出现，暂时不知道什么原因，无法解决。

加载失败的问题 我对复写规则用排除法测试 最后发现 哪怕不用知乎助手复写规则也会出现加载失败的问题 而且用流量不会加载失败 用wifi就会出现

**Comment by blackmatrix7** [comment]
谢谢，很详细的测试。的确是只在Wifi下出现，原因不明。

可以试试把 ip-cidr,118.89.204.198/32,reject 这条规则注释掉看看在Wifi下还会不会加载失败。

**Comment by LuzMasonj** [comment]
> 谢谢，很详细的测试。的确是只在Wifi下出现，原因不明。
> 
> 可以试试把 ip-cidr,118.89.204.198/32,reject 这条规则注释掉看看在Wifi下还会不会加载失败。

现在肯定是分流规则的问题 我挨个测试一下

**Comment by blackmatrix7** [comment]
> > 谢谢，很详细的测试。的确是只在Wifi下出现，原因不明。
> > 可以试试把 ip-cidr,118.89.204.198/32,reject 这条规则注释掉看看在Wifi下还会不会加载失败。
> 
> 现在肯定是分流规则的问题 我挨个测试一下

期待你的测试结果
