### ISSUE TITLE
关于ChinaIPs规则

### ISSUE THREAD

**Issue by ameyukisora** [blackmatrix7/ios_rule_script#255]
简而言之：部分dns会将部分网址污染到国内云服务商的国外地址上，
<details>
  <summary>折叠的内容</summary>
今早查日志发现部分国内dns会将pbs.twimg.com（twitter上的图片）解析成47.88.58.234的美国阿里云ip，据我所知twitter并没有在阿里云上架服务器，测试一下也确实无法连接，这会导致一个问题：

如果规则是ChinaIPs走DIRECT，Match(或Final)走远程服务器，47.88.58.234会走DIRECT而无法连接，原因是ChinaIPs规则里将国内云服务商的国外ip也包含进来了，但其中部分ip已经被用于dns污染，之前也有部分网站被不正确地解析到香港华为云ip段上，
</details>

建议将ChinaIPs规则来源的
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
剔除或者加以说明。

**Comment by blackmatrix7** [comment]
谢谢反馈。

已经从ChinaIPS去掉了，明天凌晨会进行更新。

ChinaIPs暂时保留，由使用者自己解决。
