### ISSUE TITLE
大佬，allinone.conf里面规则会误屏蔽keep app里面社区的正常图片

### ISSUE THREAD

**Issue by WoodyLin** [blackmatrix7/ios_rule_script#256]
RT…我在这个配置里把两条关于keep的reject都注释也不行，只有取消allinone才能显示，麻烦大佬看下，谢谢…

![A5AE0E2A-4F01-453F-ABE2-0E4D8F57F0A7](https://user-images.githubusercontent.com/1460489/111301935-bcbdd400-868d-11eb-8130-648d1889793d.png)

**Comment by blackmatrix7** [comment]
谢谢反馈，已经加到过滤器中，等待明天凌晨的统一更新。
