### ISSUE TITLE
使用bilibili去广告模块后APP无法访问网络

### ISSUE THREAD

**Issue by honeyjuice** [blackmatrix7/ios_rule_script#258]
为了避免分流规则对模块的影响，禁用了所有分流，禁用所有其他插件
bilibili版本为6.20.0
Loon版本为2.1.8
使用模块https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/bilibili/bilibili_plus.lnplugin
已经尝试过的操作，重启Loon，重启手机，删除重装B站
只要打开了bilibili_plus.lnplugin这个插件，bilibili立马无法访问网络，关闭此插件后恢复正常

![IMG_1519](https://user-images.githubusercontent.com/32090001/111420034-7451f500-8725-11eb-9c26-2cceec105dea.PNG)
![IMG_1518](https://user-images.githubusercontent.com/32090001/111420040-774ce580-8725-11eb-8202-1306e36119e9.PNG)
![IMG_1517](https://user-images.githubusercontent.com/32090001/111420044-79af3f80-8725-11eb-8b6a-72947724fca4.PNG)
![IMG_1516](https://user-images.githubusercontent.com/32090001/111420065-80d64d80-8725-11eb-87d0-d4a2ea5e2c69.PNG)
![IMG_1515](https://user-images.githubusercontent.com/32090001/111420074-86339800-8725-11eb-81b7-b02b113368aa.PNG)
![IMG_1520](https://user-images.githubusercontent.com/32090001/111421810-95681500-8728-11eb-81d3-4ef8a092705a.PNG)

**Comment by blackmatrix7** [comment]
我是6.19，配合最新的Loon TF 无法复现此问题。
不清楚6.20是否有什么改变导致，B站App我不太好升级，因为升级就没办法抓包降级了。

你可以抓包试试哪些网络请求被拦截，也可以提供一份配置文件，我试试。

不过我只能在6.19下面测试。

**Comment by blackmatrix7** [comment]
你可以尝试一下，把B站去广告的插件禁用掉，然后在MITM中手动加入如下主机名：app.bilibili.com,api.bilibili.com,api.live.bilibili.com,api.vc.bilibili.com

看看是否有网络请求异常，如果依旧是请求异常，那很有可能已经使用SSL Pinning，就比较麻烦了。

**Comment by honeyjuice** [comment]
我改了下插件只剩下mitm的部分
https://raw.githubusercontent.com/honeyjuice/Clash_Loon_Configs/main/bilibili_plus.lnplugin
和之前一样，禁用所有乱七八糟的规则和插件，访问正常
启用这个只剩下mitm的插件，B站报错

```
2021年3月17日 星期三 中国标准时间 17:54:42
Model:iPhone 11 iOS14.4
APP版本:6.20.0(62000200)
是否联网:YES
网络权限:正常
网络类型:无线局域网
长连接状态:正常

本地DNS:127.0.0.1
www.bilibili.com:443
ip:240.1.0.3    connect:1ms    ping:1ms
interface.bilibili.com:443
ip:240.1.0.22    connect:1ms    ping:1ms
api.bilibili.com:443
ip:240.1.0.23    connect:1ms    ping:1ms
passport.bilibili.com:443
ip:240.1.0.24    connect:2ms    ping:1ms
account.bilibili.com:443
ip:240.1.0.25    connect:1ms    ping:1ms
bangumi.bilibili.com:443
ip:240.1.0.26    connect:1ms    ping:1ms
live.bilibili.com:443
ip:240.1.0.27    connect:1ms    ping:1ms
message.bilibili.com:443
ip:240.1.0.28    connect:1ms    ping:1ms
elec.bilibili.com:443
ip:240.1.0.29    connect:1ms    ping:1ms
pay.bilibili.com:443
ip:240.1.0.30    connect:1ms    ping:1ms
secure.bilibili.com:443
ip:240.1.0.31    connect:1ms    ping:1ms
s1.hdslb.com:443
ip:240.1.0.32    connect:1ms    ping:1ms
s.search.bilibili.com:443
ip:240.1.0.33    connect:1ms    ping:1ms
api.biligame.com:443
ip:240.1.0.34    connect:1ms    ping:1ms
grpc.biliapi.net:443
ip:240.1.0.35    connect:1ms    ping:1ms
apigame.bilibili.com:443
ip:240.1.0.36    connect:1ms    ping:1ms
acg.tv:443
ip:240.1.0.37    connect:1ms    ping:1ms
static.hdslb.com:443
ip:240.1.0.38    connect:1ms    ping:1ms
i1.hdslb.com:443
ip:240.1.0.39    connect:1ms    ping:1ms
i2.hdslb.com:443
ip:240.1.0.40    connect:1ms    ping:1ms
app.bilibili.com:443
ip:240.1.0.41    connect:1ms    ping:1ms
i0.hdslb.com:443
ip:240.1.0.42    connect:1ms    ping:1ms
member.bilibili.com:443
ip:240.1.0.43    connect:1ms    ping:1ms
URL:https://app.bilibili.com/x/v2/param
->失败:Error Domain=BFCApiCronetErrorDomain Code=11 "网络错误，请稍后再试" UserInfo={NSLocalizedFailureReason=net::ERR_CERT_COMMON_NAME_INVALID, NSLocalizedDescription=网络错误，请稍后再试}
URL:https://app.biliapi.net/x/v2/feed/index
->成功
Moss:bilibili.app.interface.v1.Search/Suggest3
->成功
http://www.qq.com 408.71 KB/s
http://www.baidu.com 33.00 KB/s
http://cn.aliyun.com 217.33 KB/s
```


![IMG_1524](https://user-images.githubusercontent.com/32090001/111449371-4cc15380-874a-11eb-9a18-9b6c2ce5bd95.PNG)
![IMG_1523](https://user-images.githubusercontent.com/32090001/111449341-43d08200-874a-11eb-9d4e-09f03a347445.PNG)

**Comment by blackmatrix7** [comment]
如果仅有MITM都会导致网络异常，那一般来说只有两种可能：Loon本身有某些Bug，另外一种就是6.20版本的B站使用了SSL Pinning。

前一种可以换一个客户端，如QuanX、Surge验证一下。如果是后一种可能，那后续版本的去广告将全部失效。

**Comment by ashurinn** [comment]
bilibili版本6.20.5，Surge无此问题

**Comment by blackmatrix7** [comment]
> bilibili版本6.20.5，Surge无此问题

谢谢反馈。

刚刚仔细看了下错误信息，ERR_CERT_COMMON_NAME_INVALID，应该和证书有关，建议检查下Loon的证书是否正常被信任，有没有过期。

**Comment by honeyjuice** [comment]
> > bilibili版本6.20.5，Surge无此问题
> 
> 谢谢反馈。
> 
> 刚刚仔细看了下错误信息，ERR_CERT_COMMON_NAME_INVALID，应该和证书有关，建议检查下Loon的证书是否正常被信任，有没有过期。

这个之前也怀疑过了 删除并重装过证书，问题还是如此
另外我刚换了quanx 载入bilibili_plus.qxrewrite后正常使用中 唯独loon有这个问题
![IMG_1526](https://user-images.githubusercontent.com/32090001/111452965-03730300-874e-11eb-9897-cc061a9ba58a.PNG)

**Comment by blackmatrix7** [comment]
> > > bilibili版本6.20.5，Surge无此问题
> 
> > 
> 
> > 谢谢反馈。
> 
> > 
> 
> > 刚刚仔细看了下错误信息，ERR_CERT_COMMON_NAME_INVALID，应该和证书有关，建议检查下Loon的证书是否正常被信任，有没有过期。
> 
> 
> 
> 这个之前也怀疑过了 删除并重装过证书，问题还是如此
> 
> 另外我刚换了quanx 载入bilibili_plus.qxrewrite后正常使用中 唯独loon有这个问题
> 
> ![IMG_1526](https://user-images.githubusercontent.com/32090001/111452965-03730300-874e-11eb-9897-cc061a9ba58a.PNG)
> 
> 

如果证书也没问题并且正常信任，仅仅MITM就会导致出现网络异常，建议反馈给Loon作者排查下。

**Comment by honeyjuice** [comment]
> > > > bilibili版本6.20.5，Surge无此问题
> > 
> > 
> > > 
> > 
> > 
> > > 谢谢反馈。
> > 
> > 
> > > 
> > 
> > 
> > > 刚刚仔细看了下错误信息，ERR_CERT_COMMON_NAME_INVALID，应该和证书有关，建议检查下Loon的证书是否正常被信任，有没有过期。
> > 
> > 
> > 这个之前也怀疑过了 删除并重装过证书，问题还是如此
> > 另外我刚换了quanx 载入bilibili_plus.qxrewrite后正常使用中 唯独loon有这个问题
> > ![IMG_1526](https://user-images.githubusercontent.com/32090001/111452965-03730300-874e-11eb-9897-cc061a9ba58a.PNG)
> 
> 如果证书也没问题并且正常信任，仅仅MITM就会导致出现网络异常，建议反馈给Loon作者排查下。

Quanx测试正常  Loon等更新吧 最近不太稳 可以close了
