### ISSUE TITLE
建议加入PrivateTracker规则

### ISSUE THREAD

**Issue by honeyjuice** [blackmatrix7/ios_rule_script#260]
这样访问PT站点时可以直接设定为direct防止走代理，触发机场的禁止BT规则

规则源：
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/PrivateTracker.list

**Comment by blackmatrix7** [comment]
谢谢提供，晚上会把它加进去。

**Comment by blackmatrix7** [comment]
已经加入。
