### ISSUE TITLE
QX Apple.list 走分流会导致 Apple 官网商店 403 Forbidden

### ISSUE THREAD

**Issue by mintyfrankie** [blackmatrix7/ios_rule_script#261]
在 QuantumultX 中若 Apple.list 走 PROXY 则会导致网页版 apple.com 商店/购买页面返回 403 Forbidden，商品介绍页则可以正常访问。若走 DIRECT 则无此问题；此问题在我这里**所有地区的 apple.com、所有设备、所有网络环境**均可复现。

麻烦 blackmatrix 检查一下是哪条规则导致的这个问题，谢谢！

**Comment by blackmatrix7** [comment]
403表示服务器拒绝处理你的请求，建议你排查下节点是否正常。

分流规则只是一份域名和IP列表集合，是一个纯文本文件，无任何功能，更不会引起403。
