### ISSUE TITLE
联通脚本可以增加每日 1G 免费流量获取

### ISSUE THREAD

**Issue by gee1k** [blackmatrix7/ios_rule_script#262]
联通脚本可以增加每日 1G 免费流量获取

其他库：
https://github.com/lmh77/A/tree/main/10010

https://github.com/srcrs/UnicomTask

**Comment by blackmatrix7** [comment]
联通的脚本有点老，近期打算做一个彻底的重写，到时候会加入。

**Comment by gee1k** [comment]
好的

**Comment by blackmatrix7** [comment]
功能已经完成，等测试几条没问题就会更新上来。

**Comment by gee1k** [comment]
好的好的

**Comment by longxiangjie** [comment]
大佬，新脚本出来了吗

**Comment by blackmatrix7** [comment]
已经更新了，测试阶段，如果有问题请反馈。

**Comment by blackmatrix7** [comment]
暂时存在一些问题，翻倍不一定会成功，需要再看下什么问题，要晚点上线了。

**Comment by blackmatrix7** [comment]
![10010](https://user-images.githubusercontent.com/27717518/112427860-3f711e00-8d75-11eb-9dd3-ca6e8b2eed78.jpg)

联通的接口稳定性实在太差，昨天还正常的功能，今天又有变化，而且经常会调用失败。

甚至最新版的客户端自己都没办法完成任务。

估计得比较长时间的反复测试和观察才能上线了。

**Comment by longxiangjie** [comment]
那大佬做出来了说一下😘

**Comment by longxiangjie** [comment]
大佬，运行脚本，显示提交任务出错，前方网络拥堵怎么解决啊

**Comment by longxiangjie** [comment]
在线等

**Comment by blackmatrix7** [comment]
联通不太好处理，昨天刚刚获取的Cookie，今天早上又过期了……

如果Cookie的有效期后续都这么短的话，就比较棘手，近期可能不会有联通脚本的更新了。

我得自己弄稳定了再更新上来。先看看明天Cookie是否会再过期吧。

**Comment by WoodyLin** [comment]
> 更新了新版，但是每日领取1G流量的任务已经下线，翻倍没办法成功已经注释掉了，现在我的账户领取美团外卖优惠券也无法成功，不清楚是账户原因还是活动接口本身出问题。
> 
> 如果有能正常领取美团外卖优惠券的麻烦给个反馈。

正常，可以抽奖大概5兆流量还有一张减三块的美团券

**Comment by blackmatrix7** [comment]
1G的活动已经下线，为了调试接口，可能调用太频繁导致我自己的账号已黑，已经领取不到美团外卖优惠券。

心塞，暂时不想再维护联通的脚本了。

**Comment by chouchoui** [comment]
> 更新了新版，但是每日领取1G流量的任务已经下线，翻倍没办法成功已经注释掉了，现在我的账户领取美团外卖优惠券也无法成功，不清楚是账户原因还是活动接口本身出问题。
> 
> 
> 
> 如果有能正常领取美团外卖优惠券的麻烦给个反馈。

![image](https://user-images.githubusercontent.com/14866249/113231155-2fa18e80-92cd-11eb-958b-ee30bb73d79e.jpeg)

目前来看每天都还能领到
其实也有点顾虑黑号，每天领了券不用，不知是否可以配合boxjs加一个美团优惠券开关
