### ISSUE TITLE
知乎readme写多了一个QX案例

### ISSUE THREAD

**Issue by EchoChan314** [blackmatrix7/ios_rule_script#263]
https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu#quantumult-x
https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu#quantumult-x-1 这个事错误的，
另外其它软件的案例有些也提了两次。

**Comment by blackmatrix7** [comment]
没有多写，因为一个是Lite，一个是Plus。

不过部分说明的确是比较陈旧，已经做了更新。
