### ISSUE TITLE
知乎广告推荐列表中的广告还是有

### ISSUE THREAD

**Issue by ghost** [blackmatrix7/ios_rule_script#264]
看上去和这个东西有关，
https://api.zhihu.com/feed-root/newbie30day?session_token=b43b30d988139gd8ba8298d476837ac3&page_number=3&limit=6&action=down&after_id=11&**ad_interval=4**&action_feed=true&reverse_order=0&scroll=down&tsp_ios_cardredesign=0&v_serial=0

ad_interval 的值是变的，好像=0时，啥也没有。
=4时， json里面就有广告信息，

![1764A34B-AC8C-4DDD-B6C7-B1ADFBFE6DB6](https://user-images.githubusercontent.com/80886532/111602610-7c399400-880e-11eb-8a25-5b885c270349.jpeg)

查了一遍rewrite和zhihu_plus.js, 好像并没有这个东西的处理。

这个是不是和推荐列表广告有关系？

**Comment by blackmatrix7** [comment]
谢谢反馈，看起来似乎是针对新用户的某些feed，可能我不是新用户的关系，没发现你的问题，具体还要再仔细看下。

**Comment by blackmatrix7** [comment]
我刷了几次都没看到响应体中含有广告，能否到处有一份含有广告的Response给我，我看下格式。

**Comment by blackmatrix7** [comment]
如果没有进一步的反馈，暂时先关闭掉，有问题你可以再回复。
