### ISSUE TITLE
QuantumultX用户知乎APP加载失败原因定位

### ISSUE THREAD

**Issue by LuzMasonj** [blackmatrix7/ios_rule_script#268]
我使用QuantumultX测试了一个多星期知乎助手规则，似乎定位到了原因。
在测试时发现，即使使用空白配置，只要MitM中存在www.zhihu.com，就有几率出现知乎APP加载失败问题。
解决方法就是在主机名中添加-www.zhihu.com，但这又会导致知乎助手中几个规则失效。
![F7A38905-493C-4040-AB6F-A098AFE3743A](https://user-images.githubusercontent.com/27768847/111864884-973b0e00-899e-11eb-9970-24ab61b6dcf9.png)

希望作者能让大家试一下是不是这个原因，最好能向QX作者反馈一下。

**Comment by blackmatrix7** [comment]
谢谢反馈，晚些时候我试下，你可以反馈给QuanX作者换取TF的资格。

另外，我之前遇到过比较类似的问题，你可以试试*.zhihu.com，然后把其他MITM全部去掉。

**Comment by LuzMasonj** [comment]
> 谢谢反馈，晚些时候我试下，你可以反馈给QuanX作者换取TF的资格。
> 
> 另外，我之前遇到过比较类似的问题，你可以试试*.zhihu.com，然后把其他MITM全部去掉。

我在开启知乎助手的情况下，仅仅在MITM中排除了www.zhihu.com，就再也没遇到过加载失败的问题。
相反，我在没有启用任何分流复写规则的情情下，仅仅在MITM中添加了www.zhihu.com，就出现了加载失败问题。
已向作者反馈，但感觉好玄学。

**Comment by blackmatrix7** [comment]
> > 谢谢反馈，晚些时候我试下，你可以反馈给QuanX作者换取TF的资格。
> > 另外，我之前遇到过比较类似的问题，你可以试试*.zhihu.com，然后把其他MITM全部去掉。
> 
> 我在开启知乎助手的情况下，仅仅在MITM中排除了www.zhihu.com，就再也没遇到过加载失败的问题。
> 相反，我在没有启用任何分流复写规则的情况下，仅仅在MITM中添加了www.zhihu.com，就出现了加载失败问题。
> 已向作者反馈，但感觉好玄学。

我将MITM规则做了一些调整，你可以试试是否有所改善。

**Comment by chouchoui** [comment]
一下午实测知乎没问题。

自用脚本加入api.ruguoapp.com同样会导致即刻app偶发出现网络异常，如法炮制改成*.ruguoapp.com之后也好了

不知道Surge和Quantumult X在MitM哪里处理方式不一样才出现的这个问题

**Comment by LuzMasonj** [comment]
> 一下午实测知乎没问题。
> 
> 自用脚本加入api.ruguoapp.com同样会导致即刻app偶发出现网络异常，如法炮制改成*.ruguoapp.com之后也好了
> 
> 不知道Surge和Quantumult X在MitM哪里处理方式不一样才出现的这个问题

即刻相关复写规则的MitM中，有www.ruguoapp.com这一项吗

**Comment by LuzMasonj** [comment]
> > > 谢谢反馈，晚些时候我试下，你可以反馈给QuanX作者换取TF的资格。
> > > 另外，我之前遇到过比较类似的问题，你可以试试*.zhihu.com，然后把其他MITM全部去掉。
> > 
> > 
> > 我在开启知乎助手的情况下，仅仅在MITM中排除了www.zhihu.com，就再也没遇到过加载失败的问题。
> > 相反，我在没有启用任何分流复写规则的情况下，仅仅在MITM中添加了www.zhihu.com，就出现了加载失败问题。
> > 已向作者反馈，但感觉好玄学。
> 
> 我将MITM规则做了一些调整，你可以试试是否有所改善。

建议删除知乎网页版去广告复写规则 这个当初也是我提的pr 现在这几条规则还有没有作用还不知道 很多余

**Comment by blackmatrix7** [comment]
> 一下午实测知乎没问题。
> 
> 自用脚本加入api.ruguoapp.com同样会导致即刻app偶发出现网络异常，如法炮制改成*.ruguoapp.com之后也好了
> 
> 不知道Surge和Quantumult X在MitM哪里处理方式不一样才出现的这个问题

之前在弄B站去广告的时候，有发现类似的问题，去广告在一段时间后效果会消失，只在QuanX上出现，后来尝试改为*.的方式后问题解决。

知乎这个确定是www.zhihu.com进行MITM导致的话，就试着改成了*.zhihu.com，没想到也可以解决。

推测QuanX在MITM上有某些Bug正好被触发了，不过具体还是不能确定。

**Comment by blackmatrix7** [comment]
> > > > 谢谢反馈，晚些时候我试下，你可以反馈给QuanX作者换取TF的资格。
> > > > 另外，我之前遇到过比较类似的问题，你可以试试*.zhihu.com，然后把其他MITM全部去掉。
> > > 
> > > 
> > > 我在开启知乎助手的情况下，仅仅在MITM中排除了www.zhihu.com，就再也没遇到过加载失败的问题。
> > > 相反，我在没有启用任何分流复写规则的情况下，仅仅在MITM中添加了www.zhihu.com，就出现了加载失败问题。
> > > 已向作者反馈，但感觉好玄学。
> > 
> > 
> > 我将MITM规则做了一些调整，你可以试试是否有所改善。
> 
> 建议删除知乎网页版去广告复写规则 这个当初也是我提的pr 现在这几条规则还有没有作用还不知道 很多余

我几乎不用网页版，也不太清楚这些规则有没有生效，如果不影响知乎APP的正常使用，就暂时保留着吧。

**Comment by LuzMasonj** [comment]
> > 一下午实测知乎没问题。
> > 自用脚本加入api.ruguoapp.com同样会导致即刻app偶发出现网络异常，如法炮制改成*.ruguoapp.com之后也好了
> > 不知道Surge和Quantumult X在MitM哪里处理方式不一样才出现的这个问题
> 
> 之前在弄B站去广告的时候，有发现类似的问题，去广告在一段时间后效果会消失，只在QuanX上出现，后来尝试改为*.的方式后问题解决。
> 
> 知乎这个确定是www.zhihu.com进行MITM导致的话，就试着改成了*.zhihu.com，没想到也可以解决。
> 
> 推测QuanX在MITM上有某些Bug正好被触发了，不过具体还是不能确定。

这个问题我给QX作者发邮件了 但是没回我 要是能给我个tf资格就好了

**Comment by blackmatrix7** [comment]
> > > 一下午实测知乎没问题。
> > > 自用脚本加入api.ruguoapp.com同样会导致即刻app偶发出现网络异常，如法炮制改成*.ruguoapp.com之后也好了
> > > 不知道Surge和Quantumult X在MitM哪里处理方式不一样才出现的这个问题
> > 
> > 
> > 之前在弄B站去广告的时候，有发现类似的问题，去广告在一段时间后效果会消失，只在QuanX上出现，后来尝试改为*.的方式后问题解决。
> > 知乎这个确定是www.zhihu.com进行MITM导致的话，就试着改成了*.zhihu.com，没想到也可以解决。
> > 推测QuanX在MITM上有某些Bug正好被触发了，不过具体还是不能确定。
> 
> 这个问题我给QX作者发邮件了 但是没回我 要是能给我个tf资格就好了

这个只能再等等了，或者有人已经提前反馈了，毕竟issues是公开的……

**Comment by Paris0-0** [comment]
订阅更新了，并且把域名加入了simple_cert_hostname生成本地证书，前两天没出现今天又开始了，

**Comment by LuzMasonj** [comment]
> 订阅更新了，并且把域名加入了simple_cert_hostname生成本地证书，前两天没出现今天又开始了，

试试在MitM中添加-www.zhihu.com 我这边试着排除了这个域名就没问题了

**Comment by LuzMasonj** [comment]
好像*.zhihu.com并不能解决 还是得排除了www.zhihu.com后解决的

**Comment by blackmatrix7** [comment]
> 好像*.zhihu.com并不能解决 还是得排除了www.zhihu.com后解决的

如果还是不能解决只能等QuanX作者更新了。

**Comment by ljfzx** [comment]
新版知乎更新，所有的去广告都失效了

**Comment by LuzMasonj** [comment]
> 新版知乎更新，所有的去广告都失效了

旧版app还行吗

**Comment by ljfzx** [comment]
> > 新版知乎更新，所有的去广告都失效了
> 
> 旧版app还行吗

从头说一遍吧，一周前quanx 商店版本更新了，解决了知乎MITM的BUG，不会再有加载失败，知乎两天前更新了新版本，那个时候，去广告还有效。但是今天发现所有的都失效了。不知道是版本的更新原因还是服务器部署的原因

**Comment by LuzMasonj** [comment]
> > > 新版知乎更新，所有的去广告都失效了
> > 
> > 
> > 旧版app还行吗
> 
> 从头说一遍吧，一周前quanx 商店版本更新了，解决了知乎MITM的BUG，不会再有加载失败，知乎两天前更新了新版本，那个时候，去广告还有效。但是今天发现所有的都失效了。不知道是版本的更新原因还是服务器部署的原因

MITM问题解决了？qx作者都没回我 还想着能给我个tf资格呢。

**Comment by Paris0-0** [comment]
目前使用的7.70依然有效

**Comment by ljfzx** [comment]
删除APP，降级到7.70，任然有广告，不知道哪里出错了

**Comment by blackmatrix7** [comment]
> 删除APP，降级到7.70，任然有广告，不知道哪里出错了

建议使用空白配置文件自行排查下

**Comment by LuzMasonj** [comment]
> 删除APP，降级到7.70，任然有广告，不知道哪里出错了

有可能是知乎ua重定向的问题

**Comment by blackmatrix7** [comment]
> > 删除APP，降级到7.70，任然有广告，不知道哪里出错了
> 
> 有可能是知乎ua重定向的问题

可能性很大，UA的正则匹配范围太大，很容易把脚本的复写覆盖掉。
