### ISSUE TITLE
b站动态圈广告

### ISSUE THREAD

**Issue by violesea** [blackmatrix7/ios_rule_script#269]
我之前反馈过一次，好了几天，好像是前天开始又有了

**Comment by blackmatrix7** [comment]
之前是有个动态历史的请求，未对其做处理，所以会出现广告，后面已经加上对它的复写操作，正常情况下不会再出现广告。

我这里没有发现这样的情况，你可以抓包提供下广告的链接、response。

**Comment by chouchoui** [comment]
<img width="458" alt="Snipaste_2021-03-22_22-48-46" src="https://user-images.githubusercontent.com/14866249/112008860-d6b15800-8b60-11eb-8a2e-f3027add5097.png">
动态广告估计可以放弃了，下拉刷新和翻页自动加载都是这个application/grpc

**Comment by violesea** [comment]
您参考

https://i0.hdslb.com/bfs/sycp/creative_img/202103/bb69390cface6f00d9af031e8899b6b5.jpg@780w_440h_1e_1c.webp

HTTP/1.1 200 OK 
Date: Tue, 23 Mar 2021 00:10:41 GMT
Content-Type: image/webp
Content-Length: 34700
Connection: keep-alive
Expires: Thu, 17 Mar 2022 12:06:09 GMT
Server: Tengine/2.1.1
Bili-Trace-Id: 2ecf8df4b46051d4
Cache-Control: max-age=31536000
ETag: adfd6e21af51ec09378fcfe2cd6d71e2157f3a77
Last-Modified: Tue, 16 Mar 2021 19:31:14 GMT
O-Height: 440
O-Width: 780
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn
Access-Control-Expose-Headers: Content-Length,X-Cache-Webcdn
X-Hash: /bfs/sycp/creative_img/202103/bb69390cface6f00d9af031e8899b6b5.jpg
Age: 1
X-Via: 1.1 anxian102:14 (Cdn Cache Server V2.0), 1.1 PS-SJW-01gQF20:16 (Cdn Cache Server V2.0)
X-Ws-Request-Id: 60593201_PS-SJW-01qO922_20365-63130
X-Cache-Webcdn: WS

**Comment by blackmatrix7** [comment]
> <img alt="Snipaste_2021-03-22_22-48-46" width="458" src="https://user-images.githubusercontent.com/14866249/112008860-d6b15800-8b60-11eb-8a2e-f3027add5097.png">
> 
> 动态广告估计可以放弃了，下拉刷新和翻页自动加载都是这个application/grpc

可能新版的修改了，最好的办法就是不要顺便升级，保持使用旧版直至功能不能满足需求。

**Comment by blackmatrix7** [comment]
> 您参考
> 
> https://i0.hdslb.com/bfs/sycp/creative_img/202103/bb69390cface6f00d9af031e8899b6b5.jpg@780w_440h_1e_1c.webp
> 
> HTTP/1.1 200 OK
> Date: Tue, 23 Mar 2021 00:10:41 GMT
> Content-Type: image/webp
> Content-Length: 34700
> Connection: keep-alive
> Expires: Thu, 17 Mar 2022 12:06:09 GMT
> Server: Tengine/2.1.1
> Bili-Trace-Id: 2ecf8df4b46051d4
> Cache-Control: max-age=31536000
> ETag: adfd6e21af51ec09378fcfe2cd6d71e2157f3a77
> Last-Modified: Tue, 16 Mar 2021 19:31:14 GMT
> O-Height: 440
> O-Width: 780
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: GET, POST, OPTIONS
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn
> Access-Control-Expose-Headers: Content-Length,X-Cache-Webcdn
> X-Hash: /bfs/sycp/creative_img/202103/bb69390cface6f00d9af031e8899b6b5.jpg
> Age: 1
> X-Via: 1.1 anxian102:14 (Cdn Cache Server V2.0), 1.1 PS-SJW-01gQF20:16 (Cdn Cache Server V2.0)
> X-Ws-Request-Id: 60593201_PS-SJW-01qO922_20365-63130
> X-Cache-Webcdn: WS

不是这样的Response，我需要的是动态这个接口返回的JSON文件。

**Comment by violesea** [comment]
> > 您参考
> 
> > 
> 
> > https://i0.hdslb.com/bfs/sycp/creative_img/202103/bb69390cface6f00d9af031e8899b6b5.jpg@780w_440h_1e_1c.webp
> 
> > 
> 
> > HTTP/1.1 200 OK
> 
> > Date: Tue, 23 Mar 2021 00:10:41 GMT
> 
> > Content-Type: image/webp
> 
> > Content-Length: 34700
> 
> > Connection: keep-alive
> 
> > Expires: Thu, 17 Mar 2022 12:06:09 GMT
> 
> > Server: Tengine/2.1.1
> 
> > Bili-Trace-Id: 2ecf8df4b46051d4
> 
> > Cache-Control: max-age=31536000
> 
> > ETag: adfd6e21af51ec09378fcfe2cd6d71e2157f3a77
> 
> > Last-Modified: Tue, 16 Mar 2021 19:31:14 GMT
> 
> > O-Height: 440
> 
> > O-Width: 780
> 
> > Access-Control-Allow-Origin: *
> 
> > Access-Control-Allow-Methods: GET, POST, OPTIONS
> 
> > Access-Control-Allow-Credentials: true
> 
> > Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn
> 
> > Access-Control-Expose-Headers: Content-Length,X-Cache-Webcdn
> 
> > X-Hash: /bfs/sycp/creative_img/202103/bb69390cface6f00d9af031e8899b6b5.jpg
> 
> > Age: 1
> 
> > X-Via: 1.1 anxian102:14 (Cdn Cache Server V2.0), 1.1 PS-SJW-01gQF20:16 (Cdn Cache Server V2.0)
> 
> > X-Ws-Request-Id: 60593201_PS-SJW-01qO922_20365-63130
> 
> > X-Cache-Webcdn: WS
> 
> 
> 
> 不是这样的Response，我需要的是动态这个接口返回的JSON文件。

不太懂… 怎么看？

**Comment by blackmatrix7** [comment]
> <img alt="Snipaste_2021-03-22_22-48-46" width="458" src="https://user-images.githubusercontent.com/14866249/112008860-d6b15800-8b60-11eb-8a2e-f3027add5097.png">
> 
> 动态广告估计可以放弃了，下拉刷新和翻页自动加载都是这个application/grpc

我这里也推送v2版本的接口了，看起来除了使用旧版本，动态的广告无法再去除，后面靠脚本能去除的广告会越来越少。
