### ISSUE TITLE
hijacking中原有的规则源失效

### ISSUE THREAD

**Issue by honeyjuice** [blackmatrix7/ios_rule_script#270]
在hijacking  https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Hijacking 规则中

调用的规则
https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Hijacking.list
因原作者更换路径已经失效

新的地址为
https://raw.githubusercontent.com/GoodHolidays/ConnersHua/master/Surge/Ruleset/Hijacking.list

**Comment by blackmatrix7** [comment]
谢谢反馈，链接失效对程序没什么影响，因为程序会缓存最后一次可以下载的内容到本地。

新的链接，我看提交记录也已经是17个月之前的，可能跟我缓存的内容差不多，所以就暂时不添加了。
