### ISSUE TITLE
分流规则修改建议

### ISSUE THREAD

**Issue by bigchalizi** [blackmatrix7/ios_rule_script#271]
将各代理工具的china分流中 - DOMAIN-SUFFIX,comicat.org 直接去掉或者去掉再加入Global中，此域名需要走代理才可访问

**Comment by blackmatrix7** [comment]
![Tracert](https://user-images.githubusercontent.com/27717518/111931138-88b33a80-8af5-11eb-99e1-5c6328035135.png)
看起来是可以直接访问的，你再确认一下。
我先关闭了，如果有问题你再反馈。

**Comment by bigchalizi** [comment]
我一直都有在用 确认需要走代理才可访问无误

**Comment by blackmatrix7** [comment]
暂时先去掉了，等待明天凌晨统一更新。
