### ISSUE TITLE
fa米家问题请教

### ISSUE THREAD

**Issue by vay1314** [blackmatrix7/ios_rule_script#272]
首先感谢您开发的脚本
我想自己做一个fa米家的小脚本
再参照您库中的脚本时一直报Invalid value "undefined" for header "deviceId"
请教是只抓取https://fmapp.chinafamilymart.com.cn/api/app/market/member/signin/usersign中的deviceId和token就可以吗？

**Comment by blackmatrix7** [comment]
不清楚你的源码是什么样子，从异常信息看，获取到deviceId的值为undefined，不符合HTTP协议，所以会报错。

 建议调试下代码看看是否正确获取到deviceId的值。

另外，如果是打算多账户签到的话，我之前测试过退出APP登录Cookie就会失效，不一定能实现多账户，不过你可以试试如飞行模式退出登录、飞行模式卸载APP等方式，但不保证能成功。

**Comment by blackmatrix7** [comment]
如果你是读取变量出现问题，可以参考一下：

https://github.com/blackmatrix7/ios_rule_script/issues/56

**Comment by vay1314** [comment]
> 如果你是读取变量出现问题，可以参考一下：
> 
> #56

十分感谢，就是变量读取的问题，使用了json后正常了
