### ISSUE TITLE
貌似网易云音乐规则抓取失败

### ISSUE THREAD

**Issue by ben-august** [blackmatrix7/ios_rule_script#274]
这个没同步上。https://raw.githubusercontent.com/o7y0/GeneralSubscribe/main/UnblockNeteaseMusic/NeteaseCloudMusic.list

**Comment by blackmatrix7** [comment]
HOST-SUFFIX,music.163.com,NeteaseMusic
可以包括以下内容
HOST-SUFFIX,interface.music.163.com,NeteaseMusic
HOST-SUFFIX,interface.music.163.com,NeteaseMusic
HOST-SUFFIX,interface1.music.163.com,NeteaseMusic
HOST-SUFFIX,interface2.music.163.com,NeteaseMusic
HOST-SUFFIX,interface3.music.163.com,NeteaseMusic
HOST-SUFFIX,interface4.music.163.com,NeteaseMusic
HOST-SUFFIX,interface5.music.163.com,NeteaseMusic
所以上面这些都会被合并掉。
同理，其他规则也是如此。

**Comment by ben-august** [comment]
好像是哦，辛苦大佬

**Comment by blackmatrix7** [comment]
不过我仔细看了下，觉得这个规则有些问题，例如DOMAIN-KEYWORD,netease，这个规则匹配范围太过于大，可能会把其他网易的服务也包括进来。

所以还是暂时把这个规则去掉了，不好意思。

**Comment by ben-august** [comment]
ok 那我用您的
