### ISSUE TITLE
clash 广告规则list只有300多条

### ISSUE THREAD

**Issue by ben-august** [blackmatrix7/ios_rule_script#276]
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising.yaml
这个文件只有300多条，和介绍的几万不对

**Comment by blackmatrix7** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml 

需要两者搭配使用
