### ISSUE TITLE
缺少一条规则

### ISSUE THREAD

**Issue by syvys** [blackmatrix7/ios_rule_script#279]
host, youtubei.googleapis.com, YouTube
缺少这条规则，这条规则包含在global使得我YouTube premium无法后台播放。（我global规则集所连节点无法后台播放，但我YouTube规则集所连节点理应可以后台播放、并且全局测试过。）
请查看下，感谢🙏

**Comment by blackmatrix7** [comment]
GlobalMedia的规则是
HOST,youtubei.googleapis.com,GlobalMedia

YouTube的规则是
HOST-SUFFIX,youtubei.googleapis.com,YouTube

QuanX的规则优先级，除了顺序之外，规则的类型也有优先级，HOST优先级高于HOST-SUFFIX，所以会出现GlobalMedia的规则优先级更高，而YouTube规则因为优先级低而不生效的情况。

因为整个生成程序是以Surge的规则为基础的，Surge没有这样的设计，当同时存在HOST,youtubei.googleapis.com 和 HOST-SUFFIX,youtubei.googleapis.com时，因为HOST-SUFFIX,youtubei.googleapis.com已经包括HOST,youtubei.googleapis.com，所以会把HOST,youtubei.googleapis.com去掉。

这对于QuanX，在优先级上会有些问题，并且不好修改，因为合并的操作在转换成QuanX的规则的前就已经完成了。

暂时的解决方案是在YouTube的规则中不进行DOMAIN-SUFFIX和DOMIAN的合并。

**Comment by syvys** [comment]
谢谢查看、回复。

我直接加的本地规则。
