### ISSUE TITLE
Quantumult x 知乎去广告脚本贴内按钮错位

### ISSUE THREAD

**Issue by s7964926** [blackmatrix7/ios_rule_script#280]
如图所示，赞同和反对按钮错位，surge没有这个问题。
![FF45A607-0BF3-475B-ABCF-FF3A9F93E062](https://user-images.githubusercontent.com/19381241/112871735-26a89580-90f2-11eb-9c86-ecd68fd982f9.png)

**Comment by WoodyLin** [comment]
别的重写影响的，不是大佬脚本的问题，你禁用排查下

**Comment by blackmatrix7** [comment]
无法复现此问题，建议再自行排查一下。

可以尝试将其他复写去掉验证。
