### ISSUE TITLE
QuantumultX的去广告规则导致腾讯视频无法登录

### ISSUE THREAD

**Issue by WowYiJiu** [blackmatrix7/ios_rule_script#281]
Quantumult X的去广告精简稳定版其中一条规则导致腾讯视频无法正常登录，然后建立新规则走直连就可以登陆了
![QQ图片20210330105139](https://user-images.githubusercontent.com/63225855/112927019-e9222780-9146-11eb-8f8f-8b25c24375ec.png)

**Comment by blackmatrix7** [comment]
已加入到过滤器，实时版会在明天凌晨更新，稳定版近期不会有更新。
