### ISSUE TITLE
圈x  wild rift分流

### ISSUE THREAD

**Issue by masaka96** [blackmatrix7/ios_rule_script#282]
圈x用wild rift分流  进游戏加载界面会卡住  直接进不去游戏

**Comment by blackmatrix7** [comment]
分流规则只是一堆域名和IP的集合，并不会造成任何不能正常访问的情况，这种通常是你的节点或策略配置错误导致的。

因为我本身不玩游戏，所以没办法帮你排查，建议自行抓包排查下。
