### ISSUE TITLE
万达电影通知错误

### ISSUE THREAD

**Issue by WowYiJiu** [blackmatrix7/ios_rule_script#286]
圈X已经获取ck了，但是还是显示本月共获得能量0个，剩余0个
![QQ图片20210403145335](https://user-images.githubusercontent.com/63225855/113471095-adf85f00-948c-11eb-8406-bd003eea01b5.png)

**Comment by blackmatrix7** [comment]
这是两个问题：

第一个问题是从接口返回数据的确没有获取到签到的能量，建议重新登录一下再试试。

第二个问题是的确有Bug在没有获取签到能量时输出undefined，这个后续会修复。

如果需要更详细的日志，可以修改代码中的

`let magicJS = MagicJS(scriptName, "INFO");`

将 INFO 改成 DEBUG，再执行脚本，看看接口返回具体的内容。

**Comment by WowYiJiu** [comment]
> 这是两个问题：
> 
> 
> 
> 第一个问题是从接口返回数据的确没有获取到签到的能量，建议重新登录一下再试试。
> 
> 
> 
> 第二个问题是的确有Bug在没有获取签到能量时输出undefined，这个后续会修复。
> 
> 
> 
> 如果需要更详细的日志，可以修改代码中的
> 
> 
> 
> `let magicJS = MagicJS(scriptName, "INFO");`
> 
> 
> 
> 将 INFO 改成 DEBUG，再执行脚本，看看接口返回具体的内容。

![image](https://user-images.githubusercontent.com/63225855/113496325-27df2580-952b-11eb-81a7-766e9f42872a.png)
非常感谢，ck失效情况下重新获取好像没用，重新登录获取ck就好了
