### ISSUE TITLE
youtube去广告建议用下边这个

### ISSUE THREAD

**Issue by milohsu** [blackmatrix7/ios_rule_script#29]
https://raw.githubusercontent.com/zhaocai/DivineEngine_Profiles/master/Quantumult/Rewrite/Block/YouTubeAds.conf

其它规则都失效了，还要在您的重写地址后边加#out=googlevideo 比较麻烦，建议更新下哈。

**Comment by blackmatrix7** [comment]
复写中不含YouTube去广告，所以不需要加#out=googlevideo。
YouTube去广告你可以单独加这个复写。
