### ISSUE TITLE
建议将180.76.76.200/32移出广告list

### ISSUE THREAD

**Issue by noobsora** [blackmatrix7/ios_rule_script#290]
规则名称：AdvertisingTest

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AdvertisingTest/AdvertisingTest..list

异常规则：ip-cidr, 180.76.76.200/32, AdvertisingTest

问题描述：该地址放在广告list里，大家对广告list的策略一般都是reject，但该地址被reject的话会导致百度地图离线导航数据百分百无法下载，离线地图数据大部分时候无法下载。测试过程：手动将该地址放行，百度地图离线导航数据可恢复正常下载。

调整方案：建议将该地址移出广告list

**Comment by blackmatrix7** [comment]
谢谢反馈，已去除。
