### ISSUE TITLE
无限期停止哔哩哔哩去广告脚本维护

### ISSUE THREAD

**Issue by blackmatrix7** [blackmatrix7/ios_rule_script#292]
目前哔哩哔哩APP的“动态“已升级为V2接口，改用grpc传输，参考：https://github.com/blackmatrix7/ios_rule_script/issues/269 。

JavaScript脚本无法处理此类的数据，去广告也就无从谈起。这可能只是一个开始，后续不排除其他的接口逐步调整为grpc，直到彻底无法去除任何广告。

所以即日起停止去广告脚本的维护，不再处理无法去除广告的反馈，特别是因为升级APP版本导致新的广告出现(可能根本处理不了)，直到有其他解决方案。

为延长脚本去广告的有效期，提供几个建议：

1. 没事不要升级APP，升级可能会带来更多的广告。
2. 尽快备份哔哩哔哩的ipa文件，目前可以下载的最早版本为6.19，此版本已无法去除动态的广告。我自用的版本为6.13，如果你有办法下载到这个版本，推荐安装，可以比较好的去除广告。

旧版接口下线是迟早问题，上面的建议也只是权宜之计。不要对去广告这个事情抱有太大希望，迟早都是会彻底失效的，包括知乎。

**Comment by luoqz9** [comment]
Surge 4.11.0(1986) TF 测试版 http 脚本开始支持二进制模式工作，可针对使用 protobuf 协议的 APP 进行广告去除。
看看大佬百忙之中有没有机会跟进一下新的解决思路。

**Comment by blackmatrix7** [comment]
等iOS15正式版发布看下……

**Comment by eliZhai** [comment]
插眼
