### ISSUE TITLE
今天首页不能刷新

### ISSUE THREAD

**Issue by lixinzai** [blackmatrix7/ios_rule_script#293]
个人页会提示ERR_PARSE_LOGIN_TICKET

**Comment by blackmatrix7** [comment]
你什么信息都不提供，什么App，什么脚本，什么版本，都不知道，帮不上你，抱歉。

**Comment by lixinzai** [comment]
知乎plus，最新的qx,7.6.0知乎

**Comment by blackmatrix7** [comment]
知乎脚本是做了比较大的更新，但是在我本地测试10天以上，没有发现这个问题。

建议手动执行一次脚本清理一下持久化数据。

**Comment by blackmatrix7** [comment]
刚刚又测试了一遍，没有发现这个问题。

如果你确认有这个问题，请提供详细的复现步骤、日志、截图。
