### ISSUE TITLE
全家签到报错

### ISSUE THREAD

**Issue by Tobyyyyt** [blackmatrix7/ios_rule_script#294]
提示如下：
[ERROR] [Fa米家]
签到失败，响应异常：{"code":"302154","message":"版本过低，请更新至最新版本后使用","data":null}

脚本文件和全家app都已是最新版，cookie重新取过，仍然报错。

**Comment by blackmatrix7** [comment]
不排除增加了其他的验证手段，旧版的接口已被强制停用。

具体的问题还要等后面抓包分析。

**Comment by blackmatrix7** [comment]
已修复，需要更新至最新的Fa米家APP，退出登录后重新获取一次Cookie。

**Comment by blackmatrix7** [comment]
签到接口增加blackBox参数，这个参数有效期很短，可能只有1天不到。

每天重新获取一次blackBox，还不如顺手签到。

所以目前脚本暂时没有办法进行签到，后面再想想办法吧。

**Comment by ROCKBUND** [comment]
> 签到接口增加blackBox参数，这个参数有效期很短，可能只有1天不到。
> 
> 每天重新获取一次blackBox，还不如顺手签到。
> 
> 所以目前脚本暂时没有办法进行签到，后面再想想办法吧。

fa米家是2.2.3
shadowrocket跑的最新脚本
还是会报和楼主一样的错，已经退出登录重新获取过cookies，不知道啥原因。。

暂时手动签了，用这个脚本换了好几瓶饮料了。谢谢大佬哈哈

**Comment by blackmatrix7** [comment]
> > 签到接口增加blackBox参数，这个参数有效期很短，可能只有1天不到。
> > 每天重新获取一次blackBox，还不如顺手签到。
> > 所以目前脚本暂时没有办法进行签到，后面再想想办法吧。
> 
> fa米家是2.2.3
> shadowrocket跑的最新脚本
> 还是会报和楼主一样的错，已经退出登录重新获取过cookies，不知道啥原因。。
> 
> 暂时手动签了，用这个脚本换了好几瓶饮料了。谢谢大佬哈哈

现在Cookie有效期只有一天左右，在找到能刷新Cookie或延长Cookie有效期之前，暂时没有办法。

**Comment by blackmatrix7** [comment]
观察了几天，签到应该恢复正常了。

如果还有问题，升级APP至最新版本，重新登录再获取Cookie。
