### ISSUE TITLE
Rule/Proxy中规则移除

### ISSUE THREAD

**Issue by IvorkChan** [blackmatrix7/ios_rule_script#295]
规则名称：Rule/Proxy

规则链接：Rule/Proxy

异常规则：HOST-SUFFIX,s3.ax1x.com,Proxy

问题描述：走代理会出现SSL错误，DIRECT正常。

调整方案：请移除该规则。

**Comment by blackmatrix7** [comment]
SSL错误可能是服务器的问题，不过最终还是会把它移除掉，因为它直接就可以访问。

正常情况下，每日的凌晨会更新。
