### ISSUE TITLE
zhihu_lite 系列模块脚本 404

### ISSUE THREAD

**Issue by mwhds97** [blackmatrix7/ios_rule_script#296]
[https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.min.js](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.min.js)

该文件似乎不存在

**Comment by blackmatrix7** [comment]
已修复
