### ISSUE TITLE
bilibili规则

### ISSUE THREAD

**Issue by MyGoodbye** [blackmatrix7/ios_rule_script#297]
有没有办法只让港澳台番剧走代理，国漫就走直连呢？我测试了很旧，目前只知道
IP-CIDR,203.107.1.33/32
IP-CIDR,203.107.1.34/32
IP-CIDR,203.107.1.65/32
IP-CIDR,203.107.1.66/32
IP-CIDR,150.116.92.250/32
IP-CIDR,45.43.32.234/32
IP-CIDR,164.52.76.18/32
IP-CIDR,128.1.62.200/32
IP-CIDR,128.1.62.201/32
DOMAIN,www.bilibili.com
IP-CIDR,58.222.35.200/29
IP-CIDR,222.186.35.80/32
IP-CIDR,222.188.43.129/29
这样是可以让b站走港澳台，但是国漫仍然会地区错误，测试了好久，希望有人能提供一个更好的规则，可以让b站分流开

**Comment by blackmatrix7** [comment]
https://github.com/NobyDa/Script/blob/master/Surge/JS/Bili_Auto_Regions.js

你可以试试这个，有问题跟原作者沟通下。
