### ISSUE TITLE
最新的去广告策略里有一个规则无法被Surge识别

### ISSUE THREAD

**Issue by stefaneliu** [blackmatrix7/ios_rule_script#299]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：去广告规则

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Surge/Advertising/Advertising.list

异常规则：URL-REGEX,^https?:\/\/(\d{1,3}\.){3}\d{1,3}/(variety|vlive\.qqvideo)\.tc\.qq\.com/,REJECT

问题描述：Surge无法识别该规则。更新带有该规则的订阅时，出现错误信息：“规则使用了一个未知的策略：3}\.){3}\d{1。"

抓包截图：(相关抓包工具的截图。)

调整方案：不懂正则，但是这种识别错误不知道是否和Surge语法有关？Clash似乎不会被此规则影响。

**Comment by blackmatrix7** [comment]
能否提供下出错的截图，我自用也是Surge，没有发现更新的时候报错。

**Comment by stefaneliu** [comment]
![IMG_7230](https://user-images.githubusercontent.com/59643653/114409645-3d181c00-9bdd-11eb-90db-049be5fad0ce.PNG)
这是出错提示。
如果把主题内说的这条规则删掉，就可以使用了。
btw，我的surge ios版本是4.11.0(build 1906)，surge mac版本是3.5.7。供参考。谢谢！

**Comment by blackmatrix7** [comment]
能否把配置文件脱敏后上传一份我看下？
感觉是没有正确换行导致，我用的是master分支下的，不过近期应该是一样的。

**Comment by fiiir** [comment]
我知道原因，这条规则如果在list中并不会报错（猜测是因为错误写法所以被略过了）
但是写入配置文件就会报错，因为surge在配置文件中不支持“\d{1,3}”这种写法的规则，改成“(\d{1}|\d{3})”就可以了

**Comment by stefaneliu** [comment]
> 我知道原因，这条规则如果在list中并不会报错（猜测是因为错误写法所以被略过了）
> 但是写入配置文件就会报错，因为surge在配置文件中不支持“\d{1,3}”这种写法的规则，改成“(\d{1}|\d{3})”就可以了

刚刚测试了，确实如此，改掉就可以正常更新订阅，谢谢。
@blackmatrix7 老大是否能改写一下规则以便正确订阅？非常感谢！

**Comment by blackmatrix7** [comment]
> 我知道原因，这条规则如果在list中并不会报错（猜测是因为错误写法所以被略过了）
> 但是写入配置文件就会报错，因为surge在配置文件中不支持“\d{1,3}”这种写法的规则，改成“(\d{1}|\d{3})”就可以了

这应该是Surge的Bug，把{1,3}的,当成规则分隔了。

**Comment by blackmatrix7** [comment]
这个正则应该是用来去除腾讯视频广告的，实测没有效果，暂时把它去掉了，等明天凌晨更新。

**Comment by ashurinn** [comment]
关于报错，将正则部分用引号" "包起来就没问题了。另外这条应该是有效果的，不过Surge不能直接处理TUN广告，需要将相关主机名加入force-http-engine-hosts，然而腾讯的IP太多了我尝试抓了几个就放弃了，不过quanx是可以直接用的。

**Comment by fiiir** [comment]
> 关于报错，将正则部分用引号" "包起来就没问题了。另外这条应该是有效果的，不过Surge不能直接处理TUN广告，需要将相关主机名加入force-http-engine-hosts，然而腾讯的IP太多了我尝试抓了几个就放弃了，不过quanx是可以直接用的。

与引号无关，我想表达的是，将规则中这类写法：
\d{1,3}
改写成这样的写法：
(\d{1}|\d{3})

**Comment by blackmatrix7** [comment]
> 关于报错，将正则部分用引号" "包起来就没问题了。另外这条应该是有效果的，不过Surge不能直接处理TUN广告，需要将相关主机名加入force-http-engine-hosts，然而腾讯的IP太多了我尝试抓了几个就放弃了，不过quanx是可以直接用的。

这条正则已经在复写中存在，所以在分流规则中去掉没有什么影响，并且只有分流规则没有force-http-engine-hosts也无法生效。

不过我在复写中加入了force-http-engine-hosts，依旧没有效果，不知道是不是版本差异。

**Comment by blackmatrix7** [comment]
> \d{1,3}

{1,3} 表示的应该是出现1-3次。

**Comment by fiiir** [comment]
> > \d{1,3}
> 
> {1,3} 表示的应该是出现1-3次。

谢谢，一直蒙在鼓里🌚
