### ISSUE TITLE
神机quanx分流规则未来将不再维护甚至移除，建议换到Surge规则下

### ISSUE THREAD

**Issue by jqbk** [blackmatrix7/ios_rule_script#301]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

规则链接：

异常规则：

问题描述：

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
https://github.com/DivineEngine/Profiles/tree/master/Quantumult/Filter  
希望老哥收集整理神机分流规则时可以换到Surge分流规则下

**Comment by blackmatrix7** [comment]
谢谢反馈，目前Surge和QuanX的规则应该都加入作为数据源，后面会再核对一下，如果Surge有缺少的再补上。

**Comment by jqbk** [comment]
> 谢谢反馈，目前Surge和QuanX的规则应该都加入作为数据源，后面会再核对一下，如果Surge有缺少的再补上。

好的 老哥

**Comment by blackmatrix7** [comment]
已补充Surge部分的规则，等待明日凌晨自动更新。
