### ISSUE TITLE
quanx分流规则下Privacy.list与AdvertisingLite.list也有大概3000条重复

### ISSUE THREAD

**Issue by jqbk** [blackmatrix7/ios_rule_script#303]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Privacy
AdvertisingLite
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Privacy/Privacy.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list
异常规则：

问题描述：
两类分流有大约3000多条重复，导致重新开启Quantumult X会报错“有大量分流规则重复”
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
能否进行洗重，谢谢！

**Comment by jqbk** [comment]
> 这种情况可能是某个上游数据源已经把Privacy的规则合并进去了。
> 
> 目前规则生成器只能支持子规则的包含关系，暂时无法实现将某个规则从另外一个规则排除出去。
> 
> 有实现此功能的计划，但需要一些时间，暂时建议将Privacy的规则禁用，后面可以支持时我再回复你。
好的，老哥，目前我已经禁用，暂时采用神机的privacy规则

**Comment by jqbk** [comment]
> 这种情况可能是某个上游数据源已经把Privacy的规则合并进去了。
> 
> 目前规则生成器只能支持子规则的包含关系，暂时无法实现将某个规则从另外一个规则排除出去。
> 
> 有实现此功能的计划，但需要一些时间，暂时建议将Privacy的规则禁用，后面可以支持时我再回复你。

好的，老哥，目前已经禁用，暂时采用神机的privacy分流规则

**Comment by blackmatrix7** [comment]
已从AdvertisingLite排除Privacy和Hijacking，等待明日凌晨自动更新。
