### ISSUE TITLE
Microsoft规则问题

### ISSUE THREAD

**Issue by MichaelPan1026** [blackmatrix7/ios_rule_script#305]
规则名称：`Microsoft`

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Microsoft/Microsoft.list

异常规则：`HOST-KEYWORD, LIVE, Microsoft`

问题描述：该规则会导致`stun.qqlive.qq.com:8000`被识别到`Microsoft`规则里

截图：![7BF1452B-A8CB-45FB-B6B0-EFE1E3A3E011](https://user-images.githubusercontent.com/26241105/114931734-31408a00-9e69-11eb-9c77-dcb1e6b59a7e.png)

**Comment by blackmatrix7** [comment]
昨天加了一个新的数据源，这个源写得不是很好，已经去掉了，会在明天凌晨更新。
