### ISSUE TITLE
建议增加社交软件的合集，谢谢！

### ISSUE THREAD

**Issue by xqXQzzz1** [blackmatrix7/ios_rule_script#306]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

规则链接：

异常规则：

问题描述：

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
不太明白你希望做什么。

**Comment by xqXQzzz1** [comment]
> 不太明白你希望做什么。

类似于globalmedia一样，做一个tg、ins之类的合集，可以吗？

**Comment by blackmatrix7** [comment]
目前没有这个计划，主要是在400多项规则中，绝大多数的规则我都未曾用过，不清楚哪些属于社交范围。

建议自行整合一下。
