### ISSUE TITLE
fa米家无法使用了

### ISSUE THREAD

**Issue by nick814** [blackmatrix7/ios_rule_script#309]
一直显示这个报错
签到失败，响应异常：{"code":"302154","message":"版本过低，请更新至最新版本后使用","data":null}

**Comment by blackmatrix7** [comment]
今天凌晨可能Fa米家又更新了接口，需要时间去调试适配。

**Comment by blackmatrix7** [comment]
目前已做修复，需要测试几天确认没问题再更新，期间先手动签到一下。

如果几天后还没更新…… 说明又遇到了新的问题……

**Comment by nick814** [comment]
谢谢大佬

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: blackmatrix7 ***@***.***>
发送时间: Saturday, April 17, 2021 3:04:50 PM
收件人: blackmatrix7/ios_rule_script ***@***.***>
抄送: nick814 ***@***.***>; Author ***@***.***>
主题: Re: [blackmatrix7/ios_rule_script] fa米家无法使用了 (#309)


目前已做修复，需要测试几天确认没问题再更新，期间先手动签到一下。

如果几天后还没更新…… 说明又遇到了新的问题……

―

**Comment by blackmatrix7** [comment]
已更新，建议重新登录一下再获取Cookie。
