### ISSUE TITLE
TikTok规则缺失

### ISSUE THREAD

**Issue by MichaelPan1026** [blackmatrix7/ios_rule_script#310]
规则名称：TikTok

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/TikTok/TikTok.list

异常规则：缺少`HOST-SUFFIX, AMEMV.COM, TikTok`

问题描述：`AMEMV.COM`频繁被`Global`接到`PROXY`，检查TikTok规则发现缺失。

抓包截图：![810c05fe9a63966dc51a3391ae23c7f](https://user-images.githubusercontent.com/26241105/115135670-b5069c00-a04c-11eb-8422-9b33e93373ce.png)

调整方案：添加规则

**Comment by blackmatrix7** [comment]
谢谢，很详细的反馈。

已补充上去，类似TikTok这种变化不大的规则，可以使用release，避免因为哪个上游删除规则造成意外情况。
