### ISSUE TITLE
多邻国cn被Global接管

### ISSUE THREAD

**Issue by MichaelPan1026** [blackmatrix7/ios_rule_script#311]
规则名称：Global

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/QuantumultX/Global/Global.list

异常规则：`HOST-SUFFIX,duolingo.cn,Global`

问题描述：该网站属于国内，被`PROXY`接管

抓包截图：![380aba005c7764e9e8313f306ecc150](https://user-images.githubusercontent.com/26241105/115135709-14fd4280-a04d-11eb-9d59-9ed591239cc2.png)

调整方案：去掉该条。

**Comment by blackmatrix7** [comment]
谢谢，很详细的反馈，已经更新了。现在给Golbal加了个正则过滤器，过滤器掉大部分.cn域名，减少错误添加的情况。
