### ISSUE TITLE
TikTok来源添加及从其他分流规则中删除

### ISSUE THREAD

**Issue by jqbk** [blackmatrix7/ios_rule_script#313]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
`TikTok.list` `Global.list` `GlobalMedia.list`
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/TikTok/TikTok.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list
异常规则：

问题描述：
`TikTok.list`中缺少几条规则
`Global.list`与`GlobalMedia.list`中有重复的`TikTok`规则
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
建议将`https://raw.githubusercontent.com/Semporia/Quantumult-X/master/Filter/TikTok.list`作为新增来源引用
删除`Global.list`与`GlobalMedia.list`中重复的`TikTok`规则

**Comment by blackmatrix7** [comment]
TikTok的数据源加入了，等待凌晨自动更新就可以。

Global是否删除TikTok还要再考虑一下，因为它们本来就是一个集合性质的东西。

**Comment by jqbk** [comment]
但是TikTok分流规则无论是国内的抖音还是需要解锁国外地区的TikTok，其实内容是一样的，而global或者globalmedia应该是必须要使用代理的场景，所以可能在这类场景中包含TikTok似乎会导致潜在的冲突。只是一点建议，希望老哥考虑一下😀

**Comment by blackmatrix7** [comment]
这段时间测试了一个Lite版本的Global，效果不是很好，所以暂时不考虑去除了。
