### ISSUE TITLE
脚本Cookie获取

### ISSUE THREAD

**Issue by L1cardo** [blackmatrix7/ios_rule_script#317]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：贴吧签到

APP版本：

客户端名称：

客户端版本：

问题描述：贴吧cookie怎么也获取不到

复现方式：

1. 打开贴吧
2. 退出后台重新进入

已使用空白配置文件验证：是

希望能描述一下各个cookie的获取方式，包括但不限于百度贴吧，什么值得买

**Comment by blackmatrix7** [comment]
什么值得买是通过safari登录zhiyou.smzdm.com获取，不要有其他的获取什么值得买Cookie的复写。

贴吧只要打开百度贴吧App就可以了，如果你贴吧有问题，提供下版本号。

**Comment by L1cardo** [comment]
贴吧版本：12.4.2
退后台重启也试过了，获取不了

各个脚本的cookie获取希望可以在readme里面描述一下

**Comment by blackmatrix7** [comment]
能提供下脚本的执行日志吗？

**Comment by L1cardo** [comment]
请问surge怎么获取这个cookie获取脚本的日志

**Comment by blackmatrix7** [comment]
你可以先抓包看下获取Cookie的请求是否触发了脚本处理

**Comment by L1cardo** [comment]
获取cookie好像是通过c.tieba.baidu.com/c/s/login来获取
`pattern=^https?:\/\/c\.tieba\.baidu\.com\/c\/s\/login`

但是这个url是没有被请求的
![image](https://user-images.githubusercontent.com/33802186/115848479-7f9bed00-a456-11eb-8d39-bb4ee3b330e9.png)

**Comment by blackmatrix7** [comment]
这样的话，可能新版的贴吧修改了什么接口，需要找时间再验证下，你可以先降级使用试试。

我用的是12.3.6，目前可以正常获取Cookie。

**Comment by blackmatrix7** [comment]
看了下新版贴吧接口的确更新了，需要适配和测试几天。

**Comment by L1cardo** [comment]
OK

**Comment by blackmatrix7** [comment]
过10分钟左右，你更新下试试吧，避免Github有缓存。

**Comment by L1cardo** [comment]
获取cookie我用的是 [这个](https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/GetCookie)，可能还要等你在这里面加上。

我想的是要把cookie脚本分开，在cookie失效时再打开获取，平时关闭
但是你的所有签到脚本都是签到和获取cookie都放在了一起，这样会不会有性能问题

**Comment by blackmatrix7** [comment]
> 获取cookie我用的是 [这个](https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/GetCookie)，可能还要等你在这里面加上。
> 
> 
> 
> 我想的是要把cookie脚本分开，在cookie失效时再打开获取，平时关闭
> 
> 但是你的所有签到脚本都是签到和获取cookie都放在了一起，这样会不会有性能问题

整合的脚本需要等待明天凌晨自动更新。

获取cookie和签到集合在一起，会有轻微的性能开销，我自己使用过程没发现有问题。

整合在一起是因为我希望降低使用门槛，让获取Cookie的过程是无感的，在日常使用App时，就自动把Cookie更新了。

不过考虑到有的人不喜欢这样，所以才有由程序自动生成的GetCookie汇总。

**Comment by L1cardo** [comment]
> > 获取cookie我用的是 [这个](https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/GetCookie?rgh-link-date=2021-04-23T10%3A11%3A44Z)，可能还要等你在这里面加上。
> > 我想的是要把cookie脚本分开，在cookie失效时再打开获取，平时关闭
> > 但是你的所有签到脚本都是签到和获取cookie都放在了一起，这样会不会有性能问题
> 
> 整合的脚本需要等待明天凌晨自动更新。
> 
> 获取cookie和签到集合在一起，会有轻微的性能开销，我自己使用过程没发现有问题。
> 
> 整合在一起是因为我希望降低使用门槛，让获取Cookie的过程是无感的，在日常使用App时，就自动把Cookie更新了。
> 
> 不过考虑到有的人不喜欢这样，所以才有由程序自动生成的GetCookie汇总。

OK  了解了，感谢

**Comment by L1cardo** [comment]
现在显示这个....
![image](https://user-images.githubusercontent.com/33802186/115943598-6b520180-a4e3-11eb-8390-dd364da7bfee.png)

**Comment by blackmatrix7** [comment]
脚本也需要更新的

**Comment by L1cardo** [comment]
> 现在显示这个....
> ![image](https://user-images.githubusercontent.com/33802186/115943598-6b520180-a4e3-11eb-8390-dd364da7bfee.png)

这个是上午cookie获取时候报错的，但是我刚刚又试了一遍，又可以了

**Comment by blackmatrix7** [comment]
应该是只更新了模块，远程脚本没更新导致的。
