### ISSUE TITLE
请问哔哩哔哩去广告停止维护了吗

### ISSUE THREAD

**Issue by ben-august** [blackmatrix7/ios_rule_script#318]
请问哔哩哔哩去广告停止维护了吗，我看正常使用没问题

**Comment by blackmatrix7** [comment]
目前新版动态部分去广告已经无法实现，其他功能暂时正常，但是后面再出问题也不再处理了。

**Comment by XuuKoo** [comment]
> 目前新版动态部分去广告已经无法实现，其他功能暂时正常，但是后面再出问题也不再处理了。

概念版还能下载到老版本 感觉是个路子。
