### ISSUE TITLE
b站、美团开屏广告

### ISSUE THREAD

**Issue by violesea** [blackmatrix7/ios_rule_script#319]
b站跟美团好像又有开屏广告了。清除过缓存还是没有用。确定qx、规则在起作用

**Comment by blackmatrix7** [comment]
没有发现这个问题，请提供下版本号，及用于验证的空白配置文件，便于复现。

如果没有空白配置文件，请先创建一个进行验证，如果确定有问题，把这个配置文件作为附件传上来。

**Comment by violesea** [comment]
是我路由器的问题 麻烦关闭吧
