### ISSUE TITLE
AllInOne的复写中存在大量无关hostname

### ISSUE THREAD

**Issue by Skyxim** [blackmatrix7/ios_rule_script#320]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
AllInOne.conf
规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/QuantumultX/AllInOne/AllInOne.conf
异常规则：

问题描述：
这个重写的hostname部分许多域名在上面并不存在对应的正则表达式。
抓包截图：(相关抓包工具的截图。)
以下为随便挑选的几个，应该还有很多无关的hostname
![image](https://user-images.githubusercontent.com/70276018/116494044-9917bb80-a8d2-11eb-926b-1539aeebee04.png)

![image](https://user-images.githubusercontent.com/70276018/116494099-b64c8a00-a8d2-11eb-8482-193fffec78c7.png)
![image](https://user-images.githubusercontent.com/70276018/116494113-be0c2e80-a8d2-11eb-8f50-88afee6e23c7.png)

调整方案：(你希望规则做哪些调整，及其原因。)
如果不是有特别用意希望通过上面的正则表达式反向生成hostname或者与上面复写进行校验减少无用的hostname的存在，毕竟解析https会对手机性能产生消耗。应该不只是这一个可能相关的复写都会存在这样的问题

**Comment by blackmatrix7** [comment]
现在比较麻烦的是很多正则，比如

^https?:\/\/.+?\.mp4\?ccode=0902 url reject
^https?:\/\/.+?\.mp4\?sid= url reject
^https?:\/\/.+?\/(mixer|track2)\? url reject
^https?:\/\/.+?\/allOne\.php\?ad_name url reject
^https?:\/\/.+?\/api\/app\/member\/ver2\/user\/login\/ url reject-img
^https?:\/\/.+?\/api\/v\d\/adRealTime url reject
^https?:\/\/.+?\/cdn-adn\/ url reject
^https?:\/\/.+?\/client?functionId=lauch\/lauchConfig&appName=paidaojia url reject-img
^https?:\/\/.+?\/eapi\/(ad|log)\/ url reject
^https?:\/\/.+?\/eapi\/[ad|event]\/ url reject-img
^https?:\/\/.+?\/eapi\/ad\/ url reject-img
^https?:\/\/.+?\/hls.cache.p4p\/ url reject-img
^https?:\/\/.+?\/img\/ad\.union\.api\/ url reject
^https?:\/\/.+?\/img\/web\.business\.image\/ url reject-img
^https?:\/\/.+?\/letv-gug\/ url reject
^https?:\/\/.+?\/music\/common\/upload\/t_splash_info url reject-img
^https?:\/\/.+?\/portal\.php\?a=get_ads url reject-img
^https?:\/\/.+?\/portal\.php\?a=get_coopen_ads url reject-img
^https?:\/\/.+?\/portal\.php\?c=duiba url reject-img
^https?:\/\/.+?\/resource\/m\/promo\/adsense url reject
^https?:\/\/.+?\/resource\/m\/sys\/app\/adpos url reject
^https?:\/\/.+?\/tips\/fcgi-bin\/fcg_get_advert url reject-img
^https?:\/\/.+?\/v1\/iflyad\/ url reject
^https?:\/\/.+?\/v2\/app_ads\/ url reject
^https?:\/\/.+?\/v\d\/iflyad\/ url reject

不知道匹配的是什么规则，更没办法推导出来。

所以对这些不知道干什么用的hostname也很难进行处理，现在正则推导hostname，也只能推导部分，不能完全依靠推导。

如果要解决这个问题，需要人工去把像上面这些正则剔除掉，或者找到哪个数据源引入这样的正则，把它们移除掉，但是又可能影响去广告效果。

**Comment by Skyxim** [comment]
主要是最近发现qx在使用这个复写时看腾讯视频会大量发热，已经暂时换回了DivineEngine的所以才看的
不过这个的确是个问题，这种规则没有明确指向

**Comment by blackmatrix7** [comment]
如果对去广告效果影响不大，可以尝试下把这些太模糊的去掉。

**Comment by Skyxim** [comment]
可否做成两个版本，提供一个lite版本去掉这些没有明确指向的规则和把相关hostname，让人自行选择，从而减少减少误识别几率

**Comment by blackmatrix7** [comment]
最近事情比较多，后面可以考虑弄一个：加个功能，用正则推导hostname，推导不出来的正则直接丢弃。

到时候看看效果。

**Comment by Skyxim** [comment]
嗯，麻烦了

**Comment by blackmatrix7** [comment]
已经弄了个Lite版本
