### ISSUE TITLE
提交一个屏蔽广告规则源

### ISSUE THREAD

**Issue by WoodyLin** [blackmatrix7/ios_rule_script#321]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

规则链接：

异常规则：

问题描述：
在github看到一个广告屏蔽更新源，更新比较及时，大佬看下有没整合到现在分流规则里面的意义。
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
整合到目前广告分流中，广告屏蔽项目地址：https://github.com/h2y/Shadowrocket-ADBlock-Rules
https://github.com/privacy-protection-tools/anti-AD

**Comment by blackmatrix7** [comment]
这两个，一个是配置文件，已经归档不会再有更新，所以不考虑加入了。

另外一个暂时不能支持，后续支持会加入的。

**Comment by blackmatrix7** [comment]
仔细看了下，第二个应该已加入了，什么时候加入我的自己也忘了，最近事情太多，可能加入了没来得及回复。
