### ISSUE TITLE
AdvertisingTest规则的增添和修改建议

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#322]
(1)
AdvertisingTest规则中
其中一些规则的数据来源是这里
https://github.com/geekdada/surge-list

最近发现来源的项目增加了几个新list，都是DOMAIN-SET格式，建议加入
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/annoyances-filter.txt
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/social-media-filter.txt
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/dns-filter.txt

(2)
依旧是 AdvertisingTest规则 相关
数据来源中有这样一个来源，是DOMAIN-SUFFIX格式
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt

最近项目推出了DOMAIN-SET格式的list
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt
如大佬觉得有必要可以更换一下

**Comment by blackmatrix7** [comment]
节前已加入了部分。
