### ISSUE TITLE
b站 动态圈广告

### ISSUE THREAD

**Issue by violesea** [blackmatrix7/ios_rule_script#323]
你好 上次反馈了b站动态圈广告问题 我这两天试着抓包 结果反馈一下，我是小白，希望能有帮助。

这是链接好像https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?access_key=455d4694cc993c525c7a2e6b7dce4541&actionKey=appkey&ad_extra=F6209EEC4D712ADB7AAF94480A782BC79D24CC3E0DA02F8F25AEA8787D11033220F612E1F607C70A81D02192EE80D17973D311CBC59AAA8ECFAB38C28C653CAC96E8B606386F8ADC8ECF18250A6F2AAF29A513D142740AC9D0883E09379C66CB06E97B418291AD13816C9A331ABE3E57FFBFE8FEBB1FC0EBF9323B16657AF7A6BC600FF7015F1D24D33B1A250FA781E30A2075502F9BB690CDEAE08ECF505DA31405A7AB77979E8B82ABB1B151228E1060F55E847F2840A5EC9CB2FE7CAECD83A9184E537A8A88F622D16835ED33D8EF8244116A9776C1D071D4ABAEF9D0607FF40CFA5D0B07CF508DE38AC1DA5DA288B237D7A29B16A1C7F4DE7B9C28404BB26C816E2C308C5652E92C1436F9E3D0085DA5DFC5A077125CBFBAACB51D4D763C808B731C9834EC1F90EB4408122C72F38A0800CF52F5EE38B881C340629B9F0F9CFB799013A0DA75FF09B44B5CDD9B6DD8368809182FE6814089210B83EA7AA3A26E8A3294D868B5FB13124E94647C33AE402940FB83687C95128D4A04CD0ACC9D45F2AB1E3CE891FC3623DACA3C92DC084CE01E33F2EC1662E7317606FFE5B29B36AB39D59EC3779C94F3D528D57E84497CF0EEED15AD06A12A186BC8C089E923EC111A94B273FAD54D65D38F697D46D395F80D37220BBCD101A9B05A0BE1370B8E62A7F8153F1F36BAF850D6BF121623E2701B57AF5984DE717EA5E4C53D0A6B14ABE0CDCFEE891465698A0B578E0002C98D5068C1614FDE3C32D9A85B990DA455571300EA69948E4E9E61B6D27D22D4933B41799F9672C85C706848FFD5A58C9607FB1992B444EF1A919ADB59F4AB38BD316208E5E1189D336D880DCCB6B1825AEDFAC6EB6ADC7AEDB9CE3AB581BCAA03C124CA54A19076A8B9350F6AD64ED8E0D392AE3A74FF7AA759463E8897385CC57E3A7B459B8CC8A58C9BC5A5BD101B429EAA3D677486D318AB280EE54CFFE216B9176B0DA1E2483EA5554B646FD9E539126417C8B44E1789CE45BB90A828933A7A04155AD883ED8BDFD600BD20BFF554B405F0ED58BAE9E3860015A2DDF43299F0A96A1339622FBBCC677E5E2039DE2E4E301CABEBCA0CEDCEAF6D7D209009EB7AC17F4C7DCA297400952754443859D7204FAE1E31A833F7A31B92FDC72562F488222529D1005AC720344301EDABDE2F4069A0517047101F578B9FCF81561FB377D4016DC02DAED16E0614618E12AB936411D8E6B06A275243478E62C240&appkey=27eb53fc9058f8c3&build=62305200&c_locale=zh-Hans_CN&device=phone&device_name=iPhone%2011&fnval=464&fnver=0&force_host=0&fourk=1&from=space&host_uid=485421093&https_url_req=0&mobi_app=iphone&need_top=1&offset_dynamic_id=0&page=1&platform=ios&player_net=1&qn=116&s_locale=zh-Hans_CN&sign=5d79fd479f65d884ec265ae5aa6fe335&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.23.5%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1619857103&visitor_uid=3179571

**Comment by blackmatrix7** [comment]
之前抓包过，已经处理不了动态内的广告了，抱歉啊。
