### ISSUE TITLE
TikTok引用规则后国内抖音无法加载

### ISSUE THREAD

**Issue by junetwentytwo** [blackmatrix7/ios_rule_script#324]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
TikTok.list
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/TikTok/TikTok.list
异常规则：
TikTok.list
问题描述：
HOST-SUFFIX,amemv.com,TikTok这个域名通过qx分流查看国内抖音也有在用，如果引用此规则导致国内抖音无法加载。
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
删除此条规则，规则来源https://github.com/Semporia/Quantumult-X/blob/master/Filter/TikTok.list

**Comment by blackmatrix7** [comment]
现在对于这种一条规则多个APP共用的情况，没什么很好的办法，建议根据自己需要，利用规则优先级关系进行调整。

https://github.com/blackmatrix7/ios_rule_script/issues/310
