### ISSUE TITLE
AdvertisingTest_Domain 误拦截谷歌

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#328]
相关list：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingTest/AdvertisingTest_Domain.list

相关规则
.google.com
.googleapis.com

怀疑是不是大佬最近添加了什么不靠谱的数据来源，这个规则一直在用，手动更新也比较频繁
虽然是今天才发现的，但基本可以将时间范围确定在最近三四天内

**Comment by XuuKoo** [comment]
同时会拦截雅虎整个域名

相关规则
.yahoo.com

**Comment by blackmatrix7** [comment]
我看下哪个源有问题，上周的确添加了一些源。

**Comment by blackmatrix7** [comment]
OMAIN-SUFFIX,fun,REJECT-200 

> 同时会拦截雅虎整个域名
> 
> 相关规则
> .yahoo.com
> 
> 问题源头：https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/Shadowrocket/SKY-NOAD.conf
> 原规则：
> DOMAIN-SUFFIX,googleapis.com,PROXY
> DOMAIN-SUFFIX,google.com,PROXY
> DOMAIN-SUFFIX,yahoo.com,REJECT-200
> 
> 同时认为，原规则这几个域名的拦截也不妥：
> DOMAIN-SUFFIX,fun,REJECT-200
> DOMAIN-SUFFIX,biz,REJECT-200
> DOMAIN-SUFFIX,club,REJECT-200
> DOMAIN-SUFFIX,info,REJECT-200
> 
> 个人看了一下原规则”DOMAIN-SUFFIX,ad.12306.cn,REJECT“这一行及以下是靠谱的，但是这一行以上的内容还得斟酌。

这个规则我添加前看了下，把DOMAIN-SUFFIX,fun,REJECT-200之类的做了去除。

现在再仔细看了下，感觉误杀太厉害了，还是把这个规则去掉吧，逐一给它加过滤器量太大。

**Comment by blackmatrix7** [comment]
> 相关list：
> https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingTest/AdvertisingTest_Domain.list
> 
> 相关规则
> .google.com
> .googleapis.com
> 
> 怀疑是不是大佬最近添加了什么不靠谱的数据来源，这个规则一直在用，手动更新也比较频繁
> 虽然是今天才发现的，但基本可以将时间范围确定在最近三四天内

google这个是生成器的问题导致的，类似这种把ss配置文件当成数据源会有些问题，先把这个源去掉。

**Comment by blackmatrix7** [comment]
这个误杀还是比较严重的，已经更新去掉，你们更新下规则。
