### ISSUE TITLE
万达电影签到无法获取Cookie

### ISSUE THREAD

**Issue by eddie506** [blackmatrix7/ios_rule_script#330]
脚本名称：万达电影—签到

APP版本：Quantumult X v1.0.21-bulid539

客户端名称：万达电影

客户端版本：version 7.2.0

问题描述：进入万达电影-我的页面，无法获取Cookie，但使用chavyleung的脚本可以获取Cookie

已使用空白配置文件验证：否

**Comment by blackmatrix7** [comment]
已修复，因为我用的接口正好在新版的万达电影中被去掉了，所以没办法获取到Cookie。
