### ISSUE TITLE
Surge 模块 AllInOne 开启后 火币无法正常使用

### ISSUE THREAD

**Issue by luoqz9** [blackmatrix7/ios_rule_script#331]
相关list：
https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rewrite/Surge/AllInOne/AllInOne_Classical.sgmodule

相关规则
[MITM]
hostname=*.club 怀疑这条规则似乎影响到了火币的 l10n-dm.huobiasia.club:443域名。
显示 MitM Failed，关闭 MitM 后一切正常。

**Comment by blackmatrix7** [comment]
这个hostname来自于

https://raw.githubusercontent.com/githubacct001/QuantumultX/master/Rewrite/githubacct001.conf

这样的写法不是很合理，我在规则生成器上加了一个判断，把类似 *.club 的hostname全部丢弃了。

稍后会做一个更新，你使用的是CDN的连接，我不太清楚它多久会更新一次，如果着急的换可以使用raw文件的链接。

**Comment by blackmatrix7** [comment]
已经更新了

**Comment by luoqz9** [comment]
感谢
