### ISSUE TITLE
Spotify 修改密码跳转页面被错误拦截

### ISSUE THREAD

**Issue by luoqz9** [blackmatrix7/ios_rule_script#332]
规则名称：Surge Advertising_Domain

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list

异常规则：.wl.spotify.com

问题描述：该规则涉及正常的 Spotify 改密行为

抓包截图：
![WechatIMG309](https://user-images.githubusercontent.com/65555676/118148022-be640800-b442-11eb-8543-64685febc71d.jpeg)
<img width="1275" alt="截屏2021-05-13 下午11 28 16" src="https://user-images.githubusercontent.com/65555676/118148168-e7849880-b442-11eb-8bf5-f053ae31abe2.png">

**Comment by blackmatrix7** [comment]
谢谢反馈，已经去掉了。
