### ISSUE TITLE
能加入jd tb历史价格吗

### ISSUE THREAD

**Issue by violesea** [blackmatrix7/ios_rule_script#333]
能加入jd tb历史价格的脚本吗

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/tree/master/external/Surge/JDPrice

有京东的，淘宝的暂时没加入，你可以用原作者的，我也只是做个备份而已。

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/tree/master/external/Surge/TBPrice

淘宝的也已加入
