### ISSUE TITLE
广告乎的新广告，大佬麻烦看下

### ISSUE THREAD

**Issue by WoodyLin** [blackmatrix7/ios_rule_script#334]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：

APP版本：知乎7.11.1(4782)

客户端名称：

客户端版本：

问题描述：知乎更新了新广告
![09CFC672-6AAE-48ED-8BED-9D9991B1EB7F](https://user-images.githubusercontent.com/1460489/118746058-127b4c00-b88a-11eb-9824-26de6a8212c4.jpeg)

请求头
POST /log_collect/analysis HTTP/1.1
Host: api.zhihu.com
X-SUGER: SURGQT0wQTQyMzQ0RS04NTE0LTRCMjYtQTI5My0xODg3NUVCNTQ5QjE7Q09PUkRfTEFUPTMwLjQ4MzA7Q09PUkRfTE5HPTExNC41OTAwO0NPT1JEX1RJTUVTVEFNUD0xNjIxMzg5MzI5O0xCUz17InBvaU5hbWUiOiLljY7lt6Xnp5HmioDmmbrog73liLbpgKDmnKrmnaXkuqfkuJrlm60iLCJjaXR5Q29kZSI6IjAyNyJ9O0xCU19MRU5HVEg9NDQ7TEJTX1RTPTE2MjEzODkzMzIwMDA7VURJRD1BQkNTOU9Oa2lSSkxCZkVxdkdTSVd2a2hzNU1Yb2Fpa3h2MD07ZGlzaz0xMjc4NzA5ODAwOTY7bWVtbz04MTgwMDU2MDY0O3N1dHM9MTYxNjgzMTE5MC41OTQ1ODg7ZG49OUE5Q0Y5N0U4RTBCMUY0N0Y2QzA4QkFDRTI1ODlGQUM7b3A95Lit5Zu96IGU6YCaO2NvdW50cnk9Q047c2J0cz0xNjE3MzIyNzE2O2xhbmc9emgtSGFucy1DTjs=
X-Ab-Param: 
Accept: */*
X-APP-VERSION: 7.11.1
Accept-Encoding: gzip, deflate, br
Content-Length: 508
x-close-recommend: 0
User-Agent: osee2unifiedRelease/4782 osee2unifiedReleaseVersion/7.11.1 Mozilla/5.0 (iPhone; CPU iPhone OS 14_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
X-ZST-82: 2.0AFBfCWOpIBMLAAAASwUAADIuMFlwpGAAAAAAtB2rz17UaL56wuig7e5zRJvellc=
X-AB-PB: 
Cookie:
X-Traffic-Free: 
X-APP-ZA: OS=iOS&Release=14.5.1&Model=iPhone13,2&VersionName=7.11.1&VersionCode=4782&Width=1170&Height=2532&DeviceType=Phone&Brand=Apple&OperatorType=46001
x-ad-styles: bv_r_sp=3;creative_form=3;pmi_8_f_d=9;canvas_scene=2;pv_8_f_d=11;canvas_image=2;pv_30_d=8;bv_r_24=10;canvas_multilevel_choice=1;bsi_r_pu=14;canvas_viewpager=1;canvas_form=14;pv_314=2;pbi_8_r_c=1;canvas_video=1;bv_8_r_o=6;pmi_8_f=9;canvas_text_choice=2;pmi_30=5;pii_31_d=2;canvas_phone_input=1;bv_f=17;pmi_30_d=5;sliding_8_r=1;pmi_8_r=10;pv_8_r_c=3;pw_8_f=13;pv_314_d=2;bv_r=19;canvas_page=3;bbi_r_24=9;bbi_31=1;bsi_f=14;pbi_8_f_d=10;pw_8_f_d=9;pw_8_r=18;creative_input=2;pv_8_f=17;pbi_30=6;canvas_text=2;canvas_input=6;pii_8_f_d=8;bsi_r=27;psi_8_r_d=16;bbi_r_sp=3;pii_8_f=10;pbi_8_f=10;canvas_imagetext=1;bl_8_r_y=3;pv_8_r=22;bp_r_24=10;bv_r_z=1;pw_30_d=7;pmi_8_r_d=11;bw_30=3;pii_8_r=13;pbi_8_r=17;canvas_button=3;bv_8_f_o=2;canvas_choice=4;pv_8_r_d=16;pii_30=6;bl_8_r_n=2;canvas_sliders=1;bsi_h=27;creative_page=2;ps_8_f=5;psi_8_f=14;pbi_31=5;bv_30_i=4;canvas_follow_button=2;pl_8_r_y=3;pbi_30_d=5;bmi_30=4;bv_30_o=4;canvas_image_choice=2;ps_8_r=2;pbi_8_r_d=13;psi_8_r=17;bmi_f=11;pv_30=8;canvas_image_option=2;bw_8_f=6;pii_8_r_d=12;bmi_r=18;bbi_f=13;ba=5;psi_8_f_d=12;pw_8_r_d=14;pl_8_r_n=2;canvas_text_option=2;pw_30=8;bw_8_r=11;pii_31=3;creative_text=1;pii_30_d=5;bbi_30=7;pbi_31_d=2;bbi_r=20;
X-PACKAGE-YTPE: appstore
Accept-Language: zh-Hans-CN;q=1
X-Network-Type: WiFi
X-ZST-81: ANBahzQctRI2RaRYpI7qNGEFQq1iCSIsjI_Fvg==
X-UDID: ABCS9ONkiRJLBfEqvGSIWvkhs5MXoaikxv0=
x-ad-sps: 
X-B3-Spanid: 3656A891FADB4942
x-zse-96: 1.0_vrab7paOMf4+wdI+w4eORt6kdVmoIvvaL2FCu2b7P9y698nZXw9o1HpIY6D+SEPJ
Authorization: Bearer 1.1wSZgAAAAAAALAAAAYAJVTUfTvmAKMkUhT32p-1fPnBvImHOXwG2NSQ==
X-APP-BUILD: release
X-API-VERSION: 3.0.93
Content-Type: application/json
X-B3-Traceid: 3656A891FADB4942
Connection: keep-alive
x-app-bundleid: com.zhihu.ios
x-zse-93: 101_2_1.0
X-MS-ID: D2bk5gykIqPeiGmAVLZM5U53Wt8k1AuKAJw6YPSo3o6acX71
X-APP-BUILD-VERSION: 4782
X-AD: canvas_version:v=5.1;setting:cad=0;

请求体
{
  "at" : "1",
  "author" : "LiHaiWei",
  "et" : "ad.3track",
  "msg" : "http://bj.imp.voiceads.cn/a/click?clickId=f4b656f1-688d-4d9f-b68f-f6393a022332-1621389356441&traceId=null&cp=%7B%22action_down_x%22%3A%22IT_CLK_PNT_DOWN_X%22%2C%22action_down_y%22%3A%22IT_CLK_PNT_DOWN_Y%22%2C%22action_up_x%22%3A%22IT_CLK_PNT_UP_X%22%2C%22action_up_y%22%3A%22IT_CLK_PNT_UP_Y%22%7D&inAId=44854&wPltId=256&wPltAdId=1AC9C2D0963AC8936E5552012BABCE5F&wPr=734_TflSUEY8GsFWOgXFUg: -1004 - 无法连接服务器。",
  "ev" : "bj.imp.voiceads.cn"
}

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
近期事情比较多，暂时没时间处理新的广告，建议先降级使用。

后面仔细看下是什么情况再继续回复你。

**Comment by WoodyLin** [comment]
> 近期事情比较多，暂时没时间处理新的广告，建议先降级使用。
> 
> 后面仔细看下是什么情况再继续回复你。

好的，谢谢大佬

**Comment by Paris0-0** [comment]
> 近期事情比较多，暂时没时间处理新的广告，建议先降级使用。
> 
> 后面仔细看下是什么情况再继续回复你。

降级了这里也还是有广告，估计是新的广告

**Comment by blackmatrix7** [comment]
我用的是

> > 近期事情比较多，暂时没时间处理新的广告，建议先降级使用。
> > 后面仔细看下是什么情况再继续回复你。
> 
> 降级了这里也还是有广告，估计是新的广告

我用的是6.60.0 2780，目前没有广告，你可以试试。

**Comment by Paris0-0** [comment]
哦我是6.70，有空试试

**Comment by XuuKoo** [comment]
> 
> 
> 我用的是
> 
> > > 近期事情比较多，暂时没时间处理新的广告，建议先降级使用。
> > > 后面仔细看下是什么情况再继续回复你。
> > 
> > 
> > 降级了这里也还是有广告，估计是新的广告
> 
> 我用的是6.60.0 2780，目前没有广告，你可以试试。

我这边测试有开屏广告。

**Comment by blackmatrix7** [comment]
已更新，如果有问题再反馈。
