### ISSUE TITLE
大佬，能否弄一个大陆 Anycast IP 表？

### ISSUE THREAD

**Issue by LisonFan** [blackmatrix7/ios_rule_script#336]
貌似没人做

为什么会提出这个想法呢？腾讯有个服务是 HTTPDNS，用的 119.29.29.29 这个 IP

相关文档：
https://cloud.tencent.com/document/product/379/3530
![image](https://user-images.githubusercontent.com/9424775/119231339-feb63b00-bb52-11eb-9dab-8033f4f54e35.png)

但是这个 IP 被 MAXMIND 标记成越南了

有这些 APP 用了腾讯这个 HTTPDNS 的服务
![image](https://user-images.githubusercontent.com/9424775/119231547-03c7ba00-bb54-11eb-8545-2e62ab462d93.png)
如果不手动单独写规则，119.29.29.29 就会走代理，解析出来的 CDN IP 就不对

还有这两个 IP 162.14.21.56 162.14.21.56
这两个 IP 是腾讯 DoH 服务 doh.pub 使用的 IP，也是 anycast 的 IP，但是被 MAXMIND 标记成香港了

所以就在想能否做一个大陆 Anycast IP 的规则

**Comment by blackmatrix7** [comment]
目前暂时没有足够的时间和精力去维护一套规则，所以很抱歉啊。

**Comment by LisonFan** [comment]
> 目前暂时没有足够的时间和精力去维护一套规则，所以很抱歉啊。

没事没事，我也就随口问问，大佬辛苦了。感谢大佬的这个项目。
