### ISSUE TITLE
请问下滴滴签到脚本的groupid应该如何获取

### ISSUE THREAD

**Issue by XuuKoo** [blackmatrix7/ios_rule_script#337]
按照文档token、activityid、channelid获取成功，但是groupid没有，执行签到脚本日志中提示：

09:05:06.735] console.log => [WARNING] [滴滴出行]
获取瓜分福利金活动明细果失败，响应异常：{"errno":101,"errmsg":"参数 group_id 缺失","traceid":"手工隐去","data":null}

[09:05:06.735] console.log => [WARNING] [滴滴出行]
获取瓜分福利金act_id失败

**Comment by blackmatrix7** [comment]
抓包看了下，group_id 可能是从响应体中去掉了。

等空下来重新做下适配，到时候我再回复你。

**Comment by XuuKoo** [comment]
> 抓包看了下，group_id 可能是从响应体中去掉了。
> 
> 
> 
> 等空下来重新做下适配，到时候我再回复你。

谢谢。

**Comment by blackmatrix7** [comment]
滴滴的签到接口已全改了，现在的脚本全部失效，后面找个时间再仔细看看，暂时没有办法处理找个问题了。

后面如果有更新会再回复你。
