### ISSUE TITLE
Quantumult X Gallery 联通附加组件 404

### ISSUE THREAD

**Issue by gee1k** [blackmatrix7/ios_rule_script#338]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：

APP版本：

客户端名称：

客户端版本：

问题描述：

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
晚些时候看下，可能没来得及更新。

**Comment by blackmatrix7** [comment]
已修复
