### ISSUE TITLE
饿了么脚本抓不到cookie了

### ISSUE THREAD

**Issue by XuuKoo** [blackmatrix7/ios_rule_script#339]
进吃货卡没有反应。
倒是这个脚本能抓：
script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemGetCookies.js,pattern=^https:\/\/h5\.ele\.me\/restapi\/eus\/v\d\/current_user$
但是 这个脚本抓到cookie本项目的脚本用不了，还是提示没有cookie。

**Comment by blackmatrix7** [comment]
已经修复
