### ISSUE TITLE
下面的规则集，导致钉钉的加班申请页面进不去，卡在顶部进度条。禁用这个规则就能进去

### ISSUE THREAD

**Issue by lxk0301** [blackmatrix7/ios_rule_script#34]
规则集： https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingLite/Domain.list

taobao.com类的域名都是返回0KB，

![image](https://user-images.githubusercontent.com/21308593/96578551-f3bed200-1307-11eb-83c2-14e82b833a09.png)

![image](https://user-images.githubusercontent.com/21308593/96578532-edc8f100-1307-11eb-845b-7a815df90c85.png)

![image](https://user-images.githubusercontent.com/21308593/96578630-10f3a080-1308-11eb-85aa-f33e1ec83eee.png)

![image](https://user-images.githubusercontent.com/21308593/96578640-151fbe00-1308-11eb-8c1e-f5aa1b3d2e2a.png)

**Comment by blackmatrix7** [comment]
实时版已经去除
