### ISSUE TITLE
知乎助手会导致知乎回答加载异常缓慢

### ISSUE THREAD

**Issue by Meonthb** [blackmatrix7/ios_rule_script#340]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：知乎助手Plus/Lite

APP版本：知乎 7.13.0

客户端名称：Surge

客户端版本：4.7.0

问题描述：开启知乎助手（无论是Plus还是Lite）后，回答页加载变得异常缓慢，相同的加载缓慢问题也出现在开启开屏去广告后的bilibili上。如果可以的话，能否提供只包含去开屏广告的知乎助手以提高性能？

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
知乎助手模块会拦截知乎回答的预加载，主要作用是避免预加载太多内容，减少付费内容、营销推广等回答的判断次数。

如果在网络情况不佳时，可能会导致回答加载缓慢。只拦截启动广告，你可以直接增加相关规则，不需要单独的模块。

`
DOMAIN,118.89.204.198,REJECT-DROP
IP-CIDR,118.89.204.198/32,REJECT-DROP,no-resolve
IP-CIDR6,2402:4e00:1200:ed00:0:9089:6dac:96b6/128,REJECT-DROP,no-resolve

^https?:\/\/api\.zhihu\.com\/(notifications\/v\d\/count|v\d\/package|me\/guides|drama\/living-info|ad|fringe|commercial|market\/popovers|.*featured-comment-ad) - reject
`
上面的正则，具体哪一条可以拦截启动广告，时间太久不太记得，你可以尝试看看。

至于B站的去广告，没有对视频的加载做任何处理，不会引擎加载缓慢的问题，推测可能是由于MITM相关域名导致，MITM是去广告的必要条件，无法去除。

**Comment by DomKing** [comment]
> 知乎助手模块会拦截知乎回答的预加载，主要作用是避免预加载太多内容，减少付费内容、营销推广等回答的判断次数。
> 
> 如果在网络情况不佳时，可能会导致回答加载缓慢。只拦截启动广告，你可以直接增加相关规则，不需要单独的模块。
> 
> `
> DOMAIN,118.89.204.198,REJECT-DROP
> IP-CIDR,118.89.204.198/32,REJECT-DROP,no-resolve
> IP-CIDR6,2402:4e00:1200:ed00:0:9089:6dac:96b6/128,REJECT-DROP,no-resolve
> 
> ^https?://api.zhihu.com/(notifications/v\d/count|v\d/package|me/guides|drama/living-info|ad|fringe|commercial|market/popovers|.*featured-comment-ad) - reject
> `
> 上面的正则，具体哪一条可以拦截启动广告，时间太久不太记得，你可以尝试看看。
> 
> 至于B站的去广告，没有对视频的加载做任何处理，不会引擎加载缓慢的问题，推测可能是由于MITM相关域名导致，MITM是去广告的必要条件，无法去除。

这个我也遇到了，不过不是回答加载异常缓慢，具体表现是，看了某个回答，下一条不会预加载。
其实在使用知乎时，看当前一条回答，下一条预加载出来会非常舒服。

我不太确定提 issue 的同学遇到的是回答列表加载慢，还是点开某一条加载慢，又或者像我一样，下一条不会预加载导致看下一条要重新发请求。

经过反复实验，我验证出来了，是这一条导致不会预加载下一条回答。
^https?:\/\/api\.zhihu\.com\/ab\/api\/v1\/products\/zhihu\/platforms\/ios\/config url reject-200

抓包看响应也没看出来这个请求到底返回的是什么。
