### ISSUE TITLE
万达电影的wanda_checkin_cookie无法正常获取了

### ISSUE THREAD

**Issue by N1rEn** [blackmatrix7/ios_rule_script#342]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：wanda_checkin.js

APP版本：7.2.0（我测试了近期所有的版本）

客户端名称：万达电影

客户端版本：最新的

问题描述：checkin cookie无法正常获取，activitycode正常。

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：否

**Comment by blackmatrix7** [comment]
提供下你使用的客户端和对应的版本，便于测试。

**Comment by N1rEn** [comment]
用的圈x， 版本1.0.21   
万达电影app的版本是7.2.0

**Comment by N1rEn** [comment]
大佬  万达您测试了吗？我是在boxjs里删除cookie之后，无法再获取了。

**Comment by blackmatrix7** [comment]
> 大佬 万达您测试了吗？我是在boxjs里删除cookie之后，无法再获取了。

最近事情太多，需要过段时间。

**Comment by gitehabu** [comment]
其实cookie你可以自己抓包填到boxjs的

**Comment by N1rEn** [comment]
cookie我抓到了  但是不会给boxjs里填……

**Comment by blackmatrix7** [comment]
![image](https://user-images.githubusercontent.com/27717518/120411959-46756780-c388-11eb-8e59-3cfb3c5f161d.jpeg)

刚刚测试了一下，可以正常获取Cookie。

建议先用空白配置文件检查下，避免重写之间的冲突之类的问题。

**Comment by blackmatrix7** [comment]
如果没有进一步反馈，我先关闭了，有问题你再回复。
