### ISSUE TITLE
请求调整 Global_Classical.yaml

### ISSUE THREAD

**Issue by JoinGitHubBa** [blackmatrix7/ios_rule_script#343]
规则名称：Global_Classical.yaml

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Global/Global_Classical.yaml

问题描述：iOS 上对于 VPN 应用有 15M 内存限制，规则数量过多会被系统强行终止进程，详情请参考[这篇文章](https://nssurge.zendesk.com/hc/zh-cn/articles/900000310366-Surge-iOS-%E7%89%88%E6%9C%AC%E5%86%85%E5%AD%98%E8%B6%85%E9%99%90%E9%97%AE%E9%A2%98%E7%9A%84%E8%AF%B4%E6%98%8E)。GFWlist 包含现在被墙的和曾经被墙的，其实大部分域名早已经不存在。

调整方案：不要集成 GFWlist ，只需要 TOPlist 。

另外，xxx_Classical.yaml 可以单独使用，其他规则必须同时使用。是不是说其它规则同时使用= xxx_Classical.yaml？如果是这样，“其它规则”是不是就没必要存在呢？

**Comment by blackmatrix7** [comment]
这个文件是用于Clash的，不是用于Surge的，你看下是不是用错了。

**Comment by JoinGitHubBa** [comment]
不好意思，我只是拿 Clash 举了个例子，不太严谨。

原理是一样的，Clash/Loon/Shadowrocket/Surge/Quantumult X 的 Global 相关部分规则，都包含了 GFWlist 。

可以在列表中随便取一段（10-20个）域名抽查一下，看看有几个域名是存在的。

**Comment by JoinGitHubBa** [comment]
GFWlist 和 dnsmasq-china-list 有太多无效域名。
v2ray-rules-dat 的思路不适合 Surge 类代理工具，很多网站或服务有国内版和国际版，而它们竟然在同一个列表里。

应该远离以上项目，或者基于以上项目的项目，比如 Loyalsoldier 大佬的规则。
刚刚还发现 Loyalsoldier 的规则里，有些域名同时存在于 proxy / direct 列表，比如 265.com 。

您的项目集合了多位大佬的规则，已经很精准了，除非各位大佬都用  DOMAIN-KEYWORD ，否则建议删除 DOMAIN-KEYWORD 规则，进一步减少误杀率。

个人理解 ，仅供参考。

**Comment by blackmatrix7** [comment]
这段时间对Global开启移除无法解析的DOAMIN规则的功能，实际效果不佳，大概只能减少30多条规则。

Global含有大量的DOMAIN-SUFFIX 类型的规则，这类规则没办法直接移除无法解析的域名，举个例子：

baidu.com可能无法解析，但是tieba.baidu.com是可以解析的，如果对DOMAIN-SUFFIX,baidu.com，直接判断baidu.com无法解析就进行移除，则会导致误删除。

所以暂时没有再做其他的调整。
