### ISSUE TITLE
Lan的相关规则中17.0.0.1/8不是常规的私有ip段，并且为苹果所有

### ISSUE THREAD

**Issue by Skyxim** [blackmatrix7/ios_rule_script#344]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Lan
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
异常规则：
  - IP-CIDR,17.0.0.0/8
问题描述：
苹果的相关域名会导致匹配上Lan规则
time.apple.com
doh.dns.apple.com
抓包截图：(相关抓包工具的截图。)
<img width="590" alt="image" src="https://user-images.githubusercontent.com/70276018/120067700-94038300-c0af-11eb-9f66-0495879ae955.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/70276018/120067706-9d8ceb00-c0af-11eb-9722-d6f01ae98ed0.png">

调整方案：(你希望规则做哪些调整，及其原因。)
可暂时只对acl4ssr进行收集，17.0.0.0/8来源为https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/LAN.list

**Comment by blackmatrix7** [comment]
已经更新
