### ISSUE TITLE
软件无法使用

### ISSUE THREAD

**Issue by junmoxio** [blackmatrix7/ios_rule_script#345]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：复写去广告(严格版)

APP版本：quanx 1.0.21

客户端名称：番茄小说

客户端版本：4.50

问题描述：会导致软件无法使用，初步查看是snssdk.com这类域名被关闭，还需大佬确认

复现方式：

1.打开软件
2. 无法使用

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
在MITM中增加  -reading.snssdk.com 规则进行排除

复写规则的更新需要过段时间，最近实在太忙了。

**Comment by junmoxio** [comment]
好的，大佬解决了回一下就行，单单屏蔽这个貌似不行，我把-*.snssdk.com全屏蔽了，等大佬解决吧

**Comment by blackmatrix7** [comment]
在AllInOne和AdvertisingLite做了严格的主机名过滤，你可以试试。
