### ISSUE TITLE
抖音 16.3.0 无法使用。

### ISSUE THREAD

**Issue by uclort** [blackmatrix7/ios_rule_script#347]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
rewrite ->  AllInOne

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/Surge/AllInOne/AllInOne.sgmodule

异常规则：

问题描述：
抖音昨天升级最新版之后无法使用了，所有网络连接不上，查看 Surge 请求记录显示 MITM 失败，下方有截图，尝试关闭 Rewrite 开关，抖音可以正常使用。

抓包截图：(相关抓包工具的截图。)
![IMG_2493](https://raw.githubusercontent.com/uclort/file/master/IMG_2493.PNG)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
先加一个-*.snssdk.com，把MITM去掉试试，过段时间会仔细看下哪个hostname mitm 失败了。

或者把miti失败的hostname发我下

**Comment by WoodyLin** [comment]
amemv.com这个排除下就好了…

**Comment by blackmatrix7** [comment]
AllInOne加入了hostname的严格过滤模式，会过滤掉如 *.baidu.com,baidu.com,*.com这类过域宽泛的域名，减少MITM的hostname数量，amemv.com因此也被移除了，可以更新试试。

**Comment by fiiir** [comment]
> AllInOne加入了hostname的严格过滤模式，会过滤掉如 `*.baidu.com,baidu.com,*.com`这类过域宽泛的域名，减少MITM的hostname数量，amemv.com因此也被移除了，可以更新试试。

同样的改动，能否也应用到“复写去广告(严格版)”等其他包含抖音rewrite规则的surge模块
这边观察到MITM Fail 的相关hostname是*.snssdk.com,*.amemv.com

**Comment by blackmatrix7** [comment]
> > AllInOne加入了hostname的严格过滤模式，会过滤掉如 `*.baidu.com,baidu.com,*.com`这类过域宽泛的域名，减少MITM的hostname数量，amemv.com因此也被移除了，可以更新试试。
> 
> 同样的改动，能否也应用到“复写去广告(严格版)”等其他包含抖音rewrite规则的surge模块
> 这边观察到MITM Fail 的相关hostname是*.snssdk.com,*.amemv.com

没发现有这两个MITM

**Comment by ziiilok** [comment]
使用了rule/Surge/AdvertisingLite
rewrite/Surge/Advertising
