### ISSUE TITLE
联通脚本无法再获取Cookie

### ISSUE THREAD

**Issue by lincanyi** [blackmatrix7/ios_rule_script#348]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/10010/unicom_signin.sgmodule

APP版本：
Surge4.7.0

客户端名称：
联通

客户端版本：
8.7.4

问题描述：
Cookie无法再获取

复现方式：

1.打开Surge，开启模块，重新开启Surge
2.进入联通，打开“签到抽奖”

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
更新到中国联通APP最新版本，测试了一下，是可以获取到Cookie的。

是在搜索栏搜索“天天抽奖”，而不是打开“签到抽奖”

你再核对一下，如果有问题再反馈。

**Comment by lincanyi** [comment]
可以啦～·～，谢谢大佬，不过我还发现另外一个问题，smzdm的脚本运行有时候会导致Surge内存报停，贼尴尬

**Comment by blackmatrix7** [comment]
有相应的错误日志吗？
