### ISSUE TITLE
Advertising.list中有规则会导致YouTube去广告失效

### ISSUE THREAD

**Issue by ftnice** [blackmatrix7/ios_rule_script#35]
不知道其中哪条规则会导致YouTube去广告模块失效黑屏
规则：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list
模块：https://gist.githubusercontent.com/codexss/9810d7f12bed2bc53eb4a19240e7fa17/raw/YouTube.sgmodule

**Comment by littlegyn** [comment]
确实会 但另一个设备在quantumultX同样添加了ADlist 却可以去油管广告（最新版）

**Comment by blackmatrix7** [comment]
可能要确定到哪一条有问题才好去除，我搜索了下含有googlevideo的规则已经没有了。含有YouTube的规则太多，我不怎么用YouTube，不太好确定是哪条的问题。

**Comment by jwojw** [comment]
怎么取消QQ邮箱的订阅？ 邮箱一直来邮件

**Comment by blackmatrix7** [comment]
> 怎么取消QQ邮箱的订阅？ 邮箱一直来邮件

试试unwatch

**Comment by blackmatrix7** [comment]
没有进一步反馈就暂时关闭了
