### ISSUE TITLE
更新Surge至4.8.0之后,运行联通签到脚本报错

### ISSUE THREAD

**Issue by lincanyi** [blackmatrix7/ios_rule_script#350]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/10010/unicom_signin.sgmodule

APP版本：
Surge4.8.0

客户端名称：
联通

客户端版本：
8.7.4

问题描述：
运行签到脚本，报错Token的json解析异常

复现方式：

1. 获取联通天天签到Cookie提示成功
2. 在脚本编辑器执行联通签到脚本

已使用空白配置文件验证：是

截图:
![telegram-cloud-photo-size-1-5066990077388892733-y](https://user-images.githubusercontent.com/46511674/122150391-341f2180-ce90-11eb-85f0-d791b2cca038.jpg)
![telegram-cloud-photo-size-1-5066990077388892734-y](https://user-images.githubusercontent.com/46511674/122150397-38e3d580-ce90-11eb-8e41-12db7f2e534f.jpg)

**Comment by blackmatrix7** [comment]
这个是联通偶尔返回的响应体不是JSON，导致解析JSON失败，避开高峰期签到，多试试。

后面考虑加个异常捕获，弹出签到失败的通知。

**Comment by blackmatrix7** [comment]
看了下，是抽奖的部分出错，后面抓包看下什么情况，改完再回复你。

**Comment by blackmatrix7** [comment]
已经修复。
