### ISSUE TITLE
百度开放平台 Advertising_Domain.list 误杀

### ISSUE THREAD

**Issue by uclort** [blackmatrix7/ios_rule_script#351]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Advertising_Domain.list

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising_Domain.list

异常规则：
.bce.baidu.com

问题描述：
百度开放平台的地址 console.bce.baidu.com，被直接 reject，无法正常打开

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
谢谢反馈，已加到过滤器，请等待明天凌晨自动更新。

**Comment by uclort** [comment]
> 谢谢反馈，已加到过滤器，请等待明天凌晨自动更新。

你好，新发现误杀百度定位 `loc.map.baidu.com:443` 域名，造成和风天气无法正常定位，
规则位置：
`DOMAIN-SET Advertising_Domain.list`
---
![image](https://user-images.githubusercontent.com/17818831/124345548-28f81f80-dc0c-11eb-90a6-18da23584ad5.png)
