### ISSUE TITLE
万达电影无法获取Cookie

### ISSUE THREAD

**Issue by kanjianjiuhao** [blackmatrix7/ios_rule_script#352]
脚本名称：Quantumult X 

APP版本：v1.0.22-564

客户端名称：万达电影 

客户端版本：v7.2.2

问题描述：
在Issues里找到已经关闭的问题，出现的是同样的问题，摸着那哥们的尝试使用空白配置（https://github.com/blackmatrix7/ios_rule_script/issues/342#issue-903537183）
也是出现的两样问题：只能获取ActivityCode，但无法获取Cookie。使用本库的万达签到脚本，执行时提示没有获取到Cookie

复现方式：
1、尝试网络WIFI、流量形式都是一样
2、更换了微信和手机号登陆也一样
3、删除应用再重装安装，也仍是只能获取ActivityCode

已使用空白配置文件验证：是

**Comment by 799953468** [comment]
+1 app-我的无法获取cookie

**Comment by blackmatrix7** [comment]
不好意思，QuanX和Loon的配置忘记更新了……

现在更新了一下，应该好了，你们再试试，如果有问题再反馈。

**Comment by kanjianjiuhao** [comment]
> 不好意思，QuanX和Loon的配置忘记更新了……
> 
> 现在更新了一下，应该好了，你们再试试，如果有问题再反馈。

辛苦啦，已经正常获取
已经能看到提示“今日已签到过了”，搞定！
多谢^_^
