### ISSUE TITLE
最近换了个华为手机，可有继续用脚本的方法？

### ISSUE THREAD

**Issue by yunv7** [blackmatrix7/ios_rule_script#353]
我只是用什么值得买的签到，但是安卓上没有圈x，看主页说用nodejs也行，可有流程？

**Comment by blackmatrix7** [comment]
参考下https://github.com/blackmatrix7/ios_rule_script/issues/56

这类说明了cookie的配置方式，但是如何运行，因为我很久不使用安卓了，并不太清楚，可能需要你自己研究一下。
