### ISSUE TITLE
Loon的哔哩哔哩脚本异常

### ISSUE THREAD

**Issue by xaver985** [blackmatrix7/ios_rule_script#355]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：
bilibili_plus.js
APP版本：
Loon 2.1.11(299)
客户端名称：
哔哩哔哩
客户端版本：
6.30.0
问题描述：
每次使用Loon的AllInOne插件点进B站UP主详情页面时第一次会什么也不显示，重复两次后再点进去就会闪退，除此之外，还有很高概率会掉登陆，需要重新登陆，具体原因不明
复现方式：
不光6.30.0这个版本，前面几个版本都有这问题

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
BiliBili这个已经停止维护了，不过我抽空测试看看吧。

**Comment by xaver985** [comment]
> BiliBili这个已经停止维护了，不过我抽空测试看看吧。

感谢大佬
这两天已经掉了两次登录了，日志里什么也没有，我也不知道什么原因

**Comment by xaver985** [comment]
刚才Loon更新了TF版，解决了bug，不用再麻烦大佬了
