### ISSUE TITLE
Bark推送什么值得买签到通知失败。

### ISSUE THREAD

**Issue by Alwaysbesideyou** [blackmatrix7/ios_rule_script#359]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：smzdm_signin.js

APP版本：

客户端名称：QX

客户端版本：1.0.22

问题描述：什么值得买在QX上签到成功后无法通过Bark推送到另一个设备。

复现方式：

1. Bark链接写入QX
2. 执行脚本

已使用空白配置文件验证：是

这时执行脚本后访问的链接：
https://api.day.app/jaggastehyoxenyh/什么值得买%20-%20xxx%20V6/Web端重复签到%20%20已签4天%0A积分2324%20经验20180%20金币55%0A碎银子175%20未读消息0%0A点值%207/7%20去购买%200/0%0A点赞%207/7%20收藏%207/7%0A用户近期经验变动情况(有延迟)：%0A11小时前%20每日登录%20+1经验值%0A11小时前%20每日签到%20+2经验值%0A12小时前%20收藏文章%20+8经验值%0A12小时前%20点赞文章%20+3经验值%0A12小时前%20收藏文章%20+8经验值%0A12小时前%20点赞文章%20+3经验值%0A12小时前%20收藏文章%20+8经验值%0A12小时前%20点赞文章%20+3经验值%0A12小时前%20收藏文章%20+8经验值%0A12小时前%20点赞文章%20+3经验值%0A12小时前%20点赞文章%20+3经验值%0A12小时前%20收藏文章%20+8经验值%0A12小时前%20好价文章打分%20+3经验值%0A12小时前%20好价文章打分%20+3经验值%0A12小时前%20好价文章打分%20+3经验值%0A12小时前%20好价文章打分%20+3经验值%0A12小时前%20好价文章打分%20+3经验值%0A22小时前%20昨日点击去购买奖励%20+10经验值%0A07-04%2000:25%20每日登录%20+1经验值%0A07-04%2000:15%20每日签到%20+2经验值%0A如经验值无变动，请更新Cookie%E3%80%82

把上述连接缩短到一定程度可以完成推送。可能是Bark的字数限制。

**Comment by blackmatrix7** [comment]
最近事情实在太多了，后面改成v2版本，用post请求试试，先鸽一段时间。

**Comment by blackmatrix7** [comment]
已支持v2接口推送
