### ISSUE TITLE
能否提供一个Mitm.sgmodule

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#36]
发现Advertising.sgmodule
与AdvertisingTest.list中的URL-REGEX类规则相同
能否提供一个Mitm.sgmodule

**Comment by fiiir** [comment]
好像没表达清楚，所说的Mitm.sgmodule文件内容是：

[MITM]
hostname = %APPEND% *.126.net,*.127.net,*.amap.com,*.amemv.com,*.atm.youku.com,*.baidu.com……

使AdvertisingTest.list中的URL-REGEX类规则可以生效

**Comment by blackmatrix7** [comment]
这个逻辑现在就是有的，在生成复写规则的MITM时，会采集同名分流规则下的URL-REGEX，算法反推主机名，进行补充和完善。
如果同时使用去广告的分流规则和复写规则，应该是会生效的。

**Comment by fiiir** [comment]
> 这个逻辑现在就是有的，在生成复写规则的MITM时，会采集同名分流规则下的URL-REGEX，算法反推主机名，进行补充和完善。
> 如果同时使用去广告的分流规则和复写规则，应该是会生效的。

问题是Advertising.sgmodule与AdvertisingTest.list中的URL-REGEX类规则是一样的，不就同一个规则匹配了两次吗？
等于有一次匹配是多出来的

**Comment by blackmatrix7** [comment]
URL-REGEX过滤掉请求后，就不会再触发复写了吧，我是这么理解的。

**Comment by fiiir** [comment]
> URL-REGEX过滤掉请求后，就不会再触发复写了吧，我是这么理解的。

是这样的，不考虑性能的前提下，如果有人单独使用了list，而没有导入那个模块，等于所有URL-REGEX规则都不起作用
是不是把list中的URL-REGEX规则去掉，在readme中加入提醒，提示list配合模块食用这样比较合理的样子？

**Comment by blackmatrix7** [comment]
已经加入。
