### ISSUE TITLE
Download规则集增加Ubisoft客户端下载规则

### ISSUE THREAD

**Issue by IvorkChan** [blackmatrix7/ios_rule_script#360]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Download

规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Download

异常规则：

问题描述：
添加Ubi相关规则后下载也会直接走代理，想了下比较好的解决方式应该是在Download里加上？

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
Download里添加：
- DOMAIN-SUFFIX,cdn.ubi.com

**Comment by blackmatrix7** [comment]
这个从域名上看是CDN服务器，不一定只用于下载，所以直接加入到Download可能并不合适。

客户端下载或者更新游戏并非高频操作，建议临时修改下应用的策略为DIRECT。
