### ISSUE TITLE
隐私保护误杀

### ISSUE THREAD

**Issue by BaileyZyp** [blackmatrix7/ios_rule_script#362]
规则名称：Privacy

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Privacy/Privacy_Domain.list

异常规则：https://github.com/blackmatrix7/ios_rule_script/blob/c549b14f065adca3d886047c2b6a591dc6cd3612/rule/Surge/Privacy/Privacy_Domain.list#L6048

问题描述：这条规则直接导致杭州银行主页白屏

抓包截图：
![7313FC3B-7210-427A-B661-F2F031BB3371](https://user-images.githubusercontent.com/16634459/124923689-49214780-e02d-11eb-9af0-8c5fa0a03f72.png)

调整方案：这条域名加个白名单或者加个杭州银行的分流规则吧

**Comment by BaileyZyp** [comment]
要么直接卡在启动页面，要么主页白屏

**Comment by blackmatrix7** [comment]
谢谢反馈，已经更新去掉了。
