### ISSUE TITLE
Apple规则影响阿里云域名

### ISSUE THREAD

**Issue by luoqz9** [blackmatrix7/ios_rule_script#363]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：Surge Apple List
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list
APP版本：4.11.0（1955）

客户端名称：Surge

客户端版本：

问题描述：
DOMAIN-KEYWORD,icloud
规则导致阿里域名alicloudccp.com
等一系列非Apple域名被加入

复现方式：

1. 阿里云盘下载 抓包
2. ………………

已使用空白配置文件验证：是

**Comment by luoqz9** [comment]
![Uploading 0E31076F-EB29-4735-B5F9-FF84CE0F4C5A.jpeg…]()

**Comment by luoqz9** [comment]
![50671B85-FCF5-4561-98E3-60893130CB49](https://user-images.githubusercontent.com/65555676/125116947-1146fc80-e120-11eb-92fe-110a3325ab84.jpeg)

**Comment by blackmatrix7** [comment]
谢谢反馈，已经更新去掉了。
