### ISSUE TITLE
复写规则问题

### ISSUE THREAD

**Issue by DecoAri** [blackmatrix7/ios_rule_script#364]
重写去广告surge的module里面 广告和广告lite都有同一条或几条影响了surge mac 和 adguard共存。测试下了 adg和surge什么都不需要设置 只要关闭这个module就能共存，否则adg会失效。

重写的url：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/Advertising/Advertising.sgmodule

**Comment by blackmatrix7** [comment]
这个可能不太好处理，主要是我的Macbook很老了，Surge Mac也一直停留在2.0版本，没办法复现这个问题，只能先鸽着。

等什么时候苹果发布下一代的Macbook，我买一台再来测试验证……

issue先开着，等能解决或者确定没办法解决再回复你。

**Comment by DecoAri** [comment]
好的谢谢

**Comment by blackmatrix7** [comment]
已快一年，请问下现在问题是否还存在？？？

**Comment by DecoAri** [comment]
不好意思，由于之前那个问题我已经很久没怎么用那个规则了，就没注意了
