### ISSUE TITLE
新的 ChinaIPs 项目

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#365]
相关项目：
https://github.com/misakaio/chnroutes2

比现有的ChinaIPs更小巧，收集ip的方式也大不相同
也许可以考虑不并入ChinaIPs，改为新设立一个ChinaIPs_chnroutes2 ？

**Comment by blackmatrix7** [comment]
已经加入了
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/ChinaIPsBGP/ChinaIPsBGP.list
