### ISSUE TITLE
Clash 的去广告规则会导致百度相关站点访问错误

### ISSUE THREAD

**Issue by MichaelPan1026** [blackmatrix7/ios_rule_script#367]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising_Classical.yaml

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Advertising/Advertising_Classical.yaml

异常规则：关于`shifen.com`的域名

问题描述：百度主站，百度贴吧访问错误

![圖片](https://user-images.githubusercontent.com/26241105/125482990-bc882d95-1d63-48f6-b03f-d61f1de876e7.png)

**Comment by blackmatrix7** [comment]
谢谢反馈，已经去掉了。
