### ISSUE TITLE
Oracle规则里放的是ebay的规则

### ISSUE THREAD

**Issue by Redeembynight** [blackmatrix7/ios_rule_script#369]
规则名称：Oracle

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Oracle/Oracle.list

问题描述：Oracle规则里放的是ebay的规则

**Comment by blackmatrix7** [comment]
谢谢反馈，看了下上游的数据的确是错的，暂时先把这个规则去掉了，以免误导大家，后续看情况再加回来。
