### ISSUE TITLE
考虑整合GetCookie为一个文件麽？

### ISSUE THREAD

**Issue by TsXcd** [blackmatrix7/ios_rule_script#37]
感谢大佬的整理，像选用多个脚本，但从描述看各个功能的GetCookie脚本均为分散 quanx得挨个添加打开并关闭，能否将已收录的所有脚本的GetCookie整合为一个便于开关调用呢？

**Comment by blackmatrix7** [comment]
暂时没有这个计划。因为我认为整合成一个大而全的获取Cookie文件，对于只需要部分脚本的人来说会带来不必要的复写，并且在还有同类签到脚本的情况下容易带来意料之外的问题。

这类的复写改动很少，建议按自己需求整合一下。
