### ISSUE TITLE
知乎助手在观看视频流时候出错，视频和评论无法对应。

### ISSUE THREAD

**Issue by yzxj3180** [blackmatrix7/ios_rule_script#370]
下滑下个视频时，评论内容还是上个视频的。
知乎是最新版本，脚本也更新过了，关闭脚本后恢复正常。
![3ADBE411-68DB-468E-97B0-00DE23965499](https://user-images.githubusercontent.com/42795396/125969123-3679c704-b6b9-498b-b816-7b48f9c54e51.png)

**Comment by blackmatrix7** [comment]
最近暂时没时间维护脚本，建议先退回旧版试试。

issue先开着，有时间处理我再回复你……

**Comment by blackmatrix7** [comment]
试了下，更新到最新版本也没有复现这个问题。

麻烦给下版本号和操作步骤。

**Comment by blackmatrix7** [comment]
再次测试无法复现此问题，如果没有再出现我先关闭了，有问题你再回复。
