### ISSUE TITLE
关于shadowrocket规则里的IP-CIDR6,PROCESS-NAME

### ISSUE THREAD

**Issue by btinfo** [blackmatrix7/ios_rule_script#372]
规则名称：
rule/Shadowrocket/*/*.list
规则链接：

问题描述：
IP-CIDR6,PROCESS-NAME选项在shadowrocket里是不支持的。

$ grep -E "^IP-CIDR6|^PROCESS-NAME" rule/Shadowrocket/*/*.list | wc -l
227

调整方案：(你希望规则做哪些调整，及其原因。)
替换 IP-CIDR6 > IP-CIDR
删除 PROCESS-NAME

**Comment by blackmatrix7** [comment]
Shadowrocket的 IP-CIDR 包括 IPV6吗？

**Comment by btinfo** [comment]
> Shadowrocket的 IP-CIDR 包括 IPV6吗？

最新版本里 IP-CIDR 是通用于 V4 和 V6的。
V6格式如： IP-CIDR,2001:67c:4e8::/48,PROXY,no-resolve

**Comment by blackmatrix7** [comment]
谢谢反馈，已经修复了。
