### ISSUE TITLE
为clash相关规则添加no-resolve

### ISSUE THREAD

**Issue by jenniferak** [blackmatrix7/ios_rule_script#374]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：clash下的Twitter,Facebook

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml

异常规则：
![1](https://user-images.githubusercontent.com/70758954/127582816-63b71f38-37a6-417f-b884-3d04afe65618.png)
![2](https://user-images.githubusercontent.com/70758954/127582833-3d2b7cce-cc9b-4335-8903-b262c0767e6d.png)

问题描述：dropbox相关连接有时会被匹配到Twitter和Facebook的分流规则，为了找到异常规则，我将Twitter和Facebook的规则放在本地，写了一个完整的配置文件，发现匹配错误的都是IP-CIDR类型。猜测可能与no-resolve有关，手动在配置文件中为相关规则添加后，再次测试dropbox相关连接，多次测试均为再次出现规则匹配错误问题。

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
为涉及到IP-CIDR类型的规则添加no-resolve，发现Surge，Loon，Shadowrocket均提供了有no-resolve和没有的两个版本，clash也可以提供两个。QuantumultX也没有no-resolve，同样可以添加上，同时提供两个版本。

**Comment by blackmatrix7** [comment]
下周看看有没有时间加这个功能

**Comment by blackmatrix7** [comment]
已经加入。
