### ISSUE TITLE
以去广告为主的surge脚本集合

### ISSUE THREAD

**Issue by tomektse** [blackmatrix7/ios_rule_script#378]
https://github.com/yjqiang/surge_scripts/tree/main

**Comment by blackmatrix7** [comment]
谢谢提供，目前处理如下：
1. 虎扑的去广告合并入去广告复写Advertising
2. 微博的需要较晚的时候测试是否正常工作再考虑添加
3. 百度网盘涉及破解不打算加入
4. B站和知乎和现有脚本重复
5. Youtube不打算加入
6. 爱奇艺已经有了

综上，等待验证微博脚本效果后处理，不过近期事情实在太多，验证时间可能会延后比较久。
