### ISSUE TITLE
中国域名备案网站被错误收入 Global_Domain 规则

### ISSUE THREAD

**Issue by luoqz9** [blackmatrix7/ios_rule_script#379]
规则名称： Surge/Global/Global_Domain.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_Domain.list

异常规则：.www.beian.gov.cn

问题描述：不属于Global范畴，并且近期境外此域名被 DNS 污染至非法 IP ，导致触发代理审查规则，不能访问。

抓包截图：(相关抓包工具的截图。)
<img width="480" alt="截屏2021-08-13 下午3 05 36" src="https://user-images.githubusercontent.com/65555676/129318181-3d38aaf5-4b69-4f99-96be-369a0a2990ad.png">

调整方案：删除该规则

**Comment by blackmatrix7** [comment]
收到，已去除。
