### ISSUE TITLE
music.126.net 屏蔽错误

### ISSUE THREAD

**Issue by Kosette** [blackmatrix7/ios_rule_script#380]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
rewrite/Surge/Advertising整个系列

规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/AdvertisingLite

异常规则：
`^https?:\/\/p[^4](c)?\.music\.126\.net\/\w+==\/10995\d{13}\.jpg$ data="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/blank/blank.gif"`

问题描述：
此条规则屏蔽了诸如 `p(1|2).music.126.net` 这样的域名，但Filebox之类的app需要向该域名请求专辑的封面图，此外该目录下的文件中多处出现`music.126.net`或者`126.net`这样的写法，应改为`music\.126\.net`。

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
`p*.music.126.net` 域名被屏蔽不知出于什么原因，如果要保留需改成`^https?:\/\/p[^124](c)?\.music\.126\.net\/\w+==\/10995\d{13}\.jpg$ data="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/blank/blank.gif"`，此外文件中多处域名中的"."没有被正确转义的应当正确处理

**Comment by Kosette** [comment]
又发现了一条`^https?:\/\/p\d\.music\.126\.net\/\w+==\/\d+\.jpg$ - reject` ，实在没时间一条条排查，暂时把module禁用了

**Comment by blackmatrix7** [comment]
谢谢反馈，已经做调整。
