### ISSUE TITLE
什么值得买的脚本，app签到失效了

### ISSUE THREAD

**Issue by lxr760** [blackmatrix7/ios_rule_script#381]
https://github.com/blackmatrix7/ios_rule_script/tree/master/script/smzdm

web签到正常，但是app签到报错    无法签到成功

**Comment by blackmatrix7** [comment]
已知问题，目前APP签到是没办法用了，近期会先去掉。

**Comment by lxr760** [comment]
> 已知问题，目前APP签到是没办法用了，近期会先去掉。

请问是app加密了还是什么原因？

**Comment by blackmatrix7** [comment]
具体还没时间看，估计是接口变化吧，最近事情实在太多，挤不出时间去弄这些脚本。

**Comment by blackmatrix7** [comment]
可能是接口有变化，此功能已暂时屏蔽掉。
