### ISSUE TITLE
connect.rom.miui.com 误封

### ISSUE THREAD

**Issue by chenyiping1995** [blackmatrix7/ios_rule_script#382]
**规则名称**
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml

**异常规则**
connect.rom.miui.com

**问题描述**
该域名被 MIUI 用于探测是否需要弹出登录窗口。具体测试路径是 http://connect.rom.miui.com/generate_204 或 https://connect.rom.miui.com/generate_204。

此链接的作用基本同 http(s)://www.gstatic.com/generate_204

**抓包截图**
![image](https://user-images.githubusercontent.com/16564295/129875354-c873fcfa-f637-454a-b294-91b9f5d65b7a.png)

**调整方案**
从规则中删除该域名，或将其添加至 Whitelist。

**Comment by blackmatrix7** [comment]
谢谢反馈，已更新。
