### ISSUE TITLE
知乎首页精选中推荐的视频播放错误

### ISSUE THREAD

**Issue by yxFeb3** [blackmatrix7/ios_rule_script#383]
部分知乎推荐的视频进去会出现不能播放的情况，不知道大佬有没有解决办法![image](https://user-images.githubusercontent.com/88957527/130177069-43d07fda-f628-4046-9975-6fe57e635292.png)

**Comment by blackmatrix7** [comment]
已修复，你看下。

**Comment by yxFeb3** [comment]
可以了 感谢！
