### ISSUE TITLE
去广告复写导致 江苏移动掌厅 无法显示当月热销

### ISSUE THREAD

**Issue by Redeembynight** [blackmatrix7/ios_rule_script#384]
规则名称：AdvertisingLite.conf

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AdvertisingLite/AdvertisingLite.conf

异常规则：^https?:\/\/wap\.js\.10086\.cn\/jsmccClient\/cd\/market_content\/api\/v\d\/market_content\.page\.query url reject

问题描述：江苏移动掌厅 无法显示当月热销
主机名加-wap.js.10086.cn后正常显示

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
能否提供下进入当月热销的操作步骤，以及抓包数据截图。

我没有移动的号，目前用联通的进入后，找不到你说的这个功能，比较难验证。

**Comment by Redeembynight** [comment]
正常显示
![17CC0150-CFF2-40AF-8F14-249E52117456](https://user-images.githubusercontent.com/64399359/130187088-661b458e-b047-43f2-8efd-cdb318475a90.jpeg)
复写命中后，无法显示
![25EB043F-73BE-4828-A203-72467FC5072F](https://user-images.githubusercontent.com/64399359/130187128-08335a6b-fb16-4c40-84fc-620c5125ce7d.jpeg)
![5ED1C44D-8180-4FF7-84F6-1DC13C549E8E](https://user-images.githubusercontent.com/64399359/130187143-59c70d6b-2a9c-4df8-9784-506bc88e06bc.png)

**Comment by blackmatrix7** [comment]
可能因为我不是移动账号的关系，登录后也不显示这个按钮，不太好测试。

我先去掉了，你试试看，如果可用解决麻烦回复我一下，谢谢。

**Comment by Redeembynight** [comment]
可解决
