### ISSUE TITLE
Surge加载知乎助手Lite版模块似乎没有效果

### ISSUE THREAD

**Issue by solymr** [blackmatrix7/ios_rule_script#385]
脚本名称：
知乎助手Lite版本的Surge模块：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.sgmodule

APP版本：
知乎 iOS 版 7.25.0 (6218)

客户端名称：
Surge

客户端版本：
4.9.1 (Build 1989)

问题描述：
Surge加载知乎助手Lite版模块似乎没有效果。例如开屏广告和关注页、推荐页的广告都还在。

复现方式：
1. 登录国区apple id，卸载并安装知乎，运行，登录后关闭后台
2. 登录美区apple id，卸载并安装Surge
3. 打开Surge，首页-模块，安装新模块，输入：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.sgmodule
4. 按提示更新下脚本资源，勾选该安装的模块，右上角点击完成，右上角点击启动
5. 打开知乎，仍然能看到开屏广告和关注页、推荐页广告

以上操作之外还尝试将模块内容直接作为配置文件、使用另一个issue中提到的知乎相关模块：https://raw.githubusercontent.com/yjqiang/surge_scripts/main/modules/zhihu/zhihu.sgmodule
新建空白配置文件后重试等，均无效。

通过抓取流量分析，在其中搜索118.89.204.198这个地址，可以看到少量80端口和443端口的请求，结果都是REJECT-DROP，但是80端口的是红色的TCP标签，状态为失败；443端口的是蓝色的HTTPS标签，状态为已完成。不知道是不是这代表着443端口的请求没有被过滤导致？但我看备注里面提示了Dropped by rule呀。

不知道是哪里的问题。本人新手，诚心求教！

**Comment by blackmatrix7** [comment]
能否提供下Surge的脚本执行日志？

**Comment by solymr** [comment]
截取了一段日志，见附件

[2021-09-03-145414.log](https://github.com/blackmatrix7/ios_rule_script/files/7103888/2021-09-03-145414.log)

**Comment by blackmatrix7** [comment]
不好意思，事情实在太多，不能及时回复。

麻烦你把配置文件脱敏发一份我测试下吧。

**Comment by solymr** [comment]
ok，配置文件之前就是空白配置加一个MitM设置，没有别的设置。

不过最近Surge更新了版本，好像多了一些其他的默认配置。我抽空晚点重置以后再测试更新一下吧

**Comment by solymr** [comment]
重新测试了一下，保存了log和配置文件，如下（配置文件后缀由conf改成了txt，里面的MitM具体参数改成了XXXXX）：
[2021-09-15-093113.log](https://github.com/blackmatrix7/ios_rule_script/files/7166024/2021-09-15-093113.log)
[blank.txt](https://github.com/blackmatrix7/ios_rule_script/files/7166026/blank.txt)
知乎版本7.27.0（最新的是7.28.0，我没有更新）
Surge版本4.9.2，配置中就启用了plus模块和MitM。
请参考。

目前发现的情况是，除了开屏广告可以正常屏蔽，其他页面，比如关注页、推荐页、问题页都还是有广告的。有些广告直接在知乎里打开，有些广告会直接跳转到微信打开小程序。

**Comment by blackmatrix7** [comment]
> 重新测试了一下，保存了log和配置文件，如下（配置文件后缀由conf改成了txt，里面的MitM具体参数改成了XXXXX）： [2021-09-15-093113.log](https://github.com/blackmatrix7/ios_rule_script/files/7166024/2021-09-15-093113.log) [blank.txt](https://github.com/blackmatrix7/ios_rule_script/files/7166026/blank.txt) 知乎版本7.27.0（最新的是7.28.0，我没有更新） Surge版本4.9.2，配置中就启用了plus模块和MitM。 请参考。
> 
> 目前发现的情况是，除了开屏广告可以正常屏蔽，其他页面，比如关注页、推荐页、问题页都还是有广告的。有些广告直接在知乎里打开，有些广告会直接跳转到微信打开小程序。

更新了知乎助手，支持BoxJS，你可以试试新版。
