### ISSUE TITLE
关于Advertising.list中规则的反馈及建议

### ISSUE THREAD

**Issue by yfue** [blackmatrix7/ios_rule_script#386]
名称：Advertising.list

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/Advertising/Advertising.list

异常规则：URL-REGEX ^https?:\/\/c\.tieba\.baidu\.com\/\w+\/\w+\/(sync|newRnSync|newlog|mlog)

问题描述：该条规则会拦截http://c.tieba.baidu.com/c/s/newlog导致其疯狂重连，甚至导致surge卡死。
由于目前贴吧广告使用protobuf协议，单靠这条规则是没有作用的，建议删除

**Comment by blackmatrix7** [comment]
之前已经丢到Map Local里了，如果没有其他问题我就先关闭了。

**Comment by godlikeanyone** [comment]
这个规则在https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf里依然存在，会导致贴吧疯狂请求newlog
