### ISSUE TITLE
关于广告规则导致多看阅读不能在线阅读问题

### ISSUE THREAD

**Issue by huang-yoshio** [blackmatrix7/ios_rule_script#388]
规则名称：Advertising_Domain

规则链接：https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Surge/Advertising/Advertising_Domain.list

异常规则：file.market.xiaomi.com

问题描述：该域名有获取文章内容的请求 `http://file.market.xiaomi.com/download/Duokan/...` ，屏蔽该域名导致不能在线看书

调整方案：在未确定该域名下是否存在广告与隐私跟踪的情况下，建议额外加修复规则
`URL-REGEX,^https?:\/\/file\.market\.xiaomi\.com\/download\/Duokan/\w{41},DIRECT`

**Comment by blackmatrix7** [comment]
请问是哪个APP？麻烦提供一下我测试。

**Comment by huang-yoshio** [comment]
> 请问是哪个APP？麻烦提供一下我测试。

多看阅读

**Comment by blackmatrix7** [comment]
已经取消了，你看下。
