### ISSUE TITLE
Advertising去广告规则导致淘宝支付宝内的商品跳转链接打开失败

### ISSUE THREAD

**Issue by Kendarou** [blackmatrix7/ios_rule_script#39]
click.mz.simba.taobao.com这个域名被屏蔽，手动放行后并无可感知的广告出现。此问题在前段时间ACL4SSR广告规则项目下反馈过，被修正了。
https://github.com/ACL4SSR/ACL4SSR/issues/426

**Comment by blackmatrix7** [comment]
如果修正过我这里还有，说明其他数据源还存在这条规则，晚点我把它加入黑名单重新生成一下就好了。

**Comment by blackmatrix7** [comment]
实时版已经去掉了
