### ISSUE TITLE
关于小火箭去广告规则中复写规则与其它app复写去广告规则的差异

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#390]
规则名称：

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising.list
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising_Domain.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/Advertising/Advertising_Classical.sgmodule
异常规则：

问题描述：
小火箭去广告规则中的复写规则与其它app（如Surge）的复写去广告规则相差有点大，不知道为什么有这种差异呢
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
小火箭我基本上没怎么用，只是顺便做下支持，目前没有收到规则有错的反馈。

如果你不能使用，可用具体说明下情况。

**Comment by JOJOforshaun** [comment]
> 小火箭我基本上没怎么用，只是顺便做下支持，目前没有收到规则有错的反馈。
> 
> 如果你不能使用，可用具体说明下情况。

不是说不能用啦，就是小火箭的去广告规则的复写规则条数比surge的复写去广告少很多捏，就是希望能合并一下

**Comment by blackmatrix7** [comment]
我看了下，数量差距不大，只少了IP-CIDR6。

原先小火箭的数量统计有点问题，会把IP-CIDR6的规则数量写成IP-CIDR，不过不影响使用。

已修复，明天凌晨应该会自动更新。
