### ISSUE TITLE
知乎助手plus和TikTok去水印冲突导致知乎评论区无法加载

### ISSUE THREAD

**Issue by yuhangrao** [blackmatrix7/ios_rule_script#392]
同时使用最新版知乎助手plus和TikTok去水印脚本时会导致知乎的评论区加载错误。
TikTok去水印的脚本用的是：
http-response https?:\/\/.*\.tiktokv\.com\/aweme\/v\d\/(feed|mix\/aweme|aweme\/post|(multi\/)?aweme\/detail|follow\/feed|nearby\/feed|search\/item|general\/search\/single|hot\/search\/video\/list|aweme\/favorite) script-path=https://github.com/yuhangrao/Loon_plugin/raw/master/TikTok/dewatermark.js, requires-body=true

测试应该是 https?:\/\/.*\.tiktokv\.com\/aweme\/v\d\/(feed|mix\/aweme|aweme\/post|(multi\/)?aweme\/detail|follow\/feed|nearby\/feed|search\/item|general\/search\/single|hot\/search\/video\/list|aweme\/favorite) 这个表达式导致的冲突，但是不清楚为什么。

复现步骤：同时启用知乎助手plus和 http-response https?:\/\/.*\.tiktokv\.com\/aweme\/v\d\/(feed|mix\/aweme|aweme\/post|(multi\/)?aweme\/detail|follow\/feed|nearby\/feed|search\/item|general\/search\/single|hot\/search\/video\/list|aweme\/favorite) script-path=https://github.com/yuhangrao/Loon_plugin/raw/master/TikTok/dewatermark.js, requires-body=true 这个Script即可复现

![IMG_0692](https://user-images.githubusercontent.com/28585220/132979842-bedd6fc7-a6cd-47b7-9437-c79dac55c6bc.PNG)

已使用空白配置文件验证：是，单独使用知乎助手plus和TikTok去水印都不会出现问题。

**Comment by blackmatrix7** [comment]
看起来有点奇怪

`^https?:\/\/.*\.tiktokv\.com\/aweme\/v\d\/(feed|mix\/aweme|aweme\/post|(multi\/)?aweme\/detail|follow\/feed|nearby\/feed|search\/item|general\/search\/single|hot\/search\/video\/list|aweme\/favorite)`

`^https?:\/\/api\.zhihu\.com\/(comment_v5\/)?(answers|comments?|articles|pins)\/\d+\/(root_|child_)?comments?`

两个正则应该没什么关联才对，具体可能还要再测试下。

**Comment by blackmatrix7** [comment]
除了Loon，其他客户端会出现此问题吗？

**Comment by yuhangrao** [comment]
> 除了Loon，其他客户端会出现此问题吗？

目前只够买了Loon，qx和surge没有测试还不清楚。

**Comment by blackmatrix7** [comment]
问题已确认，TikTok去水印的插件，其中有一条规则 

`(^h.+v5\/)(.+) $1 302`，会匹配到知乎的评论地址 `https://api.zhihu.com/comment_v5/answers/2092008335/root_comment`

导致知乎评论无法加载，需要插件原作者做下修改。

**Comment by blackmatrix7** [comment]
issue先关闭了，如果有问题再反馈。

**Comment by yuhangrao** [comment]
好的谢谢
