### ISSUE TITLE
关于 ChinaIPsBGP 更新频率的疑问

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#393]
相关规则：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/ChinaIPsBGP

查看了一下 History ，创建至今只更新过一次
再确认了一下来源项目，发现更新频率完全跟不上

**Comment by blackmatrix7** [comment]
谢谢反馈，的确是有个Bug，已处理，麻烦再观察几天看看效果。

如果还有问题请再这里继续反馈。

**Comment by fiiir** [comment]
> 谢谢反馈，的确是有个Bug，已处理，麻烦再观察几天看看效果。
> 
> 如果还有问题请再这里继续反馈。

经过观察感觉更新频率正常了，不过又发现一个现象：
ChinaIPs也包含了ChinaIPsBGP的数据来源，按理说两个list的更新频率不应该差这么多才对？
