### ISSUE TITLE
很多答案无法载入，用的Lite版

### ISSUE THREAD

**Issue by alaya129** [blackmatrix7/ios_rule_script#395]
脚本名称：知乎助手Lite

APP版本：知乎 7.28.0(6526)

客户端名称：Surge

客户端版本：4.9.2 (1993)

问题描述：大概有1/3的答案无法载入或极慢，主要集中在专栏文章，排除网络问题，用Safari打开没有问题。

**复现方式：**
用App打开
https://zhuanlan.zhihu.com/p/410710318
https://zhuanlan.zhihu.com/p/410801280

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
我测试了几天，没办法复现这个问题，你是在蜂窝网络下验证的吗？

**Comment by alaya129** [comment]
4G和Wifi都试过了，关了Mitm可以解决问题，另外我自己的Mitm主机列表是空的

**Comment by blackmatrix7** [comment]
出现这个问题时把日志发给我看下吧。

**Comment by alaya129** [comment]
有些神奇，我为了让Surge干净些，就删了所有的旧日志，准备复现问题留下关键的日志，结果貌似问题解决了@_@

**Comment by blackmatrix7** [comment]
能解决就好，最近实在比较忙，不好意思啊。

**Comment by alaya129** [comment]
多谢多谢，这个脚本真的非常好用。
