### ISSUE TITLE
重写导致 百度网盘 Mac 4.0.2 无法登录并循环请求

### ISSUE THREAD

**Issue by chouchoui** [blackmatrix7/ios_rule_script#396]
https://github.com/blackmatrix7/ios_rule_script/blob/67f48a8c328d2667b25bfdb5e9923901facdee43/rewrite/Surge/Advertising/Advertising.sgmodule#L432

无法登录好像并不是上面的重写的造成的，刷日志太多好像隐约有看到passport.baidu.com mitm fail，好像有个*.baidu.com的hostname

<img width="1243" alt="Snipaste_2021-09-16_20-08-51" src="https://user-images.githubusercontent.com/14866249/133609564-0449c597-c538-4bfe-b974-4a3858f33f9c.png">

**Comment by chouchoui** [comment]
经测试添加
```
hostname = %INSERT% -pan.baidu.com,-passport.baidu.com
```
正常登录
建议添加到重写hostname最前

**Comment by blackmatrix7** [comment]
谢谢反馈，已经加入并且更新。
