### ISSUE TITLE
重写导致随申办市民云无法联网

### ISSUE THREAD

**Issue by kbskfy** [blackmatrix7/ios_rule_script#397]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

名称：Upgrade.conf

APP版本：Quantumult X 1.0.24

客户端名称：iPhone 12 Pro

客户端版本：iOS 14.6

问题描述：^https?:\/\/api\.eshimin\.com\/api\/core\/version url reject-dict 这条重写会导致随申办市民云App无法联网无法登陆，去除主机名api.eshimin.com后App正常联网。

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
这个是用来屏蔽随申办弹窗提示更新，建议登录时先进行放行，登录完成后再屏蔽。

issue先打开着，后面再仔细看下有没有办法区分出登录和检查更新。

**Comment by blackmatrix7** [comment]
看了下，是MITM Failed，还是建议关闭MITM进行登录，随后再打开。

因为它的更新弹窗不定时出现，等下次确认拦截更新功能彻底失效后会把这条复写删除。
