### ISSUE TITLE
哔哩哔哩追番banner广告无法去除

### ISSUE THREAD

**Issue by litesheng** [blackmatrix7/ios_rule_script#398]
RT，哔哩哔哩追番上面滚动栏广告无法去除，或者可以像首页一样直接把banner栏直接删除

**Comment by blackmatrix7** [comment]
bilibili暂时停止维护了，后面有时间再看看，最近事情实在太多，不好意思。

**Comment by litesheng** [comment]
客气了，本来都是免费用你的东西，哪还有抱歉一说，好多大佬都忙自己的事情都停止维护了。你这还是很好的了，谢谢你了。加油，能坚持多久就坚持多久，你不欠谁的，就希望你即使不维护了也别删库就行，毕竟大家都是订阅你的脚本。

**Comment by litesheng** [comment]
回复了邮件不知道你能不能收到，谢谢你了
