### ISSUE TITLE
严格版会导致safari图片丢失

### ISSUE THREAD

**Issue by junmoxio** [blackmatrix7/ios_rule_script#399]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AdvertisingLite/AdvertisingLite.conf

APP版本：quanx测试版最新build596

客户端名称：Safari

客户端版本：iOS15

问题描述：搜索图片丢失

复现方式：

1. 搜索一本小说，比如鬼吹灯
2. 封面丢失

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
应该是某些复写导致百度的图片显示出现问题，还需要再排查下。

**Comment by blackmatrix7** [comment]
已经去除掉这个规则，等待明天凌晨自动更新。

**Comment by blackmatrix7** [comment]
已经去除掉这个规则，等待明天凌晨自动更新。
