### ISSUE TITLE
可屏蔽微博app多数广告以及各部分推广模块

### ISSUE THREAD

**Issue by tomektse** [blackmatrix7/ios_rule_script#401]
https://github.com/zmqcherish/proxy-script

**Comment by Sagittarius16th** [comment]
原all in one里的微博似乎没有去广告功能了，建议重新整合一下

**Comment by Sagittarius16th** [comment]
> 原all in one里的微博似乎没有去广告功能了，建议重新整合一下

不过建议用这个：https://github.com/srk24/profile/blob/master/quanx/weibo.conf

**Comment by blackmatrix7** [comment]
谢谢提供。

不过如果原作者的可以正常使用，建议直接使用原作者的conf文件即可。

目前没有把它爬到当前项目的打算……

主要是我不用微博客户端，抱歉啊。
