### ISSUE TITLE
yandex image 搜索结果预览被拦截

### ISSUE THREAD

**Issue by mwhds97** [blackmatrix7/ios_rule_script#407]
规则名称：去广告规则

规则链接：[Advertising_Domain.yaml](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml)

异常规则：.mds.yandex.net

问题描述：yandex image 无法显示搜索结果预览

![image](https://user-images.githubusercontent.com/32876945/135723014-e9521869-714f-431f-a960-0bc8ff6d66a2.png)

**Comment by blackmatrix7** [comment]
谢谢反馈，已经将误杀的规则加入过滤器，请等待今天凌晨的更新。
