### ISSUE TITLE
知乎助手近期更新说明

### ISSUE THREAD

**Issue by blackmatrix7** [blackmatrix7/ios_rule_script#408]
长话短说，主要更新以下内容：

1. 部分设置支持BoxJS配置
2. 推荐页的关键词过滤支持正则表达式
3. 优化执行效率及修复Bug
4. 增加部分内容的屏蔽
5. 适配知乎7.30.0(6732)

具体的内容，访问 https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu

因为工作和生活都比较忙，不一定能及时适配新版，所以强烈建议保存知乎7.30.0(6732)的IPA文件。

**Comment by blackmatrix7** [comment]
部分设置项支持BoxJS配置，此功能还未经过长期测试， 如果有问题，特别是不使用BoxJS时如果存在问题，请在此反馈。

**Comment by Me-x** [comment]
https://github.com/blackmatrix7/ios_rule_script/issues/409

**Comment by blackmatrix7** [comment]
> #409
谢谢反馈，的确是疏忽了，已修正。

**Comment by fiiir** [comment]
对知乎进行去广告存在一个很蛋疼的问题：
就是如果某一次在没启用surge的前提下，打开了知乎
那么在这以后重新启用surge，打开知乎，知乎便会非常频繁地请求118.89.204.198，哪怕规则已经对这ip进行reject-drop

遇到这种情况可以通过卸载重装知乎解决，不过知乎app所有的设置要重新设定一遍很烦就是了

如果频繁访问118.89.204.198这个有解的话，还是期待可以完善一下

**Comment by blackmatrix7** [comment]
> 对知乎进行去广告存在一个很蛋疼的问题： 就是如果某一次在没启用surge的前提下，打开了知乎 那么在这以后重新启用surge，打开知乎，知乎便会非常频繁地请求118.89.204.198，哪怕规则已经对这ip进行reject-drop
> 
> 遇到这种情况可以通过卸载重装知乎解决，不过知乎app所有的设置要重新设定一遍很烦就是了
> 
> 如果频繁访问118.89.204.198这个有解的话，还是期待可以完善一下

第一次收到这样的反馈，目前会造成什么问题？？可能得12月底才有时间看下。

**Comment by blackmatrix7** [comment]
> > > 对知乎进行去广告存在一个很蛋疼的问题： 就是如果某一次在没启用surge的前提下，打开了知乎 那么在这以后重新启用surge，打开知乎，知乎便会非常频繁地请求118.89.204.198，哪怕规则已经对这ip进行reject-drop
> > > 遇到这种情况可以通过卸载重装知乎解决，不过知乎app所有的设置要重新设定一遍很烦就是了
> > > 如果频繁访问118.89.204.198这个有解的话，还是期待可以完善一下
> > 
> > 
> > 第一次收到这样的反馈，目前会造成什么问题？？可能得12月底才有时间看下。
> 
> 在6sp+最新商店版的环境下，逛知乎越久，cpu发热感知越强烈，切到surge上看有大量该ip被reject-drop的日志 这张截图是我特地在首页稍作停留，没进行任何浏览操作后截取下来的👇 https://telegra.ph/file/010ced5eada75e1d81d7a.jpg 考虑到A9已经是上古的cpu，不排除A12、A13这样的节能怪物对发热情况无法重现

问题已复现，知乎APP的确会对118.89.204.198发起大量的请求，看起来似乎是知乎APP自身有些重连的逻辑。

目前手上最老的设备是iPhone X，因为是备用机用得比较少，再找时间看下发热情况吧，更具体的确认问题可能还是得到12月底。

**Comment by fiiir** [comment]
> > 停用脚本，只保留规则，118.89.204.198无限请求依旧存在
> 
> 如果把拦截118.89.204.198的规则也去掉，还会一直请求此地址吗？

不会重复请求，走geoip,direct，只有一个请求

**Comment by fiiir** [comment]
> > 停用脚本，只保留规则，118.89.204.198无限请求依旧存在
> 
> 如果把拦截118.89.204.198的规则也去掉，还会一直请求此地址吗？

经过不停测试，118.89.204.198重复请求的问题排查出来了，
如果 surge - 更多设置- 实验性功能 - “network framework”，这个开关处于打开状态，118.89.204.198就会处于无限请求状态，关闭开关后会在有限请求次数后停止（5-10次）

不过首页“时间排序”模式下的广告又回来了（“首页” - 左上角“关注” - “时间排序”）
默认排序刷了十来屏没发现，时间排序三屏必有，商店版本7.31.0

**Comment by blackmatrix7** [comment]
> 关于圈X也存在和surge一样的ip无限请求这点忘了补充，因为我的圈X和surge都是TestFlight版本，不确定和大家用的商店版存在多大差别。
> 
> 刚才又发现一个新问题：知乎商店版7.31.0版，回答页和专栏文章页，图片无法加载。
> 在电脑角落里翻出来知乎6.X版本覆盖安装后所有问题完美解决了……
> 建议大佬还是无视我，等其他人反馈吧，折腾两天下来我也懵了！

谢谢，很详细的反馈。我还需要一些时间做下测试，有新的结果再沟通。

**Comment by AlanLang** [comment]
https://alan-picpack.oss-cn-hangzhou.aliyuncs.com/uPic/20211130/知乎_已砸壳.ipa
砸壳了7.30.0版本的知乎，有需要的可以自行签名安装。
