### ISSUE TITLE
知乎助手lite版本订阅出现404问题

### ISSUE THREAD

**Issue by opts98** [blackmatrix7/ios_rule_script#409]
脚本名称：知乎助手_去广告

APP版本：知乎 7.30.0（6732）

客户端名称：Quantumult X

客户端版本：v1.0.24

问题描述：作者更新脚本后订阅，出现提示“7个问题存在于子资源”，之前一直都没问题，点开查看发现是资源404了，尝试使用plus版本则没有出现此问题。

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是
![微信图片_20211004234604](https://user-images.githubusercontent.com/68179719/135882714-0f0bf1a4-b49e-4d95-a4dc-cf565b306d25.png)
![微信图片_20211004234555](https://user-images.githubusercontent.com/68179719/135882724-a472b937-3906-4e51-80f5-8f14cb8ddd01.jpg)

**Comment by Me-x** [comment]
我也是一样 ，知乎版本 7.27.0（6422）

**Comment by blackmatrix7** [comment]
谢谢反馈，的确是疏忽了，已修正。
