### ISSUE TITLE
什么值得买广告残留

### ISSUE THREAD

**Issue by Jessire** [blackmatrix7/ios_rule_script#41]
mitm和rewrite配置都是对的，但在首页推荐以及详情评论下方还是有广告，不过广告内容似乎是固定的，尝试过清楚缓存和卸载重装依然出现

**Comment by blackmatrix7** [comment]
什么值得买没有深入去分析如何去广告，只是简单去除一些常见的。如果有去不干净，可能属于正常情况。

**Comment by Jiaowoz** [comment]
> mitm和rewrite配置都是对的，但在首页推荐以及详情评论下方还是有广告，不过广告内容似乎是固定的，尝试过清楚缓存和卸载重装依然出现

用的什么代理软件？证书是否配置好并信任，去广告规则有没有在最上面？

**Comment by Jessire** [comment]
> > mitm和rewrite配置都是对的，但在首页推荐以及详情评论下方还是有广告，不过广告内容似乎是固定的，尝试过清楚缓存和卸载重装依然出现
> 
> 用的什么代理软件？证书是否配置好并信任，去广告规则有没有在最上面？
QuanX，重写没有顺序要求吧，规则一直是最上面的。

**Comment by Jessire** [comment]
> 什么值得买没有深入去分析如何去广告，只是简单去除一些常见的。如果有去不干净，可能属于正常情况。

嗯嗯，只是感觉是什么残留导致的，广告内容没变化这点有点疑惑

**Comment by blackmatrix7** [comment]
> > 什么值得买没有深入去分析如何去广告，只是简单去除一些常见的。如果有去不干净，可能属于正常情况。
> 
> 
> 
> 嗯嗯，只是感觉是什么残留导致的，广告内容没变化这点有点疑惑

看了下，新版改版了，之前适配的是旧版，失效了。有空再改改。

**Comment by Jessire** [comment]
> > > 什么值得买没有深入去分析如何去广告，只是简单去除一些常见的。如果有去不干净，可能属于正常情况。
> > 
> > 
> > 嗯嗯，只是感觉是什么残留导致的，广告内容没变化这点有点疑惑
> 
> 看了下，新版改版了，之前适配的是旧版，失效了。有空再改改。

好的，多谢大佬了

**Comment by blackmatrix7** [comment]
增加了去除详情页广告和浮动广告，如果还有残留，说明是已经缓存到本地，建议卸载APP后重装试试。
