### ISSUE TITLE
不知道是哪个项目的把几个在线网络分析平台的域名拦截了……

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#413]
这是网络安全研究人员常用的的网站啊，很正经啊
规则名称：（一）ios_rule_script/rule/Shadowrocket/Advertising/Advertising_Domain.list
（二）ios_rule_script/rule/Shadowrocket/Advertising/Advertising.list

规则链接：（一）https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising_Domain.list
（二）
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising.list
异常规则：
（一）
.threat-analytics.com
.threatbook.cn
（二）
DOMAIN-KEYWORD,analysis

问题描述：
误拦截
抓包截图：(相关抓包工具的截图。)
![截屏2021-10-18 23 14 39](https://user-images.githubusercontent.com/63553362/137759642-bb909031-1ad5-400d-81bd-691aaf3cb558.png)

![截屏2021-10-18 23 13 57](https://user-images.githubusercontent.com/63553362/137759552-29cfc9b3-379c-4618-866d-15fa7ceda8d2.png)
调整方案：（一）里的那两条应该删除，（二）里的那个那个不知道删除了合不合适，不知道小火箭的优先级怎么设定的，或许可以在不删除（二）里那条规则的情况下，我自己添加一条代理hybrid-analysis.com的规则？

**Comment by blackmatrix7** [comment]
上述规则已经全部移除，谢谢反馈。
