### ISSUE TITLE
对本地局域网地址的补充

### ISSUE THREAD

**Issue by ArsenicX** [blackmatrix7/ios_rule_script#414]
规则名称：本地局域网地址

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/Lan

问题描述：我找到了另一个收集 LAN 地址的库
 - 库地址：https://github.com/Loyalsoldier/clash-rules
 - 对应链接1：https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
 - 库地址：https://github.com/Loyalsoldier/surge-rules
 - 具体链接2：https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/private.txt

调整方案：(你希望规则做哪些调整，及其原因。)
希望能同步补充到 https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/Lan 下
麻烦大佬了，谢谢！

**Comment by loyle5** [comment]
虽然加入了规则 但是在分类里并没有体现 需要手动搜索LAN规则 希望在readme中添加
