### ISSUE TITLE
解析的优酷视频播放不了

### ISSUE THREAD

**Issue by cl0925** [blackmatrix7/ios_rule_script#415]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list

异常规则：https://sf等数字-ttcdn-tos.pstatp.com

问题描述：无法播放解析的视频

抓包截图：(相关抓包工具的截图。)

调整方案：^https:\/\/sf[1-9]-ttcdn-tos\.pstatp\.com\/

**Comment by blackmatrix7** [comment]
能否提供一下复现的步骤？

我目前优酷视频播放正常。
