### ISSUE TITLE
大神Advertising.sgmodule 是否包含了您的list规则呢

### ISSUE THREAD

**Issue by Mircc** [blackmatrix7/ios_rule_script#417]
我的是surge客户端 我看到您在两个地方都有更新

您的Advertising.sgmodule 和Advertising_Classical.sgmodule  是否包含了Advertising.list和Advertising_Domain.list，还是属于两个不一样的规则，可以同时添加呢

**Comment by blackmatrix7** [comment]
不包含，两个可以共存。

**Comment by Mircc** [comment]
有无可能整合到一个模块里去啊大神，allInone

**Comment by Mircc** [comment]
> 不包含，两个可以共存。

有无可能整合到一个模块里去啊大神，allInone
