### ISSUE TITLE
用Loon听不了QQ音乐

### ISSUE THREAD

**Issue by hazxy** [blackmatrix7/ios_rule_script#42]
环境：ios13.7, loon最新2.1.3,qq音乐最新10.5.5,
订阅的规则有: rewrite/Loon/Advertising.plugin;
rule/Loon/Advertising/Advertising.list + Domain.list + MITM.plugin;
rule/Loon/Global/Global.list + MITM.plugin;
rule/Loon/Apple/Apple.list + Domain.list;
rule/Loon/China/China.list;
rule/Loon/ChinaIPs/ChinaIPs.list;
script/zhihu/zhihu_lite.loonplugin;

逐个排除都没发现是具体哪个规则有影响，但是关掉Loon就可以听了

**Comment by blackmatrix7** [comment]
我试了没有这个问题。你可以试着建一份空白文件，不要加载任何分流与复写规则，看看QQ音乐能不能正常使用。

**Comment by hazxy** [comment]
我排查了一下，是因为Final规则选了代理，估计是QQ音乐检测到了，换成direct就可以了

**Comment by Jiaowoz** [comment]
@hazxy 建议加个China规则放在底部

**Comment by blackmatrix7** [comment]
能解决就好，我先关闭了。

**Comment by hazxy** [comment]
好的好的，谢谢大佬提供的资源，感谢呀
