### ISSUE TITLE
手机qq app打开会卡顿几秒才能正常使用

### ISSUE THREAD

**Issue by GN006** [blackmatrix7/ios_rule_script#420]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：
HOST-SUFFIX,bsrv.qq.com
每次卡顿我就去看拦截列表都有这个

问题描述：使用了该分流规则以后打开qq会卡顿一段时间才能正常使用

调整方案：去除屏蔽

**Comment by GN006** [comment]
可能还涉及其他规则或者我判断错误不是这个规则，，我试着放行这条规则也会卡顿，我继续测试或者大佬帮忙看看

**Comment by blackmatrix7** [comment]
QQ的版本是多少？我没发现有这个问题啊。

**Comment by GN006** [comment]
> QQ的版本是多少？我没发现有这个问题啊。你把规则改成Direct后能正常吗？

版本是8.8.38.705，刚开始启用不会遇到这问题，一天左右才开始会这样，关掉就正常。我自己也试了一星期才确定是规则里有什么被拦截了才导致的，我昨天排除了很多规则，用了一晚上不会了，以下是我排除掉的，可能有的不是真正的原因。

HOST-SUFFIX,mdt.qq.com
HOST-SUFFIX,rqd.qq.com
HOST-SUFFIX,bugly.qq.com
HOST-SUFFIX,wup.imtt.qq.com
HOST-SUFFIX,up-hl.3g.qq.com
HOST-SUFFIX,yun-hl.3g.qq.com
HOST-SUFFIX,bsrv.qq.com
HOST-SUFFIX,beacon.qq.com
HOST,vv.video.qq.com
HOST-SUFFIX,gdt.qq.com
HOST-SUFFIX,event.toggle.qq.com
HOST-SUFFIX,soup.v.qq.com
HOST-SUFFIX,appsupport.qq.com
HOST-SUFFIX,iadsdk.apple.com
HOST-SUFFIX,hd2.3g.qq.com
HOST-SUFFIX,d3g.qq.com
HOST-SUFFIX,wspeed.qq.com
HOST-SUFFIX,dp3.qq.com

**Comment by GN006** [comment]
HOST-SUFFIX,event.toggle.qq.com
HOST-SUFFIX,appsupport.qq.com
测了一个星期，把这两个规则放白名单就没出现过卡顿的情况，，

**Comment by blackmatrix7** [comment]
谢谢反馈，已经移除，等待明天凌晨自动更新。
