### ISSUE TITLE
知乎助手，关键词屏蔽用不了，显示只有盐会员可以。。。

### ISSUE THREAD

**Issue by Sheldontao** [blackmatrix7/ios_rule_script#421]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：**知乎助手**

APP版本：**v1.0.26-build613**

客户端名称：

客户端版本：**知乎v 7.35.0(7228)**

问题描述：
还有能不能说一下，boxjs的订阅链接

复现方式：

1. ………**重装知乎**
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
麻烦提供下执行日志

或者退货到知乎7.30.0(6732)版本，目前只验证过此版本的运行效果，更高的版本不能确定功能是否正常。

**Comment by Sheldontao** [comment]
哥真的感谢！把那个假装的盐会员打开就可以进去了。。。。。正则过滤真的好用！！！！！！！你啥时候更新我啥时候更新app

**Comment by blackmatrix7** [comment]
最近不会有更新，12月份可能会看看，再修一修bug什么的。

**Comment by Sheldontao** [comment]
哥，求一个quora广告过滤可以吗😘

**Comment by blackmatrix7** [comment]
> 哥，求一个quora广告过滤可以吗😘

因为很多方面的原因，目前不会再新增单独对于某一个APP去广告的脚本。

**Comment by Sheldontao** [comment]
哥，发现一个问题，，，我之前不是用不了那个正则过滤麻，然后我开了那个伪装盐会员就可以了，但是最近他突然提示过期
![IMG_582758AE8B09-1](https://user-images.githubusercontent.com/36765652/143477718-f54c0f7e-baa6-4240-83c1-f3e4a58e7a61.jpeg)

然后所有的script都失效了，不知道怎么回事。。。。我还把知乎退回到7.35.0了但是没用，还是显示会员到期，，，有可能过段时间就没了吧。。。我等一下？

**Comment by Sheldontao** [comment]
而且无论是否退回到老版本（设置里面有版本显示），知乎的界面全部变成最新的了（关注页 新设置在下面）

**Comment by blackmatrix7** [comment]
目前我看还是正常的，如果所有功能都失效，要看下是不是脚本没有正确执行。

提供下日志我看下。

**Comment by Sheldontao** [comment]
找到原因了大佬，我不小心把重写给关了
