### ISSUE TITLE
去广告规则导致阿里云传输加速异常

### ISSUE THREAD

**Issue by mwhds97** [blackmatrix7/ios_rule_script#422]
规则名称：去广告规则

规则链接：[Advertising_Domain.yaml](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml)

异常规则：.oss-accelerate.aliyuncs.com

问题描述：这条规则导致使用阿里云 oss 传输加速服务的站点出现异常

**Comment by blackmatrix7** [comment]
谢谢反馈，最近事情实在太多，忙不开，周日或下周会统一验证处理，请稍等一下。

**Comment by blackmatrix7** [comment]
谢谢反馈，已去除此规则。

**Comment by mwhds97** [comment]
该规则似乎并未去除
可能是我没写完整的关系，完整形式是 +.oss-accelerate.aliyuncs.com
