### ISSUE TITLE
今日头条专业版无法联网

### ISSUE THREAD

**Issue by xiaojun-space** [blackmatrix7/ios_rule_script#423]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：去广告

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：与snssdk.com有关的规则

问题描述：今日头条专业版无法联网

抓包截图：(相关抓包工具的截图。)以下是用HTTP Catcher在今日头条专业版运行时抓的
![855F0B9D-507E-4D03-B7C1-DD5C75E846C5](https://user-images.githubusercontent.com/93051683/141830010-9c0fd0ca-4dab-48a7-b82a-88070526838e.jpeg)

调整方案：(你希望规则做哪些调整，及其原因。)希望核实一下去除相关规则后是否影响今日头条普通版，今日头条极速版拦截广告效果

**Comment by xiaojun-space** [comment]
![611C119B-22F4-4ABE-9923-7B176C11F934](https://user-images.githubusercontent.com/93051683/142129055-d6067646-12ac-4833-89d4-40966fe6e7f8.png)

**Comment by xiaojun-space** [comment]
问题找到了，是这四条被误拦截了，添加到白名单就恢复正常了，希望在规则里删除被误拦截的
log.snssdk.com, 
ib.snssdk.com, 
i.snssdk.com, 
dig.bdurl.net

**Comment by blackmatrix7** [comment]
谢谢反馈，最近事情实在太多，忙不开，周日或下周会统一验证处理，请稍等一下。

**Comment by blackmatrix7** [comment]
我这里测试删除ib.snssdk.com规则就正常了，我更新了一下，你再试试，有问题再反馈。
