### ISSUE TITLE
使用知乎脚本后回答页面出现空白加载条

### ISSUE THREAD

**Issue by Meonthb** [blackmatrix7/ios_rule_script#424]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：知乎助手Lite

APP版本：知乎7.35.1

客户端名称：Surge

客户端版本：4.9.4

问题描述：使用知乎脚本后回答页面出现空白加载条，且该加载条会不定期消失/出现

![](https://i.imgur.com/IlO2RJ7.png)

复现方式：不定期（几天至几周不等）复现

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
这个是正常情况，拦截广告后，对应广告位偶尔不会消失，不影响使用。

**Comment by dcty** [comment]
应该是使用 surge，surge 的 reject 会自动升级到 reject-drop，REJECT-DROP policy will be closed in 60-120s later without any data returned。
可以考虑用 reject-no-drop 试试看。
