### ISSUE TITLE
Apple News research 域名

### ISSUE THREAD

**Issue by wangxin6** [blackmatrix7/ios_rule_script#425]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AppleNews

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/AppleNews

异常规则：news-client-search.apple.com

问题描述：Mac news app 搜索框使用

抓包截图：(相关抓包工具的截图。)
<img width="357" alt="image" src="https://user-images.githubusercontent.com/24645789/142587596-3a3f822a-922d-42e0-872f-54ec3ef6f7ae.png">

调整方案：(你希望规则做哪些调整，及其原因。)加入此域名

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
