### ISSUE TITLE
随申办app 使用异常

### ISSUE THREAD

**Issue by WHaveFun** [blackmatrix7/ios_rule_script#426]
规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf

异常规则：api.eshimin.com

问题描述：随申办app会使用异常，抓包貌似这个app接口都是走这个url的
![181FAD8B-8B17-44FE-AAED-3C21E9B5B1F9](https://user-images.githubusercontent.com/13980779/142714565-c6ec9d91-5472-4429-9df2-51f4b70e60ea.jpeg)
![ED1FD8F7-8978-435D-9D93-66018553C225](https://user-images.githubusercontent.com/13980779/142714566-b24ba113-5ae9-48e3-8407-68dd01975f1e.jpeg)

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
影响随申办App的正常使用，如果是广告，可以不去除～

**Comment by blackmatrix7** [comment]
这个是屏蔽随申办更新检查的，已去除，等待稍后更新。

**Comment by blackmatrix7** [comment]
已移除，你再试试。
