### ISSUE TITLE
去开屏广告中美团外卖开屏广告已失效

### ISSUE THREAD

**Issue by yuhangrao** [blackmatrix7/ios_rule_script#431]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：startup.js 

APP版本：Loon 2.1.15

客户端名称：美团外卖

客户端版本：v7.71.0_28708

问题描述：开屏广告再次出现
![image](https://user-images.githubusercontent.com/28585220/143575981-8ac35fd8-e070-4060-a46a-9bf8275311f6.png)

复现方式：

已使用空白配置文件验证：是/否

脚本日志：![image](https://user-images.githubusercontent.com/28585220/143575963-73b92a12-9b31-43f3-984f-96ab0f1bd54f.png)

**Comment by blackmatrix7** [comment]
可能更新了获取广告的地址或响应体，有时间看一下。

**Comment by yuhangrao** [comment]
> 可能更新了获取广告的地址或响应体，有时间看一下。

好的谢谢大佬！

**Comment by litesheng** [comment]
> 可能更新了获取广告的地址或响应体，有时间看一下。

感谢大佬，更新了通知下

**Comment by blackmatrix7** [comment]
我的美团账号在两个不同的设备上登录，更新到最新版后，抓包结果都显示美团外卖没有给我推送广告，即使关闭VPN也没有广告。

目前先根据抓包结果对脚本做了一些修改。

https://gist.githubusercontent.com/blackmatrix7/281d382cf84d0ada343f56244e8dcd3c/raw/893b0d56463dc481f0d0cc6bebb19829a9c388a7/startup.js

暂时没法进一步验证脚本是否正常工作，你可以自己试一下。

如果能正常工作，麻烦回复我一下。

**Comment by yuhangrao** [comment]
> 我的美团账号在两个不同的设备上登录，更新到最新版后，抓包结果都显示美团外卖没有给我推送广告，即使关闭VPN也没有广告。
> 
> 
> 
> 目前先根据抓包结果对脚本做了一些修改。
> 
> 
> 
> https://gist.githubusercontent.com/blackmatrix7/281d382cf84d0ada343f56244e8dcd3c/raw/893b0d56463dc481f0d0cc6bebb19829a9c388a7/startup.js
> 
> 
> 
> 暂时没法进一步验证脚本是否正常工作，你可以自己试一下。
> 
> 
> 
> 如果能正常工作，麻烦回复我一下。

用新脚本测试了几次，还是会有广告，清除缓存和重装都没用。

**Comment by blackmatrix7** [comment]
> > 我的美团账号在两个不同的设备上登录，更新到最新版后，抓包结果都显示美团外卖没有给我推送广告，即使关闭VPN也没有广告。
> > 目前先根据抓包结果对脚本做了一些修改。
> > https://gist.githubusercontent.com/blackmatrix7/281d382cf84d0ada343f56244e8dcd3c/raw/893b0d56463dc481f0d0cc6bebb19829a9c388a7/startup.js
> > 暂时没法进一步验证脚本是否正常工作，你可以自己试一下。
> > 如果能正常工作，麻烦回复我一下。
> 
> 用新脚本测试了几次，还是会有广告，清除缓存和重装都没用。

你把原来的插件禁用了吗？

如果插件禁用，并且将wmapi.meituan.com加到MITM中，还是有问题的话，把response贴一份给我看下吧。

我这里抓到response，启动广告部分是空的。

**Comment by yuhangrao** [comment]
> > > 我的美团账号在两个不同的设备上登录，更新到最新版后，抓包结果都显示美团外卖没有给我推送广告，即使关闭VPN也没有广告。
> 
> > > 目前先根据抓包结果对脚本做了一些修改。
> 
> > > https://gist.githubusercontent.com/blackmatrix7/281d382cf84d0ada343f56244e8dcd3c/raw/893b0d56463dc481f0d0cc6bebb19829a9c388a7/startup.js
> 
> > > 暂时没法进一步验证脚本是否正常工作，你可以自己试一下。
> 
> > > 如果能正常工作，麻烦回复我一下。
> 
> > 
> 
> > 用新脚本测试了几次，还是会有广告，清除缓存和重装都没用。
> 
> 
> 
> 你把原来的插件禁用了吗？
> 
> 
> 
> 如果插件禁用，并且将wmapi.meituan.com加到MITM中，还是有问题的话，把response贴一份给我看下吧，response中的敏感信息可以手动处理下。
> 
> 
> 
> 我这里抓到response，启动广告部分是空的。

我直接替换掉原来的脚本测试的，这是抓包匹配到脚本的那个链接的response，但我看不懂😂
![image](https://user-images.githubusercontent.com/28585220/143841214-1ee0e634-bfc3-4ff5-840a-7f9a379c1f1a.png)

**Comment by blackmatrix7** [comment]
> 到脚本的那个链接的response，但我看不懂😂

点下JSON Viewer，看下里面的内容。

**Comment by yuhangrao** [comment]
> > 到脚本的那个链接的response，但我看不懂😂
> 
> 
> 
> 点下JSON Viewer，看下里面的内容。

[json](https://drive.google.com/file/d/1jp3bX0aSSukUsWQ1su6v8N4SC5vG8m9m/view?usp=drivesdk)

**Comment by litesheng** [comment]
> > > 到脚本的那个链接的response，但我看不懂😂
> > 
> > 
> > 
> > 点下JSON Viewer，看下里面的内容。
> 
> [json](https://drive.google.com/file/d/1jp3bX0aSSukUsWQ1su6v8N4SC5vG8m9m/view?usp=drivesdk)

我的也是这样，大佬也是用的loon吗

**Comment by blackmatrix7** [comment]
广告的图片已经抓到，但是没有在响应的json中找到对应的url。

初步推测广告图片的地址可能是在丢在压缩包里，传回来的是个zip。

目前抓包到300多个zip，近期没时间去确认哪个压缩包内可能含有广告。

并且目前Sugre、QuanX、Loon能否将压缩包传给js脚本，暂时也不知道。

总的来说，有时间会尝试看一下，但很可能解决不了。

**Comment by litesheng** [comment]
> 广告的图片已经抓到，但是没有在响应的json中找到对应的url。
> 
> 初步推测广告图片的地址可能是在丢在压缩包里，传回来的是个zip。
> 
> 目前抓包到300多个zip，近期没时间去确认哪个压缩包内可能含有广告。
> 
> 并且目前Sugre、QuanX、Loon能否将压缩包传给js脚本，暂时也不知道。
> 
> 总的来说，有时间会尝试看一下，但很可能解决不了。
> 

请问大佬也是用loon的吗，为什么你这边会没有广告呢

**Comment by yuhangrao** [comment]
> 广告的图片已经抓到，但是没有在响应的json中找到对应的url。
> 
> 
> 
> 初步推测广告图片的地址可能是在丢在压缩包里，传回来的是个zip。
> 
> 
> 
> 目前抓包到300多个zip，近期没时间去确认哪个压缩包内可能含有广告。
> 
> 
> 
> 并且目前Sugre、QuanX、Loon能否将压缩包传给js脚本，暂时也不知道。
> 
> 
> 
> 总的来说，有时间会尝试看一下，但很可能解决不了。
> 
> 

好的，非常感谢！

**Comment by blackmatrix7** [comment]
近期没有发现有开屏广告，issue先关闭了，如果有广告再反馈。
