### ISSUE TITLE
GlobalMax.list 规则执行时间过长

### ISSUE THREAD

**Issue by luoqz9** [blackmatrix7/ios_rule_script#432]
规则名称：

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GlobalMax/GlobalMax.list

异常规则：URL-REGEX,(.+.|^)(360|so|qihoo|360safe|qhimg|360totalsecurity|yunpan).(cn|com)

问题描述：Surge 反复提示执行时间过长，已经自动禁用

抓包截图：(相关抓包工具的截图。)
![IMAGE 2021-11-27 16:18:44](https://user-images.githubusercontent.com/65555676/143673939-7b887128-0025-40ea-8165-441cd67ed985.jpg)

调整方案：(你希望规则做哪些调整，及其原因。)
删除或优化规则

**Comment by blackmatrix7** [comment]
目前这个是试验性规则，暂时没有明确的使用场景，它可能同时含有国内和国外的服务，现阶段不太推荐使用。
