### ISSUE TITLE
Advertising ChinaMax大量重复规则

### ISSUE THREAD

**Issue by LuzMasonj** [blackmatrix7/ios_rule_script#433]
规则名称：Advertising ChinaMax

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMax/ChinaMax.list

异常规则：

问题描述：两规则同时启用时提示有大量规则重复

抓包截图：(相关抓包工具的截图。)
![58DA9144-A82D-471D-A75E-0E1B0470ACE4](https://user-images.githubusercontent.com/27768847/143764130-f316a0f6-f132-4d40-a105-2ab6091569d2.png)

调整方案：(你希望规则做哪些调整，及其原因。)
能否剔除重复规则

**Comment by blackmatrix7** [comment]
规则自身经过去重是不会有重复的，但是你如果引用了其他的China类型规则，就可能出现重复，建议手动逐一排查一下。

目前这个属于实验性规则，可能有其他的问题，你可以使用其他的China规则。

**Comment by LuzMasonj** [comment]
经过排除了 就是这两个规则有重复

**Comment by blackmatrix7** [comment]
我试试把Advertising.list排除掉，晚点更新一下。

**Comment by LuzMasonj** [comment]
> 我试试把Advertising.list排除掉，晚点更新一下。

好的
