### ISSUE TITLE
知乎最新版app去广告功能失效及临时解决办法

### ISSUE THREAD

**Issue by yfue** [blackmatrix7/ios_rule_script#435]
感谢大佬的工作🙏知乎app更新后首页去广告功能已失效，建议各位谨慎更新

**Comment by blackmatrix7** [comment]
最新版改动有点大，失效的功能不止首页去广告，需要比较多的时间去适配，建议先不要更新。

**Comment by yfue** [comment]
收到。知乎也是，一个小版本更新居然有这么大变更

**Comment by blackmatrix7** [comment]
> 收到。知乎也是，一个小版本更新居然有这么大变更

我下午更新到最新版，测试了下，似乎脚本工作是正常的？？？

能否再帮忙验证一下。

**Comment by yfue** [comment]
看了一下新版首页的广告被干掉了，问题详情页的还有。 ps.APP打开又和上次不一样了

**Comment by blackmatrix7** [comment]
> 看了一下新版首页的广告被干掉了，问题详情页的还有。 ps.APP打开又和上次不一样了

问题详情页的广告能截个图我看下吗？我这里没发现。

**Comment by yfue** [comment]
![Uploading 6EB91CD0-80FE-413D-B4CE-770C9DB5BF22.png…]()

**Comment by yfue** [comment]
![5D78B719-3D3F-4035-B884-6BC41EF07325](https://user-images.githubusercontent.com/58805062/145950577-f0a2856d-07e8-4601-b7eb-d49f8efc07bb.png)

**Comment by blackmatrix7** [comment]
目前无法复现这个广告，推测可能是灰度测试，需要再观察一段时间看看。

**Comment by fiiir** [comment]
在知乎最新版中，“问题页”的广告我也遇到了，而且发现“设置”中刷新黑名单的方式并不能更新“脚本的黑名单”
至于黑名单功能有没有起作用，这个未知，因为目前还没没在“问题页”发现知乎盐选

**Comment by yfue** [comment]
而且广告也时有时无，感觉知乎还是在测试

**Comment by tttwwy** [comment]
使用的plus版，在box里把所有选项关闭了。后面经常会遇到打开页面知乎app卡死的问题。把知乎去广告脚本关闭以后，就再也没遇到这个问题了。感觉有可能因为知乎改版太大，某些去广告逻辑有冲突，导致新版知乎卡死。

**Comment by blackmatrix7** [comment]
目前初步推测是无法正常拦截新版知乎APP获取CDN地址导致脚本失效。

脚本依赖于拦截知乎对118.89.204.198和2402:4e00:1200:ed00:0:9089:6dac:96b6的访问，迫使知乎APP使用域名如api.zhihu.com请求数据。

新版知乎，在规则已经正确拦截上述两个IP地址访问的情况下，依旧可以通过CDN服务器的IP地址直接请求数据，导致MITM失效，进而脚本的正则也无法正常匹配到请求的URL，最终导致脚本没有正常执行。

目前尚不清楚新版知乎是如何获取CDN服务器IP的，在解决此问题前，脚本没办法正常执行。

目前旧版本的7.30.0 6732可以正常使用，新版中QuanX开启HTTP抓包后，也可以正常执行脚本。

**Comment by blackmatrix7** [comment]
目前QuanX临时解决办法是添加一个*.*.*.*的MITM hostname，缺点是会造成大量不必要的MITM，可能造成发热等问题。如果要更精确一些，可以抓包获取到CDN服务器IP地址，将最后一位改为*，再逐一添加到hostname中。

Surge此方法行不通，会显示“证书名称于输入不匹配”，导致知乎显示503错误，还是建议退回旧版知乎App使用。

Loon目前不清楚，可以自己尝试一下，如果Loon能正常，麻烦在这里反馈给。

**Comment by blackmatrix7** [comment]
已经更新适配QuanX和Loon，Surge暂时无法解决。
