### ISSUE TITLE
AdvertisingLite.sgmodule 里面的有三个 Domain 规则的策略是 None

### ISSUE THREAD

**Issue by dcty** [blackmatrix7/ios_rule_script#436]
https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule

[Rule]
DOMAIN,api.cupid.dns.iqiyi.com,None
DOMAIN,video-ad.sm.cn,None
DOMAIN-SUFFIX,cupid.iqiyi.com,None

这个 None 是自动生成规则的问题还是说是 surge 有内置这样的策略？

**Comment by blackmatrix7** [comment]
这个是程序Bug，已经修复了。
