### ISSUE TITLE
关于能否在青龙面板运行

### ISSUE THREAD

**Issue by asimovo** [blackmatrix7/ios_rule_script#437]
首先感谢大佬的辛苦付出提供这么好用的脚本,
之前一直用备用机6s跑圈x张大妈的签到脚本,可能因为小6长期充电最近开不开机,于是在nas上部署了青龙跑一些之前jd类的任务
但是之前圈x里跑zdm我想移植到青龙里跑,奈何本人纯小白一个,脚本可以运行,Cookie是个问题,
遂想向大佬请教一下

**Comment by blackmatrix7** [comment]
参考一下 https://github.com/blackmatrix7/ios_rule_script/issues/56
