### ISSUE TITLE
会考虑把 去广告 类的另建立项目？

### ISSUE THREAD

**Issue by laincat** [blackmatrix7/ios_rule_script#439]
目前的规则每天更新量挺大，有时候查看起来，大部分都有 去广告规则。

**Comment by blackmatrix7** [comment]
暂时没有这方面的考虑，主要原因：

1. 目前规则间都有互相包含和排除的关系
2. 规则生成器暂时不支持多平台多项目生成

最近在做一些修改和修Bug，所以会有几次对整个仓库的规则全部进行更新。

通常情况下，只会更新需要更新的部分。
