### ISSUE TITLE
知乎助手只会提醒一次付费文章，每更新一次提醒一次。

### ISSUE THREAD

**Issue by aa8655** [blackmatrix7/ios_rule_script#44]
![image](https://user-images.githubusercontent.com/72448776/97060982-d1f37280-15c7-11eb-9a20-3cb83fc07142.png)![image](https://user-images.githubusercontent.com/72448776/97060984-d61f9000-15c7-11eb-9684-aaf5b5630f4f.png)

**Comment by blackmatrix7** [comment]
测试了几天不同的App，无法复现此问题。推测可能是VPN重启之类的原因导致，付费内容提醒需要消耗较大的资源，如果频繁出现建议使用Lite版本，或自行修改配置去除此功能。
