### ISSUE TITLE
battle规则建议增加

### ISSUE THREAD

**Issue by whatagoodboy** [blackmatrix7/ios_rule_script#440]
规则名称：
battle
规则链接：

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Battle/Battle.list

异常规则：
缺少cdn.blz-contentstack.com  211.99.100.17

问题描述：

抓包截图：(相关抓包工具的截图。)
![E855B11F-EC57-4CF3-A548-8FD145990745](https://user-images.githubusercontent.com/6156891/145696184-07b122f8-793f-4583-ac0e-1028419a709e.jpeg)

调整方案：(你希望规则做哪些调整，及其原因。)
请将cdn.blz-contentstack.com加入规则，谢谢

**Comment by blackmatrix7** [comment]
谢谢反馈，已经加入，等待明天凌晨自动更新。
