### ISSUE TITLE
去广告list，部分URL-REGEX类规则 不完整

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#442]
相关list：
ios_rule_script/rule/(Loon|Shadowrocket|Surge)/Advertisin(g|gLite|gTest)/Advertisin(g|g_Resolve).list

相关规则：
URL-REGEX,^https?+:\/\/(?>heic|gw)\.alicdn\.com\/tfs\/tb1.+?-\d{4}-\d{4}\.jpg_1200x1200q90\.jpg_\.\w{3
URL-REGEX,^https?+:\/\/kaola-haitao\.oss\.kaolacdn.com\/.+?_\d{3
URL-REGEX,^https?+:\/\/y\.gtimg\.cn\/music\/common\/\/upload\/kg_ad\/.+?\d{3
(人工粗略查找可能有遗漏)
有劳大佬检修一下自动化工具，补全这部分规则

----------------------------------

另外关于去广告还有两个问题，不知道大佬之前是否没留意到

1、
ios_rule_script/rule/(Loon|Surge)/Advertisin(g|gLite|gTest)/Advertisin(g|g_Resolve).list
中的 URL-REGEX类规则，和
ios_rule_script/rewrite/(Loon|Surge)/Advertisin(g|gLite)/(Advertisin((g|gLite)|(g|gLite)_Classical).(plugin|sgmodule))
中的 ([URL Rewrite]|[Map Local])规则
存在大量同样的规则，如果同时使用list和(sgmodule|plugin)会产生一次多余的匹配

一个建议是：
是否能将 URL-REGEX类规则 整合到“一个”独立的list
剩下的 (DOMAIN|DOMAIN-(KEYWORD|SUFFIX)|IP-CID(R|R6))类规则 整合到“另一个”独立的list
这样可以按需取用，实现list和sgmodule自由组合使用

2、
ios_rule_script/rewrite/Surge/Advertisin(g|gLite)/Advertisin((g|gLite)|(g|gLite)_Classical).sgmodule
中存在部分Surge不支持的规则写法

规则举例：
[URL Rewrite]
^https?:\/\/(\d{1,3}\.){3}\d{1,3}/(variety|vlive\.qqvideo)\.tc\.qq\.com/ - reject
Surge的 ([URL Rewrite]|[Map Local])规则
中间不允许出现逗号“,”

即本条规则应修改为
^https?:\/\/((\d{1}|\d{2}|\d{3})\.){3}(\d{1}|\d{2}|\d{3})/(variety|vlive\.qqvideo)\.tc\.qq\.com/ - reject
才能被Surge视为合法规则并应用
(Loon和Shadowrocket对规则中存在逗号“,”的情况 是否视为合法规则尚未验证)

**Comment by blackmatrix7** [comment]
谢谢，很详细的反馈。

1. 规则不完整的问题已解决
2. 独立URL-REGEX类的规则暂时没有这个计划，原因是尽量不要改变已有规则文件的作用和效果。目前是否有资料可以证明分流规则的正则和Surge模块会产生重复匹配？
3. 正则中存在逗号，这个问题以前反馈过，从我个人使用情况来说没有发现会影响使用，也不排除测试不到位，没有发现正则没有生效。目前暂时的解决办法是给正则加上双引号，简单测试了一下工作正常。

上述内容会在今天晚些时候或者明天凌晨更新。

**Comment by fiiir** [comment]
> 谢谢，很详细的反馈。
> 
> 1. 正则类型的规则不完整问题已解决
> 2. 分流规则和复写的正则重复是特意为之，主要是解决QuanX在分流规则中不能使用正则的问题。考虑到尽量不要改变已有规则文件的作用和效果，暂时没有计划独立URL-REGEX类的规则。目前是否有资料可以证明分流规则的正则和Surge模块会产生重复匹配？
> 3. 正则中存在逗号，这个问题以前反馈过，从我个人使用情况来说没有发现会影响使用，也不排除测试不到位，没有发现正则没有生效。目前暂时的解决办法是给正则加上双引号，简单测试了一下工作正常。
> 
> 上述内容会在今天晚些时候或者明天凌晨更新。

加引号确实可以解决规则不生效的问题，学习了
至于重复匹配这个还真想不到怎么验证，就是直觉上认为过多规则必然影响效率，所以两个不同类型但对应同一个请求链接的reject，会想要缩减去其中一个

**Comment by honeyjuice** [comment]
有个问题
如果启动了去广告规则
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list
圈x会启动失败，提示
![QQ图片20211216110022](https://user-images.githubusercontent.com/32090001/146300322-5a4ce60b-9951-4c77-9506-dcf5fdbdacc8.jpg)

**Comment by blackmatrix7** [comment]
> 有个问题
> 
> 如果启动了去广告规则
> 
> https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list
> 
> 圈x会启动失败，提示
> 
> ![QQ图片20211216110022](https://user-images.githubusercontent.com/32090001/146300322-5a4ce60b-9951-4c77-9506-dcf5fdbdacc8.jpg)
> 
> 

重新更新一下

**Comment by blackmatrix7** [comment]
> 有个问题 如果启动了去广告规则 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list 圈x会启动失败

如果使用了Proxy，改成ProxyLite试试，这个排除掉了一些规则，减少重复的情况。

**Comment by blackmatrix7** [comment]
QuanX规则重复问题应该已解决。

Surge经过验证，应该不会触发两次。

暂时关闭，有问题再反馈。
