### ISSUE TITLE
饿了么脚本获取不到cookie 无法领取任务

### ISSUE THREAD

**Issue by HisZ** [blackmatrix7/ios_rule_script#443]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：eleme_daily.js eleme_mission.js

APP版本：quanX1.0.26

客户端名称：饿了么

客户端版本：10.4.5

问题描述：获取不了cookie 

复现方式：
![微信图片_20211216154755](https://user-images.githubusercontent.com/36467007/146329569-aba97ce8-a33a-4962-91ba-0e79be0a391c.jpg)

手动替换cookie后
![3170d9c1d870f85e54fb8d7401eb66f](https://user-images.githubusercontent.com/36467007/146329608-acc9070f-eb73-4cdf-aaa3-06e952f6298c.jpg)

![640e8ec52ab357a56be9726569e44d9](https://user-images.githubusercontent.com/36467007/146329622-9b630484-74df-4eff-9c7b-e830d6b2d2a6.jpg)

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
饿了么更新至最新版验证可以正常获取Cookie，后两张图表明脚本已正常运行，只是没有符合条件的任务和吃货豆可以领取。
