### ISSUE TITLE
All in One部分复写不好使

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#447]
规则名称：AllInOne

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/AllInOne

异常规则：AllInOne.sgmodule

问题描述：第453行不生效。`"^https?:\/\/(www.)?(g|google)\.cn" https://www.google.com 302`
实测： `https://google.cn` 复写为 `https://www.google.com` 不生效。

调整方案：经测试，将*.google.cn添加到MitM列表后，该URL复写可生效。
（推测为所有https的URL类复写都需要解密）

系统环境：macOS12.1
Surge for mac版本：4.3.0 (1430)

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入。
