### ISSUE TITLE
.sina.com被放进了Global_Domain.list

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#448]
规则名称：Global_Domain.list

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Global/Global_Domain.list

异常规则：.sina.com

问题描述：这个域名放在里面，会导致新浪的POP3服务器（pop.sina.com）、SMTP服务器（smtp.sina.com）、IMAP服务器（imap.sina.com）无法直连。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
