### ISSUE TITLE
Advertising list会导致百度地图不可用

### ISSUE THREAD

**Issue by wuming-xiaozu** [blackmatrix7/ios_rule_script#45]
如题。

**Comment by chouchoui** [comment]
应该是这条规则的问题
^https?:\/\/.+?\/client\/phpui2\/ url reject

**Comment by wuming-xiaozu** [comment]
我排除了一下，确认不是重写的问题，而是去广告规则advertising list里的问题。
换其它去广告规则，保留blackmatrix的去广告重写，百度地图没有任何问题

**Comment by blackmatrix7** [comment]
实时版已更新

**Comment by wuming-xiaozu** [comment]
我刚刚用实时版又试了一下，还是不行。等会再试试
