### ISSUE TITLE
规则错误反馈

### ISSUE THREAD

**Issue by Tartarus2014** [blackmatrix7/ios_rule_script#450]
DOMAIN,vv.video.qq.com,DIRECT
这条应该是直连，否则腾讯视频会卡加载
这条目前在https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Advertising/Advertising_Domain.list

这里面
![BD22A942-6CFB-4AA1-97EF-2ECEC0E92334](https://user-images.githubusercontent.com/39802246/146783169-ada51919-33ce-435c-85dc-a58387e4f5f0.png)

**Comment by blackmatrix7** [comment]
谢谢，已经移除了。
