### ISSUE TITLE
提交一个HBO的域名

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#452]
规则名称：HBO

规则链接：所有HBO的规则

异常规则：N/A

问题描述：发现一个没有收录的地址`wmff.warnermediacdn.com`，这个地址如果没有被代理到USA的节点，会导致网页访问HBOMAX站点被提示“地区未开通HBO MAX”。

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入，等待明天凌晨自动更新。
