### ISSUE TITLE
提交一个PayPal地址

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#454]
规则名称：PayPal

规则链接：PayPal

异常规则：PayPal

问题描述：提交一个会影响登陆的地址`www.paypal-mktg.com`。登录时，访问这个地址时的IP和其他PayPal规则集的IP不一致时，会导致登陆失败。

**Comment by blackmatrix7** [comment]
谢谢反馈，已经加入蛮久的了，忘了跟你说。
