### ISSUE TITLE
提交几个Apple.list中没有的Apple相关域名

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#455]
规则名称：Apple

规则链接：Apple

异常规则：Apple

问题描述：经过抓包，以下Apple域名不存在于Apple.list当中，而存在于global或streaming中。故会导致当用户希望Apple服务完全direct时，下列域名无法direct，而走向了proxy。
`tv.apple.com`
`smoot.apple.com`
`cdn.apple-cloudkit.com`
`js-cdn.music.apple.com`
`np-edge.itunes.apple.com`
`play-edge.itunes.apple.com`
` radio.itunes.apple.com`
`uts-api.itunes.apple.com`

虽然Apple.list中有`HOST-SUFFIX,apple.com,Apple`，但由于在global或streaming中有（上述）更具体的二级域名的分流规则，所以代理软件优先按照更具体的分流规则进行了匹配。

**Comment by blackmatrix7** [comment]
这个近期无法解决，因为整套规则生成器是以Surge为模板生成的，Surge中不存在类似QuanX的规则优先级问题，所以遇到DOMAIN-SUFFIX,apple.com时，会将DOMAIN,*.apple.com的所有规则移除。

现在的情况是即使把上面的域名加入，依旧会被程序认为规则重复自动移除。

如果需要QuanX独立生成不同的规则，需要对现有的规则生成器程序做比较大的改动，短期内实现不了。

记得QuanX有配置或者第三方的资源解析器可以支持过滤掉不需要的规则，你可以先尝试这个方法把global中的apple相关规则去掉，具体如何操作我也不记得了。
