### ISSUE TITLE
大佬考虑增加 堆糖 app的 去广告规则么

### ISSUE THREAD

**Issue by FlechazoPh** [blackmatrix7/ios_rule_script#460]
主要是瀑布流广告和插屏广告
如图
![167AB90B-B55A-419A-ABB0-E87A64702F14](https://user-images.githubusercontent.com/94276146/147853684-85367851-c1a4-497b-8bc6-f2eec754dfc9.png)
![986357D9-4D81-4348-9C97-D7BE147153E8](https://user-images.githubusercontent.com/94276146/147853687-b7194ab2-6d17-4df2-8bf9-c2d27ec3c7f7.png)
![A8D501AE-B29E-45A5-8FFB-8BAB1A387F48](https://user-images.githubusercontent.com/94276146/147853688-37a41743-4bbf-4c0c-8d23-89a5cded24db.png)

**Comment by blackmatrix7** [comment]
不考虑增加新的App去广告了：

一方面是我不用这个App，不能及时维护；另外一方面是实在没时间去弄，抱歉。
