### ISSUE TITLE
苹果的 cdn 怎么走直连?

### ISSUE THREAD

**Issue by mtgq** [blackmatrix7/ios_rule_script#461]
![1641436888(1)](https://user-images.githubusercontent.com/29910922/148319728-29c6f3ca-6256-4174-8793-20c233abfadc.png)

HOST-SUFFIX,cdn-apple.com,GlobalMax  ，GlobalMax  现在走的 proxy 

想让苹果的 cdn 也走直连怎么设置呢？

**Comment by blackmatrix7** [comment]
不建议使用GlobalMax……

这个是我弄着试试的，有很多问题。

**Comment by mtgq** [comment]
> 

谢谢恢复，因为我就用了两个规则，一个境内合集，一个是境外合集，如果不用 GlobalMax，那用那个？

**Comment by mtgq** [comment]
> Global就好

好的，谢谢大佬

**Comment by mtgq** [comment]
> Global就好

![image](https://user-images.githubusercontent.com/29910922/149877528-4c7b5302-dbcf-43e3-9c66-d68a3df10487.png)
通过我的排查，可以把这条去掉吗？他不应该出现在这里吧

**Comment by mtgq** [comment]
@blackmatrix7 大佬可以帮忙看下吗？

**Comment by blackmatrix7** [comment]
不好意思，如果issue关闭后还有问题，你试试能不能重新打开，否则有时候不能及时看到。

我试着把这个域名过滤掉， 你再试试，如果解决了麻烦跟我说一下。

**Comment by mtgq** [comment]
> 不好意思，如果issue关闭后还有问题，你试试能不能重新打开，否则有时候不能及时看到。
> 
> 我试着把这个域名过滤掉， 你再试试，如果解决了麻烦跟我说一下。

  大佬，不是过滤掉这个域名的原因，是因为 AppleGlobal.list 存在于 Glabl 中了，应该是把他给移除出去。另外， AppleGlobal.list 也存在于 Apple 的集合中，你看下是不是

**Comment by blackmatrix7** [comment]
不太理解你的需求。之前把cdn-apple.com丢到Global里的确是不太准确的，已经去除，现在是还有其他的问题吗？

**Comment by mtgq** [comment]
> 不太理解你的需求。之前把cdn-apple.com丢到Global里的确是不太准确的，已经去除，现在是还有其他的问题吗？

那好吧，没事了，就是觉得这条规则在这里有点多余。

**Comment by blackmatrix7** [comment]
> > 不太理解你的需求。之前把cdn-apple.com丢到Global里的确是不太准确的，已经去除，现在是还有其他的问题吗？
> 
> 那好吧，没事了，就是觉得这条规则在这里有点多余。

如果只是为了部分网站走代理，你可以试试Proxy这个规则。
