### ISSUE TITLE
知乎8.3.0版本适配说明

### ISSUE THREAD

**Issue by blackmatrix7** [blackmatrix7/ios_rule_script#465]
### 知乎8.3.0 2021年1月14日适配情况

提供两个解决方案：

方案一

通过处理知乎服务端下发配置实现，让8.3.0版本回退到7.X版本的请求方式，以保证脚本正常运行。优点是无需任何修改，更新模块/插件/复写后即生效，缺点是遇到如VPN忘开或切换等情况，没有正常处理知乎下发的配置，可能造成脚本暂时失效，需要重启几次知乎APP，每次等待一小会让其重新请求服务端配置来解决。

方案二

将`103.41.167.235` `103.41.167.226` `103.41.167.234` `103.41.167.236`四个IP地址填入客户端的MITM中。

Surge需要额外进行一些操作：
1. 打开Surge客户端，首页 -> MITM -> 配置根证书，打开跳过服务端证书验证。
2. 需要修改模块和脚本内的正则，对以下内容进行替换：
将`^https?:\/\/api\.zhihu\.com\/`替换为`^https?:\/\/(api\.zhihu\.com|(103\.41\.167\.(226|234|235|236)))`
将`^https?:\/\/www\.zhihu\.com\/`替换为`^https?:\/\/(www\.zhihu\.com|(103\.41\.167\.(226|234|235|236)))`
感谢 [@dcty](https://github.com/dcty) 提供的Surge适配方案。
如果不想动手修改，可以使用dcty提供的模块链接：
https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule
https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule

此方案通过对IP地址进行MITM，优点是不受知乎服务端下发的配置影响，较为稳定。缺点是如果IP地址有变化就需要手动修改。Surge还需要额外修改模块和脚本的正则，需要一定的手动能力。

**综合考虑，Quantumult X、Loon混用方案一和方案二；Surge因方案二改动太大，并且未开启”跳过服务端证书验证“会导致知乎无法正常使用，所以仅应用方案一。**

### 知乎8.3.0 2021年1月7日适配情况

**Quantumult X、Loon**

适配至知乎8.3.0版本，更新复写脚本或相关插件即可。简单测试通过，如果有问题在这里反馈。

**Surge**

适配至知乎7.37.0版本，知乎8.x版本无法正常触发脚本执行，建议降级App使用。后续会尝试其他方案，但不保证能解决。

**吐槽**

知乎内容越来越差，已经沦为软文营销平台，作为十年老用户，考虑放弃使用知乎。

如无意外，在知乎停止摆烂之前，8.x版本应该是最后一次大版本适配，后续如果有小更新会尽快跟进。如果再次大更新导致脚本失效，不会再进行适配。

强烈建议使用旧版iTunes备份知乎7.37.0和8.3.0的ipa文件，以备不时之需。

**Comment by jiaoqingshan** [comment]
all in one 存在12个问题在自资源。用的软件为qx

**Comment by blackmatrix7** [comment]
> all in one 存在12个问题在自资源。用的软件为qx

哪个分支下的？

**Comment by jiaoqingshan** [comment]
现在已经没事啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: blackmatrix7 ***@***.***&gt;
发送时间: 2022年1月10日 17:10
收件人: blackmatrix7/ios_rule_script ***@***.***&gt;
抄送: jiaoqingshan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [blackmatrix7/ios_rule_script] 知乎8.3.0版本适配说明 (Issue #465)





  
all in one 存在12个问题在自资源。用的软件为qx
  
哪个分支下的？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mircc** [comment]
非常感谢作者辛苦更新。

目前知乎首页的 视频  可以屏蔽掉他吗，一不小心点到，就进入视频页面了。

**Comment by dcty** [comment]
知乎8.x版本无法正常触发脚本执行
========================
看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测）
比较粗暴的解决方案就是修改正则表达式
提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了
https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule
https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule

**Comment by blackmatrix7** [comment]
> 知乎8.x版本无法正常触发脚本执行
> 
> ========================
> 
> 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测）
> 
> 比较粗暴的解决方案就是修改正则表达式
> 
> 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了
> 
> https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule
> 
> https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule

谢谢反馈。

能否提供下Surge版本，我这里测试如果把IP加入到Surge的MITM中，就会报证书不匹配，不知道是不是我Surge的配置文件问题。

所以Surge的适配一直没解决。

![image](https://user-images.githubusercontent.com/27717518/149124754-353aec97-430c-4f58-8a69-6b2003466ec8.jpeg)

**Comment by blackmatrix7** [comment]
> 非常感谢作者辛苦更新。
> 
> 
> 
> 目前知乎首页的 视频  可以屏蔽掉他吗，一不小心点到，就进入视频页面，结果播放声音出来，很扰人（目前用的是plus模块）

你说的是右划进入视频页面吗？如果是，这个有简单看过，没找到数据在哪里，后面还会再看看，估计可能性不大。

**Comment by Mircc** [comment]
> > 非常感谢作者辛苦更新。
> > 目前知乎首页的 视频  可以屏蔽掉他吗，一不小心点到，就进入视频页面，结果播放声音出来，很扰人（目前用的是plus模块）
> 
> 你说的是右划进入视频页面吗？如果是，这个有简单看过，没找到数据在哪里，后面还会再看看，估计可能性不大。

不是、是ios知乎 首页现在分为  视频  推荐 热榜 这个模块、我截个图给您看看

![zhihu](https://user-images.githubusercontent.com/18692324/149257139-bc8ad73c-6bac-425f-8215-7c040aae4622.png)

**Comment by dcty** [comment]
> > 知乎8.x版本无法正常触发脚本执行
> > ========================
> > 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测）
> > 比较粗暴的解决方案就是修改正则表达式
> > 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了
> > https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule
> > https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule
> 
> 谢谢反馈。
> 
> 能否提供下Surge版本，我这里测试如果把IP加入到Surge的MITM中，就会报证书不匹配，不知道是不是我Surge的配置文件问题。
> 
> 所以Surge的适配一直没解决。
> 
> ![image](https://user-images.githubusercontent.com/27717518/149124754-353aec97-430c-4f58-8a69-6b2003466ec8.jpeg)

目前用的是TF 版本 4.11.0

**Comment by Sheldontao** [comment]
我在在用上一个版本7.35.0，之前一直都可以用，然后可能是重写更新了，正则屏蔽就消失了（打开就是让你冲会员）

您看一下脚本记录

状态:		已释放
网络请求:	无
描述:		 	
❚  script-response-body
❚  https://www.zhihu.com/appview/v2/answer/2304410084?no_image=false&X-SUGER=VURJRD1BTUJmdU1wcVBCTkxCVUhCVEdTWmltaDlrM0czS1RVa3U2Zz07RElTSz0xMjc4NzA5ODAwOTY7TUVNTz04MTc3ODExNDU2O01PREVMPUQ1M2dBUDtTQlRTPTE2NDIwMTcyMTU7U1VUUz0xNjM3NjU0MDk4LjM0NTgzNDtETj04NjdFNTdCRDA2MkM3MTY5OTk1REMwM0NDMDU0MUMxOTtPUD3kuK3lm73np7vliqg7Q09VTlRSWT1ISztMQU5HPXpoLUhhbnMtSEs7VFo9Mjg4MDA7TUFDSElORT1pUGhvbmUxMywyO0FMSVNCVFM9MTY0MjAxNzIxNS44MDA3NDM7QUxJU1VUUz0xNjE2Mjc4MjExLjU1NjU5MTIwODs7WC1BRC1JUFY0PTM2LjE4NC4yMjAuNDQ%3D&X-AD=canvas_version%3Av%3D5.1%3Bsetting%3Acad%3D0&follow_guide=1&is_enable_double_click_voteup=1&preload=prefetch&entry=preload-topstory&omni=1&ab_signature=CiRBTUJmdU1wcVBCTkxCVUhCVEdTWmltaDlrM0czS1RVa3U2Zz0SIDg1ODQzNDNhZDRiMjJjYzViZGYxNDAwZTQ2YWU5MGVhGhAIAhIGNy4zNS4wGgQ3MjI4
❚  ^https?:\/\/www\.zhihu\.com\/appview\/v2\/answer\/.*(entry=(?!(preload-topstory|preload-search|preload-subscription)))?
❚  https://gist.githubusercontent.com/blackmatrix7/2e550ebf28ca60d620654e394ec47e0b/raw/zhihu.js
日志:		 	
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
❚  [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.012S.

**Comment by sieveLau** [comment]
> # 知乎8.x版本无法正常触发脚本执行
> 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测） 比较粗暴的解决方案就是修改正则表达式 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了 https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule

Surge 4.10.0使用这个修改版的module可以正常使用知乎助手

**Comment by blackmatrix7** [comment]
Quantumult X、Loon、Surge都已经适配目前最新版本的8.3.0 (8020)，具体说明见顶楼。

如果有问题欢迎继续反馈！

**Comment by Sheldontao** [comment]
提供一个重写冲突！！！！！！！nobyda.js关掉之后就可以用了。

感谢互联网，感谢作者大大

**Comment by yuhangrao** [comment]
> # 知乎8.x版本无法正常触发脚本执行
> 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测） 比较粗暴的解决方案就是修改正则表达式 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了 https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule

你好，surge4.11.1用了这个更改后的之后获取黑名单功能正常了，但屏蔽关键词解锁还是无法使用，点开就会推荐开通严选会员，看最近请求https://api.zhihu.com/feed-root/block已经触发了脚本运行，但就是无法使用，换成loon也是相同url触发脚本的运行，但切换成loon立刻就可以使用，请问有什么解决方式吗

**Comment by blackmatrix7** [comment]
> > # 知乎8.x版本无法正常触发脚本执行
> 
> > 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测） 比较粗暴的解决方案就是修改正则表达式 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了 https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule
> 
> 
> 
> 你好，surge4.11.1用了这个更改后的之后获取黑名单功能正常了，但屏蔽关键词解锁还是无法使用，点开就会推荐开通严选会员，看最近请求https://api.zhihu.com/feed-root/block 已经触发了脚本运行，但就是无法使用，换成loon也是相同url触发脚本的运行，但切换成loon立刻就可以使用，请问有什么解决方式吗

屏蔽关键词需要开启伪装盐选会员的功能，看下这个功能是否开启？

**Comment by yuhangrao** [comment]
> > > # 知乎8.x版本无法正常触发脚本执行
> > 
> > 
> > > 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测） 比较粗暴的解决方案就是修改正则表达式 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了 https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule
> > 
> > 
> > 你好，surge4.11.1用了这个更改后的之后获取黑名单功能正常了，但屏蔽关键词解锁还是无法使用，点开就会推荐开通严选会员，看最近请求https://api.zhihu.com/feed-root/block 已经触发了脚本运行，但就是无法使用，换成loon也是相同url触发脚本的运行，但切换成loon立刻就可以使用，请问有什么解决方式吗
> 
> 屏蔽关键词需要开启伪装盐选会员的功能，看下这个功能是否开启？
> 
> 在“我的”页面必须显示为盐选会员，否则会跳转到开通会员页面。
> 
> 如果实在不行也没关系，配置界面只是借用知乎App的功能。在BoxJS里可以直接配置json，格式不要写错就行。

我直接导入plus的模块，没有使用BoxJS，但测试伪装盐选会员没有成功，我的页面会显示开通按钮，但切换到loon就会伪装成功。

**Comment by yuhangrao** [comment]
> > > # 知乎8.x版本无法正常触发脚本执行
> > 
> > 
> > > 看了一下请求，大概是因为直接用的 IP 请求导致无法匹配到规则导致的。 loon 和 qx 大概率是拿了 header 信息来组装成 URL 进行规则匹配，surge 未采用此方案所以匹配不到（猜测） 比较粗暴的解决方案就是修改正则表达式 提供两个修改后的，nodrop 链接修改了原版的 REJECT-DROP 为 REJECT-NO-DROP ，这样在每个回答后面就不会有一块未加载的区域了 https://gitee.com/lanbone/surge/raw/master/zhihu_plus_nodrop.sgmodule https://gitee.com/lanbone/surge/raw/master/zhihu_plus.sgmodule
> > 
> > 
> > 你好，surge4.11.1用了这个更改后的之后获取黑名单功能正常了，但屏蔽关键词解锁还是无法使用，点开就会推荐开通严选会员，看最近请求https://api.zhihu.com/feed-root/block 已经触发了脚本运行，但就是无法使用，换成loon也是相同url触发脚本的运行，但切换成loon立刻就可以使用，请问有什么解决方式吗
> 
> 屏蔽关键词需要开启伪装盐选会员的功能，看下这个功能是否开启？
> 
> 在“我的”页面必须显示为盐选会员，否则会跳转到开通会员页面。
> 
> 如果实在不行也没关系，配置界面只是借用知乎App的功能。在BoxJS里可以直接配置json，格式不要写错就行。

请问伪装成盐选会员是处理用户信息那一个脚本吗，surge运行会输出警告未获取到本次登录的用户信息，但loon则正常运行成功

**Comment by blackmatrix7** [comment]
> 请问伪装成盐选会员是处理用户信息那一个脚本吗，surge运行会输出警告未获取到本次登录的用户信息，但loon则正常运行成功

是这个，有极少数情况会获取不到用户信息，你可以直接执行脚本，把数据做一次清理试试。

**Comment by yuhangrao** [comment]
> > 请问伪装成盐选会员是处理用户信息那一个脚本吗，surge运行会输出警告未获取到本次登录的用户信息，但loon则正常运行成功
> 
> 是这个，有极少数情况会获取不到用户信息，你可以直接执行脚本，把数据做一次清理试试。
> 
> 或者在Loon中配置好，使用boxjs把屏蔽关键词的json填到surge中。

我现在是借用loon配置的，我在surge的脚本编辑下导入知乎助手的模块运行，结果没有任何输出，数据也没被清除，正常应该输出知乎助手数据清除成功才对，不知道为什么。

**Comment by blackmatrix7** [comment]
> > > 请问伪装成盐选会员是处理用户信息那一个脚本吗，surge运行会输出警告未获取到本次登录的用户信息，但loon则正常运行成功
> > 
> > 
> > 是这个，有极少数情况会获取不到用户信息，你可以直接执行脚本，把数据做一次清理试试。
> > 或者在Loon中配置好，使用boxjs把屏蔽关键词的json填到surge中。
> 
> 我现在是借用loon配置的，我在surge的脚本编辑下导入知乎助手的模块运行，结果没有任何输出，数据也没被清除，正常应该输出知乎助手数据清除成功才对，不知道为什么。

提供下执行日志看看，清理功能做的事情很简单，只是把数据写入空字符串。

**Comment by yuhangrao** [comment]
> > > > 请问伪装成盐选会员是处理用户信息那一个脚本吗，surge运行会输出警告未获取到本次登录的用户信息，但loon则正常运行成功
> > > 
> > > 
> > > 是这个，有极少数情况会获取不到用户信息，你可以直接执行脚本，把数据做一次清理试试。
> > > 或者在Loon中配置好，使用boxjs把屏蔽关键词的json填到surge中。
> > 
> > 
> > 我现在是借用loon配置的，我在surge的脚本编辑下导入知乎助手的模块运行，结果没有任何输出，数据也没被清除，正常应该输出知乎助手数据清除成功才对，不知道为什么。
> 
> 提供下执行日志看看，清理功能做的事情很简单，只是把数据写入空字符串。

执行后没有任何输出，surge需要脚本有输出或执行错误才有log，所以找不到log
![78040F9C-C354-4843-BE25-1E3D84D2079D](https://user-images.githubusercontent.com/28585220/155096673-f2e67f40-85a3-4d08-8fea-3971f785575b.png)
![5131237B-71FE-42B8-BCDF-B49CCC8834B9](https://user-images.githubusercontent.com/28585220/155096681-de047000-a053-4fd3-adc8-182f8f83f19d.png)

**Comment by yuhangrao** [comment]
> > > > > 请问伪装成盐选会员是处理用户信息那一个脚本吗，surge运行会输出警告未获取到本次登录的用户信息，但loon则正常运行成功
> > > > 
> > > > 
> > > > 是这个，有极少数情况会获取不到用户信息，你可以直接执行脚本，把数据做一次清理试试。
> > > > 或者在Loon中配置好，使用boxjs把屏蔽关键词的json填到surge中。
> > > 
> > > 
> > > 我现在是借用loon配置的，我在surge的脚本编辑下导入知乎助手的模块运行，结果没有任何输出，数据也没被清除，正常应该输出知乎助手数据清除成功才对，不知道为什么。
> > 
> > 
> > 提供下执行日志看看，清理功能做的事情很简单，只是把数据写入空字符串。
> 
> 执行后没有任何输出，surge需要脚本有输出或执行错误才有log，所以找不到log ![78040F9C-C354-4843-BE25-1E3D84D2079D](https://user-images.githubusercontent.com/28585220/155096673-f2e67f40-85a3-4d08-8fea-3971f785575b.png) ![5131237B-71FE-42B8-BCDF-B49CCC8834B9](https://user-images.githubusercontent.com/28585220/155096681-de047000-a053-4fd3-adc8-182f8f83f19d.png)

已经解决了，一开始直接使用的[@dcty](https://github.com/dcty)更改后的模块，他模块内的正则没有替换完全，我自己修改后解决，其他人如果也有问题不想修改也可用我修改好的 : https://github.com/yuhangrao/Surge/raw/master/Module/Zhihu/Zhihu_Plus.sgmodule
