### ISSUE TITLE
脚本去广告重写内容似乎出现问题

### ISSUE THREAD

**Issue by LucaLin233** [blackmatrix7/ios_rule_script#466]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：脚本去广告

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AdvertisingScript/AdvertisingScript.conf

异常规则：zhihu_puls相关

问题描述：2021.1.7晚间更新时发现知乎plus部分出现404错误，单独的知乎plus规则可以正常更新，没有报错

抓包截图：暂无

调整方案：猜测是佬链接填写错误，烦请检查一下

**Comment by blackmatrix7** [comment]
今天的确替换了知乎的脚本链接，而上面这个复写是每天凌晨自动生成的，因为还没到达生成的时间点，所以链接是错的。

已经手动触发了一次生成，大概10分钟后更新下文件应该就可以了。
