### ISSUE TITLE
重写-网易云音乐开屏广告去除

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#468]
#网易云广告
^https?:\/\/iadmusicmat\.music\.126\.net\/.+\.jpg url reject
^http:\/\/interface\.music\.163\.com\/eapi\/ad\/config\/get url reject
^https?:\//m\.ads\.8le8le\.com\/adShow url reject

hostname=m.ads.8le8le.com,iadmusicmat.music.com

**Comment by RuCu6** [comment]
Qx 的重写，亲测有效，但是开屏等待时间有点长，可能需要优化

**Comment by blackmatrix7** [comment]
目前现有规则没有发现网易云音乐会有广告，能否提供下网易云音乐的版本？

**Comment by RuCu6** [comment]
最新版 8.6.65

**Comment by joyoner** [comment]
8.7.46 版本已经出现开屏广告了。
清除缓存、卸载重装都是必现(3-4次即可复现)。

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入。
