### ISSUE TITLE
请问规则是否未经过去重？

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#47]
观察了一下，以/rule/Surge/AdvertisingTest中的Domain.list为例

比如这组，
“.a.com”等效于“DOMAIN-SUFFIX,a.com”，
前面不带“.”的那个可以去除
botiviga.com
.botiviga.com

这是另一组例子
.jumptap.com
bo.jumptap.com
bos-tapreq01.jumptap.com
bos-tapreq02.jumptap.com
bos-tapreq03.jumptap.com
bos-tapreq04.jumptap.com
bos-tapreq05.jumptap.com
bos-tapreq06.jumptap.com
bos-tapreq07.jumptap.com
bos-tapreq08.jumptap.com
bos-tapreq09.jumptap.com
bos-tapreq10.jumptap.com
bos-tapreq11.jumptap.com
bos-tapreq12.jumptap.com
bos-tapreq13.jumptap.com
bos-tapreq14.jumptap.com
bos-tapreq15.jumptap.com
bos-tapreq16.jumptap.com
bos-tapreq17.jumptap.com
bos-tapreq18.jumptap.com
bos-tapreq19.jumptap.com
bos-tapreq20.jumptap.com
web63.jumptap.com
web64.jumptap.com
web65.jumptap.com

**Comment by blackmatrix7** [comment]
实时版已经更新去重
