### ISSUE TITLE
Apple Podcast 播客部分频道无法下载

### ISSUE THREAD

**Issue by wangxin6** [blackmatrix7/ios_rule_script#476]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AppleProxy

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleProxy/AppleProxy.yaml

异常规则：

问题描述：
Apple iOS 的播客会有部分频道无法下载。在播客中订阅了 The Daily, 需要全局翻墙才能播放。

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
在 AppleProxy 更新 apple podcast 的域名。或者将 podcast 规则单独

**Comment by wangxin6** [comment]
问题找到了。

pdst.fm 没有被 dns sever 正确的解析

**Comment by tefiszx** [comment]
> 问题找到了。
> 
> pdst.fm 没有被 dns sever 正确的解析

能请教一下，分析和解决问题的方法吗？通过抓包工具还是其他办法发现的这个症结？

**Comment by li2282231** [comment]
> 问题找到了。
> 
> pdst.fm 没有被 dns sever 正确的解析

你好，方便告知您是如何解决这个问题的吗？我似乎遇到了和您同样的问题，我也是部分播客频道无法播放，有的可以通过设置域名代理解决，有的即使设置了域名代理也不行，例如：https://anchor.fm，这是隶属于Spotify家的podcast，我要听的播客就是这家上面的，但是我设置了anchor.fm域名代理，也无法正常播放，请教除了设置域名代理，是否还应设置别的比如dns啥的？
