### ISSUE TITLE
建议Steam规则中不要包含LM-Firefly的规则

### ISSUE THREAD

**Issue by alecthw** [blackmatrix7/ios_rule_script#479]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Steam

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/Steam

异常规则：

问题描述：Steam和SteamCN是为了区分需要代理的Steam规则，但是LM-Firefly大佬的规则思路和其他不一样，导致Steam包含所有的相关规则，无法区分下载的走直连

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
谢谢，很详细的反馈，因为一直没什么时间玩游戏，所以没注意到这一点。

我现在做了一个处理，在还是包含包含LM-Firefly的规则的情况下，**将steamcn的规则从steam中排除出去了**。

麻烦帮忙做下验证，如果还有问题，我再把LM-Firefly的规则移除掉。

**Comment by blackmatrix7** [comment]
大概晚上会进行更新。

**Comment by Rakau** [comment]
其实把CN的移出去可以，本身是大陆的CDN。但只要代理了steam的流量都会被分到外区CDN下载，设置里选了也无效，不知道是哪个域名区分的。~~也许是登录之后就被分到外区CDN了？~~

**Comment by blackmatrix7** [comment]
已经更新好了，麻烦帮忙验证下
