### ISSUE TITLE
VSCode设置同步域名广告误杀

### ISSUE THREAD

**Issue by chouchoui** [blackmatrix7/ios_rule_script#481]
规则名称：
Advertising.list

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/4a72e6320fecec8f12879144cf3698e7d9d1d0be/rule/Surge/Advertising/Advertising.list#L91

异常规则：

```
DOMAIN-KEYWORD,traffic
```

问题描述：

广告规则导致VSCode无法同步，同步域名`vscode-sync.trafficmanager.net`

抓包截图：(相关抓包工具的截图。)

<img width="427" alt="Snipaste_2022-01-19_18-38-09" src="https://user-images.githubusercontent.com/14866249/150114147-6792f40e-2140-4e98-8b33-ba1ffb091175.png">
<img width="1451" alt="Snipaste_2022-01-19_18-37-52" src="https://user-images.githubusercontent.com/14866249/150114201-fc57ec69-6656-47e1-9a9b-1b5b21cbe4b6.png">

**Comment by blackmatrix7** [comment]
谢谢反馈，已更新去除。
