### ISSUE TITLE
cdn.cnbj1.fds.api.mi-img.com 导致小米商城无法加载图片

### ISSUE THREAD

**Issue by Edger** [blackmatrix7/ios_rule_script#483]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：cdn.cnbj1.fds.api.mi-img.com

问题描述：cdn.cnbj1.fds.api.mi-img.com 导致小米商城无法加载图片

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
能否提供下小米商城无法加载图片的复现步骤？？？

目前更新到最新版小米商城后，没有找到无法加载图片的地方。

**Comment by RuCu6** [comment]
并没有出现你说的问题啊

**Comment by RuCu6** [comment]
> 不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。
> 
> 规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。
> 
> 反馈前请先确认：
> 
> 1. 请勿涉及政治、成人等敏感或非法内容
> 2. 分流规则的更新需要等待次日凌晨生效
> 3. 仅接受规则引起异常的反馈
> 4. 已自行抓包明确引起异常的规则
> 5. 不规范填写的Issue可能不会得到任何回复
> 
> 规则名称：Advertising
> 
> 规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list
> 
> 异常规则：cdn.cnbj1.fds.api.mi-img.com
> 
> 问题描述：cdn.cnbj1.fds.api.mi-img.com 导致小米商城无法加载图片
> 
> 抓包截图：(相关抓包工具的截图。)
> 
> 调整方案：(你希望规则做哪些调整，及其原因。)

我这没有出现你说的问题

**Comment by Edger** [comment]
> 能否提供下小米商城无法加载图片的复现步骤？？？
> 
> 
> 
> 目前更新到最新版小米商城后，没有找到无法加载图片的地方。

上周确实有碰到，我把这条规则禁用了就好了。
现在我也复现不了了，可能是小米的问题😂
