### ISSUE TITLE
MitM Failed - render.alipay.com

### ISSUE THREAD

**Issue by godlikeanyone** [blackmatrix7/ios_rule_script#485]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AllInOne.conf

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/QuantumultX/AllInOne/AllInOne.conf

异常规则：MitM hostname = render.alipay.com

问题描述：render.alipay.com采用了SSL/TLS Pinning，会导致此域名下的所有页面MitM Failed，例如支付宝五福部分界面无法正常打开，显示空白

调整方案：希望删除AllInOne.conf中第663行：
^https?:\/\/render\.alipay\.com\/p\/s\/h5data\/prod\/spring-festival-2019-h5data\/popup-h5data\.json url reject
并取消对render.alipay.com进行MitM

**Comment by blackmatrix7** [comment]
能否提供下哪些页面无法显示？？

我试了下，MITM的确是存在的，但是没有找到出发上述复写的请求，其他的关于render.alipay.com的MITM没有发现问题。

**Comment by godlikeanyone** [comment]
## 支付宝五福的福气店完全无法显示，如下图
![photo_2022-01-24_14-51-20.jpg](https://s2.loli.net/2022/01/24/SKzJCvqOkfeHhb7.jpg)
![photo_2022-01-24_14-55-41.jpg](https://s2.loli.net/2022/01/24/IwKeRzu3t2WVETm.jpg)
## MiTM失败记录如下
![photo_2022-01-24_14-51-24.jpg](https://s2.loli.net/2022/01/24/dDKuXjwYEZovkIr.jpg)

**Comment by blackmatrix7** [comment]
![image](https://user-images.githubusercontent.com/27717518/150737195-a4449e5e-8a63-473b-8c38-dd1474e8a395.jpeg)
![image](https://user-images.githubusercontent.com/27717518/150737389-8b66aa3d-66b2-4260-8bdd-d9efedeee2f8.jpeg)
我用了QuanX、Surge测试，都是正常的。

没有出现MITM FAIL……

**Comment by blackmatrix7** [comment]
你可以看到我的请求记录中，render.alipay.com是可以正常MITM的，否则不会看到QueryString。

感觉比较奇怪，是不是跟账户、地区之类的有关系。

**Comment by godlikeanyone** [comment]
> 你可以看到我的请求记录中，render.alipay.com是可以正常MITM的，否则不会看到QueryString。
> 
> 感觉比较奇怪，是不是跟账户、地区之类的有关系。

应该是和访问支付宝的IP所在地有关，全局代理新加坡IP同样无法MiTM这个域名。

**Comment by blackmatrix7** [comment]
> > 你可以看到我的请求记录中，render.alipay.com是可以正常MITM的，否则不会看到QueryString。
> > 感觉比较奇怪，是不是跟账户、地区之类的有关系。
> 
> 应该是和访问支付宝的IP所在地有关，全局代理新加坡IP同样无法MiTM这个域名。

再观察下吧，如果没有其他人反馈这个问题就暂时不动了。

**Comment by GilesWong** [comment]
我昨天从其他规则换到这里之后也遇到了这个问题，表现是余利宝页面无法加载，充校园卡的页面金额快速选择的按钮无法出现。
![A727AC93-6734-4AB3-90AF-B8FF711E46CE](https://user-images.githubusercontent.com/13916856/180672290-71acb9cd-e369-4e5b-ad89-e122713b8c7a.png)
![C7668CD6-2EAF-45A1-ACF4-1A27AC659616](https://user-images.githubusercontent.com/13916856/180672292-64825f74-9c29-42dc-afec-c6a11e0bfc79.jpeg)
![A54FAF47-608A-477D-9955-09C7A7E64B7A](https://user-images.githubusercontent.com/13916856/180672293-0e3fab2a-ee9f-47d8-9b83-af4174fde78f.png)
检查mitm证书的配置是正常的。

**Comment by GilesWong** [comment]
> 

没事了，早上发现mitm失败，晚上自己又好了，网络环境都相同。明早再观察一下😂

**Comment by blackmatrix7** [comment]
> > 
> 
> 没事了，早上发现mitm失败，晚上自己又好了，网络环境都相同。明早再观察一下😂

我昨天把这个MITM去掉了
