### ISSUE TITLE
Steam域名缺少steamcontent.com

### ISSUE THREAD

**Issue by AllForLandlord** [blackmatrix7/ios_rule_script#486]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Steam.list

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Steam

异常规则：缺少以steamcontent.com为域名后缀的规则

问题描述：想要让steam的所有流量走某个节点，在使用了上述规则作为分流后，发现有漏网之鱼走了其他节点

抓包截图：
![image](https://user-images.githubusercontent.com/68906347/150810870-a63d78d5-c727-4eac-8efd-6346a9e94235.png)

调整方案：希望能添加DOMAIN-SUFFIX,steamcontent.com这一条规则

麻烦查看一下，谢谢！

**Comment by AllForLandlord** [comment]
我发现在客户端里steam会自己直接请求Valve Corporation的IP地址以判断登录区域，为此我把Valve的IP地址全整理到了下面这个list文件中，有需要的话可以使用~
链接：https://github.com/AllForLandlord/SelfUse/blob/main/Steam.list

**Comment by blackmatrix7** [comment]
重新调整了steam的规则配置，已经把steamcontent.com加回去了。

**Comment by blackmatrix7** [comment]
> 看到V2EX一位网友的帖子（链接：https://www.v2ex.com/t/809612#r_10991409 ），了解到steam的windows客户端会自己直接请求Valve Corporation的IP地址以判断登录区域，为此我把Valve的IP地址全整理到了下面这个list文件中，有需要的话可以使用~ list链接：https://github.com/AllForLandlord/SelfUse/blob/main/Clash/Steam.list
这样的话，是不是可以认为value的IP应该在Steam和SteamCN都存在？

**Comment by AllForLandlord** [comment]
> > 看到V2EX一位网友的帖子（链接：https://www.v2ex.com/t/809612#r_10991409 ），了解到steam的windows客户端会自己直接请求Valve Corporation的IP地址以判断登录区域，为此我把Valve的IP地址全整理到了下面这个list文件中，有需要的话可以使用~ list链接：https://github.com/AllForLandlord/SelfUse/blob/main/Clash/Steam.list
> 
> 这样的话，是不是可以认为value的IP应该在Steam和SteamCN都存在？

我认为是的，但是没验证过（不知道怎么验证）

**Comment by AllForLandlord** [comment]
> * "steampipe.steamcontent.tnkjmec.com"
> * "steampipe.akamaidh.net"
> * "steamcdn-a.akamaidh.net"
>   Steam规则里面，这几个不要走代理，有多少流量都给跑光。

谢谢建议，但是我现在就是要这个全局代理steam的效果
