### ISSUE TITLE
MitM Failed - dimg04.c-ctrip.com

### ISSUE THREAD

**Issue by godlikeanyone** [blackmatrix7/ios_rule_script#489]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AllInOne.conf

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/QuantumultX/AllInOne/AllInOne.conf

异常规则：MitM hostname = dimg04.c-ctrip.com

问题描述：MiTM Failed 导致智行火车票App无法显示查询的酒店图片，客服发送的图片也无法显示，如下图。
![photo_2022-01-28_22-41-12.jpg](https://s2.loli.net/2022/01/28/9ceUYDX8q4oun6V.jpg)
![photo_2022-01-28_22-41-15.jpg](https://s2.loli.net/2022/01/28/5GFMr9IZDBO4hzL.jpg)

抓包截图：
![photo_2022-01-28_22-41-46.jpg](https://s2.loli.net/2022/01/28/KzVgGHCBJOjFR6t.jpg)

调整方案：鉴于无法MiTM，相关规则无效，希望可以删除AllInOne.conf中第379行：
^https?:\/\/dimg04\.c-ctrip\.com\/images\/\w+(_\d{4}){2} url reject-img
并取消对dimg04.c-ctrip.com进行MitM。

**Comment by blackmatrix7** [comment]
新年好！

谢谢反馈，已经移除了。
