### ISSUE TITLE
什么值得买，登录zhiyou.smzdm.com/user，还未登录账号，就提示获取cookie成功，导致签到失败

### ISSUE THREAD

**Issue by cexe** [blackmatrix7/ios_rule_script#49]
清空浏览器缓存之后，问题依旧

**Comment by blackmatrix7** [comment]
访问 zhiyou.smzdm.com 进行登录，登录成功后自动重定向到zhiyou.smzdm.com/user获取Cookie，而不是访问zhiyou.smzdm.com/user进行登录。
