### ISSUE TITLE
Netflix规则里没有"netflix.com"的HOST-SUFFIX

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#492]
Netflix.list规则中虽然有“netflix”的keyworld规则，但是由于没有"netflix.com"的HOST-SUFFIX规则，导致quanx根据规则类型优先原则，会策略选择global.list中的HOST-SUFFIX, netflix.com, proxy。

致使proxy为HK节点的土区用户在使用quanx时无法正确策略选择至Netflix策略组（选择的节点）。使得app在播放影片时总是提示“您的账号无法在该地区使用”

建议：
在quanx的Netflix.list规则中添加HOST-SUFFIX, netflix.com, Netflix

新年快乐！！！！！

**Comment by blackmatrix7** [comment]
新年好！

感谢反馈，已经调整。
