### ISSUE TITLE
京东多合一签到脚本导入surge失败

### ISSUE THREAD

**Issue by bryanwongxin** [blackmatrix7/ios_rule_script#498]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：京东多合一签到脚本

APP版本：4.20.0

客户端名称：surge

客户端版本：4.20.0

问题描述：导入签到脚本模块出错
![86FE40C1-6EA0-4DC8-B509-329026A23CED](https://user-images.githubusercontent.com/12653413/154127581-6c8dcd57-406f-4b98-8b46-bbb35d720268.jpeg)
包括稳定版和实时版

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
谢谢反馈，目前存在Bug，会陆续删除掉外部脚本。

后续的需要等规则生成器下个版本更新统一修复，目前改动太大，上线时间未知。
