### ISSUE TITLE
哔哩哔哩脚本问题

### ISSUE THREAD

**Issue by HZY040122** [blackmatrix7/ios_rule_script#499]
脚本名称：哔哩哔哩_去广告

APP版本：quantumult x 1.0.27

客户端名称：哔哩哔哩

客户端版本：6.60.0

问题描述：应用首页“推荐”视频 若设置为单列模式则无法显示

复现方式：将首页推荐设定 设定为单列模式

1. ………
2. ………………

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
因为时间问题，这个脚本暂时不维护了，后续维护时间待定。
