### ISSUE TITLE
商店版loon的知乎去广告脚本没有

### ISSUE THREAD

**Issue by xiazhijueju** [blackmatrix7/ios_rule_script#5]
大佬，发现你的脚本库里知乎文件内，就是商店版的loon没有去广告的脚本，只有一个后缀js的文件，这个在loon里也不能用。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by blackmatrix7** [comment]
后续以支持Loon插件为主，规则很容易因为优先级问题被覆盖导致失效。
不过你现在可以从历史的提交记录里找回来以前的配置：
https://github.com/blackmatrix7/ios_rule_script/tree/194fbdaa42a83e04e09093493c51c5fff6b5f588/script/zhihu
如果需要用旧版的js，将配置文件中的js地址，替换成历史提交记录里的raw文件地址即可。

**Comment by xiazhijueju** [comment]
谢谢，已经在使用你提供的旧版js> 后续以支持Loon插件为主，规则很容易因为优先级问题被覆盖导致失效。
> 不过你现在可以从历史的提交记录里找回来以前的配置：
> https://github.com/blackmatrix7/ios_rule_script/tree/194fbdaa42a83e04e09093493c51c5fff6b5f588/script/zhihu
> 如果需要用旧版的js，将配置文件中的js地址，替换成历史提交记录里的raw文件地址即可。
