### ISSUE TITLE
什么值得买cookie获取不了呀？ 还是获取方式有误，现在是用浏览器打开zhiyou.smdzm.com提示已经获取了但是运行脚本还是未获取状态

### ISSUE THREAD

**Issue by dwx5278** [blackmatrix7/ios_rule_script#501]
![IMG_20220220_170957.jpg](https://user-images.githubusercontent.com/47168878/154835812-c30aabd9-5fba-4b3d-b094-6245e12e11ec.jpg)

**Comment by blackmatrix7** [comment]
只能用safari获取，如果显示没有cookie可以看下日志。

刚刚在QuanX上测试过没有问题。
