### ISSUE TITLE
奈飞的 IP 收录

### ISSUE THREAD

**Issue by NiceNicks** [blackmatrix7/ios_rule_script#502]
奈飞的 IP 能否收录这个库
https://github.com/QiuSimons/Netflix_IP

**Comment by blackmatrix7** [comment]
问题不大，不过我没弄明白这个AWS IP和Netflix之间的关系，AWS IP是CDN的地址吗？

**Comment by NiceNicks** [comment]
> 问题不大，不过我没弄明白这个AWS IP和Netflix之间的关系，AWS IP是CDN的地址吗？

可能是奈飞部署在aws服务器上 用来检测代理的
之前有看过类似新闻：

“ 近期Netflix在AWS美西增加了一组代理检测节点，URL地址如下：
https://dualstack.apiproxy-device-prod-nlb-*-********************.us-west-2.amazonaws.com
其中URL中有2组*号，第一组表示数字0-9（大概率为3，小概率为2），第二组为长度为16的十六进制字符串（有一定随机性，有兴趣可以自行搜集一下）。

如果通过iOS/Android端升级后的app观看Netflix，且观看Netflix的线路中使用了分流，就会有一定概率会出现网络无法连接的提示。
解决办法：
分流位置为netflix增加一个针对上面URL的分流规则即可。

参考分流规则：
*.us-west-2.amazonaws.com
”

**Comment by blackmatrix7** [comment]
已经把带AWS IP的加入了，稍后更新。
