### ISSUE TITLE
建议将AppleDaily移出Apple大类

### ISSUE THREAD

**Issue by pharrio** [blackmatrix7/ios_rule_script#504]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Apple / Apple Daily

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/Apple

异常规则：

问题描述：

抓包截图：(相关抓包工具的截图。)

调整方案：AppleDaily（苹果日报）和Apple（苹果公司）没有联系，它们不应该被分在一个类别下。请作者考虑把Apple Daily移出Apple大类。

**Comment by blackmatrix7** [comment]
非常感谢，很及时的反馈，批量添加时弄错了，一直没发现。

稍后会进行一次更新。
