### ISSUE TITLE
奇怪为什么圈X的广告重写和loon色鸡的不是同步更新

### ISSUE THREAD

**Issue by Sagittarius16th** [blackmatrix7/ios_rule_script#506]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：

APP版本：

客户端名称：

客户端版本：

问题描述：

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

如题，圈X的去广告重写已经十天没更新了，但是loon和sugar一直都有更新

**Comment by blackmatrix7** [comment]
其实都是没有更新的，Surge和Loon，是因为在渲染README文档时，没有给规则类型统计加上顺序，导致生成时显示的顺序变化，看起来有更新。

这个问题会记录下来，在新版中改掉，因为不影响使用，当前版本暂不处理。
