### ISSUE TITLE
使用AllInOne Rewrite 之后,b站首页仅剩直播一栏而无其他推荐等项目

### ISSUE THREAD

**Issue by ABreadTree** [blackmatrix7/ios_rule_script#507]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：AllInOne

APP版本：QX 1.0.27-build626

客户端名称：b站

客户端版本：6.61.0

问题描述：如题

复现方式：

1. 重写打开此AllInOne 清后台进B站 就会出现首页导航区只剩直播一个 

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
B站去广告脚本暂停维护，下次更新会把它从AllInOne里移除。
