### ISSUE TITLE
大佬你好!能不能做一个openclash的RULE-SET分流规则，谢谢！

### ISSUE THREAD

**Issue by ABXYvvv** [blackmatrix7/ios_rule_script#51]
clash for windows也是通用的
不支持USER-AGENT
支持PROCESS-NAME

示例：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

If arule-provider file named as testprovider and behavior is domain:
testprovider
payload:
  - '.blogger.com'
  - '*.*.microsoft.com'
  - 'books.itunes.apple.com'
  
If arule-provider file named as testprovider2 and behavior is ipcidr:
testprovider2
payload:
  - '192.168.1.0/24'
  - '10.0.0.0.1/32'

If arule-provider file named as testprovider3 and behavior is classical:
testprovider3
payload:
  - DOMAIN-SUFFIX,google.com
  - DOMAIN-KEYWORD,google
  - DOMAIN,ad.com
  - SRC-IP-CIDR,192.168.1.201/32
  - IP-CIDR,127.0.0.0/8
  - GEOIP,CN
  - DST-PORT,80
  - SRC-PORT,7777

**Comment by blackmatrix7** [comment]
这个项目以满足自用需求为主，暂时没有这个计划。

**Comment by blackmatrix7** [comment]
已支持Clash

**Comment by ABXYvvv** [comment]
收到，感谢大佬辛苦付出！
