### ISSUE TITLE
clash规则格式问题

### ISSUE THREAD

**Issue by linger040831** [blackmatrix7/ios_rule_script#510]
老哥您的clash规则都是yaml格式的，规则列表里每行开头还有-这个字符，我自己写的分流规则没办法直接使用，还需要修改后缀和去除-，想知道为什么这样，或者有什么快捷的方式能直接修改您写的规则，望回复，谢谢！

**Comment by blackmatrix7** [comment]
能否细说一下？我觉得你是behavior选错了。

我自己使用OpenClash没有发现问题。

**Comment by linger040831** [comment]
我是用https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Full.ini   acl4大佬这个模版写的，用    https://acl4ssr-sub.github.io/      这个订阅转换，使用您的yaml结尾的规则会不行，转换出来的是空白，acl4的规则都是list结尾，每行规则开头也没有-这个符号，https://acl4ssr-sub.github.io/ 
，openclash的转换我还没试过那个好像是本地的，可能支持您的格式

**Comment by blackmatrix7** [comment]
你可以试试使用Surge的规则。

**Comment by linger040831** [comment]
好的，surge的规则格式没问题，谢谢答复
