### ISSUE TITLE
203.208.40.0/23和183.128.0.0/11被Global和Proxy规则错误包含

### ISSUE THREAD

**Issue by Xin929** [blackmatrix7/ios_rule_script#515]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Global、proxy

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Proxy/Proxy.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list

异常规则：IP-CIDR,183.128.0.0/11,Proxy
IP-CIDR,203.208.40.0/23,Proxy

问题描述：这两个地址似乎都是国内的IP，访问百度/苹果/b站等网站时都有出现，似乎是个国内的cdn？然后被包含在了global和proxy规则里面，请问大佬能去除掉吗

抓包截图：(相关抓包工具的截图。)
![B472497501469C961A658A31A0FDDDA5](https://user-images.githubusercontent.com/49789102/157902248-fb803403-cd0c-4bfe-9e88-31ecb429d09f.png)

调整方案：(你希望规则做哪些调整，及其原因。)
去除错误的规则

**Comment by Xin929** [comment]
又研究了一下，183.128.0.0/11的这个ip段好像是上海的谷歌云？那我也不是很清楚是走代理好还是不走代理好😂应该是国内的ip都不需要走代理吧，哪怕是谷歌的？请大佬指教

**Comment by blackmatrix7** [comment]
183.128.0.0/11 可分配的主机数为2097150个，这么多IP很难去验证是否能够直连，所以从你的抓包记录上来看，B站也会走这个规则，所以会把它移除掉。

203.208.40.0/23 可分配主机数为510个，用我自己的网络进行ping验证，191个可用，319个不可达，不可达也不代表是被墙，可能是本身就没有主机在使用这个IP，或者服务器禁ping。在没办法进一步确认的情况下，这个地址暂时保留。后续有其他反馈再做处理。

明天凌晨会自动更新。
