### ISSUE TITLE
能否考虑添加 fa米家（全家 App）的签到脚本，感谢！

### ISSUE THREAD

**Issue by HotKids** [blackmatrix7/ios_rule_script#52]
获取 cookie 的地址为 https://fmapp.chinafamilymart.com.cn/api/app/market/member/sign/sign，自己尝试照葫芦画瓢写了下不是很成功。希望大佬能考虑下，感谢！

**Comment by blackmatrix7** [comment]
已增加

**Comment by blackmatrix7** [comment]
做完活动就结束了……

**Comment by HotKids** [comment]
现在又可以签了 不清楚他活动是几点出来 建议把时间调到下午

**Comment by blackmatrix7** [comment]
并不是，10月的签到活动结束了。这个是11月的签到活动，刚刚开始。

**Comment by HotKids** [comment]
似乎签到的网址换了

**Comment by blackmatrix7** [comment]
目前已经跟进最新的接口，不过有几个响应参数还需要再验证下，过几天会更新到Github上。

**Comment by loadeng** [comment]
现在还能用吗

**Comment by loadeng** [comment]
签到米粒

**Comment by loadeng** [comment]
能否给个Fa米家获取 cookie 的地址
