### ISSUE TITLE
关于bilibili脚本停用疑问？

### ISSUE THREAD

**Issue by Mazeorz** [blackmatrix7/ios_rule_script#520]
哔哩哔哩脚本是因为没精力维护而停止使用还是？

**Comment by chivesssss** [comment]
同问~

**Comment by blackmatrix7** [comment]
高情商的说法：适当的广告有利于社区健康发展
低情商的说法：通过脚本去广告，涉及对APP数据的修改，有一定的法律风险，后续会逐步停止
其他原因：个人工作实在太忙
