### ISSUE TITLE
advertisingListe domain set 规则集出错

### ISSUE THREAD

**Issue by srk24** [blackmatrix7/ios_rule_script#521]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite_Domain

规则链接：https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml

异常规则：
![image](https://user-images.githubusercontent.com/25836646/159123520-b13b54a8-2a72-48bd-bbd2-3cd40ac12560.png)

问题描述：在新版本clash上无法运行（[Premium 2022.03.19](https://github.com/Dreamacro/clash/releases/tag/premium)）

抓包截图：

调整方案：删除

**Comment by mwhds97** [comment]
当前共有三处

**Comment by blackmatrix7** [comment]
谢谢反馈，已修复。
