### ISSUE TITLE
多邻国国内版域名被 Global_Domain 误判了

### ISSUE THREAD

**Issue by gee1k** [blackmatrix7/ios_rule_script#522]
Global_Domain 中包含 `.duolingo.cn` 导致国内版多邻国访问困难

<img width="912" alt="image" src="https://user-images.githubusercontent.com/12059800/159267751-6f1e2765-d076-4c6f-a286-c8b23c5e3901.png">

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加到过滤器，稍后更新。
