### ISSUE TITLE
Surge AllInOne 模块中包含 Google 搜索重写，但缺少主机名

### ISSUE THREAD

**Issue by stcharlesc** [blackmatrix7/ios_rule_script#523]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：surge rewrite 模块 AllInOne

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/AllInOne/AllInOne.sgmodule

异常规则：Google 搜索重定向
```shell
"^https?:\/\/(ditu|maps).google\.cn" https://maps.google.com 302
"^https?:\/\/(www.)?(g|google)\.cn" https://www.google.com 302
```

问题描述：规则中包含 Google 搜索重定向，但缺少 MitM 主机名 google.cn，发现有相关issue但已关闭。
抓包截图：(相关抓包工具的截图。)

调整方案：MitM部分加入 *.google.cn 测试后发现确实需添加后才可生效。

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后更新。
