### ISSUE TITLE
能否将surge中的重写规则都删除不必要的双引号？

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#526]
https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge 中的重写都包含了不必要的双引号，是否可以删除？因为小火箭现在也能引用surge的模块了，使用mitm和重写很方便，但是小火箭无法识别重写规则里的双引号，希望能够删除。

**Comment by blackmatrix7** [comment]
删除会导致部分正则无法正常匹配，所以没办法删除。

临时的方案：复写的更新频率比较低，可以手动修改使用。

后面再为小火箭专门增加一个目录。

**Comment by JOJOforshaun** [comment]
> 删除会导致部分正则无法正常匹配，所以没办法删除。
> 
> 临时的方案：复写的更新频率比较低，可以手动修改使用。
> 
> 后面再为小火箭专门增加一个目录。

最近有打算增加吗

**Comment by blackmatrix7** [comment]
按目前的进度，预计最快也要1-2个月后才会添加。

主要是新版还没写完，我又不想去改旧版的代码，这样同时维护新旧两个版本的代码太废时间了。

**Comment by JOJOforshaun** [comment]
> 按目前的进度，预计最快也要1-2个月后才会添加。
> 
> 主要是新版还没写完，我又不想去改旧版的代码，这样同时维护新旧两个版本的代码太废时间了。

好哒，期待大佬的新版
