### ISSUE TITLE
您好，请问可否增加iobit驱动软件的代理站点支持

### ISSUE THREAD

**Issue by lyjhyjyes** [blackmatrix7/ios_rule_script#528]
目前iobit booster driver只能通过全局代理的方式进行下载驱动，直接设置iobit.com无法下载驱动
网上找的添加ip无效，可能因为ip经常变

**Comment by blackmatrix7** [comment]
设置 .iobit.com 也无法使用吗？

**Comment by honeyjuice** [comment]
> 设置 .iobit.com 也无法使用吗？

看日志是访问了www.cd4o.com:80这个域名下载驱动，会直接命中Proxy这个规则
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Proxy/Proxy_Domain.yaml

**Comment by lyjhyjyes** [comment]
> > 设置 .iobit.com 也无法使用吗？
> 
> 看日志是访问了www.cd4o.com:80这个域名下载驱动，在我的配置中，会命中Proxy这个规则 https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Proxy/Proxy_Domain.yaml

哦哦，谢谢
