### ISSUE TITLE
同时使用“国外媒体”和“spotify”分流时，spotify还是走的国外媒体

### ISSUE THREAD

**Issue by HaloWww** [blackmatrix7/ios_rule_script#529]
qx同时使用“国外媒体”和“spotify”分流时，spotify.com还是走的国外媒体，已确认spotify分流规则优先级高

spotify分流规则希望添加
HOST-SUFFIX,spotify.com,Spotify

**Comment by Coldvvater** [comment]
> qx同时使用“国外媒体”和“spotify”分流时，spotify.com还是走的国外媒体，已确认spotify分流规则优先级高
> 
> spotify分流规则希望添加 HOST-SUFFIX,spotify.com,Spotify

我觉得应该把spotify规则放在国外媒体上面

**Comment by blackmatrix7** [comment]
谢谢反馈，规则已增加，稍后更新。
