### ISSUE TITLE
关于知乎视频的建议

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_script#53]
现在知乎有很多推荐电影的视频，都是标题党的，很影响体验，又不是靠关键词能屏蔽掉的，有没有办法解决啊？

**Comment by blackmatrix7** [comment]
对外发布的版本，我注释掉了两行代码
// element['extra']['type'] === 'drama' ||
// element['extra']['type'] == 'zvideo' ||
分别对应屏蔽推荐列表中的直播和视频。
目前暂时不考虑去掉这两行的注释，因为这不属于广告范畴，同时也不想把个人屏蔽喜好强加给其他人。

如果你有屏蔽需求，建议fork后自行把这两行注释代码去掉，这样在推荐列表中就不会有直播和视频了。

**Comment by blackmatrix7** [comment]
增加了一个减少推荐列表内视频的策略，不知道能否生效，有兴趣可以试试。

**Comment by zjcfynn** [comment]
完美的状态，感谢🙏
