### ISSUE TITLE
建议将ChinaIPs中的ipv4和ipv6，分割成两个单独的list

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#532]
相关规则：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/*/ChinaIPs

ipv6的数量已经来到6K+，对比之前的纯ipv4版本，规则数量直接翻一倍
鉴于ipv6的普及程度，ipv6多出来6K+规则，在纯ipv4网络下属于累赘
是否考虑将ipv4和ipv6，分割成两个单独的list

**Comment by blackmatrix7** [comment]
可以考虑单独新增两个单独的文件，但是现有的文件，可能已有人在使用，不便改动。

不过这个涉及程序的修改，目前新版还未改完，现有的生成器暂不做改动。

等新版改完上线再回复你，可能要比较晚，最近事情太多，进展缓慢。
