### ISSUE TITLE
海航航空规则的补充建议

### ISSUE THREAD

**Issue by EliceAM** [blackmatrix7/ios_rule_script#534]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：HaiNanHangKong

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/HaiNanHangKong/HaiNanHangKong.list

异常规则：

问题描述：

抓包截图：(相关抓包工具的截图。)
![1C2D42B3305FFDE70D588BC7A5AD51C8](https://user-images.githubusercontent.com/81452851/160812148-189b4a7d-d405-4318-bd61-9c47ca3e8107.png)

调整方案：(你希望规则做哪些调整，及其原因。)
建议添加如下两条规则，以便用于海航内部员工机票的购买，以及企业邮箱的使用
DOMAIN-SUFFIX,hnair.net
DOMAIN-KEYWORD,hnagroup

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入。
