### ISSUE TITLE
关于上游ip规则的选择问题

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#536]
规则名称：所有引用了下面这个ip列表的规则https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

规则链接：

异常规则：

问题描述：中国云服务商的ip也不是只在国内使用吧？例如47.74.12.194是日本阿里云的ip，但依然命中了国内ip规则…

抓包截图：(相关抓包工具的截图。)

调整方案：生成规则时不再引用https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
