### ISSUE TITLE
TikTok 误判

### ISSUE THREAD

**Issue by uclort** [blackmatrix7/ios_rule_script#539]
amemv.com 是国内抖音的 URL.
现在只发现这一个，不知道其他规则会不会影响。
[神机 TikTok](https://github.com/DivineEngine/Profiles/blob/master/Quantumult/Filter/StreamingMedia/Video/TikTok.list)
建议作者参考这个过滤抖音

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/issues/310

现在这两个反馈是冲突的，我需要验证一下才能确定。

**Comment by blackmatrix7** [comment]
测了一会，的确没有发现amemv.com的连接，已经从配置中删掉了，稍后更新。
