### ISSUE TITLE
下方两条去广告的规则可以适配一下，效果非常好

### ISSUE THREAD

**Issue by Angelalisa-x** [blackmatrix7/ios_rule_script#54]
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt
https://badmojr.github.io/1Hosts/Pro/adblock.txt

**Comment by blackmatrix7** [comment]
谢谢提供。只是目前暂时没办法支持ADBlock的规则。
后续会考虑支持，支持的时候我再回复你。
