### ISSUE TITLE
你好，可以添加小红书的分流规则吗？

### ISSUE THREAD

**Issue by XXXGITHUB777** [blackmatrix7/ios_rule_script#542]
help

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by blackmatrix7** [comment]
可以考虑添加，但是需要稍后一些。

暂时不要关闭Issue。

**Comment by blackmatrix7** [comment]
已添加。

https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/XiaoHongShu
