### ISSUE TITLE
quantumltX分流规则advertising.list导致酷我音乐无法连接网络

### ISSUE THREAD

**Issue by sdkhfkdsfkh** [blackmatrix7/ios_rule_script#543]
quantumltX分流规则advertising.list导致酷我音乐无法连接网络以及会将酷我音乐后台杀死

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：advertising.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：nmobi.kuwo.cn

问题描述：上述规则会使酷我音乐无法连接网络！ 杀后台的异常规则没有检测出来，但使用advertisinglite.list无上述任何问题

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by sdkhfkdsfkh** [comment]
log.kuwo.cn此条规则会使酷我音乐后台杀掉

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
