### ISSUE TITLE
Quantumult X使用去广告精简版报错

### ISSUE THREAD

**Issue by godlikeanyone** [blackmatrix7/ios_rule_script#545]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list

异常规则：HOST-SUFFIX,2txt.cc:8862,AdvertisingLite

问题描述：Quantumult X 会报错invalid line HOST-SUFFIX,2txt.cc:8862,AdvertisingLite，域名不支持端口号

抓包截图：(相关抓包工具的截图。)

调整方案：去掉端口号，修改为HOST-SUFFIX,2txt.cc,AdvertisingLite

**Comment by blackmatrix7** [comment]
已知问题，稍后会进行更新。

后续在新版会再加个过滤，去除上游数据源中带有端口号的错误规则。

**Comment by xaver985** [comment]
还是有报错，比如63xs.com, qinhemuye.com

**Comment by blackmatrix7** [comment]
已经全部移除上述规则并测试通过。

不过由于上游规则不可控，在新版彻底过滤掉这类规则前，很难防止这类情况再次出现。
