### ISSUE TITLE
关于复写去广告误杀京东商品搜索页的问题反馈

### ISSUE THREAD

**Issue by imjachen** [blackmatrix7/ios_rule_script#546]
![image](https://user-images.githubusercontent.com/26639154/164959812-157916df-c0b6-4df6-91f2-c5f1c0921d08.png)
商品详情页也会误拦截关闭复写之后正常. 辛苦大佬修复一下

**Comment by imjachen** [comment]
用的Surge模块 经测试https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/Advertising/Advertising.sgmodule

**Comment by blackmatrix7** [comment]
我用的跟你是一样的配置，京东也是经常在用，也测试过打开跟你一样的店铺，无法复现这个问题。

能否提供下拦截请求的截图，我再看下是什么问题。

**Comment by imjachen** [comment]
![image](https://user-images.githubusercontent.com/26639154/164977172-83539d29-7f73-477b-810d-7a8af337acf1.png)
应该是360buyimg.com 这个域名 的问题

**Comment by imjachen** [comment]
抱歉，是我自己的问题！ 证书失效了！ 抱歉 耽误您时间了

**Comment by imjachen** [comment]
![image](https://user-images.githubusercontent.com/26639154/164977223-4ae61129-7dfd-4446-9527-f0e338a76f9d.png)

**Comment by imjachen** [comment]
证书失效不会自动关闭！ 抱歉

**Comment by blackmatrix7** [comment]
没事，可以解决就好。
