### ISSUE TITLE
M1 mac上用圈X，去广告脚本会导致知乎的图片都打不开

### ISSUE THREAD

**Issue by qinyq** [blackmatrix7/ios_rule_script#547]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Advertising
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list
异常规则：
知乎的图片，例如：
https://pic2.zhimg.com/80/b7fc5433b580bfa32722e4e069c28b95_1440w.jpg?source=1940ef5c
https://pic1.zhimg.com/c63114247_xl.jpg?source=32738c0c
问题描述：

1. 用的是M1 的Mac安装的圈x，上述规则添加在分流规则里
2. 开启上述规则，会导致知乎的很多图片（也不是全部）打不开
3. 如果拷贝图像链接然后试着打开，会提示 无法与该服务器建立安全连接

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
<img width="749" alt="Xnip2022-04-27_18-43-21" src="https://user-images.githubusercontent.com/27717518/165501307-dc93c10a-33b4-41c9-b9b9-618114974848.png">

无法复现你这个问题。

从异常信息上看，推测是SSL连接不受信任，不太可能是分流规则造成的。

你可以试着抓包，看看打开你所提供的图片是否有REJECT的记录。

**Comment by qinyq** [comment]
> <img alt="Xnip2022-04-27_18-43-21" width="749" src="https://user-images.githubusercontent.com/27717518/165501307-dc93c10a-33b4-41c9-b9b9-618114974848.png">
> 
> 无法复现你这个问题。
> 
> 从异常信息上看，推测是SSL连接不受信任，不太可能是分流规则造成的。
> 
> 你可以试着抓包，看看打开你所提供的图片是否有REJECT的记录。

好的 感谢快速的回复！！我又试了几次发现好像确实不是广告脚本的问题 但奇怪的是一开关广告脚本就会有机会能打开（难道是因为其他的规则导致的）

**Comment by blackmatrix7** [comment]
> 好的 感谢快速的回复！！我又试了几次发现好像确实不是广告脚本的问题 但奇怪的是一开关广告脚本就会有机会能打开（难道是因为其他的规则导致的）

不客气，那我先关闭了。

建议看下MITM的证书是否受信任，或者电脑上有没有其他的去广告软件，或者DNS是否受到污染。

**Comment by qinyq** [comment]
> > 好的 感谢快速的回复！！我又试了几次发现好像确实不是广告脚本的问题 但奇怪的是一开关广告脚本就会有机会能打开（难道是因为其他的规则导致的）
> 
> 不客气，那我先关闭了。
> 
> 建议看下MITM的证书是否受信任，或者电脑上有没有其他的去广告软件，或者DNS是否受到污染。

好的 我检查了～关掉mitm也没管用。。去广告软件没有 不过公司装了杀毒软件或者其它的我还不知道的后台程序就不知道了。。我再查查，再次表示感谢～
