### ISSUE TITLE
希望增加clash的.list格式的规则

### ISSUE THREAD

**Issue by Pollo3470** [blackmatrix7/ios_rule_script#548]
能否提供clash的.list格式的规则文件供订阅
本人使用openclash在线订阅转换配合自己写的.ini模板来使用，.ini格式的模板只支持引用.list格式的规则文件，如https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Apple.list

**Comment by Pollo3470** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list
像这种是无法使用的

**Comment by blackmatrix7** [comment]
> https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list
> 
> 像这种是无法使用的

能否提供下list格式的相关文档？

我对openclash了解不多。

**Comment by Pollo3470** [comment]
https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html

**Comment by blackmatrix7** [comment]
麻烦了。

可能是我没说清楚，我需要了解的是OpenClash对list这种形式的支持，在哪个文档里有描述，然后list和yaml除了格式，还有没有其他的区别之类的文档。

**Comment by Pollo3470** [comment]
其实是像subconverter这样的订阅转换服务的配置文件支持.list格式的引用，可以参考https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
https://mybj.org/2021/09/subconverter/

**Comment by Pollo3470** [comment]
跟yaml应该只有格式有区别

**Comment by blackmatrix7** [comment]
我的理解是Clash本身不支持list的格式，但是订阅转换服务需要list格式的规则文件，这样子对吗？

然后clash类似domain和ip-cidr的文件，不需要单独区分，全部写在一个list里就可以了？

**Comment by Pollo3470** [comment]
对的，是订阅转换需要引用.list规则
不需要区分

**Comment by blackmatrix7** [comment]
已在新版加上了，不过需要等把复写规则的部分写完，测试没有问题才会一起更新。

复写部分今天才刚刚开始写，所以最快也要1个月之后了。

到时候再回复你。

**Comment by Pollo3470** [comment]
好的，感谢大佬的付出

**Comment by ameyukisora** [comment]
subconverter支持在配置文件中引用clash的.yaml格式rule-set，不过需要在链接前加上源文件类型：clash-classic、clash-ipcidr、clash-domain。例：
```ini
ruleset=DIRECT,clash-ipcidr:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPsBGP/ChinaIPsBGP_IP.yaml
ruleset=BiliBili,clash-classic:https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Bilibili.yaml
ruleset=AdBlock,clash-domain:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/test/rule/Clash/Advertising/Advertising_Domain.yaml
```

> 其实是像subconverter这样的订阅转换服务的配置文件支持.list格式的引用，可以参考https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 https://mybj.org/2021/09/subconverter/

**Comment by Pollo3470** [comment]
学到了，原来这么久无法引用.ymal是因为没添加前缀，感谢指出
另外不好意思麻烦大佬专门制作了clash的.list文件

**Comment by jdjxk** [comment]
list文件目录在哪里？
