### ISSUE TITLE
目前几乎所有有过滤字节跳动广告的重写都会导致字节跳动的办公app，飞书无法正常使用

### ISSUE THREAD

**Issue by gee1k** [blackmatrix7/ios_rule_script#55]
目前几乎所有有过滤字节跳动广告的重写都会导致字节跳动的办公app，飞书无法正常使用

飞书获取聊天接口会调用
mon.snssdk.com

我目前是自己加了一个 hostname: -mon.snssdk.com

**Comment by blackmatrix7** [comment]
谢谢反馈，这个问题可能不太好处理。
我看部分的正则类似 ^https?:\/\/[\s\S]*\.snssdk\.com\/api\/ad\/，对于子域名的匹配太过宽泛。如果hostname没有*.snssdk.com，这些正则都不会生效。
因为我不是规则实际维护者，并不清楚上面的正则实际去除的是哪些地方的广告，没办法动手去修改它。
所以你的方法可能是现阶段比较好的解决方式了。
