### ISSUE TITLE
希望给增加韩国体育类OTT - 【spotvnow】 的规则

### ISSUE THREAD

**Issue by skylover007** [blackmatrix7/ios_rule_script#550]
https://www.spotvnow.co.kr/

是韩国体育类OTT平台，找了好多地方没找到分流规则，自己抓包的又不太完整，希望大佬能帮帮忙弄一下，谢谢

能临时提供平台的账号密码，安卓的apk安装包，如果需要请联系 skylover1982@gmail.com

**Comment by blackmatrix7** [comment]
这个可能需要后面看看有没有时间，目前优先级比较低，暂时没不会加入。

**Comment by blackmatrix7** [comment]
流媒体类型的规则，因为可能需要特定的节点IP才能访问，暂时没有条件添加。
