### ISSUE TITLE
hbomax阿根廷账户使用HBOUSA时有部分规则遗漏

### ISSUE THREAD

**Issue by luuanng** [blackmatrix7/ios_rule_script#554]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：HBOUSA

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/HBOUSA/HBOUSA.list

异常规则：HBO中剔除掉HBOAsia之后的剩余部分，并且HBOUSA中没有的规则，如DOMAIN-SUFFIX,execute-api.us-east-1.amazonaws.com等等。

问题描述：hbomax阿根廷账户使用HBOUSA时显示无服务。

抓包截图：(相关抓包工具的截图。)无抓包截图，仅自行测试了规则。

调整方案：(你希望规则做哪些调整，及其原因。)我用大佬的规则自己整理了一个HBOUSA规则，已经生效，我做的HBOUSA和大佬的HBOAsia可以共存。https://raw.githubusercontent.com/luuanng/surge/main/HBOUSA.list

**Comment by blackmatrix7** [comment]
谢谢提供，已经把你的规则加入到数据源中，稍后会更新。
