### ISSUE TITLE
希望添加“TikTok”屏蔽APP更新检查

### ISSUE THREAD

**Issue by Sokachss** [blackmatrix7/ios_rule_script#555]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：屏蔽APP更新检查

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite/Surge/Upgrade

异常规则：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/Upgrade/Upgrade_Classical.sgmodule

问题描述：希望添加TikTok这个app屏蔽检查的规则

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)希望添加TikTok这个app屏蔽检查的规则，这样就不用防止TikTok自动更新而关闭自动更新了，也不用再一个一个点击app升级更新了，希望能够添加，谢谢！

**Comment by blackmatrix7** [comment]
脚本类的更新，后面会在规则生成器写完后统一做一次更新和维护。

现在赶规则生成器的进度，暂时不给脚本添加功能了。

**Comment by Sokachss** [comment]
好的，老哥。

**Comment by blackmatrix7** [comment]
怎么操作会触发它的更新检查？

我是21的版本，测试了很久它不提示更新。

**Comment by Sokachss** [comment]
好像我表述的不太清楚，我看到这个模块里有屏蔽部分app，例如京东、美团、10010等。我的理解是开启app store App自动更新开关后，其他app都会后台自动更新，只有这个模块里设定的app不会更新。所以我希望老哥能把TikTok也添加进去，这样就可以在自动更新app的时候屏蔽TikTok更新了，这样就可以防止TikTok自动更新而造成解锁失效。

**Comment by blackmatrix7** [comment]
那你理解错了，这个重写是让APP不弹出更新提醒，并不能控制App Store能否更新某个App。

所以最简单的办法是关闭自动更新……

**Comment by Sokachss** [comment]
好吧，那我搞明白了🤣，谢谢老哥解答。
