### ISSUE TITLE
去广告重写脚本snssdk，会导致抖音视频购物入口打不开

### ISSUE THREAD

**Issue by CivelXu** [blackmatrix7/ios_rule_script#556]
如题

![image](https://user-images.githubusercontent.com/19768199/166435708-b852d131-618c-4361-b1e8-aba1060f6a10.png)

**Comment by blackmatrix7** [comment]
QuanX和Surge都试了，没有发现购物车打不开的情况。

抖音为目前最新版。

我是从”我的“内的”抖音商城“进人，然后点右上角购物车。

如果步骤和你的不同，麻烦告知下复现步骤。

**Comment by CivelXu** [comment]
> QuanX和Surge都试了，没有发现购物车打不开的情况。
> 
> 
> 
> 抖音为目前最新版。
> 
> 
> 
> 我是从”我的“内的”抖音商城“进人，然后点右上角购物车。
> 
> 
> 
> 如果步骤和你的不同，麻烦告知下复现步骤。

不好意思，之前表述的不清楚 是从视频中左下角的的购物入口。![image](https://user-images.githubusercontent.com/19768199/167136807-aa9bcfa8-611c-4bdc-82c7-eb48a7aa110f.png)

**Comment by blackmatrix7** [comment]
你说的这个作者我看了下，竟然没有找到购物入口，是我抖音用得少，所以需要开通什么功能吗？

或者能给我个有购物入口的视频链接吗？

我点进去看看

**Comment by CivelXu** [comment]
不需要呀 就是视频推荐购物的流程 看到我发的截图的左下角购物tag吗？

8.76 zTy:/ 这个折叠收纳盒真的太方便了，家里的鞋子不会扔的到处都是了，用来储存杂物也很不错！%蚂蚁盒子 %折叠收纳鞋盒 %居家好物 %好物分享 %好物推荐  https://v.douyin.com/FBcVCa5/ 复制此链接，打开Dou音搜索，直接观看视频！

随便找的视频 你复制一下 你看看能不能行

**Comment by blackmatrix7** [comment]
我上一次的确是能看到购物入口的，然后去除掉重写中一些mitm失败的规则，再进行复验，就看不到购物入口了。

哪怕打开跟你一样的视频，也是看不到购物入口。

不知道抖音后台是怎么控制这个购物入口显示，目前先做了更新，你看看效果怎么样，我没办法验证。

**Comment by CivelXu** [comment]
我更新了 还是不行 你可以找个直播带货的直播间 如 https://v.douyin.com/FSSkYFt/ 进入找商品尝试购买也可以复现。
quanx里面的记录显示MITM Fail已经是443了。我这里测试纸只用了你这这边的两个广告的重写。

![image](https://user-images.githubusercontent.com/19768199/167233068-333c1cef-8be3-4be2-9a60-33a97da65a86.png)
![image](https://user-images.githubusercontent.com/19768199/167232961-04757bc6-f701-429b-80fc-71adf78fc9a9.png)
![image](https://user-images.githubusercontent.com/19768199/167232968-326bfa91-180f-4d1a-8559-6d311e1b7ea7.png)

**Comment by blackmatrix7** [comment]
test分支下移除了大量的重写，你可以再试试。
