### ISSUE TITLE
广告规则误拦截click.aliyun.com

### ISSUE THREAD

**Issue by hacamer** [blackmatrix7/ios_rule_script#558]
这个URL中https://m.mydrivers.com/newsview/829387.html

有一个click.aliyun.com的链接 

clash广告规则拦截了它

请求放行

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml

**Comment by blackmatrix7** [comment]
能否说下拦截的影响？

**Comment by hacamer** [comment]
大概是阿里云的跳转链接，屏蔽了就无法跳转

**Comment by blackmatrix7** [comment]
已加入到过滤器中，稍后更新。
