### ISSUE TITLE
【提问】请问统一推送Bark这个需要怎么配置

### ISSUE THREAD

**Issue by goodtiger** [blackmatrix7/ios_rule_script#559]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

不是很清楚怎么去配置生效

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

规则链接：

异常规则：

问题描述：

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by goodtiger** [comment]
> 这个需要知道你用的是什么环境？

Shawdowrocket

**Comment by blackmatrix7** [comment]
小火箭我不太清楚怎么通过脚本写入变量。

试试Surge的？

$persistentStore.write("https://api.day.app/VXTWvaQ18N29bsQAg7DgkT", "magicjs_unified_push_url");

后面给BoxJS加个配置项吧，不过还得等一下再鸽一段时间，现在在赶重写规则部分的开发。

**Comment by goodtiger** [comment]
> 

圈X 要 把这段代码加在哪里

**Comment by gclm** [comment]
圈X 如何配置呢？

**Comment by blackmatrix7** [comment]
参考下https://github.com/blackmatrix7/ios_rule_script/tree/master/script/eleme

不过目前只有饿了么的脚本支持，其他的脚本需要等框架更新后统一调整。
