### ISSUE TITLE
请问如何自定义什么值得买签到脚本的 cookie

### ISSUE THREAD

**Issue by jiegto** [blackmatrix7/ios_rule_script#56]
你好，请问如果我要把什么值得买的 cookie 直接写到签到脚本里，可以怎么定义？

我在瞎改成使用 GitHub actions 来运行签到，因为不懂代码，参考的“ [https://github.com/BlueskyClouds/My-Actions](https://github.com/BlueskyClouds/My-Actions) ”尝试了很多种改法，一直未能成功。

希望能得到你的解答，非常感谢！

`
// 公共变量
const KEY = process.env.SMZDM_COOKIE
const USER = process.env.SMZDM_USER
const PASS = process.env.SMZDM_PASS
const SEND_KEY = process.env.SEND_KEY

async function downFile () {
    const url = 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_checkin.js'
    await download(url, './')
}

async function changeFiele () {
    let content = await fs.readFileSync('./smzdm_checkin.js', 'utf8')
    content = content.replace(/smzdmCookieKey = 'smzdm_cookie' = ''/, `smzdmCookieKey = '${KEY}'`)
    content = content.replace(/const smzdmAccount = ''/, `const smzdmAccount = '${USER}'`)
    content = content.replace(/const smzdmPassword = ''/, `const smzdmPassword = '${PASS}'`)
    await fs.writeFileSync( './smzdm_checkin.js', content, 'utf8')
}
`

**Comment by blackmatrix7** [comment]
脚本的实现思路不一样。
具体的说，就是我的脚本不支持将cookie值等变量硬编码到代码中，所以你通过正则去替换代码内容是无法生效的。
对于Nodejs的环境，脚本支持在根目录下创建一个名为magic.json的文件，用于存储供脚本读取的变量。
以什么值得买为例，内部结构如下：
`
{
  "smzdm_cookie": "",
  "smzdm_session": "",
  "smzdm_token": "",
  "smzdm_account": "",
  "smzdm_password": ""
}
`
将你的变量写入，然后用nodejs运行脚本就可以，不需要改动任何代码。
所以你应该做的是：
`await fs.writeFileSync( './magic.json', content, 'utf8');`
将你的变量写入到脚本的根目录中，而不需要去改代码。
此方法对于项目中使用了MagicJS的脚本都有效。

**Comment by blackmatrix7** [comment]
补充一下，如果你需要推送，那么在magic.json中再加入一个key/value就可以：
`{ "smzdm_cookie": "你的值", "smzdm_session": "你的值", "smzdm_token": "你的值", "smzdm_account": "你的值", "smzdm_password": "你的值", "magicjs_unified_push_url": "Bark的推送链接" }`
后续可以考虑增加从环境变量或启动参数读取的功能，不过近期没时间弄了。

**Comment by jiegto** [comment]
非常感谢指导，经过多次尝试，终于成功了。

我是将信息推送到 TG，目前的缺点是吧 [INFO] 的信息也推送过去了，还在看怎么才能只推送 [NOTIFY] 部分的内容。

再次感谢！

**Comment by blackmatrix7** [comment]
脚本本身不支持TG推送。我不清楚你的实现方式，如果你推送的是整个输出日志，可以尝试通过正则过滤掉INFO的日志。

**Comment by jiegto** [comment]
是的，我目前是推送的整个输出日志，这部分我自己再琢磨下。Cookie 问题已经解决，结束掉这个 issue，再次感谢！
