### ISSUE TITLE
希望可以增加对安卓Surfboard的支持

### ISSUE THREAD

**Issue by MreDiaos** [blackmatrix7/ios_rule_script#560]
首先，感谢大神提供的分流规则，辛苦了。

规则在Clash上不论cfa还是cfw都是没有问题的。只是个人一个小的建议，希望增加对Surfboard的支持。

因为Surfboard使用的规则格式遵循Surge4，但是因为安卓系统现在砍掉了MITM，所以相应的URL-REGEX及USER-AGENT类型都无法使用。

下面是Surfboard虽遵循Surge4但是因安卓系统问题无法实现的功能，烦请大神空闲时间参阅。
https://getsurfboard.com/docs/faq#why-not-support-these-surge-standard

不知可否在Surge的分流规则中单独增加一个Surfboard分支的支持或者其他方式？因为是个小白，对代码这些都不懂，如果可以实现就劳烦大神，在此先谢过。

**Comment by MreDiaos** [comment]
> 我看了下，如果用带有UA和URL-REGEX的规则，会有什么问题吗？
> 
> 我没有安卓手机，无法验证。

是这样的，大神。因为安卓现在砍掉了系统的MITM，导致这两类规则无法在安卓机子上实现了，所以这两类规则是Surfboard没办法只能放弃的规则。现在这两类是直接Surfboard会无视就会造成规则不全无法发挥它的效果。比如涉及到URL改写这些安卓上直接是系统不支持这个功能了，没法实现了。
不知道我讲的大神你听不听得懂了，主要太小白只能以自己理解的尽量说明白。

**Comment by blackmatrix7** [comment]
那我的理解，用Surge的规则也不会有什么问题，只是两类规则不能匹配上而已。

如果在新增一个客户端的规则，把这两类规则去掉，那实际上没什么有区别。

**Comment by MreDiaos** [comment]
> 那我的理解，用Surge的规则也不会有什么问题，只是两类规则不能匹配上而已。
> 
> 如果在新增一个客户端的规则，把这两类规则去掉，那实际上没什么有区别。

> 也是，可能就是强迫症了，233
> 感谢大神解答了，也再次感谢提供分流规则

**Comment by MreDiaos** [comment]
> 我看了下，如果用带有UA和URL-REGEX的规则，会有什么问题吗？
> 
> 我没有安卓手机，无法验证。

> 大神，抱歉之前因为还添加了其他规则原因导致我判断失误。刚刚把除了大神的其他规则都剔除了以后发现带有UA和URL-REGEX的surge的规则surfboard是完全无法读取使用的。
> > 所以如果大神这里有这个精力、时间的话还是希望可以出一个Surfboard专用的分流规则。
> > > 感谢大神。

**Comment by blackmatrix7** [comment]
如果使用Surge规则没有问题，不再增加新的规则，项目的文件越来越多了，要控制下数量。

**Comment by blackmatrix7** [comment]
> > 如果使用Surge规则没有问题，不再增加新的规则，项目的文件越来越多了，要控制下数量。
> 
> > 大神，可以确定的就是因为有不支持的部分所以规则文件无法使用，规则不生效。

能否提供下不能生效的日志之类的，我看看什么原因。

我没有安卓设备，所以不好测试。
