### ISSUE TITLE
小火箭去广告MITM问题

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#561]
规则名称：Shadowrocket/Advertising/

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising_MITM.conf

异常规则：
MITM文件
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Advertising/Advertising_MITM.conf

问题描述：MITM.conf不方便引入小火箭，也不方便更新。

调整方案：建议在小火箭的Advertising下替换或增加Surge中对应的MITM模块。方便小火箭用户引入和更新MITM。
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising_MITM.sgmodule

PS：AdvertisingLite、AdvertisingTest等含有MITM配置的也应该这么做

**Comment by blackmatrix7** [comment]
当初实现这个功能的时候小火箭还不能支持Surge模块，所以只能写个类似纯文本的用于手动添加。

你可以先用Surge的，目前这个功能已经在新版生成器里已经实现了。

等我把重写规则部分写完会上线测试。

**Comment by JOJOforshaun** [comment]
> 当初实现这个功能的时候小火箭还不能支持Surge模块，所以只能写个类似纯文本的用于手动添加。
> 
> 你可以先用Surge的，目前这个功能已经在新版生成器里已经实现了。
> 
> 等我把重写规则部分写完会上线测试。

好的，给大佬点赞
