### ISSUE TITLE
facebook & whatsapp ipcidr

### ISSUE THREAD

**Issue by malikshi** [blackmatrix7/ios_rule_script#562]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：facebook and whatsapp

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Facebook & https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Whatsapp

异常规则：-

问题描述：fix IP-CIDR LIST based on https://bgp.he.net/AS32934#_prefixes

抓包截图：Openclash with clash dev version

调整方案：the list not completed, some IPCIDR is missing,
```yaml
  - IP-CIDR,102.132.96.0/20
  - IP-CIDR,129.134.160.0/24
  - IP-CIDR,157.240.192.0/18
```

**Comment by blackmatrix7** [comment]
Thanks for your feedback. We have selected some data and added them into the rule.
