### ISSUE TITLE
建议增加一个单独的广告过滤规则列表：AdGuard DNS filter

### ISSUE THREAD

**Issue by ameyukisora** [blackmatrix7/ios_rule_script#564]
AdGuard DNS filter 是一个基于域名的广告过滤规则列表。作为AdGuard团队维护的规则之一，其更新频率有保证，误拦截率低，个人认为还是比较适合clash、surge这类网络工具的，如果可以的话希望能作为一个单独的广告过滤分组。

以下为官方链接（用于广告拦截器）：
[https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt)

以下为r-a-y将其转化为的hosts文件：
[https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt](https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt)

**Comment by blackmatrix7** [comment]
有这个计划，会在把重写部分的代码写完后开始做AdGuard规则的解析。

**Comment by cloudsurges** [comment]
https://github.com/cloudsurges/AdGuardSDNSFilter/blob/main/AdGuardSDNSFilter.txt
