### ISSUE TITLE
广告规则误拦截

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#568]
规则名称：advertising_domain

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising_Domain.list

异常规则：appboy-images.com

问题描述：这个是正常域名，很多图片都经过它

抓包截图：(相关抓包工具的截图。)

调整方案：删除appboy-images.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已去除。
