### ISSUE TITLE
希望对clash分流规则新增类别

### ISSUE THREAD

**Issue by BULikeS** [blackmatrix7/ios_rule_script#569]
大佬你好，因为clash的premium核对类型 ”domain"和"ipcidr"类型的有特殊优化，
而项目内绝大部分都是"classical"类型的。
目前了解到大佬在重构项目，因此想问问大佬有没有意向对clash的类型进行拆分（拆成"domain“和"ipcidr"类型），
这样感觉对clash的性能也比较好，希望大佬能考虑一下，谢谢惹😙
[Rule Providers](https://github.com/Dreamacro/clash/wiki/premium-core-features#rule-providers)

**Comment by blackmatrix7** [comment]
这个功能一直都有，目前设置拆分的阈值是1000。即domain或ipcidr类型的规则数量达到1000，就会拆分出单独的文件。

例如

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml

如果其他规则目录下没有，说明规则数量没有达到阈值。暂时没有找到资料能说明Clash拆分阈值的合理值，所以采用的是Surge的标准，达到1000条进行拆分。

另外一方面是调整拆分阈值需要比较慎重，如果规则已有人在使用的话，降低拆分的阈值，可能会导致原先完整的规则文件突然缺少domain或ipcidr。

后面新版会增加Stash的分流规则，目前阈值设置的是500，因为还没上线，倒是可以调整。不过Stash没有提供domain和ipcidr类型的规则，而是提供纯txt格式的。

**Comment by BULikeS** [comment]
> 

感谢大佬的回复，我目前的考虑是想尽量把域名和IP规则分开来，让它先匹配域名，再匹配IP，这样感觉会比较适合分流规则编写。
-------------
拆分阈值这个clash好像是没有的，因为看到有些是几条的域名/IP规则也能用 domain/ipcidr，主要原因还是因为有针对性优化
-------------
我感觉可以在已有的基础上弄一份仅域名和仅IP规则？虽然感觉工作量会非常大就是了（
-------------
Stash的支持纯txt确实比较好，毕竟文档里也写了支持优秀，原核premium感觉得看D大会不会改了。
-------------
还是感谢大佬创建了这个优秀的项目🤗

**Comment by BULikeS** [comment]
对于拆分的想法，我这里有几个拙见

对于 `domain`类型  仅保留 `DOMAIN(完整域名)`和`DOMAIN-SUFFIX(域名后缀)`
对于 `ipcidr`类型 仅保留 `IP-CIDR(IPV4)`和`IP-CIDR6(IPV6)`
剩下的不方便进行分类的可以考虑丢进 `classical` 
如  `DOMAIN-KEYWORD(域名关键字)` 和 `PROCESS-NAME(进程名)` 
对于想懒直接用的话 可以考虑新建个 `xxxALL_classical.yaml(全部)` 这样的？
例：
```
RULE-SET,apple_domain,apple（纯域名）
RULE-SET,apple_ipcidr,apple（纯IP）
RULE-SET,apple_classical,apple（特殊分类KEYWORD/PROCESS）
RULE-SET,appleALL_classical,apple（全部）
```
这样一看文件就变多了呢 嘎嘎
题外话
在 `classical` 里使用 `PROCESS-NAME(进程名)`  要注意  [点这里](https://github.com/Dreamacro/clash/issues/2141)

按照上面的方法来拆分的话，一般情况下只用 `domain` 和 `ipcidr` 其实也够了，
个人感觉 `DOMAIN-KEYWORD(域名关键字)` 容易误命中，
而 `PROCESS-NAME(进程名)`  建议用户按需写进规则里（clash对大小写、完整度敏感）
规则重复肯定有，毕竟是先细分流最后再到大分流兜底，对于clash来说即使规则重复也问题不大，
毕竟纯 `domain` 和 纯 `ipcidr` 格式的性能较好、内存消耗较少，通过尽量少使用 `classical` 类型的而达到最优使用premium内核

尽量优先匹配域名，再匹配IP
```
例：
RULE-SET,apple-domain,apple（纯域名）
RULE-SET,google-domain,google（纯域名）
RULE-SET,apple-ipcidr,apple（纯IP）
```

[因为clash的premium内核在  2022.05.17 发布的版本中增加了对 `RULE-SET,xxx,xxx,no-resolve` 的支持](https://github.com/Dreamacro/clash/releases/tag/premium)
因此可以考虑所有IP规则后面都不加no-resolve了，让用户自己在 `RULE-SET规则` 末尾写上就行

最后谢谢大佬的辛苦付出🥰

**Comment by BULikeS** [comment]
对于拆分的想法，我这里有几个拙见

对于 `domain`类型  仅保留 `DOMAIN(完整域名)`和`DOMAIN-SUFFIX(域名后缀)`
对于 `ipcidr`类型 仅保留 `IP-CIDR(IPV4)`和`IP-CIDR6(IPV6)`
剩下的不方便进行分类的可以考虑丢进 `classical` 
如  `DOMAIN-KEYWORD(域名关键字)` 和 `PROCESS-NAME(进程名)` 
对于想懒直接用的话 可以考虑新建个 `xxxALL_classical.yaml(全部)` 这样的？
例：
```
RULE-SET,apple_domain,apple（纯域名）
RULE-SET,apple_ipcidr,apple（纯IP）
RULE-SET,apple_classical,apple（特殊分类KEYWORD/PROCESS）
RULE-SET,appleALL_classical,apple（全部）
```
这样一看文件就变多了呢 嘎嘎

按照上面的方法来拆分的话，一般情况下只用 `domain` 和 `ipcidr` 其实也够了，
个人感觉 `DOMAIN-KEYWORD(域名关键字)` 容易误命中，
而 `PROCESS-NAME(进程名)`  建议用户按需写进规则里（clash对大小写、完整度敏感）
规则重复肯定有，毕竟是先细分流最后再到大分流兜底，对于clash来说即使规则重复也问题不大，
毕竟纯 `domain` 和 纯 `ipcidr` 格式的性能较好、内存消耗较少，通过尽量少使用 `classical` 类型的而达到最优使用premium内核

尽量优先匹配域名，再匹配IP
```
例：
RULE-SET,apple-domain,apple（纯域名）
RULE-SET,google-domain,google（纯域名）
RULE-SET,apple-ipcidr,apple（纯IP）
```

[因为clash的premium内核在  2022.05.17 发布的版本中增加了对 `RULE-SET,xxx,xxx,no-resolve` 的支持](https://github.com/Dreamacro/clash/releases/tag/premium)
因此可以考虑所有IP规则后面都不加no-resolve了，让用户自己在 `RULE-SET规则` 末尾写上就行

最后谢谢大佬的辛苦付出🥰

**Comment by blackmatrix7** [comment]
> 对于拆分的想法，我这里有几个拙见
> 
> 对于 `domain`类型 仅保留 `DOMAIN(完整域名)`和`DOMAIN-SUFFIX(域名后缀)` 对于 `ipcidr`类型 仅保留 `IP-CIDR(IPV4)`和`IP-CIDR6(IPV6)` 剩下的不方便进行分类的可以考虑丢进 `classical` 如 `DOMAIN-KEYWORD(域名关键字)` 和 `PROCESS-NAME(进程名)` 对于想懒直接用的话 可以考虑新建个 `xxxALL_classical.yaml(全部)` 这样的？ 例：
> 
> ```
> RULE-SET,apple_domain,apple（纯域名）
> RULE-SET,apple_ipcidr,apple（纯IP）
> RULE-SET,apple_classical,apple（特殊分类KEYWORD/PROCESS）
> RULE-SET,appleALL_classical,apple（全部）
> ```
> 
> 这样一看文件就变多了呢 嘎嘎
> 
> 按照上面的方法来拆分的话，一般情况下只用 `domain` 和 `ipcidr` 其实也够了， 个人感觉 `DOMAIN-KEYWORD(域名关键字)` 容易误命中， 而 `PROCESS-NAME(进程名)` 建议用户按需写进规则里（clash对大小写、完整度敏感） 规则重复肯定有，毕竟是先细分流最后再到大分流兜底，对于clash来说即使规则重复也问题不大， 毕竟纯 `domain` 和 纯 `ipcidr` 格式的性能较好、内存消耗较少，通过尽量少使用 `classical` 类型的而达到最优使用premium内核
> 
> 尽量优先匹配域名，再匹配IP
> 
> ```
> 例：
> RULE-SET,apple-domain,apple（纯域名）
> RULE-SET,google-domain,google（纯域名）
> RULE-SET,apple-ipcidr,apple（纯IP）
> ```
> 
> [因为clash的premium内核在 2022.05.17 发布的版本中增加了对 `RULE-SET,xxx,xxx,no-resolve` 的支持](https://github.com/Dreamacro/clash/releases/tag/premium) 因此可以考虑所有IP规则后面都不加no-resolve了，让用户自己在 `RULE-SET规则` 末尾写上就行
> 
> 最后谢谢大佬的辛苦付出🥰

no-resolve会彻底把它从规则里去掉。

拆分太细的话，容易让人困惑：一堆的文件哪些和哪些组合才是正确的。

所以这个还是需要再谨慎考虑下。

**Comment by blackmatrix7** [comment]
仔细考虑了一下，还是不宜对Clash原本规则文件的功能做调整，这会影响到其他人，不好意思。
