### ISSUE TITLE
ChinaIPs 增加 gaoyifan 作者的库

### ISSUE THREAD

**Issue by krkrchan** [blackmatrix7/ios_rule_script#570]
在日常浏览过程中，我发现 gaoyifan 作者有在维护 [china-operator-ip](https://github.com/gaoyifan/china-operator-ip) 库，

且细分了各大运营商，以及 ipv6 地址。

每日自动更新。

请问可否整合进 ChinaIPs 中，或者另外增加一条分流规则。

感谢阅读！

**Comment by blackmatrix7** [comment]
已经加入 https://github.com/blackmatrix7/ios_rule_script/tree/test/rule/Surge/ChinaIPs/ChinaIPsTest

**Comment by krkrchan** [comment]
看到啦，感谢！
