### ISSUE TITLE
能否整合张军大佬的规则？

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#575]
https://github.com/28413761/QX
这是大佬的仓库，希望也能转化成surge的规则。
很多重写都是大佬自己抓包的规则

**Comment by blackmatrix7** [comment]
已加入https://github.com/blackmatrix7/ios_rule_script/tree/test/rule/Shadowrocket/AdvertisingTest

测试版规则，误杀需要自行处理。

另外两个去广告规则原则上不再新增数据源，并且考虑去除部分数据源。
