### ISSUE TITLE
网易云分流规则导致 光遇 游戏无法进入，网易云音乐APP内的 音乐人中心，皮肤商店 都无法进入

### ISSUE THREAD

**Issue by FlechazoPh** [blackmatrix7/ios_rule_script#578]
网易云分流规则导致网易 光遇 游戏无法进入（其他网易游戏可能也无法进入），网易云音乐APP内的音乐人中心，皮肤商店都无法进入
**HOST-KEYWORD,netease   这条关键字匹配太宽泛了，所有的网易系流量都走了这个规则，是不是可以修改下**

规则名称：
NetEaseMusic.list
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/NetEaseMusic/NetEaseMusic.list
异常规则：

问题描述：

抓包截图：(相关抓包工具的截图。)
![image](https://user-images.githubusercontent.com/94276146/170294654-6475dcd2-b7ec-4527-8981-7fa43f5888a0.png)
![image](https://user-images.githubusercontent.com/94276146/170295108-bbd7558e-717b-42a9-96ac-f234c9bff99e.png)

调整方案：(你希望规则做哪些调整，及其原因。)
**去除关键字 netease 匹配，或者规则匹配更细一点**

**Comment by blackmatrix7** [comment]
谢谢反馈，已修复。

目前暂时只在test分支维护。

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/test/rule/QuantumultX/NetEaseMusic/NetEaseMusic.list
