### ISSUE TITLE
Surge 运行饿了么 eleme_daily.js  脚本一直转圈

### ISSUE THREAD

**Issue by 52znn** [blackmatrix7/ios_rule_script#58]

**Comment by blackmatrix7** [comment]
无法复现此问题，手动执行建议加长超时时间。

**Comment by 52znn** [comment]
![Uploading E5A86D4D-8B2B-416A-98C2-7182BB78BBD9.png…]()

**Comment by 52znn** [comment]
![A730BC75-C9E5-4637-B8F7-35191F67A2E3](https://user-images.githubusercontent.com/42986378/98235507-d4c56e80-1f9c-11eb-9283-9b6c7d63e45d.jpeg)
手动运行选择180秒提示这个

**Comment by blackmatrix7** [comment]
你不是超级会员？目前没有对会员状态做判断。

**Comment by 52znn** [comment]
![EFE47377-7879-4CA5-9C6F-601E1954A21A](https://user-images.githubusercontent.com/42986378/98240320-33421b00-1fa4-11eb-89ee-e93a5c5b07ee.jpeg)
![23F90852-F972-4196-A6C3-D5E6C6D37B8B](https://user-images.githubusercontent.com/42986378/98240420-55d43400-1fa4-11eb-87fa-07c8db4ac2bb.jpeg)

是会员并且cookie提示获取成功了

**Comment by blackmatrix7** [comment]
这个感觉和你会员状态有关系，你在APP内能领取任务吗？

**Comment by blackmatrix7** [comment]
把Cookie删掉，别人可以利用你的Cookie来操作你的账号。

**Comment by blackmatrix7** [comment]
问题已复现，新版APP可能有些地方改掉了，需要重新适配，等几天吧。

**Comment by 52znn** [comment]
好的  多谢
