### ISSUE TITLE
Google规则分流疑问

### ISSUE THREAD

**Issue by linger040831** [blackmatrix7/ios_rule_script#581]
规则名称：Google

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/Google

异常规则：ocsp.pki.goog
                  mtalk.google.com

问题描述：这两条规则在ACL4SSR的规则中是包含在https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Google.list内的

抓包截图：

![photo_2022-05-29_11-23-37](https://user-images.githubusercontent.com/84896599/170850615-b5e50efe-934d-4a89-aea8-3a19d3db404e.jpg)
![photo_2022-05-29_11-23-36](https://user-images.githubusercontent.com/84896599/170850616-4f3bfcfe-508c-44d1-b787-6b0421a2cf86.jpg)

调整方案：不知这两条规则会对使用有没有影响，所以想先询问一下，谢谢。

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/blob/test/rule/QuantumultX/Google/Google.list

ocsp.pki.goog 这条在测试版里是有的，因为旧版的会对规则做合并去重，对于QuanX来说不合适，所以新版解决了这个问题。

mtalk.google.com 这条在你提供的规则里没有找到。

注意，测试版在6月中旬会删除掉。

**Comment by blackmatrix7** [comment]
mtalk.google.com 手动加入了测试版

测试版预计下周五合并入正式版，如果不着急建议先用正式版，到时候更新规则就可以。

如果着急可以先用测试版，后续再换成正式版。
