### ISSUE TITLE
添加PrivateTracker数据规则

### ISSUE THREAD

**Issue by honeyjuice** [blackmatrix7/ios_rule_script#582]
建议将Meilieage的PT下载规则
https://raw.githubusercontent.com/Meilieage/webcdn/main/rule/list/PrivateTracker.list

添加到以下规则的爬虫数据来源中
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/PrivateTracker/PrivateTracker.yaml

对比了下差异，多了几个PT站点域名

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/blob/test/rule/Clash/PrivateTracker/PrivateTracker.yaml

暂时加入在测试版中，测试版在周五会合并到正式版，月底删除测试版。

如果不急用可以等周末从正式版更新。
