### ISSUE TITLE
添加DMM分流规则

### ISSUE THREAD

**Issue by honeyjuice** [blackmatrix7/ios_rule_script#583]
我记得dmm的规则以前有过，不知道什么时候去除了
数据源1：ACLSSR
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Dmm.list

数据源2：Meilieage其中的dmm部分
https://github.com/Meilieage/webcdn/blob/main/rule/list/RiHanMeiTi.list

**Comment by blackmatrix7** [comment]
之前是加入的。

后面了解了一下，DMM似乎与成人内容有关，就被我去掉了。

我对DMM不太了解，如果判断错误请告知。

**Comment by honeyjuice** [comment]
DMM是一家日本的电子商务网站，其下业务太多了。视频发行业务、网络游戏业务、FX等金融服务、在线英语会话服务、制造支持业务、邮购、在线租赁、电子书发行业务、太阳能发电业务、娱乐业务、足球业务、VAPE业务、MVNO业务、在线沙龙业务、动漫业务、虚拟货币相关业务等。当然也有R18区，现在DMM的R18区已经改名为FANZA。

**Comment by blackmatrix7** [comment]
感谢告知。

已重新加入 https://github.com/blackmatrix7/ios_rule_script/tree/test/rule/Clash/DMM
