### ISSUE TITLE
希望增加 知乎app 的分流规则

### ISSUE THREAD

**Issue by I-am-R-E** [blackmatrix7/ios_rule_script#586]
请求作者增加：知乎app 的分流规则
最新版的知乎客户端除了域名需要分流之外，域名解析后的IP也需要，因为DNS解析成功后 知乎第二次访问同一个域名会直接访问IP，可能还需添加User-Agent
这里可以看到众多的子域名:https://chaziyu.com/zhihu.com/
谢谢！

**Comment by blackmatrix7** [comment]
增加规则需要一些时间，近期比较忙，后续抓包处理好再回复你。

**Comment by I-am-R-E** [comment]
好的 麻烦您了
