### ISSUE TITLE
关于quantumultx的AllInOne规则发现一处错误

### ISSUE THREAD

**Issue by vhdj** [blackmatrix7/ios_rule_script#588]
[此文件中](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf) 
^https?:\/\/api\.zhihu\.com\/feed-root\/block url script-request-body https://gist.githubusercontent.com/blackmatrix7/2e550ebf28ca60d620654e394ec47e0b/raw/zhihu.js  这条重写的类型错误，不应该是“script-request-body”，而是“script-analyze-echo-response”，正确写法应该是：
^https?:\/\/api\.zhihu\.com\/feed-root\/block url script-analyze-echo-response https://gist.githubusercontent.com/blackmatrix7/2e550ebf28ca60d620654e394ec47e0b/raw/zhihu.js
另外主机名缺失了 103.41.167.236,103.41.167.234,103.41.167.235,103.41.167.226
以上错误导致了知乎部分页面优化功能失效和屏蔽关键词解锁不生效。

**Comment by blackmatrix7** [comment]
谢谢反馈，这是个Bug。

最近暂时没时间修复，建议先直接使用知乎的重写文件。

后续修复完毕再回复你。

**Comment by blackmatrix7** [comment]
已修复。
