### ISSUE TITLE
AdGuard格式的规则改进

### ISSUE THREAD

**Issue by hacamer** [blackmatrix7/ios_rule_script#591]
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/AdGuard/Advertising

AdGuard规则一般以txt结尾 `.txt`

注释的文本是 `!` 而不是 `#`

标题（规则名称）是` ! Title:`

主页是 `! Homepage:`

参考范例 https://easylist.to/easylist/easylist.txt

另外 每个readme文件里的链接似乎有问题 请查看一下

**Comment by blackmatrix7** [comment]
谢谢反馈，已做调整。

README文件的链接实测没有问题。

RELEASE分支下暂时没有文件属于正常情况。
