### ISSUE TITLE
MITM失败导致无法访问apple music具体歌手的歌曲排行页面

### ISSUE THREAD

**Issue by dorty3541** [blackmatrix7/ios_rule_script#592]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：复写去广告

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf

异常规则：hostname = *.58cdn.com.cn,*.atm.youku.com,*.baidu.com,*.beacon.qq.com,*.cloudfront.net,*.com1.z0.glb.clouddn.com,*.gdt.qq.com,*.hxsame.hexun.com,*.iydsj.com,*.jstucdn.com,*.kakamobi.cn,*.kingsoft-office-service.com,*.l.qq.com,*.logic.cpm.cm.kankan.com,*.music.126.net,*.music.127.net,*.ott.cibntv.net,*.pstatp.com,*.sina.com,*.tc.qq.com,*.tv.sohu.com,*.up.qingdaonews.com,*.ximalaya.com,*.zhangle.com,101.201.175.228,203.205.255.16,3gimg.qq.com,47.97.20.12,4gimg.map.qq.com,7n.bczcdn.com,a.apicloud.com,a.qiumibao.com,acs.m.taobao.com,act.vip.iqiyi.com,activity2.api.ofo.com,ad*.sina.com.cn,adpai.thepaper.cn,aes.acfun.cn,agent-count.pconline.com.cn,api*.futunn.com,api-access.pangolin-sdk-toutiao.com,api-ks.wtzw.com,api-mifit.huami.com,api-new.app.acfun.cn,api-one.wallstcn.com,api-release.wuta-cam.com,api.21jingji.com,api.abema.io,api.applovefrom.com,api.bjxkhc.com,api.caijingmobile.com,api.catch.gift,api.cdmcaac.com,api.chelaile.net.cn,api.club.lenovo.cn,api.dangdang.com,api.daydaycook.com.cn,api.douban.com,api.feng.com,api.gaoqingdianshi.com,api.gotokeep.com,api.hanju.koudaibaobao.com,api.haohaozhu.cn,api.huomao.com,api.intsig.net,api.izuiyou.com,api.jr.mi.com,api.jxedt.com,api.k.sohu.com,api.kkmh.com,api.laifeng.com,api.m.mi.com,api.meipian.me,api.mgzf.com,api.pinduoduo.com,api.psy-1.com,api.qbb6.com,api.qiuduoduo.cn,api.rr.tv,api.videozhishi.com,api.vistopia.com.cn,api.vuevideo.net,api.waitwaitpay.com,api.wallstreetcn.com,api.xiachufang.com,api.xueqiu.com,api.yangkeduo.com,api.yizhibo.com,api.zhuishushenqi.com,app-api.jinse.com,app-api.niu.com,app-gw.csdn.net,app.58.com,app.api.ke.com,app.badmintoncn.com,app.ddpai.com,app.dewu.com,app.mixcapp.com,app.poizon.com,app.relxtech.com,app.variflight.com,app.wy.guahao.com,app.xinpianchang.com,app.yinxiang.com,app.zhuanzhuan.com,app3.qdaily.com,appapi.huazhu.com,appconf.mail.163.com,appv6.55haitao.com,asp.cntv.myalicdn.com,b-api.ins.miaopai.com,b.zhuishushenqi.com,bbs.tianya.cn,bdsp-x.jd.com,btrace.qq.com,business-cdn.shouji.sogou.com,business.msstatic.com,c.m.163.com,c.tieba.baidu.com,cap.caocaokeji.cn,capi.mwee.cn,capis*.didapinche.com,ccsp-egmas.sf-express.com,cdn-1rtb.caiyunapp.com,cdn.api.fotoable.com,cdn.dianshihome.com,cdn.moji.com,cdnfile1.msstatic.com,channel.beitaichufang.com,client.mail.163.com,clientaccess.10086.cn,cloud.189.cn,cms.daydaycook.com.cn,cmsapi.wifi8.com,cn.pornhub.com,cntv.hls.cdn.myqcloud.com,consumer.fcbox.com,creditcardapp.bankcomm.com,ct.xiaojukeji.com,ctrl.playcvn.com,ctrl.playcvn.net,ctrl.zmzapi.com,ctrl.zmzapi.net,d*.sinaimg.cn,daoyu.sdo.com,dict-mobile.iciba.com,dili.bdatu.com,dl.app.gtja.com,dsa-mfp.fengshows.cn,dsp-impr2.youdao.com,dsp-x.jd.com,dsp.toutiao.com,dxy.com,e.dangdang.com,easyreadfs.nosdn.127.net,edit.sinaapp.com,explorer.tratao.com,fb.fbstatic.cn,flowplus.meituan.net,foodie-api.yiruikecorp.com,g.cdn.pengpengla.com,games.mobileapi.hupu.com,gateway.shouqiev.com,gfp.veta.naver.com,gg*.cmvideo.cn,goblin.hupu.com,gw-passenger.01zhuanche.com,gw.aihuishou.com,gw.alicdn.com,gw.csdn.net,gw.kaola.com,haojia.m.smzdm.com,heic.alicdn.com,hk.app.joox.com,home.mi.com,huami.com,i.ys7.com,iapi.bishijie.com,ib-soft.net,icc.one,iface.iqiyi.com,ih2.ireader.com,image.suning.cn,images.client.vip.xunlei.com,imeclient.openspeech.cn,img*.10101111cdn.com,img*.g.pptv.com,img-ys011.didistatic.com,img.360buyimg.com,img.jiemian.com,img.meituan.net,img.umetrip.com,impserviceyoudao.com,interface*.music.163.com,intl.iqiyi.com,ios.lantouzi.com,ios.wps.cn,issuecdn.baidupcs.com,**itunes.apple.com**,js.dilidd.com,jxd524.github.io,learn.chaoxing.com,list-app-m.i4.cn,m*.amap.com,m.caijing.com.cn,m.client.10010.com,m.creditcard.ecitic.com,m.ctrip.com,m.ibuscloud.com,m.tuniu.com,m.yhdm.io,ma.ofo.com,mage.if.qidian.com,magev6.if.qidian.com,maicai.api.ddxq.mobi,mangaapi.manhuaren.com,mapi.dangdang.com,mapi.mafengwo.cn,media.qyer.com,mlife.jf365.boc.cn,mm.app.joox.com,mob.mddcloud.com.cn,mobi.360doc.com,mobile-pic.cache.iciba.com,mobileapi-v6.elong.com,mp.weixin.qq.com,mpcs.suning.com,mps.95508.com,mrobot.pcauto.com.cn,mrobot.pconline.com.cn,ms.jr.jd.com,msg.umengcloud.com,msspjh.emarbox.com,news.ssp.qq.com,nnapp.cloudbae.cn,nochange.ggsafe.com,notch.qdaily.com,notice.send-anywhere.com,oimage*.ydstatic.com,open.qyer.com,optimus-ads.amap.com,overseas.weico.cc,p*.meituan.net,p.du.163.com,p.kuaidi100.com,paopao*.qiyipic.com,pic*.ajkimg.com,pic.edaijia.cn,pic.k.sohu.com,pic1.chelaile.net.cn,pic1cdn.cmbchina.com,pocketuni.net,portal-xunyou.qingcdn.com,pss.txffp.com,qt.qq.com,r.inews.qq.com,render-oss-cdn.amap.com,render.alipay.com,res-release.wuta-cam.com,res.xiaojukeji.com,restapi.iyunmai.com,richmanapi.jxedt.com,rtbapi.douyucdn.cn,s*.zdmimg.com,s1.api.tv.itc.cn,s3plus.meituan.net,sa*.tuisong.baidu.com,saad.ms.zhangyue.net,sax*.sina.cn,sax*.sina.com.cn,sdkapp.uve.weibo.com,server-*.imrworldwide.com,service.4gtv.tv,service.iciba.com,sh-gateway.shihuo.cn,shopic.sf-express.com,slapi.oray.net,smkmp.96225.com,smusic.app.wechat.com,snailsleep.net,sp.kaola.com,ss0.bdstatic.com,ssl.kohsocialapp.qq.com,static.vuevideo.net,status.boohee.com,support.you.163.com,supportda.ofo.com,syh.zybang.com,thor.weidian.com,tiasdk.app.wechat.com,tiku.zhan.com,tj.playcvn.com,tqt.weibo.cn,tracker-download.oss-cn-beijing.aliyuncs.com,u*.iqiyipic.com,update.pan.baidu.com,v*-api.miaopai.com,v.cctv.com,v.icbc.com.cn,vali.cp31.ott.cibntv.net,video.dispatch.tc.qq.com,vv.video.qq.com,wap.ngchina.cn,wbapp.uve.weibo.com,web.chelaile.net.cn,webboot.zhangyue.com,weibointl.api.weibo.cn,wmapi.meituan.com,www.bldimg.com,www.bodivis.com.cn,www.cmbc.com.cn,www.cntv.com,www.dandanzan.com,www.didapinche.com,www.dililitv.com,www.flyertea.com,www.hxeduonline.com,www.icourse163.org,www.inoreader.com,www.iyingdi.cn,www.myhug.cn,www.pornhub.com,www.shihuo.cn,www.xiaohongshu.com,www.zybang.com,xueqiu.com,xyst.yuanfudao.com,xyz.cnki.net,y.gtimg.cn,yxhd.hori-gz.com,yxyapi*.drcuiyutao.com,zjh5api.189smarthome.com

问题描述：当对itunes.apple.com进行MITM后访问apple music某一歌手的歌曲排行页面时,会出现访问失败的情况，同时quantumultX的网络活动记录中会出现MITM fail的log

抓包截图：(相关抓包工具的截图。)
![图片](https://user-images.githubusercontent.com/25359346/172052515-bbff89bf-865f-47a3-98a5-fb06ff4afec3.png)
![图片](https://user-images.githubusercontent.com/25359346/172052538-f99ab350-9cd7-4f29-a21c-101141343523.png)
![图片](https://user-images.githubusercontent.com/25359346/172052545-f6b4edee-49cc-40eb-9c62-e8504bf3e127.png)

调整方案：(你希望规则做哪些调整，及其原因。)
虽然手动添加规则-itunes.apple.com后可以使得页面的访问恢复正常，但考虑到用户的操作难度因此建议去除MITM中的itunes.apple.com

**Comment by blackmatrix7** [comment]
已将Apple相关的MITM去除。
