### ISSUE TITLE
佬可以优化下喜马拉雅的去广告规则吗

### ISSUE THREAD

**Issue by dawnAaa** [blackmatrix7/ios_rule_script#593]
在用规则：surge配置，AdvertisingTest.list，AdvertisingTest_domain.list，以及去广告重写模块
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingTest/AdvertisingTest.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingTest/AdvertisingTest_Domain.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule

问题描述：喜马拉雅首页依旧有滚动广告，播放界面有音频广告

调整方案：这是墨鱼佬的圈叉重写规则，https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Rewrite/AdBlock/Ximalaya.conf
希望大佬可以优化一下，自己转换成surge模块没有奏效

**Comment by blackmatrix7** [comment]
不好意思，暂时无法加入。

hostname = *.xima*.*，这个MITM范围太大了。

而且AdvertisingLite不引入脚本处理，只保留Reject规则。

如果能把hostname确定在一个比较小的范围，可以加入reject类型的规则。
