### ISSUE TITLE
Surge规则的Download规则中部分 URL-REGEX 规则导致请求匹配规则时耗时过长

### ISSUE THREAD

**Issue by SyllableSpec** [blackmatrix7/ios_rule_script#594]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Download

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Download/Download.list

异常规则：(.+.)?(torrent|announce.php?passkey=|tracker|BitTorrent|bt_key|ed2k|find_node|get_peers|info_hash|magnet:|peer_id=|xunlei)(..+)?

问题描述：部分URL-REGEX 规则导致请求匹配规则时耗时过长，Surge报错。

抓包截图：
![IMG_2257](https://user-images.githubusercontent.com/59154499/172113115-9236dea7-b1d7-402a-a00c-08176aec8834.jpg)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by SyllableSpec** [comment]
今天Download.list里的这条URL-REGEX 规则   (.+.|^)(360|so|qihoo|360safe|qhimg|360totalsecurity|yunpan).(cn|com)   又报错了。不知道是不是Download.list里所有URL-REGEX规则都会报错
!
[IMG_2275](https://user-images.githubusercontent.com/59154499/172279456-1517369e-5616-42fa-bd9c-21bf926e4c99.jpg)
。

**Comment by blackmatrix7** [comment]
将Surge Download URL-REGEX 规则去掉。

https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Download/Download.list
