### ISSUE TITLE
每个问题的第一个回答的评论加载不出来

### ISSUE THREAD

**Issue by wulifuji** [blackmatrix7/ios_rule_script#6]
如题，不是lite

**Comment by blackmatrix7** [comment]
我这里无法复现这个问题。你用的是什么APP？什么版本？知乎版本是多少？日志里是否有异常信息，如果有贴出来我看下。

**Comment by wulifuji** [comment]
我还以为都有这个问题

我大概知道什么原因了

**Comment by blackmatrix7** [comment]
> 我还以为都有这个问题
> 
> 我大概知道什么原因了

如果能解决麻烦贴出来和大家分享一下。

**Comment by wulifuji** [comment]
资源挂多了，解决方法就是自己找
