### ISSUE TITLE
Quantumult X bilibili去广告报错

### ISSUE THREAD

**Issue by Paris0-0** [blackmatrix7/ios_rule_script#60]
大量报错
2020/11/07 21:01:11:170  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['sections_v2'][0]')
2020/11/07 21:01:11:173  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:01:11:602  <console>    [JS Console]: [ERROR] [BiliBili]
开屏广告处理出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:01:11:602  <console>    [JS Console]: [ERROR] [BiliBili]
标签页处理出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:01:11:602  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:01:11:602  <console>    [JS Console]: [ERROR] [BiliBili]
直播去广告出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:01:11:603  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:04:32:767  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['sections_v2'][0]')
2020/11/07 21:04:32:773  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:04:36:627  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['sections_v2'][0]')
2020/11/07 21:04:36:629  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')
2020/11/07 21:12:03:003  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['sections_v2'][0]')
2020/11/07 21:12:03:006  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'magicJS.response.body')

**Comment by blackmatrix7** [comment]
已修复
