### ISSUE TITLE
quanx和loon中什么值得买脚本出现错误（surge无法测试）

### ISSUE THREAD

**Issue by 6asd** [blackmatrix7/ios_rule_script#601]
rewrite-script-最新master每日更新分支中出现脚本错误 导致最新allinone也出现同样报错，具体错误日志如下
状态:		已释放
网络请求:	无
描述:		 	
❚  script-response-header
❚  https://homepage-api.smzdm.com/v3/home?device_brand_name=Apple&device_type_name=iPhone11%2C6&f=iphone&filter_brand=&filter_category=&filter_channel=&filter_zhifa=&haojia_title_abtest=a&is_cache=0&limit=20&page=1&past_num=0&pch=izhihu42&screen_h=2688&screen_w=1242&sign=E84D175888B99208E9B3A4209EF2086C&sys_o=ios&sys_v=15.5&tab_id=0&time=1654961388000&time_sort=&update_timestamp=1654961388543&v=10.3.0&weixin=1
❚  ^https?:\/\/homepage-api\.smzdm\.com\/v3\/home
❚  https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/javascript/7abc2b807287bb592981145658b7b20b.js
日志:		 	
❚  [ERROR] [什么值得买]
首页去广告出现异常：SyntaxError: JSON Parse error: Unexpected identifier "undefined"

首页去广告和好价去广告相同异常报错

辛苦开发者修复！感谢！（不定时更新的分支中无报错）

**Comment by blackmatrix7** [comment]
能否提供下什么值得买的版本，这个脚本比较长时间没有更新了，可能没有适配新版。

**Comment by 6asd** [comment]
软件为 美区最新版 10.3.0的版本 感谢！

**Comment by blackmatrix7** [comment]
脚本没有问题，可以适配最新版。

是生成器的Bug导致转换后的重写规则不正确，已修复，在QuanX上测试了一下没发现问题。

Loon尚未测试，如果有问题你再打开issue。
