### ISSUE TITLE
复写AllInOne.conf中包含iTunes域名的MITM导致Apple Music无法加载“浏览”

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#602]
复写AllInOne.conf中包含iTunes域名的MITM导致Apple Music无法加载“浏览”。quanx提示MITM Fail

规则名称：
AllInOne.conf

规则链接：
`https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf`

异常规则：
`itunes.apple.com`

问题描述：
如标题

调整方案：删除

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
