### ISSUE TITLE
ByteDance分流规则优化

### ISSUE THREAD

**Issue by aimetu** [blackmatrix7/ios_rule_script#603]
规则名称：ByteDance.list

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/ByteDance/ByteDance.list

规则名称：TikTok.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/TikTok/TikTok.list

异常规则：冲突

问题描述：ByteDance(字节跳动)中包含TikTok(海外抖音)分流规则，二者单独设置分流后，由于设置的ByteDance规则优先，所以会导致TikTok引用ByteDance分流设置

调整方案：希望能从ByteDance踢除TikTok站点，二者好单独分流使用

**Comment by blackmatrix7** [comment]
很好的提议，已排除掉TikTok。

你先试试，如果还有问题再打开issue。
