### ISSUE TITLE
可否加入Britbox 分流规则，非常感谢🙏

### ISSUE THREAD

**Issue by XUYinong** [blackmatrix7/ios_rule_script#604]

**Comment by blackmatrix7** [comment]
暂时没有时间添加规则，可以先留着issue，后面有精力再处理。

不过优先级比较低，近期不会处理它。

**Comment by blackmatrix7** [comment]
流媒体类型的规则，因为可能需要特定的节点IP才能访问，暂时没有条件添加。

**Comment by XUYinong** [comment]
你好，我自行抓包以User Agent 的方式过滤出了Britbox UK (BritBox 在北美也有运营，但与UK并非同一应用，特此区分) 使用的链接地址，自己测试了一下没有问题
# > Britbox UK
DOMAIN-SUFFIX,britbox.com
DOMAIN-SUFFIX,britbox.co.uk
DOMAIN-SUFFIX,bbc.co.uk
DOMAIN-SUFFIX,bb-static.com
DOMAIN-SUFFIX,massive-itv.com
DOMAIN-SUFFIX,itv.com
DOMAIN,itvpnp.stage.ott.irdeto.com
DOMAIN,itvpnp.live.ott.irdeto.com
