### ISSUE TITLE
能否加入这个全是ipv6 DNS

### ISSUE THREAD

**Issue by heudisi** [blackmatrix7/ios_rule_script#606]
https://raw.githubusercontents.com/lennylxx/ipv6-hosts/main/hosts

**Comment by blackmatrix7** [comment]
这个是作用是？生成重写规则吗？

**Comment by heudisi** [comment]
分流的ipv6 如果能生成复写也不错

**Comment by blackmatrix7** [comment]
很好的提议，不过目前还不支持，后面会添加此功能。

**Comment by heudisi** [comment]
https://dns.icoa.cn 这里有些ipv6整合就好

**Comment by blackmatrix7** [comment]
这两个不是一个东西，https://dns.icoa.cn/适合自己在配置文件中直接修改，基本上不会有什么变化。

**Comment by blackmatrix7** [comment]
仔细看了下文件的更新时间，是2018年。

如果把它转换为重写规则，而它又长达数年不更新的话，可能会导致使用此重写规则后部分网站无法访问。

所以，最终觉得不会加入这个hosts。

如果需要建议手动做个替换修改，毕竟4年不更新了。
