### ISSUE TITLE
Clash的Global规则说明存在问题

### ISSUE THREAD

**Issue by MreDiaos** [blackmatrix7/ios_rule_script#607]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Clash/Global

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml

异常规则：readme介绍中包含和排除的规则都有PROXY这个规则集，不太清楚是单纯说明里错误还是实际规则一样出现了这个问题。亦或者是我没有理解正确。

问题描述：截图所示

抓包截图：(相关抓包工具的截图。)
![Screenshot_20220619-143820_GitHub.jpg](https://user-images.githubusercontent.com/94931475/174469041-86712ce4-7980-489c-8a35-3285dafb45ec.jpg)
调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
先打开issue，否则容易忘掉。

**Comment by blackmatrix7** [comment]
已修复。
