### ISSUE TITLE
Advertising.list的规则怎么导入qx或shadow啊

### ISSUE THREAD

**Issue by yaoshuangshl** [blackmatrix7/ios_rule_script#608]
如题，我花了整整一下午时间查youtube google gayhub，始终无法找到答案，加了3个qq群也没人知道，app内每一个地方尝试都提示资源不可用或url错误。所以这个连接到底是在qx或shadow或adguard哪里填写啊，我已经崩溃了，这么难吗

**Comment by blackmatrix7** [comment]
可以理解你的心情，但是这里无法提供任何客户端的使用帮助和讨论，所以还是建议你通过其他方式寻找解决方法。

抱歉帮不上你。
