### ISSUE TITLE
IP规则没有加no-resolve，导致DNS泄漏

### ISSUE THREAD

**Issue by fshh1988** [blackmatrix7/ios_rule_script#609]
大部分ip规则没有no-resolve，以前都是有的，麻烦作者加回去一下，谢谢。

**Comment by blackmatrix7** [comment]
麻烦提供下规则文件的链接。

**Comment by fshh1988** [comment]
> 麻烦提供下规则文件的链接。

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml

**Comment by fshh1988** [comment]
我自己写了个脚本，几行命令搞定，谢谢。考虑到通用性问题，可能作者不方便修改。

**Comment by blackmatrix7** [comment]
![20220623093555](https://user-images.githubusercontent.com/27717518/175188681-f32f2071-7a0a-4dc5-9994-843b5bf0d6f0.png)

参考一下这个。

按我的理解，classical类型的规则，无论是否添加no-resolve，都会触发DNS解析。

所以在新版将它去掉了。

如果理解错误请告知。

**Comment by fshh1988** [comment]
嗯，clash其实我没测试过，按作者说的字面理解确实可能会解析。
但是我是用的openclash，加了no-resolve,在上游监测确实不会解析规则内的DNS了
对openclash是有效的。
感谢回复

**Comment by blackmatrix7** [comment]
RULE-SET,apple,DIRECT,no-resolve

我看网上的例子，还可以这么写。

你可以试试。

**Comment by wxh00111** [comment]
希望clash规则的classical类型中的IP-CIDR后面加上no-resolve，不加的话容易导致一些问题，比如youtube没有播放历史记录

**Comment by fshh1988** [comment]
> 希望clash规则的classical类型中的IP-CIDR后面加上no-resolve，不加的话容易导致一些问题，比如youtube没有播放历史记录

看楼上作者回复的写法，这样就可以了

**Comment by fshh1988** [comment]
> 希望clash规则的classical类型中的IP-CIDR后面加上no-resolve，不加的话容易导致一些问题，比如youtube没有播放历史记录

`rules:
  - RULE-SET,Rule-provider-YouTube,Youtube,no-resolve
  - RULE-SET,Rule-provider-Netflix,Netflix,no-resolve
  - RULE-SET,Rule-provider-Google,Google,no-resolve
  - RULE-SET,Rule-provider-Microsoft,Microsoft,no-resolve
  - RULE-SET,Rule-provider-Telegram,Telegram,no-resolve
  - RULE-SET,Rule-provider-Apple,Apple,no-resolve
  - RULE-SET,Rule-provider-Disney,Disney,no-resolve
  - RULE-SET,Rule-provider-TikTok,TikTok,no-resolve
  - RULE-SET,Rule-provider-Bilibili,Bilibili,no-resolve
  - RULE-SET,Rule-provider-Spotify,Spotify,no-resolve
  - RULE-SET,Rule-provider-PayPal,PayPal,no-resolve
  - RULE-SET,Rule-provider-GlobalMedia,GlobalTV,no-resolve
  - RULE-SET,Rule-provider-PlutoTV,GlobalTV,no-resolve
  - RULE-SET,Rule-provider-NetEaseMusic,NetEaseMusic,no-resolve
  - RULE-SET,Rule-provider-Game,Game,no-resolve
  - RULE-SET,Rule-provider-PrivateTracker,DIRECT,no-resolve
  - RULE-SET,Rule-provider-Global,Global,no-resolve
  - RULE-SET,Rule-provider-CustomizeProxy,Others,no-resolve
  - RULE-SET,Rule-provider-ChinaIPs,DIRECT
  - MATCH,Others`

**Comment by wxh00111** [comment]
> classical

classical中还有其他类型的规则，会有影响吗？

**Comment by wxh00111** [comment]
> > 希望clash规则的classical类型中的IP-CIDR后面加上no-resolve，不加的话容易导致一些问题，比如youtube没有播放历史记录
> 
> 看楼上作者回复的写法，这样就可以了

classical类型中还有其他类型的规则会有影响吗？

**Comment by yoshyv** [comment]
> 按我的理解，classical类型的规则，无论是否添加no-resolve，都会触发DNS解析。
> 
> 所以在新版将它去掉了。
> 
> 如果理解错误请告知。

挖尸一下。如果classical类型里面所有IP规则都有no-resolve的话就能避免掉解析，也就是防止泄漏dns。
并且classical不同于ipcidr类型，无法在ruleset后面添加no-resolve让其中的IP分流不去解析。
参考这
https://dreamacro.github.io/clash/configuration/rules.html#rule-set
`When encountering RULE-SET, Clash will resolve the domain name to an IP address when the ruleset is of type IPCIDR. If you want to skip the DNS resolution, use no-resolve option for the RULE-SET entry.`

为了避免泄漏dns，就应该在优先级高的位置放各种域名规则和无需解析的ip规则，最后兜底才用需要解析判断ip分流的规则。
希望能考虑下这点提供两版规则。一个是带no-resolve给放在优先级高的位置，一个不带放在最后兜底。或者拆分domain和ip-cidr成两个。
例如上放的google分流规则里面的IP规则兜底，如果不加no-resolve，上面域名也没匹配上可能根本不会走，这些可以分开单独文件？
