### ISSUE TITLE
希望可以提供GitLab仓库

### ISSUE THREAD

**Issue by ArriettyQAQ** [blackmatrix7/ios_rule_script#610]
鉴于GitHub访问困难，而GitLab访问则无此问题，希望可以提供GitLab仓库，在此表示感谢。

**Comment by blackmatrix7** [comment]
多平台的支持在新版时就已经写好了，不过后面考虑控制项目的传播范围，就没有启用这个功能。

现阶段，你可以先试试 https://ghproxy.com/
