### ISSUE TITLE
重写脚本里有淘宝重定向302规则，导致淘宝打不开

### ISSUE THREAD

**Issue by Hwatu** [blackmatrix7/ios_rule_script#613]
平台 Mac M1 Max
软件 quantumult X
使用浏览器访问 www.taobao.com 显示重定向太多
规则： 
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf
这条规则导致
^https?:\/\/(www.)?taobao\.com\/ url 302 https://taobao.com/

**Comment by blackmatrix7** [comment]
谢谢 反馈，已修复。
