### ISSUE TITLE
Advertising.list中导致B站模块功能失效

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_script#62]
你好，在Advertising.list中的 URL-REGEX,^https?+:\/\/app\.bilibili\.com\/x\/v\d\/splash\/ 会导致哔哩哔哩模块中的脚本去开屏广告失效，能不能去除这条

**Comment by blackmatrix7** [comment]
这条之前已经被我加入黑名单了，尝试更新一下远程文件试试。

**Comment by zjcfynn** [comment]
还是有，这个文件中
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list

**Comment by zjcfynn** [comment]
直接把包含bilibili的条目都屏蔽掉

**Comment by blackmatrix7** [comment]
之前只去除了复写，没有去除分流规则中的这条规则，晚点会更新。

**Comment by blackmatrix7** [comment]
已经更新去除
