### ISSUE TITLE
Mail规则补全

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#621]
规则名称：Mail

规则链接：m.hotmail.com（已包含在Microsoft规则中，希望注明）, apple.imap.mail.yahoo.com

异常规则：

问题描述：实际使用发现outlook邮箱走的规则是m.hotmail.com，以及缺少Yahoo邮箱

抓包截图：

调整方案：添加规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已补充。
