### ISSUE TITLE
新浪微博网页打开白屏问题

### ISSUE THREAD

**Issue by rule-airport** [blackmatrix7/ios_rule_script#622]
规则名称：AdvertisingLite

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/AdvertisingLite/AdvertisingLite_Domain.list

异常规则：h5.sinaimg.cn

问题描述：当把这个 REJECT 后无法打开网页版的新浪微博，当我手动允许后可以打开网页版微博。

调整方案：希望删除这个规则

**Comment by blackmatrix7** [comment]
没有发现会白屏的链接，麻烦提供一下。

**Comment by rule-airport** [comment]
> 没有发现会屏白的链接，麻烦提供一下。

https://weibo.com/n/BoPeeeep
https://weibo.com/n/sunwear
这样的用户页面无法打开。

**Comment by blackmatrix7** [comment]
谢谢反馈，已修复。
