### ISSUE TITLE
Wechat规则补充

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#624]
规则名称：Wecaht

规则链接：sgfindershort.wechat.com

异常规则：

问题描述：

[抓包截图：
![20220711093319](https://user-images.githubusercontent.com/57618347/178172782-5a70eb10-5b71-4e47-b151-5e07ce7d1c84.jpg)

调整方案：添加规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入。
