### ISSUE TITLE
WeChat list 和 Instagram 有冲突

### ISSUE THREAD

**Issue by neutron1988** [blackmatrix7/ios_rule_script#626]
规则名称：Wechat.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/QuantumultX/WeChat/WeChat.list

异常规则：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/QuantumultX/WeChat/WeChat.list

问题描述：QuantumultX 加载 Wechat.list并设置为直连之后，Instagram 无法访问，设置为代理后，Instagram 正常

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
需要找个时间安装注册Instagram验证一下，可能要晚些才能处理了。

**Comment by blackmatrix7** [comment]
测试无法复现此问题。

如果有确认冲突的规则，麻烦提供一下。

issue我先关闭了。
