### ISSUE TITLE
services.googleapis.cn直连导致Google play商店无法下载应用

### ISSUE THREAD

**Issue by justdoiting** [blackmatrix7/ios_rule_script#627]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：ChinaMax

规则链接：https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml

异常规则：services.googleapis.cn

问题描述：services.googleapis.cn在ChinaMax中直连会导致Google play商店不能下载应用

抓包截图：(相关抓包工具的截图。)
![image](https://user-images.githubusercontent.com/109136320/178437073-dfab5322-cab9-4c61-ab1c-4fa1acc522fc.png)

调整方案：(你希望规则做哪些调整，及其原因。)
希望可以将services.googleapis.cn加入Global规则中

**Comment by blackmatrix7** [comment]
![20220712155426](https://user-images.githubusercontent.com/27717518/178438926-691dafc6-ed42-44db-a060-df1c5a9b2ac9.png)

目前看起来国内都可以正常直连

**Comment by blackmatrix7** [comment]
按我的理解，如果DNS将解析结果指向北京的IP，那即使走代理应该也是访问不了的。

或者说这个北京的IP，仅限国外访问，禁止国内访问？

**Comment by blackmatrix7** [comment]
是我理解错误。

services.googleapis.cn走代理后，应该是有代理服务器配置的DNS进行解析，所以不会解析到北京的IP。

已经把它加入到Proxy，并从China中移除。
