### ISSUE TITLE
【建议】希望加上分流gfwlist

### ISSUE THREAD

**Issue by Sagittarius16th** [blackmatrix7/ios_rule_script#628]
https://github.com/gfwlist/gfwlist
原版不会转换，看看大佬可以不，我平时的分流其实就是geoip cn direct；final final
但是这个有很多时候并不能准确的以我的想法走直连还是代理。
个人需求其实就是被墙的走代理，其余能直连就直连。
并不强求，如果能做最好！
感谢。

**Comment by blackmatrix7** [comment]
我看了下，文件内容是Base64编码的。

添加这个数据源的支持，需要单独为它写一套定制化的逻辑，这样定制化的代码过多，不利于项目的维护。

是否加入还需要再评估一下。

5Y+m5aSW77yM4oCcRXZlcnlvbmUga25vd3MgdGhhdCBuZXRpemVucyBpbiBNYWlubGFuZCBDaGluYSBhcmUgdW5kZXIgb3BwcmVzc2lvbi4g4oCd77yMUkVBRE1F5Lit6L+Z5qC355qE5YaF5a6577yM5Y+v6IO95Lya5bim5p2l5LiN5b+F6KaB55qE6bq754Om77yM5pqC5pe25LiN6ICD6JmR5Yqg5YWl5LqG44CC
