### ISSUE TITLE
国内抖音问题

### ISSUE THREAD

**Issue by MoSplain** [blackmatrix7/ios_rule_script#63]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Proxy/Domain.list中amemv.com规则会影响国内抖音无法使用，添加直连后解决，麻烦大佬验证下

**Comment by blackmatrix7** [comment]
谢谢反馈。
https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/proxy.txt
这个数据源会把抖音加入proxy，不清楚原因，看了下里面感觉问题比较多。
晚点会把它剔除掉。

**Comment by blackmatrix7** [comment]
已经去掉了
