### ISSUE TITLE
增加nga玩家社区规则

### ISSUE THREAD

**Issue by ameyukisora** [blackmatrix7/ios_rule_script#638]
nga已上线显示ip归属地功能，此规则方便大家穿梭国际之间发帖（bushi）

规则列表：
[https://raw.githubusercontent.com/ameyukisora/Clash-Rule/master/provider/nga.yaml](https://raw.githubusercontent.com/ameyukisora/Clash-Rule/master/provider/nga.yaml)

**Comment by blackmatrix7** [comment]
谢谢提供，已加入。
