### ISSUE TITLE
B站播放详情页有广告

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_script#64]
B站播放详情页有广告或推广链接，应该是js没过滤到，surge的B站模块

**Comment by blackmatrix7** [comment]
这个广告没抓到数据，目前没办法去除。如果你知道哪个接口可以跟我说。

**Comment by zjcfynn** [comment]
我也没有找到

**Comment by blackmatrix7** [comment]
暂时没什么办法了，好在这个广告不是很影响体验。

**Comment by zjcfynn** [comment]
概念版居然没有，这俩版本还有这区别

**Comment by blackmatrix7** [comment]
那就先用概念版吧，这个推测是传输的二进制数据，暂时没办法处理。看看有没有大牛能解决吧。
