### ISSUE TITLE
Telegram规则出现错误

### ISSUE THREAD

**Issue by stefaneliu** [blackmatrix7/ios_rule_script#643]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Telegram

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list

异常规则：OR,((IP-ASN,44097,no-resolve),(IP-ASN,59930,no-resolve),(IP-ASN,62014,no-resolve),(IP-ASN,62041,no-resolve),(IP-ASN,211157,no-resolve))

问题描述：这一段内容似乎surge desktop 3.5.8 无法辨认。

抓包截图：
<img width="258" alt="截屏2022-07-22 22 28 06" src="https://user-images.githubusercontent.com/59643653/180460922-394da74b-8225-42c6-a551-d1c4fce99ee1.png">

调整方案：我不懂语法。。。。就是不知道这个错误该怎么解决啊？

**Comment by blackmatrix7** [comment]
必须要Surge4才能支持OR的规则。

建议更新Surge，或者使用旧版的规则。

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/e54156e2f1794f41627fbec3fec565c2f695cbd8/rule/Surge/Telegram/Telegram.list
