### ISSUE TITLE
Loon上使用知乎助手Plus加载缓慢

### ISSUE THREAD

**Issue by ravy-alt** [blackmatrix7/ios_rule_script#644]
脚本名称：知乎助手Plus

APP版本：知乎8.25.1

客户端名称：Loon

客户端版本：2.1.20

问题描述：Loon在使用知乎助手时首页加载慢、关注页面加载慢、回答浏览页面下方广告位长期为灰色；相同配置下Quantumult X和Surge不存在这个问题。
 
![IMG_0101](https://user-images.githubusercontent.com/26875324/180590395-1770b85d-0712-4122-9f90-c699c33d1149.PNG)

复现方式：

1. 在Loon上配置知乎去广告规则、知乎MITM、知乎助手Plus
2. 进入知乎可发现以上问题

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
这个是客户端的Bug。

从TF的422版本开始就会出现此问题，商店版本也同样存在此问题。

可以先降级使用，等待作者修复。

![image](https://user-images.githubusercontent.com/27717518/180592541-43cf463b-a41f-467c-8527-b709508fadcf.jpeg)
