### ISSUE TITLE
多看阅读无法访问云空间

### ISSUE THREAD

**Issue by LuzMasonj** [blackmatrix7/ios_rule_script#645]
规则名称：Advertising.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：
HOST,api.micloud.xiaomi.net,Advertising

问题描述：
该条规则会导致小米旗下的多看阅读无法访问云空间，其结果为无法同步上传下载图书。
抓包截图：(相关抓包工具的截图。)
![166FCFB3-39FC-4A65-BA4B-6AFB0DDBCC1C](https://user-images.githubusercontent.com/27768847/180600537-d9940010-7d85-476f-b6c7-e06a0c9edf47.png)

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
