### ISSUE TITLE
知乎助手失效了

### ISSUE THREAD

**Issue by Sheldontao** [blackmatrix7/ios_rule_script#646]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：

APP版本：qx 1.0.30-707；zhihu：8.3.0（8020）

客户端名称：

客户端版本：

问题描述：

复现方式：

1. ………
2. ………………

已使用空白配置文件验证： 不会

之前一般只要把知乎退了重新进就行，今天突然脚本执行不出来了

box.js重新打开没啥变化
日志：
---
READ DATA [zhihu_blocked_users][8584343ad4b22cc5bdf1400e46ae90ea](object)
{"会员推荐":"00000000000000000000000000000000","故事仙女":"2baface78b00136188737979b5e4b6f8","莫仙":"4c3a18b8a40aa9f15cd60ba89e0ad872","沐杉蓝":"1b6d7fb4fe7858e90d8381ad14828b14","花浪":"5b281a03a429d2188a15d9265e95df47","盐选点金":"9f8e736a6d629c39bd6f84660a949e79","睡前消息":"22adc602755babbe0e486806a83967e8","疯狂小杨哥":"fbd8520a7a2fc86e8e83719fdb6332e7","盐选推荐":"f508f14833f52639e8c2dbbbff7d8933","大牛聊DeFi":"cb5b72ff6cacd4e749ac7475e23f0176","西部决策网D视频":"9bfc8d75dea00de1080ac029deae8266","小央视频":"48883a48a567133caccd995d7c7d34b7","风行财富密码":"aa60dd32936cd289c2090952997f0a81","历史环游记":"c167dea2f593c4315cfff1e9ea6d023a","盐选科普":"b13b0a3f97549f3854ce96b2faa41a55","知乎用户83UcjK":"33cc5640e7b6c2f207213a92fb884358","剧说叨叨":"79e061b7e0164f5b64f5f981844b66c9","斯巴达电影":"352e489696c7f90fe79d0a76cd5a88ea","知乎用户PusW1F":"08ac6fdb097d992079f52cee18db064a","知识来了":"3e092186a5ca026d04c1dd89e42ef2c5","日用窍门":"1e8c491df19309a2cc62f1e9593f05ad","桥视频":"427f05afa55453e3cab54b30150154d1","石榴熟了":"e8b05aca437895104d8e05685a5d564e","零九":"383ca2c2839d04142ad5d43e99ef55ff","四川观察":"5de0bd7bec3e56341b7f6b2d42ffede6","观察者网":"0f266fddf1315d97c652161dd58de5e1","高原战士":"b75a0ec53e1ce4a0e6792d81046bc84f","故事档案局":"9714a0a7d9164fb8d68d8c983f9799b5","知乎放映厅":"4acb7131d089f70c9f7469583b631467","知乎故事大赛":"11f81fd09f3e27064b676802c7772f4c","知乎视频":"15d2cc02530e0b4e37838eba04dabfa9","知乎答案奇遇夜":"a51842622e5b9f77277d0bc39b301ea4","知乎盐选会员":"17c6a13f6086efebfaf728cf6b37f908","苍野故事城":"943129da84e5d1d507f32f56ee9e864b","酷猫街拍女神":"a100937bf913b1d9ad600a1d8ddfc83c","健身问答":"57926913e3af6b4cfdfae25ad8f91f55","浮云游系列":"263fbd8114e37d083cfc9f03895b7296","静静香":"85950ec2c9b8d6bb808b40184ed321dc","一行白鹭进铁锅":"12122838ee4b9e693f2482e37bd63b4f","推理档案馆":"6ffe09933d10643ede0423e504385d47","猪里猪气":"849e4d5a310f21f472bbb5b549b4a104","尽力而为的人":"f70304eb8f72e0743f30f4683e301810","共青团中央":"53fa7c2fb1fcade1f2eb8e25e10e0f84"}
2022/07/23 20:46:32:416  <console>    [JS Console]: [ERROR] [知乎助手]
知乎推荐列表去广告出现异常：SyntaxError: Invalid regular expression: unmatched parentheses
2022/07/23 20:46:32:418  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.317S.
2022/07/23 20:46:34:382  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
2022/07/23 20:46:34:386  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
2022/07/23 20:46:34:389  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.014S.
2022/07/23 20:46:34:473  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
2022/07/23 20:46:34:478  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
2022/07/23 20:46:34:481  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.014S.
2022/07/23 20:46:47:285  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
2022/07/23 20:46:47:291  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
2022/07/23 20:46:47:294  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.017S.
2022/07/23 20:46:47:510  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
2022/07/23 20:46:47:515  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
2022/07/23 20:46:47:519  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.015S.
2022/07/23 20:46:50:591  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
2022/07/23 20:46:50:596  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
2022/07/23 20:46:50:599  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.014S.

---
脚本执行情况：

❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
❚  [DEBUG] [知乎助手]
用户登录用户信息，接口响应：{"id":"8584343ad4b22cc5bdf1400e46ae90ea","url_token":"xun-zhao-74-15-49","name":"TaiyangXiang","use_default_avatar":false,"avatar_url":"https://pic1.zhimg.com/v2-8b99d617588b44df216fca15d1958cf7_l.jpg?source=32738c0c","avatar_url_template":"https://pic2.zhimg.com/v2-8b99d617588b44df216fca15d1958cf7.jpg?source=32738c0c","is_org":false,"type":"people","url":"https://api.zhihu.com/people/8584343ad4b22cc5bdf1400e46ae90ea","user_type":"people","headline":"摇摇杯泡枸杞","headline_render":"摇摇杯泡枸杞","is_active":true,"description":"白天外卖晚上滴滴半夜保安","gender":1,"is_advertiser":false,"ip_info":"IP 属地山西","vip_info":{"is_vip":false,"rename_days":"60","entrance":{"icon":{"url":"https://pic3.zhimg.com/v2-5b7012c8c22fd520f5677305e1e551bf.png","night_mode_url":"https://pic4.zhimg.com/v2-e51e3252d7a2cb016a70879defd5da0b.png"},"title":"盐选会员 为你严选好内容","expires_day":"","sub_title":null,"button_text":"首月 9 元","jump_url":"zhihu://vip/purchase","button_jump_url":"zhihu://vip/purchase","sub_title_new":null,"identity":"guest"},"entrance_new":{"left_button":{"title":"精选会员内容","description":"为您严选好内容","jump_url":"zhihu://market/home"},"right_button":{"title":"开通盐选会员","description":"畅享 10w+ 场优质内容等特权","jump_url":"zhihu://vip/purchase"}},"entrance_v2":{"title":"续费盐选会员","sub_title":"畅享 5000W+ 优质内容","jump_url":"https://www.zhihu.com/xen/market/vip-privileges","button_text":"最低0.5元/天","sub_title_color":"#999999","sub_title_list":["已过期"],"card_jump_url":"https://www.zhihu.com/xen/market/vip-privileges","coupon_remain_sec":-1},"rename_frequency":0,"rename_await_days":0},"level_info":{"exp":105092,"level":7,"nickname_color":{"color":"","night_mode_color":""},"notice":"签到领盐值","level_icon":"https://pica.zhimg.com/v2-925f3f81dab3105fd42b785305a1cc28_l.png?source=32738c0c","icon_info":{"url":"https://pica.zhimg.com/v2-925f3f81dab3105fd42b785305a1cc28_l.png?source=32738c0c","night_mode_url":"https://pic1.zhimg.com/v2-4e20c1d51a61ffb91eebdc40e420e382_l.png?source=32738c0c","width":93,"height":51},"is_marked":false,"icon_info_v2":{"url":"https://pica.zhimg.com/v2-835da626f7a3081e23bccab15354ee46_l.png?source=32738c0c","night_mode_url":"https://pica.zhimg.com/v2-835da626f7a3081e23bccab15354ee46_l.png?source=32738c0c","width":102,"height":60}},"badge":[],"badge_v2":{"title":"","merged_badges":[],"detail_badges":[],"icon":"","night_icon":""},"all_verify_apply":{"apply_status":0,"applys":[],"show_entrance":true},"account_status":[],"audio":{"id":"","duration":0,"type":"audio","url":""},"is_following":false,"is_followed":false,"is_activity_blocked":false,"is_baned":false,"is_locked":false,"is_force_renamed":false,"is_apply_renamed":false,"is_hanged":false,"is_force_reset_password":false,"is_noti_reset_password":false,"is_destroy_waiting":false,"follower_count":41,"following_count":85,"answer_count":27,"question_count":3,"articles_count":5,"independent_articles_count":0,"columns_count":0,"zvideo_count":0,"favorite_count":26,"favorited_count":144,"lite_favorite_content_count":0,"pins_count":7,"reactions_count":0,"shared_count":0,"voteup_count":142,"thanked_count":39,"live_count":2,"hosted_live_count":0,"participated_live_count":2,"included_answers_count":0,"included_articles_count":0,"included_text":"","marked_answers_text":"","following_columns_count":8,"following_topic_count":46,"following_question_count":63,"following_favlists_count":0,"recognize_count":0,"recognized_count":0,"recognize_balance":0,"is_professional":false,"available_medals_count":0,"business":{"id":"","type":"topic","url":"","name":"","avatar_url":""},"locations":[],"employments":[{"job":{"id":"21183027","type":"topic","url":"https://api.zhihu.com/topics/21183027","name":"外卖员","avatar_url":"https://pic1.zhimg.com/e82bab09c_l.jpg?source=32738c0c"},"company":{"id":"20001899","type":"topic","url":"https://api.zhihu.com/topics/20001899","name":"美团外卖","avatar_url":"https://pica.zhimg.com/v2-a98e4dbde41ab0daf416a021174e02ce_l.jpg?source=32738c0c"}},{"job":{"id":"19656689","type":"topic","url":"https://api.zhihu.com/topics/19656689","name":"保安","avatar_url":"https://picx.zhimg.com/v2-39c1be68002a2f1e01771fc1ea5ff226_l.jpg?source=32738c0c"},"company":{"id":"","type":"topic","url":"","name":"Mc  Donald","avatar_url":"https://pic1.zhimg.com/e82bab09c_l.jpg?source=32738c0c"}}],"educations":[{"school":{"id":"19606307","type":"topic","url":"https://api.zhihu.com/topics/19606307","name":"南开大学","avatar_url":"https://pic1.zhimg.com/v2-b66f648232d915647345a2ec00598b96_l.jpg?source=32738c0c"},"major":{"id":"20172057","type":"topic","url":"https://api.zhihu.com/topics/20172057","name":"应用物理学","avatar_url":"https://pic1.zhimg.com/v2-cf138ec0d737a3524d8c9afb2b8bf9aa_l.jpg?source=32738c0c"},"diploma":3}],"cover_url":"","cover_url_template":"","juror":{"is_juror":false,"vote_count":0,"review_count":0,"review_liked_count":0},"is_bind_sina":false,"uid":"825865682280411136","email":"16****@qq.com","phone_no":"173****0160","renamed_fullname":"","created_at":1489681722,"actived_at":1489767989,"draft_count":3,"total_creation_count":42,"total_following_count":202,"total_favorite_count":26,"is_bind_phone":true,"is_realname":true,"is_unicom_free":false,"has_applying_column":false,"is_enable_watermark":true,"is_enable_double_click_voteup":true,"is_enable_unfriendly_message":true,"is_enable_signalment":true,"is_moments_user":0,"open_ebook_feature":true,"agora_published":true,"friendly_score":5,"auto_sending_creations":false,"has_daily_recommend_permission":false,"entrance":["add_video","use_processing_staging_content"],"push_channel":"pm_n_2d6f2ccc4b8b017c584a6030b18afa3c","algorithm_right":{"sarcasm":"off"},"oppose_right":{"status":"none","score":"low"},"verify_status":"not_applied","infinity":{"user_id":"0","is_activated":true,"url":"https://www.zhihu.com/zhi?utm_campaign=zhi_three\u0026utm_source=zhihuapp\u0026utm_medium=button","show_my_infinity_entrance":true,"consultations_count":0},"mcn_user_info":{"status":0,"showcase_permission":0,"jingdong_param":"d5e6f2f714c24fa65d2750607b17f492e577fe781c7e1a26207289fa347e3c2afc99b9f2d27e64df1a1db29a4d367c8a","jingdong_app_param":"840dad069ca5ccebffda8b7fb3da6070e3513c808265b2be3af1514f01c57bde14df6c255e4dbce90b5f9658ac5f6520f0e49816c9fae39f99dee22b058b0e17b50a09284fe08b2ccc09b38238d06510e6ef8740aa22bc5ac1e5dce9caeebd04096064dcef8e25eaa0f067c0dd93107e926eb72332cc6ca59f8c040a62fe1addd666325d6370823080e24945deea8748230dde194ca9db14cec1885f1d695f74c72662f1420a4fd4","available_source":[],"bind_info":[{"pid":"","source":"jingdong"},{"pid":"","source":"taobao"}],"goods_count":0},"creator_info":{"is_allow_enter":true,"activity_topping":false},"finance_info":{"url":"","show_my_finance_entrance":false},"self_recommend":"","exposed_medal":{"medal_id":"972475023013875712","medal_name":"有口皆碑","avatar_url":"https://pic1.zhimg.com/v2-eb56655cce39587eedeacb2824f6a116_l.png?source=32738c0c","description":"获得 50 个赞同","mini_avatar_url":"https://pic3.zhimg.com/v2-eb56655cce39587eedeacb2824f6a116_l.png?source=32738c0c","medal_avatar_frame":"","profile_medal_avatar_frame":""},"follow_content_count":0}
❚  [DEBUG] [知乎助手]
当前用户id：8584343ad4b22cc5bdf1400e46ae90ea，是否为VIP：false
❚  [DEBUG] [知乎助手]
WRITE DATA [zhihu_current_userinfo](object)
{"id":"8584343ad4b22cc5bdf1400e46ae90ea","is_vip":false}
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_fake_vip](boolean)
true
❚  [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.022S.

**Comment by Sheldontao** [comment]
正则屏蔽也可以用，但是广告出现了，，，，我是不是应该停留老版本，等大版本在更新脚本？

**Comment by blackmatrix7** [comment]
我两部手机能搜到的最新版都是8.26，没有找到8.3版本。

另外近期可能没有时间及时支持大版本的更新，如果功能正常不建议升级。

特别是知乎越升级越恶心的情况下，现在新版本推荐列表的营销内容，已经没办法通过右下角三个小点去屏蔽了。

**Comment by Sheldontao** [comment]
知乎是8.03.0,这就是老老版本了，，，，我感觉他可能一直在更新内容结构之类的

**Comment by blackmatrix7** [comment]
从日志上看，是正则匹配出了问题。看起来不像知乎客户端的问题。

但是我在目前最新版测试是正常的，你这个版本我可能要找个时间抓包，退回旧版看下才知道是什么情况。

**Comment by Sheldontao** [comment]
那我更新成8.26了？

**Comment by blackmatrix7** [comment]
> 那我更新成8.26了？

我觉得你可以先换个客户端试试。

**Comment by Sheldontao** [comment]
8.20也用不了有广告，，，但是8.26好很多，只有一些科普视频，没有广告

**Comment by Sheldontao** [comment]
8.20也用不了有广告，，，但是8.26好很多，，，但也有广告，，，应该不是客户端的问题

**Comment by Sheldontao** [comment]
2022/07/23 22:08:36:255  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_keyword_block][8584343ad4b22cc5bdf1400e46ae90ea](object)
["果.*(华为|小米|国产)+","男士.*(沐浴露|香水)+","鸿蒙.*(安卓|套壳)+","(张维为|陈平).*不满","全网.*(大火|盲盒)","盲盒","低价.*衣服","永动机","拼多多.*砍价","彩票","(京东|淘宝).*白嫖","约会.*app","宋智雅","丰巢","冬奥","彩礼","谷爱凌","梦想改造家","大专.*诺贝尔","牛排.*八分熟","磁器口.*星巴克","冰露","吴京","潘长江","中国足球","钻石.*智商","男士.*洗发水","影视.*app","光明日报","百度","乌合麒麟","儿童.*(插图|教材)","杨笠","(美国|乌克兰).*侵略","曲婉婷","胡锡进","汉语编程","孙杨","乘风破浪","靖国神社","钟薛高","张维为","易洋千玺.*(特权|小镇)","李承铉.*戚薇","(美|中)国.*远超","wps","qq音乐","(张)?.*菜刀","学生会","艾跃进","（优酷|腾讯)视频"]
2022/07/23 22:08:36:257  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_blocked_users][8584343ad4b22cc5bdf1400e46ae90ea](object)
{"会员推荐":"00000000000000000000000000000000","故事仙女":"2baface78b00136188737979b5e4b6f8","莫仙":"4c3a18b8a40aa9f15cd60ba89e0ad872","沐杉蓝":"1b6d7fb4fe7858e90d8381ad14828b14","花浪":"5b281a03a429d2188a15d9265e95df47","盐选点金":"9f8e736a6d629c39bd6f84660a949e79","睡前消息":"22adc602755babbe0e486806a83967e8","疯狂小杨哥":"fbd8520a7a2fc86e8e83719fdb6332e7","盐选推荐":"f508f14833f52639e8c2dbbbff7d8933","大牛聊DeFi":"cb5b72ff6cacd4e749ac7475e23f0176","西部决策网D视频":"9bfc8d75dea00de1080ac029deae8266","小央视频":"48883a48a567133caccd995d7c7d34b7","风行财富密码":"aa60dd32936cd289c2090952997f0a81","历史环游记":"c167dea2f593c4315cfff1e9ea6d023a","盐选科普":"b13b0a3f97549f3854ce96b2faa41a55","知乎用户83UcjK":"33cc5640e7b6c2f207213a92fb884358","剧说叨叨":"79e061b7e0164f5b64f5f981844b66c9","斯巴达电影":"352e489696c7f90fe79d0a76cd5a88ea","知乎用户PusW1F":"08ac6fdb097d992079f52cee18db064a","知识来了":"3e092186a5ca026d04c1dd89e42ef2c5","日用窍门":"1e8c491df19309a2cc62f1e9593f05ad","桥视频":"427f05afa55453e3cab54b30150154d1","石榴熟了":"e8b05aca437895104d8e05685a5d564e","零九":"383ca2c2839d04142ad5d43e99ef55ff","四川观察":"5de0bd7bec3e56341b7f6b2d42ffede6","观察者网":"0f266fddf1315d97c652161dd58de5e1","高原战士":"b75a0ec53e1ce4a0e6792d81046bc84f","故事档案局":"9714a0a7d9164fb8d68d8c983f9799b5","知乎放映厅":"4acb7131d089f70c9f7469583b631467","知乎故事大赛":"11f81fd09f3e27064b676802c7772f4c","知乎视频":"15d2cc02530e0b4e37838eba04dabfa9","知乎答案奇遇夜":"a51842622e5b9f77277d0bc39b301ea4","知乎盐选会员":"17c6a13f6086efebfaf728cf6b37f908","苍野故事城":"943129da84e5d1d507f32f56ee9e864b","酷猫街拍女神":"a100937bf913b1d9ad600a1d8ddfc83c","健身问答":"57926913e3af6b4cfdfae25ad8f91f55","浮云游系列":"263fbd8114e37d083cfc9f03895b7296","静静香":"85950ec2c9b8d6bb808b40184ed321dc","一行白鹭进铁锅":"12122838ee4b9e693f2482e37bd63b4f","推理档案馆":"6ffe09933d10643ede0423e504385d47","猪里猪气":"849e4d5a310f21f472bbb5b549b4a104","尽力而为的人":"f70304eb8f72e0743f30f4683e301810","共青团中央":"53fa7c2fb1fcade1f2eb8e25e10e0f84"}
2022/07/23 22:08:36:467  <console>    [JS Console]: [ERROR] [知乎助手]
知乎推荐列表去广告出现异常：SyntaxError: Invalid regular expression: unmatched parentheses
2022/07/23 22:08:36:470  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.245S.
2022/07/23 22:08:37:317  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
2022/07/23 22:08:37:321  <console>    [JS Console]: [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
2022/07/23 22:08:37:324  <console>    [JS Console]: [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.014S.

**Comment by blackmatrix7** [comment]
我自己主力机用的是8.4.0 8126

备用机更新至最新版。

目前可以确认这两个版本没有广告。

其他的版本需要测试才能知道，也不排斥知乎针对旧版客户端更改了响应内容。

**Comment by blackmatrix7** [comment]
你试试把关键词屏蔽这个功能关闭试试？？

**Comment by Sheldontao** [comment]
可可可可可，，，，确实一不小心打错一个符号就g了，，，，，谢谢大佬操心😘

**Comment by blackmatrix7** [comment]
能解决就好，下次我加个异常判断，避免因为正则错误导致脚本失效。
