### ISSUE TITLE
all in one 重写淘宝商品页图片不加载

### ISSUE THREAD

**Issue by joyoner** [blackmatrix7/ios_rule_script#649]
iOS15.6
Surge TF
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Surge/AllInOne/AllInOne.sgmodule

**Comment by joyoner** [comment]
https://heic.alicdn.com/imgextra/i1/2204110394461/O1CN01NOd07K1ipBcHW6beX_!!2204110394461.jpg_1200x1200q90.jpg_.heic

**Comment by blackmatrix7** [comment]
谢谢反馈，已经移除异常规则。
