### ISSUE TITLE
quanx下知乎去广告规则和复写导致部分回答加载失败

### ISSUE THREAD

**Issue by shangguanhongxin** [blackmatrix7/ios_rule_script#65]
随机看一些回答会显示加载失败点击重试就可以加载了
surge没有这样的问题

**Comment by blackmatrix7** [comment]
我quanx用得很少，没出现过这个问题。你看看出现问题时是否有对应日志？

**Comment by blackmatrix7** [comment]
如果经常加载失败，几个建议：1.取消拦截预加载的规则 2.取消付费内容提醒的功能，这个功能比较消耗资源。

**Comment by shangguanhongxin** [comment]
> 如果经常加载失败，几个建议：1.取消拦截预加载的规则 2.取消付费内容提醒的功能，这个功能比较消耗资源。

就是换lite的是吧 日志的话看不出来啥……

**Comment by shangguanhongxin** [comment]
> 如果经常加载失败，几个建议：1.取消拦截预加载的规则 2.取消付费内容提醒的功能，这个功能比较消耗资源。

换了之后尝试了很久没有出现加载失败的问题 
感谢
![Uploading 203C2129-1CD5-4549-801D-9359821D9274.png…]()

**Comment by shangguanhongxin** [comment]
还是发生了……lite的话还是有加载失败…

**Comment by shangguanhongxin** [comment]
刷推荐里面的回答 会出现加载失败
lite出现的概率会更低
 在热榜里面打开回答不会出现

**Comment by blackmatrix7** [comment]
没办法复现，你试试建一个空白的配置文件，只加载这个复写看看。

**Comment by shangguanhongxin** [comment]
更新quanx到最新版本后貌似没有出现了 我再观察观察

**Comment by shangguanhongxin** [comment]
![E523DC57-0040-4251-B561-8E4A5525AA40](https://user-images.githubusercontent.com/58215734/98624615-25481d80-2349-11eb-8f36-b9d3a79ad3f5.png)
![7A125547-4E62-4548-A18E-CE69F35DB97B](https://user-images.githubusercontent.com/58215734/98624617-27aa7780-2349-11eb-8558-ff9ef22526cc.png)

**Comment by blackmatrix7** [comment]
脚本需要获取用户ID，用来区分不同的账号，以隔离不同账号下的黑名单。这个操作通常在打开知乎的时候会完成，你知乎的版本是什么？

**Comment by shangguanhongxin** [comment]
> 脚本需要获取用户ID，用来区分不同的账号，以隔离不同账号下的黑名单。这个操作通常在打开知乎的时候会完成，你知乎的版本是什么？

是最新的6.62.0
我是不登陆看zhihu的 只浏览

**Comment by blackmatrix7** [comment]
之前没有考虑到不登录账号的情况，你可以直接建一个复写文件。先把 ^https?:\/\/api\.zhihu\.com\/people\/ url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.js 这条复写注释掉。
后面会更新解决这个问题。

**Comment by shangguanhongxin** [comment]
> 之前没有考虑到不登录账号的情况，你可以直接建一个复写文件。先把 ^https?://api.zhihu.com/people/ url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu_plus.js 这条复写注释掉。
> 后面会更新解决这个问题。

好的

**Comment by blackmatrix7** [comment]
已增加未登录用户的判断，你试试。

**Comment by shangguanhongxin** [comment]
> 已增加未登录用户的判断，你试试。

![D5F587AF-EAD3-43EA-9EA2-D1935EDB46C4](https://user-images.githubusercontent.com/58215734/98778553-80ebd700-242d-11eb-9681-641a7ac25177.jpeg)

还是有加载失败的情况

**Comment by blackmatrix7** [comment]
之前获取用户的复写是不是去掉了？如果是需要先加回来，让它重写写入一次正确的数据。

或者手动执行一下代码，把 zhihu_current_userinfo 这个key的值清空。

**Comment by shangguanhongxin** [comment]
> 之前获取用户的复写是不是去掉了？如果是需要先加回来，让它重写写入一次正确的数据。
> 
> 或者手动执行一下代码，把 zhihu_current_userinfo 这个key的值清空。

这个我不太懂是什么意思 
我是更新了最新的复写
我重下知乎算不算重写了

**Comment by blackmatrix7** [comment]
应该算，你看下有没有类似 获取到当前登录用户信息 的日志

**Comment by shangguanhongxin** [comment]
> 应该算，你看下有没有类似 获取到当前登录用户信息 的日志

重下了 还是不行

**Comment by blackmatrix7** [comment]
晚上我再更新一下，你再试试。

**Comment by shangguanhongxin** [comment]
> 晚上我再更新一下，你再试试。

好的

**Comment by blackmatrix7** [comment]
已经更新

**Comment by shangguanhongxin** [comment]
> 已经更新

![1C56454B-FAD2-4CF2-A697-3211375E4E59](https://user-images.githubusercontent.com/58215734/98879854-6f540f00-24c1-11eb-8a50-2c18440a8d18.png)

还是有加载失败啊……

**Comment by shangguanhongxin** [comment]
我用apple账户注册知乎了
给这个加载失败搞得头疼

**Comment by shangguanhongxin** [comment]
![017DDC13-F8CC-4593-B1FF-A23FA78894E9](https://user-images.githubusercontent.com/58215734/99029915-afdd8680-25ae-11eb-9025-92645e6a3853.png)
现在加载失败的信息是这样的了

**Comment by PowerDi** [comment]
美团外卖好像有还有广告。

**Comment by urzz** [comment]
```
2020/11/17 10:56:18:009  <console>    [JS Console]: [ERROR] [知乎助手]
知乎推荐列表去广告出现异常：TypeError: undefined is not an object (evaluating 'element['common_card']['feed_content']['source_line']['elements']')
2020/11/17 10:56:21:533  <console>    [JS Console]: [ERROR] [知乎助手]
知乎推荐列表去广告出现异常：TypeError: undefined is not an object (evaluating 'element['common_card']['feed_content']['source_line']['elements']')
```

**知乎的去广告，日志里面会报上面的问题**

**Comment by PowerDi** [comment]
各位朋友有没有发现软件耗电量的问题. 非统计问题而是待机耗电



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fooksky <notifications@github.com&gt;
发送时间: 2020年11月17日 11:01
收件人: blackmatrix7/ios_rule_script <ios_rule_script@noreply.github.com&gt;
抄送: PowerDi <578661971@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[blackmatrix7/ios_rule_script] quanx下知乎去广告规则和复写导致部分回答加载失败 (#65)

**Comment by blackmatrix7** [comment]
目前已知QuanX有问题，等后续有空看看。

**Comment by LuzMasonj** [comment]
@shangguanhongxin 

[QuantumultX用户知乎APP加载失败原因定位](https://github.com/blackmatrix7/ios_rule_script/issues/268#issue-836760611)
