### ISSUE TITLE
请问 Apple.list 中.cn域名是否应该单独走直连？

### ISSUE THREAD

**Issue by 42vio** [blackmatrix7/ios_rule_script#650]
因为通常情况下Apple分流都是走的代理，但是考虑到.cn也会一起走，是不是需要单独处理呢，比如增加 AppleCN.list，谢谢。

**Comment by blackmatrix7** [comment]
这只是一个Apple规则的集合，用什么策略取决与你的需求。

另外，Apple在国内有不少CDN服务器，个人认为走代理不一定能获得最佳访问速度。

我个人是全部使用直连，部分不能正常访问的才使用代理。
