### ISSUE TITLE
规则反馈

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#651]
Advertising.list 某条规则会影响 iCloud 的文件传输。
举个例子，我在文件 app 里面上传、下载或者重命名一个文件，这个文件无法同步到 iCloud 。

看网络活动应该是 metrics.icloud.com 这一条

**Comment by RuCu6** [comment]
现在基本确定就是 Advertising.list 中的 host-suffix, metrics.icloud.com 这一条

**Comment by blackmatrix7** [comment]
没有复现此问题。

不过考虑icloud.com一般不应该拦截，所以把这个规则去掉了。

**Comment by RuCu6** [comment]
无法复现的原因可能是我用了 release 的版本，去掉此规则确实有效果
