### ISSUE TITLE
知乎助手视频广告筛选

### ISSUE THREAD

**Issue by Sheldontao** [blackmatrix7/ios_rule_script#655]
忘记说了，知乎他有一种广告是以视频的形式出现，多是米哈游原神，，，如果有时间希望可以处理一下。
（因为经常看一些推送的ted教育类视频，所以在box.js里面把视频打开了）

**Comment by Sheldontao** [comment]
但是它词条的右下角会显示“广告”字样，不知道能不能抓取到

**Comment by blackmatrix7** [comment]
最近事情比较多，能否提供一下返回的JSON内容，直接根据JSON做下处理会比较快。

**Comment by Sheldontao** [comment]
你是说脚本记录嘛？
------

状态:		已释放
网络请求:	无
描述:		 	
❚  script-response-body
❚  https://api.zhihu.com/feed-root/sections/query/v2?city=
❚  ^https?:\/\/api\.zhihu\.com\/feed-root\/sections\/query\/v2
❚  https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zhihu/zhihu.js
日志:		 	
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_remove_sections](object)
null
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_answer_tip](boolean)
true
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_blocked_users](boolean)
true
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_hot_list](boolean)
true
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_sys_msg](boolean)
true
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_sys_msg](boolean)
true
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_preset_words](boolean)
true
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_app_conf](boolean)
false
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_hot_search](boolean)
false
❚  [DEBUG] [知乎助手]
READ DATA [zhihu_settings_blocked_users](boolean)
true
❚  [DEBUG] [知乎助手]
SCRIPT COMPLETED: 0.045S.

**Comment by blackmatrix7** [comment]
可以使用内置的关键词过滤功能，添加正则进行过滤。
