### ISSUE TITLE
重定向模块导致无限重定向

### ISSUE THREAD

**Issue by chouchoui** [blackmatrix7/ios_rule_script#657]
https://github.com/blackmatrix7/ios_rule_script/blob/82dab023f2b9862b44ee7ebcf5e8cc9a0e3d4b18/rewrite/Surge/Redirect/Redirect.sgmodule#L50

---

测试发现以下几条均会导致无限重定向
https://github.com/blackmatrix7/ios_rule_script/blob/82dab023f2b9862b44ee7ebcf5e8cc9a0e3d4b18/rewrite/Surge/Redirect/Redirect.sgmodule#L71

https://github.com/blackmatrix7/ios_rule_script/blob/82dab023f2b9862b44ee7ebcf5e8cc9a0e3d4b18/rewrite/Surge/Redirect/Redirect.sgmodule#L61

https://github.com/blackmatrix7/ios_rule_script/blob/82dab023f2b9862b44ee7ebcf5e8cc9a0e3d4b18/rewrite/Surge/Redirect/Redirect.sgmodule#L64

**Comment by blackmatrix7** [comment]
谢谢反馈，已修复。
