### ISSUE TITLE
disneyplus规则缺漏

### ISSUE THREAD

**Issue by luuanng** [blackmatrix7/ios_rule_script#658]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：/Surge/DiscoveryPlus/DiscoveryPlus.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/DiscoveryPlus/DiscoveryPlus.list

异常规则：DOMAIN-SUFFIX,dssott.com

问题描述：缺少部分domain导致流量走不到正确的分流规则

抓包截图：(相关抓包工具的截图。)在个人工程下测试后可走正确分流规则。个人工程链接：https://github.com/luuanng/surge/blob/main/disneyplus.list

调整方案：(你希望规则做哪些调整，及其原因。)添加规则「DOMAIN-SUFFIX,dssott.com」

**Comment by luuanng** [comment]
经测试网站上还有一些相关规则也需要添加（不涉及播放流量分流）
DOMAIN-SUFFIX,disney.demdex.net
DOMAIN-SUFFIX,disney-plus.net
DOMAIN-SUFFIX,disneyplus.com
DOMAIN-KEYWORD,bamgrid.com

**Comment by blackmatrix7** [comment]
已经加入很久了，一直忘了回复你，不好意思。
