### ISSUE TITLE
去广告分流可否把银行的单独放置，好多活动页面打不开了

### ISSUE THREAD

**Issue by 875793595** [blackmatrix7/ios_rule_script#66]
感谢一直在更新，最近在用的时候银行app活动经常打不开，发现被阻止。
可否单独放置，一遍使用的时候关闭

**Comment by blackmatrix7** [comment]
这个不太好实现，因为我不是规则实际维护者，并不清楚哪些规则会导致银行APP误拦截。建议你在去广告规则前弄一个放行的规则，写入需要放行的域名，将放行规则的优先级设置得比去广告的高，这样就可以解决问题。

**Comment by 875793595** [comment]
对的，我现在就在一条条放行，感谢！

**Comment by blackmatrix7** [comment]
> 对的，我现在就在一条条放行，感谢！

方便的话可以把你的放行规则分享出来，我把它们加到过滤器里，下次生成就不会含有这些规则了。
