### ISSUE TITLE
百度贴吧签到无法获得cookie

### ISSUE THREAD

**Issue by leowolf1993** [blackmatrix7/ios_rule_script#660]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：百度贴吧签到脚本

APP版本：12.26.5

客户端名称：Surge

客户端版本：4.9

问题描述：仅勾选百度贴吧签到脚本，打开app无法获取cookie

复现方式：

1. 登陆百度贴吧app 
2. 退出app，打开surge脚本，重新打开贴吧app，无法获取cookie

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
已更新。
