### ISSUE TITLE
surge优化：针对规则数量多的大规则文件，推出专门的DOMAIN-SET规则组

### ISSUE THREAD

**Issue by asdfj2381k** [blackmatrix7/ios_rule_script#661]
来源：https://manual.nssurge.com/book/understanding-surge/cn/#%E7%AD%96%E7%95%A5

![image](https://user-images.githubusercontent.com/56584082/183361665-de7ed1db-3b51-43ce-a095-f8cdcf9368dc.png)

**Comment by blackmatrix7** [comment]
功能已经存在，建议仔细阅读下README
