### ISSUE TITLE
部分特殊网站需要新增一个分流规则

### ISSUE THREAD

**Issue by asdfj2381k** [blackmatrix7/ios_rule_script#665]
很多机场对 部分时政网站 进行了二次屏蔽措施，比如 https://www.epochtimes.com/   （都的都懂，相信我也不用多说什么）

屏蔽的结果是：访问这部分网站的时候，需要切换一些没有采取屏蔽措施的机场。

现在市面上，就缺少了统计这种网站的规则文件。

希望 @blackmatrix7  可以开一个新的domain-set， 逐步记录，逐步统计，把这些网站都记录下来。

方便有需要的人使用。

**Comment by blackmatrix7** [comment]
issues模板有明确的说明，不会整理和归类此类网站，所以很抱歉帮不上你。
