### ISSUE TITLE
知乎助手plus 7.7.0 评论无法正常显示

### ISSUE THREAD

**Issue by TaiPresident** [blackmatrix7/ios_rule_script#666]
![7E9F15C6-55A3-4171-8F03-3EFDB783F25A](https://user-images.githubusercontent.com/76845019/183810938-e56bc956-7a12-486c-a9b1-fb8eb6814786.png)

**Comment by dycwuxing** [comment]
+1

**Comment by dycwuxing** [comment]
我是8.16版本，看起来好像是评论上面的广告和评论一起呗屏蔽了
![Uploading 2CCDE834-1A62-4984-90DF-2219A0C2EEDB.png…]()

**Comment by alluserss** [comment]
+1
![D60B3298FA5458981AEF125C191A92DD](https://user-images.githubusercontent.com/60608150/186351734-602ba3b5-cf63-4384-b66d-47d58e0ce694.png)
知乎屏蔽广告显示不了评论

**Comment by blackmatrix7** [comment]
目前 在知乎 8.30.0(10714) 和 8.4.0(8126) 中无法复现此问题。

其他的版本，需要等空了降级去分析下请求，近期可能不会有更新。

**Comment by alluserss** [comment]
> 目前 在知乎 8.30.0(10714) 和 8.4.0(8126) 中无法复现此问题。
> 
> 其他的版本，需要等空了降级去分析下请求，近期可能不会有更新。

我的是8.30.0版本，不能显示评论，不知道是否与我是盐选会员有无关系

**Comment by alluserss** [comment]
> 目前 在知乎 8.30.0(10714) 和 8.4.0(8126) 中无法复现此问题。
> 
> 其他的版本，需要等空了降级去分析下请求，近期可能不会有更新。

我的知乎版本是8.30.0，但还是无法显示评论

**Comment by alluserss** [comment]
> > 目前 在知乎 8.30.0(10714) 和 8.4.0(8126) 中无法复现此问题。
> > 其他的版本，需要等空了降级去分析下请求，近期可能不会有更新。
> 
> 我的知乎版本是8.30.0，但还是无法显示评论

已解决，经测试，禁用tiktok插件，问题解决

**Comment by dycwuxing** [comment]
> > > 目前 在知乎 8.30.0(10714) 和 8.4.0(8126) 中无法复现此问题。
> > > 其他的版本，需要等空了降级去分析下请求，近期可能不会有更新。
> > 
> > 
> > 我的知乎版本是8.30.0，但还是无法显示评论
> 
> 已解决，经测试，禁用tiktok插件，问题解决

我也发现了,我是使用了这个TIKTOK的解锁"https://github.com/Tartarus2014/Loon-Script/tree/master/Plugin/Unlock"
且这个里面的去水印脚本导致的,禁用脚本即可
