### ISSUE TITLE
Surge rules without rule type

### ISSUE THREAD

**Issue by Franky18** [blackmatrix7/ios_rule_script#667]
规则名称：AdvertisingLite_Domain, ChinaMax_Domain

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AdvertisingLite/AdvertisingLite_Domain.list, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax_Domain.list

异常规则：All rules.

问题描述：No specified rule type before domain.
                   
NAME: AdvertisingLite
AUTHOR: blackmatrix7
REPO: https://github.com/blackmatrix7/ios_rule_script
UPDATED: 2022-08-05 22:35:17
DESCRIPTION: 分流规则中含有URL-REGEX类型，建议搭配MITM使用
AND: 1
DOMAIN: 23692
DOMAIN-KEYWORD: 27
DOMAIN-SUFFIX: 13399
IP-CIDR: 190
URL-REGEX: 295
TOTAL: 37604
00-gov.cn
001.0x1f4b0.com
002.0x1f4b0.com
0024aadd.com
0026645142c89aeb1.com
003.0x1f4b0.com
004.0x1f4b0.com
005.0x1f4b0.com
006.0x1f4b0.com
006a039c957c142bb.com
007.0x1f4b0.com
008.0x1f4b0.com
......

**Comment by blackmatrix7** [comment]
Please use **DOMAIN-SET**.

**Comment by Franky18** [comment]
Thanks.

**Comment by Franky18** [comment]
> Please use **DOMAIN-SET**.

Thanks.
