### ISSUE TITLE
对于哔哩哔哩的去广告脚本的建议

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#668]
哔哩哔哩版本：6.84.0

不知道从哪个版本开始的哔哩哔哩左上角变成了类似于抖音的短视频入口，脚本处理以后，右上角小电视也是同一个功能的入口。

所以建议一下，可不可以右上角只保留消息盒子这一个icon 。可以参考这位大佬
![B8BFDC2C-893C-478C-AA10-B76E00AA7A02](https://user-images.githubusercontent.com/49463634/184107092-43cb2813-cfe5-487c-b172-b3f5b91c4a59.jpeg)
https://github.com/app2smile/rules/blob/master/js/bilibili-json.js

自己不会写  劳烦😬😬

**Comment by blackmatrix7** [comment]
目前B站去广告脚本暂时没精力维护。

我自己使用的是国际版，你可以试试。
