### ISSUE TITLE
iCloud 规则反馈

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#669]
上次去掉的这个规则现在怎么又添加回去了？
![4CBC0158-F24B-45AE-A0B7-8C674A44A862](https://user-images.githubusercontent.com/49463634/184276009-245a25e5-42a6-4636-8c48-c37fdbf96f62.png)

**Comment by blackmatrix7** [comment]
上次过滤的是DOMAIN，这次变为DOMAIN-SUFFIX，必须再过滤一次。
