### ISSUE TITLE
请问知乎新增的“精简顶部标签页”能否提供一下效果图

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#67]
看文字不能直观理解精简效果
而且自己手动加了几条知乎的规则（不知道会不会影响精简效果），精简是否生效根本无从判断

**Comment by blackmatrix7** [comment]
精简完上面的标签页应该只剩下三个：关注、推荐和热榜。如果还有其他的说明没有生效。生效有些滞后，可能需要多重启几次APP，如果一直没办法生效，就是被拦截了。

**Comment by fiiir** [comment]
> 精简完上面的标签页应该只剩下三个：关注、推荐和热榜。如果还有其他的说明没有生效。生效有些滞后，可能需要多重启几次APP，如果一直没办法生效，就是被拦截了。

杀后台重启10+次，除了你说的三个标签，还有一个“视频”
属于没有生效的情况？
如果是的话我排查一下规则？

**Comment by blackmatrix7** [comment]
不要拦截appcloud2.zhihu.com域名，并且需要MITM

**Comment by fiiir** [comment]
> 不要拦截appcloud2.zhihu.com域名，并且需要MITM

已按照教程操作，删除多余知乎规则，并前置appcloud2.zhihu.com强制走DIRECT
“视频”标签依旧存在
先用段时间观察一下，看是否属于滞后情况

**Comment by blackmatrix7** [comment]
你抓包看看https://appcloud2.zhihu.com/v2/config 这个请求是不是有触发脚本执行

**Comment by fiiir** [comment]
> 你抓包看看https://appcloud2.zhihu.com/v2/config 这个请求是不是有触发脚本执行

多次尝试，不能没有发现v2的请求，只有v3
https://appcloud2.zhihu.com/v3/config
备注：
01:21:38.071249 Rule matched: DOMAIN appcloud2.zhihu.com
01:21:38.072210 HTTP response script found: 知乎_优化软件配置
01:21:38.121958 TCP connection established
01:21:38.229832 TLS handshake completed, negotiated cipher: ECDHE-RSA-CHACHA20-POLY1305, protocol TLSv1.2
01:21:38.434180 Response is modified by script

**Comment by blackmatrix7** [comment]
是V3，我记错了。看起来触发脚本，不应该没效果。你把脚本修改后的JSON贴给我看看。

**Comment by fiiir** [comment]
> 是V3，我记错了。看起来触发脚本，不应该没效果。你把脚本修改后的JSON贴给我看看。

{"error": {"message": "App \u4e0d\u5b58\u5728", "code": 4041, "name": "ResourceNotFoundException"}}

**Comment by blackmatrix7** [comment]
> {"error": {"message": "App \u4e0d\u5b58\u5728", "code": 4041, "name": "ResourceNotFoundException"}}

你的知乎版本是？感觉response跟我完全就不一样。

**Comment by blackmatrix7** [comment]
抓包里的响应，有个导出。不过导出的是原始的还是脚本修改过的就不太确定了。

**Comment by fiiir** [comment]
> 抓包里的响应，有个导出。不过导出的是原始的还是脚本修改过的就不太确定了。

{"config":{"question_hybrid_preload_time":0,"all_requests_encrypt_switch":1,"videox_filter_json":{"filter":"standard","sharpen":0.3,"redden":0.36,"whiten":0.3,"filters":[{"display_name":"标准","ios_value":0.35,"name":"standard","android_value":0.25},{"display_name":"樱红","ios_value":0.5,"name":"sakura","android_value":0.8},{"display_name":"云裳","ios_value":0.5,"name":"ella","android_value":0.8},{"display_name":"纯真","ios_value":0.5,"name":"pure","android_value":0.8},{"display_name":"白兰","ios_value":0.5,"name":"prynne","android_value":0.9},{"display_name":"元气","ios_value":0.5,"name":"vitality","android_value":0.8},{"display_name":"超脱","ios_value":0.5,"name":"detachment","android_value":0.9},{"display_name":"香氛","ios_value":0.5,"name":"fragrance","android_value":0.5},{"display_name":"美白","ios_value":0.3,"name":"whitening","android_value":0.5},{"display_name":"浪漫","ios_value":0.3,"name":"romantic","android_value":0.5},{"display_name":"清新","ios_value":0.3,"name":"fresh","android_value":0.5},{"display_name":"唯美","ios_value":0.3,"name":"aestheticism","android_value":0.5},{"display_name":"粉嫩","ios_value":0.3,"name":"pink","android_value":0.5},{"display_name":"怀旧","ios_value":0.3,"name":"classic","android_value":0.5},{"display_name":"蓝调","ios_value":0.3,"name":"blues","android_value":0.5},{"display_name":"清凉","ios_value":0.3,"name":"cool","android_value":0.5},{"display_name":"日系","ios_value":0.3,"name":"jap","android_value":0.5}]},"net_diag":1,"enable_youdao":1,"sdAviDec":1,"pk_bind_one_click":0,"ios_feed_refresh_214_timer":{"300":20,"3600":30,"28800":50,"172800":70},"feed_rec_switch_setting":1,"remix_share_icon":0.001,"km_sku_report_error":1,"km_join_shelf_guide":{"usage_amount":[2,4],"guide_min_interval":24,"consume_duration":[60,180]},"us_settings_NPS":{"url":"https://www.zhihu.com/nps/25?zh_forcehybrid=1&zh_hide_tab_bar=true&zh_nav_right=empty","show":1},"slow_device_threshold":1.2,"perinfo":"查看详情","share_pic_sys":0,"haowu_video_cardnum":10,"live_configure":{"video_fps":20,"video_height":1280,"video_bitrate":1500,"video_width":720},"new_user_7days_V2":{"image_url":"https://pic4.zhimg.com/80/v2-43216d3068feebbb6dff5ccd69086467_1440w.png","link_url":"https://www.zhihu.com/growth/event7d?from=2","ratio":0.93,"message":"参与活动赢 iPhone 11","id":"11001"},"crash":true,"videox_network":{"maxValue":0.6,"minValue":0.3},"vessay_xf_timbre":[{"speeds":[{"estimate":169,"speed":6,"name":"较慢"},{"estimate":153,"speed":7,"name":"正常"},{"estimate":138,"speed":8,"name":"较快"}],"style":"沉稳男声","speed":7,"estimate":153,"param":"4106"},{"speeds":[{"estimate":170,"speed":6,"name":"较慢"},{"estimate":153,"speed":7,"name":"正常"},{"estimate":139,"speed":8,"name":"较快"}],"style":"欢快男声","speed":7,"estimate":153,"param":"4003"},{"speeds":[{"estimate":183,"speed":6,"name":"较慢"},{"estimate":168,"speed":7,"name":"正常"},{"estimate":153,"speed":8,"name":"较快"}],"style":"温柔女声","speed":7,"estimate":168,"param":"4117"},{"speeds":[{"estimate":174,"speed":6,"name":"较慢"},{"estimate":158,"speed":7,"name":"正常"},{"estimate":146,"speed":8,"name":"较快"}],"style":"御姐女声","speed":7,"estimate":158,"param":"4100"},{"speeds":[{"estimate":170,"speed":8,"name":"较慢"},{"estimate":164,"speed":9,"name":"正常"},{"estimate":149,"speed":10,"name":"较快"}],"style":"可爱女声","speed":9,"estimate":164,"param":"4103"}],"mcn_editor_cardCount_max":30,"video_buffing_interval":1,"video_player_iOS_config_array":{"default":{"dacHighWaterMarkInMsecForLiving":8000,"agentIsDataReport":false,"isIgnoreVideoURL":false,"enablePlayerReuse":true,"agentCheckQuality":true,"disableMultiSeekType":false,"timeOutForLiving":10000,"agentDefaultPieceSize":81920,"agentPlayerLowWaterMark":1,"agentPlayerHighWaterMark":3,"agentReserveNotFullDownloadFile":true,"agentLogEnable":true,"autoPlay":true,"agentErrorToPlayer":true,"enablePreLoadForCurrentVideo":false,"enableProbeOptimizeForLiving":true,"agentVideoRestartTimeInMsec":5000,"agentSocketTimeoutInMsec":5000,"agentPreloadSectionCount":4,"agentSaveVideoInfoJson":true,"enableSmartSeekOnStart":true,"disableUseHttpReplaceHttps":true,"dacLowWaterMarkInMsecForLiving":6000,"isRecyclePlayer":false},"type1":{"dacHighWaterMarkInMsecForLiving":8000,"agentIsDataReport":false,"isIgnoreVideoURL":false,"enablePlayerReuse":true,"agentCheckQuality":true,"disableMultiSeekType":false,"timeOutForLiving":10000,"agentDefaultPieceSize":81920,"agentPlayerLowWaterMark":1,"agentPlayerHighWaterMark":3,"agentReserveNotFullDownloadFile":true,"agentLogEnable":true,"autoPlay":true,"agentErrorToPlayer":true,"enablePreLoadForCurrentVideo":false,"enableProbeOptimizeForLiving":true,"agentVideoRestartTimeInMsec":5000,"agentSocketTimeoutInMsec":5000,"agentPreloadSectionCount":4,"agentSaveVideoInfoJson":true,"enableSmartSeekOnStart":true,"disableUseHttpReplaceHttps":false,"dacLowWaterMarkInMsecForLiving":6000,"isRecyclePlayer":false}},"prefetch_on_low":true,"video_entity_html_preload_effective_duration":0,"ebook_pub_key":{"key_hash":"E48FBEA6AACC8177E10AF1190421E92B","key":"-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDgkB5vTONXv15SukpyFKKbkO3m\nMbZ8z4u8HwtV14qEoOJaOhh6pu75o6bojX3RFnWm3wHxFjmdJu1+JurChFiY2fxD\nQ+SZWXKzNvfK/fvi3JNMfgVfp0HcuCzKDWE+vPeactLeTNnjFRYlnaUygiwm0KNE\nhDDHw2/41xjcPLmPpQIDAQAB\n-----END PUBLIC KEY-----"},"launchad":1,"article_preload":1,"feed_prefetch":false,"appcloud_remove_startup_network":true,"appcloud_crash_fix":false,"pk_explore_apple_regist":0,"apm_traffic_monitor":0,"yangyao":{},"ui_auto_log_switch":true,"mine_refresh_time":2,"xf_tts_host":"tts-api.xfyun.cn","km_vip_mixtape_video_hint":"首月开通仅需 ¥9.9","sep_conf":{"firebase_end":70,"bugly_end":50,"matrix_begin":71,"firebase_begin":51,"bugly_begin":1,"matrix_end":100},"14d_day_new_retention":{"ratio":1.22241087,"message":"点这里领取限时好礼☝️","image_url":"https://pic3.zhimg.com/80/v2-7c34d742339a496dec8fb0fe7be0ad93_hd.png","id":"1013","link_url":"https://www.zhihu.com/appview/new_user_task?zh_hide_nav_bar=true&zh_hide_tab_bar=true&type=1"},"ios_alibcsdk_open":1,"enable_my_balance_entrance":1,"mon_json":{"argus_last_reboot_type":100,"ios_network_statistics":5,"MQTT_foreground_online":5},"mercury_event_blank_set":{"allOpenHostSuffixWhiteList":[".zhihu.dev",".zhihu.test"],"partiallyOpenHostSuffixWhiteList":[".zhihu.com"],"allOpenHostWhiteList":["pay.zhihu.com"],"partiallyOpenMessageWhiteList":["base/trackZA","browser/closeCurrentPage"]},"comment_input_placeholder":{"list":["友善的评论是交流的起点","友善评论的人运气都不会太差","评论千万条，友善第一条"]},"pk_setName_hide_wechat":0,"ios_editor_updateVersion_blackList":{"item":["1.0.7","4.4.0","4.6.0"]},"HTTPDNS_SWITCH":0,"ios_send_za_monitor":10,"float_notice":{"push_interval":300,"float_interval":1200,"active_interval":60},"ca_keychain_manager_control":1,"za_new_url":1,"new_user_7days_switch":0,"ac_logout_next_login":1,"cronet":{"start":"2020-10-14 00:00:00","enable":true,"end":"2020-11-10 18:00:00","description":"62 版本开启 Cronet","probability":1,"metrics_enabled":true,"quic":{"hosts":[{"origin":"www.zhihu.com","target":"www-quic.zhihu.com"},{"origin":"api.zhihu.com","target":"api-quic.zhihu.com"},{"origin":"pic1.zhimg.com","target":"pic-quic.zhimg.com"},{"origin":"pic2.zhimg.com","target":"pic-quic.zhimg.com"},{"origin":"pic3.zhimg.com","target":"pic-quic.zhimg.com"},{"origin":"pic4.zhimg.com","target":"pic-quic.zhimg.com"}],"methods":["GET","DELETE","PUT"],"probability":0.5}},"pk_carrier_login_new":0,"pk_login_apple":1,"presetWordEndurance":20,"follow_renew":20,"ios_share_comment":1,"videox_survey":{"bg":"https://pic4.zhimg.com/v2-85e2c5f2746fd13737bc10a33e1614fa.png","link":"https://www.zhihu.com/questionnaire?id=69","version":6,"max_time":30,"title":"直播满意度调研","min_time":10,"desc":"诚邀你参与知乎直播调研，方便为你提供更好的直播内容"},"ca_token_manager_keychain_async":1,"weak_network_sampling_rate":50,"argus_block_timeout_number":3,"panel_preload_duration":"168","KM_Video_Default_Quality":{"H264":{"4G":"SD","WiFi":"HD"},"H265":{"4G":"SD","WiFi":"HD"},"preload":{"4G":"SD","WiFi":"HD"}},"literature_detail_page":1,"new_user_7days_feed_view":{"subTitle":"精华都在这里，免费畅读7天......","target_url":"http://www.zhihu.com/api/v4/event7d/rights/collect","image_url":"https://picb.zhimg.com/80/v2-70ecf0f4cbf9685f7dc756d31d149c05_1440w.png","title":"知乎有哪些让人欲罢不能的回答?"},"html_preload_state_switch":1,"content_has_card_share":"1","prelopt":1,"udid_ruid_update":1,"svip_za_channel":{"69":{"channel_id":"L003P0018B00039","level":3},"135":{"channel_id":"L001P0006B00027","level":1},"160":{"channel_id":"L002P0011B00032","level":2},"172":{"channel_id":"L002P0013B00034","level":2},"197":{"channel_id":"L001P0003B00006","level":1},"258":{"channel_id":"L001P0002B00005","level":1},"581":{"channel_id":"L001P0003B000072","level":1},"582":{"channel_id":"L001P0003B000072","level":1},"583":{"channel_id":"L001P0003B000072","level":1},"584":{"channel_id":"L001P0003B000072","level":1},"585":{"channel_id":"L001P0003B000072","level":1},"586":{"channel_id":"L001P0003B000072","level":1},"587":{"channel_id":"L001P0003B000072","level":1},"763":{"channel_id":"L003P0019B00040","level":3},"917":{"channel_id":"L003P0017B00038","level":3},"1043":{"channel_id":"L002P0013B00034","level":2},"1132":{"channel_id":"L002P0045B00115","level":2},"1377":{"channel_id":"L001P0004B00071","level":1},"1406":{"channel_id":"L002P0010B00031","level":2},"1571":{"channel_id":"L001P0001B00001","level":1},"1572":{"channel_id":"L001P0001B00001","level":1},"1573":{"channel_id":"L001P0001B00001","level":1},"1596":{"channel_id":"L001P0001B00001","level":1},"1603":{"channel_id":"L001P0004B00042","level":1},"1649":{"channel_id":"L001P0001B00002","level":1},"1740":{"channel_id":"L002P0007B00064","level":2},"2131":{"channel_id":"L001P0009B00030","level":1},"2133":{"channel_id":"L001P0009B00030","level":1},"2452":{"channel_id":"L001P0003B000072","level":1},"2454":{"channel_id":"L001P0003B000072","level":1},"3478":{"channel_id":"L001P0005B00111","level":1},"3480":{"channel_id":"L001P0005B00021","level":1},"3491":{"channel_id":"L001P0005B00023","level":1},"3657":{"channel_id":"L003P0035B00100","level":3},"3698":{"channel_id":"L003P0035B00100","level":3},"3702":{"channel_id":"L001P0005B00022","level":1},"3706":{"channel_id":"L003P0035B00100","level":3},"3828":{"channel_id":"L001P0003B00073","level":1},"3881":{"channel_id":"L001P0006B00026","level":1},"3979":{"channel_id":"L001P0005B00110","level":1},"4095":{"channel_id":"L003P0036B00102","level":3},"4240":{"channel_id":"L002P0011B00032","level":2},"4262":{"channel_id":"L002P0012B00033","level":2},"4510":{"channel_id":"L003P0020B00041","level":3},"4515":{"channel_id":"L001P0003B00006","level":1},"4660":{"channel_id":"L001P0005B00025","level":1},"4661":{"channel_id":"L001P0005B00024","level":1},"4721":{"channel_id":"L001P0001B00004","level":1},"4774":{"channel_id":"L001P0008B00029","level":1},"4865":{"channel_id":"L001P0004B00092","level":1},"5022":{"channel_id":"L003P0037B00103","level":3},"5032":{"channel_id":"L004P0039B00105","level":4},"5325":{"channel_id":"L002P0011B00032","level":2},"5326":{"channel_id":"L002P0011B00032","level":2},"5328":{"channel_id":"L004P0016B00037","level":4},"5490":{"channel_id":"L001P0001B00003","level":1},"5513":{"channel_id":"L003P0021B00043","level":3},"5514":{"channel_id":"L002P0029B00050","level":2},"5578":{"channel_id":"L002P0015B00036","level":2},"5579":{"channel_id":"L003P0024B00045","level":3},"5619":{"channel_id":"L002P0030B00051","level":2},"5621":{"channel_id":"L003P0023B00044","level":3},"5622":{"channel_id":"L003P0025B00046","level":3},"5623":{"channel_id":"L003P0026B00047","level":3},"5624":{"channel_id":"L003P0027B00048","level":3},"5625":{"channel_id":"L003P0028B00049","level":3},"5634":{"channel_id":"L001P0002B00005","level":1},"5663":{"channel_id":"L003P0029B00065","level":3},"5670":{"channel_id":"L003P0031B00094","level":3},"5671":{"channel_id":"L001P0001B00004","level":1},"5673":{"channel_id":"L001P0001B00052","level":1},"5896":{"channel_id":"L002P0014B00059","level":2},"5915":{"channel_id":"L001P0003B00058","level":1},"6044":{"channel_id":"L001P0003B00058","level":1},"6045":{"channel_id":"L001P0003B00058","level":1},"6087":{"channel_id":"L002P0014B00035","level":2},"6208":{"channel_id":"L002P0011B00101","level":2},"6235":{"channel_id":"L003P0019B00040","level":3},"6272":{"channel_id":"L002P0014B00074","level":2},"6310":{"channel_id":"L001P0004B00075","level":1},"6312":{"channel_id":"L001P0004B00076","level":1},"6314":{"channel_id":"L001P0004B00077","level":1},"6315":{"channel_id":"L001P0004B00078","level":1},"6317":{"channel_id":"L001P0004B00079","level":1},"6319":{"channel_id":"L001P0004B00080","level":1},"6321":{"channel_id":"L003P0038B00104","level":3},"6323":{"channel_id":"L001P0004B00081","level":1},"6325":{"channel_id":"L001P0004B00082","level":1},"6327":{"channel_id":"L001P0004B00083","level":1},"6328":{"channel_id":"L001P0004B00084","level":1},"6330":{"channel_id":"L001P0004B00085","level":1},"6332":{"channel_id":"L001P0004B00086","level":1},"6334":{"channel_id":"L001P0004B00087","level":1},"6336":{"channel_id":"L001P0004B00088","level":1},"6338":{"channel_id":"L001P0004B00089","level":1},"6340":{"channel_id":"L001P0004B00090","level":1},"6341":{"channel_id":"L001P0004B00091","level":1},"6626":{"channel_id":"L001P0003B00006","level":1},"6628":{"channel_id":"L001P0003B00006","level":1},"6629":{"channel_id":"L001P0003B00006","level":1},"6652":{"channel_id":"L002P0047B00119","level":2},"6828":{"channel_id":"L002P0050B00126","level":2},"6843":{"channel_id":"L003P0033B00098","level":3},"6890":{"channel_id":"L001P0001B00001","level":1},"6940":{"channel_id":"L001P0003B00006","level":1},"7011":{"channel_id":"L002P0055B00134","level":2},"7198":{"channel_id":"L003P0032B00095","level":3},"7204":{"channel_id":"L002P0013B00097","level":2},"7207":{"channel_id":"L002P0014B00096","level":2},"7218":{"channel_id":"L003P0034B00099","level":3},"7265":{"channel_id":"L002P0047B00118","level":2},"7500":{"channel_id":"L002P0011B00032","level":2},"7505":{"channel_id":"L002P0049B00125","level":2},"7531":{"channel_id":"L002P0040B00106","level":2},"7729":{"channel_id":"L001P0003B00107","level":1},"7730":{"channel_id":"L001P0003B00107","level":1},"7732":{"channel_id":"L001P0003B00107","level":1},"7757":{"channel_id":"L004P0041B00108","level":4},"7953":{"channel_id":"L001P0043B00114","level":1},"8050":{"channel_id":"L003P0044B00113","level":3},"8109":{"channel_id":"L002P0042B00109","level":2},"8334":{"channel_id":"L001P0043B00112","level":1},"8468":{"channel_id":"L002P0011B00032","level":2},"8469":{"channel_id":"L002P0011B00032","level":2},"8500":{"channel_id":"L002P0046B00116","level":2},"8515":{"channel_id":"L001P0001B00120","level":1},"8518":{"channel_id":"L002P0048B00121","level":2},"8519":{"channel_id":"L002P0048B00122","level":2},"8522":{"channel_id":"L002P0048B00123","level":2},"8629":{"channel_id":"L002P0047B00117","level":2},"8667":{"channel_id":"L002P0013B00124","level":2},"8670":{"channel_id":"L002P0013B00124","level":2},"8711":{"channel_id":"L003P0052B00129","level":3},"8968":{"channel_id":"L003P0032B00128","level":3},"8983":{"channel_id":"L001P0004B00071","level":1},"8994":{"channel_id":"L002P0054B00133","level":2},"8996":{"channel_id":"L002P0054B00133","level":2},"8999":{"channel_id":"L002P0054B00133","level":2},"9000":{"channel_id":"L001P0001B00132","level":1},"9018":{"channel_id":"L003P0051B00127","level":3},"9032":{"channel_id":"L002P0014B00035","level":2},"9037":{"channel_id":"L004P0053B000131","level":4},"9127":{"channel_id":"L002P0055B00135","level":3},"9386":{"channel_id":"L003P0027B00130","level":3},"9747":{"channel_id":"L002P0055B00136","level":3},"9953":{"channel_id":"L003P0058B00139","level":3},"9962":{"channel_id":"L003P0024B00137","level":3},"9963":{"channel_id":"L003P0025B00138","level":3}},"enable_others_infinity_entrance":1,"bangbang_interface_encryption":[{"PUT":["/account/password","/payments/*","/people/self","/people/self/profile_v2"],"POST":["/auth/digits","/sms/digits","/sign_in","/account/unlock/request/sms","/account/unlock/request/email","/account/unlock/request/voice","/api/account/phone_no","/account/email","/api/security_center/trust_devices","/messages","/collections","/bean/recharges","/account/unlock/digits"]}],"video_editor_topic_expcerpt":"请绑定合适的话题","organization_pay":{"service_ids":["108"]},"launch_weibo":true,"video_agent_close_time":[],"km_epub_limit":2048,"myinvite":{"target_url":"https://www.zhihu.com/special/21515636","image_url":"https://pic3.zhimg.com/v2-7b6794ceb2148a50dada585e12483a83.png","title":"进站必看"},"weak_network_HTTP_factor":700,"is_enable_feed_pull_for_new_itmes":0,"card_share_templates":{"templates":[{"body":{"content":{"color":"#1a1a1a"},"footer":{"color":"#999999","line_color":"#EBEBEB"},"description":{"color":"#808080"},"quote_icon":{"color":"#66d3d3d3","visible":true},"id":"card"},"qrcode":{"color":"#444444","visible":true,"background_color":"#ffffff","desc_content":"长按识别二维码\n阅读全文","desc_color":"#cc999999"},"background":{"color":"#ffffff","type":"solid"},"preview_icon":"default","logo":{"color":"#0f88eb","visible":true},"id":"default"},{"body":{"content":{"color":"#d2b495"},"footer":{"color":"#ccd2b495","line_color":"#66D2B495"},"description":{"color":"#d2b495"},"quote_icon":{"color":"#66d2b495","visible":true},"id":"card"},"qrcode":{"color":"#d2b495","visible":true,"background_color":"#3e3c3c","desc_content":"长按识别二维码\n阅读全文","desc_color":"#ccd2b495"},"background":{"start_point":"0.5,0","colors":["#303030","#3e3c3c"],"type":"gradient","end_point":"0.5,1"},"preview_icon":"gold","logo":{"color":"#cc8e8e8e","visible":true},"id":"gold"},{"body":{"content":{"color":"#ffffff"},"footer":{"color":"#ccffffff","line_color":"#66ebebeb"},"description":{"color":"#ffffff"},"quote_icon":{"color":"#66ffffff","visible":true},"id":"card"},"qrcode":{"color":"#ffffff","visible":true,"background_color":"#515e9f","desc_content":"长按识别二维码\n阅读全文","desc_color":"#ccffffff"},"background":{"start_point":"0.5,0","colors":["#353a72","#515e9f"],"type":"gradient","end_point":"0.5,1"},"preview_icon":"purple","logo":{"color":"#ccffffff","visible":true},"id":"purple"},{"body":{"content":{"color":"#ffffff"},"footer":{"color":"#ccffffff","line_color":"#66ebebeb"},"description":{"color":"#ffffff"},"quote_icon":{"color":"#66ffffff","visible":true},"id":"card"},"qrcode":{"color":"#ffffff","visible":true,"background_color":"#69a9ea","desc_content":"长按识别二维码\n阅读全文","desc_color":"#ccffffff"},"background":{"start_point":"0.5,0","colors":["#6386e8","#69a9ea"],"type":"gradient","end_point":"0.5,1"},"preview_icon":"blue","logo":{"color":"#ccffffff","visible":true},"id":"blue"},{"body":{"content":{"color":"#ffffff"},"footer":{"color":"#ccffffff","line_color":"#66ebebeb"},"description":{"color":"#ffffff"},"quote_icon":{"color":"#66ffffff","visible":true},"id":"card"},"qrcode":{"color":"#ffffff","visible":true,"background_color":"#43cdc8","desc_content":"长按识别二维码\n阅读全文","desc_color":"#ccffffff"},"background":{"start_point":"0.5,0","colors":["#05aac6","#43cdc8"],"type":"gradient","end_point":"0.5,1"},"preview_icon":"green","logo":{"color":"#ccffffff","visible":true},"id":"green"}]},"ab_cache_report_header_string_switch":true,"net_TO":60,"zhihu_live_check_red_point_duration":7200,"livestop":1,"feed_load_timer_threshhold_one":20,"liveretr":1,"image_oss_upload_fetcher":{"networkDelayTime":1000,"fetchServerStatusTime":500,"maxRetryCount":120,"networkMaxRetryCount":3},"ca_lastURL_refresh":1,"question_hybrid_preload_time_v2":300,"adpreloa":1,"presetWordDefaultFetchPeriod":86400,"ios_mp_configuration":{"apps":[{"ratio":50,"appId":"zhihu6f09cbb57f6524e"},{"ratio":50,"appId":"zhihufdc07257693688e"}]},"Performance_interval":2000,"enable_my_coupon_entrance":1,"enable_new_za":1,"URL_Signature_body_size_threshold":4096,"pk_active_refresh":1,"new_user_7days_anwser_view":{"target_url":"https://www.zhihu.com/growth/event7d/luckydraw?zh_hide_nav_bar=true","image_url":"https://pic3.zhimg.com/80/v2-acd42cf575136c1a3a419ac540b8873d_1440w.png"},"enable_user_center_infinity_badge":0,"videox_gift_delay":5,"ios_hybrid_set_js_cookie":{"opt":false,"delay":100},"showSougouLogo":false,"ios_httpdns_ipv6":100,"card_share_feedback":{"items":["实际功能和我想要的不一样","生成的卡片样式不吸引我","想换一段内容再分享","随便看看"],"title":"能否留下没有分享的原因，以帮助我们改进"},"ui_auto_log_ids":{"7":8351,"9":8352,"1_91":8356,"1_65":8410,"1_75":8409,"9_1":8353,"1_154":8411,"1_26":8359,"1_24":8358,"1_25":8359,"1_23":8358,"1_1":8360,"4_7":8357},"feed_load_timer_threshhold_two":240,"video_editor_tagore_excerpt":"请选择合适的领域","leancloud_urls":{"push":"https://avoscloud.com","engine":"https://avoscloud.com","RTM":"https://router-g0-push.avoscloud.com","api":"https://avoscloud.com"},"ol_edit":true,"startup_cache_info_apm":true,"pk_cmcc_enabled":1,"enable_infinity_web_entrance":1,"interface_signature_list":[{"api.zhihu.com":["/zst/events/r","/people/*/followers","/columns/*/followers","/collections/*/followers","/articles/*/voters","/pins/*/reactions","/comments/*/voters","/comments/*/dislike"],"zhihu-web-analytics.zhihu.com":[]}],"html_preload_hit_cache_log_switch":1,"edulive_use_native_room":1,"enable_bugly":1,"enable_new_search":1,"km_kill_old_reader":0,"pk_login_autoshow":7,"pk_ctcc_enabled":1,"refresh_fast":true,"manuscript_show_bottom":false,"user_not_bind_phone_tip_string":{"timestamp":1501344000,"tip":"应国家法规对于帐号实名的要求，进行下一步操作前，需要先完成手机绑定。","skip_ut_verification":0,"continue_time":3600,"continue":0},"14d_low_frequency":{"ratio":1.22241087,"message":"限时礼物已发放，速领☝️","image_url":"https://pic2.zhimg.com/80/v2-a520495aa30a584c1242d5c1315380e7_hd.png","id":"1003","link_url":"https://www.zhihu.com/appview/new_user_task?zh_hide_nav_bar=true&zh_hide_tab_bar=true&type=3"},"zhihu_external_urls":{"gray_list":{"host":["bilibili.com"],"scheme":["bilibili"]},"white_list":{"host":[],"scheme":[]},"black_list":{"host":[],"scheme":[]}},"ls_followee_count_limit":"10000","enable_pocket":1,"enable_wechat":1,"enable_qq":1,"enable_weibo_client_share":1,"video_entity_html_preload_switch":1,"km_audio_player_timeout":40,"enable_all_infinity_entrances":1,"share_pic_emoticon":0,"editor_enable_uploadimage":{"text":"图片服务进行升级改造，暂时不能在「问题」「回答」中添加图片","is_enable":false},"ios_gold_word":{"0":"卡片分享","1":"金句分享"},"weak_network_diagnosis":0,"enable_sogou":1,"homepage_feed_tab":{"tabs_sort_key":"ios_nvrank","tab_infos":[]},"target_begin_end_timerInterval":1,"answer_preload":true,"metrics":{"start":"2020-10-14 00:00:00","enable":true,"end":"2020-11-30 20:00:00","probability":0.1},"frbs_new":true,"pk_cucc_enabled":0,"new_column":1,"ios_answer_hybrid_preload_time":300,"exposure":true,"zvideo_max_number":1,"km_recorder_setting":{"sample_rate":32000,"encoder_bit_rate":64000,"channel":1},"pk_register_withOutPhone":1,"ab_new_discover_percentage":10,"ls_followee_update_cycle":24,"HTTP_DNS_HOSTS":["pic1.zhimg.com","pic2.zhimg.com","pic3.zhimg.com","pic4.zhimg.com"]}}

**Comment by blackmatrix7** [comment]
看起来脚本顺利执行完成，"tab_infos": [] 被设置为空数组了。可能是知乎版本不同，你那个视频是不是一开始在知乎APP里就存在，而不是通过接口下发的配置。如果是，那就没办法去掉了。脚本能去掉的只能是后期通过接口下发的配置，比如最近的双11推广标签这种。
你提供下知乎的版本我试试。

**Comment by fiiir** [comment]
> 看起来脚本顺利执行完成，"tab_infos": [] 被设置为空数组了。可能是知乎版本不同，你那个视频是不是一开始在知乎APP里就存在，而不是通过接口下发的配置。如果是，那就没办法去掉了。脚本能去掉的只能是后期通过接口下发的配置，比如最近的双11推广标签这种。
> 你提供下知乎的版本我试试。

版本是6.62.0

**Comment by blackmatrix7** [comment]
确认了，这个版本已经把视频内置到APP里，不再是通过接口下发的配置，所以无法去除。
