### ISSUE TITLE
求百度贴吧分流规则，万分感谢！

### ISSUE THREAD

**Issue by mayochow** [blackmatrix7/ios_rule_script#672]
大神好，有空能不能单独写个百度贴吧的分流规则？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by blackmatrix7** [comment]
已添加 https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/BaiDuTieBa

**Comment by mayochow** [comment]
非常感谢，不过经测试，分流规则选代理的时候还是会显示大陆ip,估计是遗漏了贴吧的其他域名地址，还请大神修复。

发自我的iPhone
