### ISSUE TITLE
希望增加ChinaMax_No_IP规则

### ISSUE THREAD

**Issue by jenniferak** [blackmatrix7/ios_rule_script#674]
对Surge，Loon，Shadowrocket和QuantumultX希望可以在ChinaMax同目录下增加一个ChinaMax_No_IP.list，去除掉ChinaMax.list中的ipv4和ipv6的规则。Clash目前有ip，域名和普通规则三个独立的文件，所以就不需要了。
一般的配置都至少包含geoip,cn，ChinaASN，ChinaIPs.list其中一个，ChinaMax也就可以不包含IP规则。

**Comment by blackmatrix7** [comment]
已增加 https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/ChinaMaxNoIP
