### ISSUE TITLE
tvb规则建议

### ISSUE THREAD

**Issue by hbxnlsy123** [blackmatrix7/ios_rule_script#676]
clash中tvb规则建议加上如下两条：
DOMAIN,tvbtracking.azurewebsites.net
DOMAIN-SUFFIX,youboranqs01.com
之前电视一直看不了tvb，加上这两条之后就没问题了

**Comment by asdfj2381k** [comment]
确实，很多港剧网站的播放器都主动屏蔽了其他区域的IP，只能用大陆IP访问。

他们用的播放器不是大陆区域的，导致无法被GEO IP CN 识别， 最后会走到FINAL规则，导致无法播放。

这些有问题的域名只能一个一个手动添加，是一个挺头疼的问题。

**Comment by asdfj2381k** [comment]
@blackmatrix7   希望能专门开一个规则，把 【只允许大陆IP访问】的域名统计进来。

**Comment by blackmatrix7** [comment]
已添加。

【只允许大陆IP访问】的域名目前没有能力收集，抱歉。
