### ISSUE TITLE
哔哩哔哩概念版底部的“消息”被去除

### ISSUE THREAD

**Issue by YM1099** [blackmatrix7/ios_rule_script#68]
概念版的“消息”是在底部第四个，“会员购”在搜索栏旁边。
底部的五个按钮是“首页、频道、动态、消息、我的”，[bilibili_plus.js](https://github.com/blackmatrix7/ios_rule_script/blob/master/script/bilibili/bilibili_plus.js) 中第 62 行的`bottomList`加上“消息”能否解决问题呢？

**Comment by blackmatrix7** [comment]
对的，对数组的修改可以控制底部显示的按钮，晚上会更新一下把“消息”加上。

**Comment by blackmatrix7** [comment]
已经更新

**Comment by fiiir** [comment]
点击底部“我的”按钮，与app界面左上角“头像”按钮
会前往相同的界面
是否可以考虑一下隐藏掉底部“我的”按钮，减少多余的入口，让界面更精简？
