### ISSUE TITLE
小红书规则IP问题

### ISSUE THREAD

**Issue by Kaiser-DMr** [blackmatrix7/ios_rule_script#680]
规则名称：小红书

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/XiaoHongShu/XiaoHongShu.list

异常规则：

问题描述：刷动态和视频走向都是节点网络，但是IP地址没有改变，还是之前的

抓包截图：
![截屏2022-08-19 下午3 08 53](https://user-images.githubusercontent.com/58213021/185563513-18c84cd3-bf93-4138-a899-08e1ac986c2a.png)

调整方案：改变IP地址

**Comment by blackmatrix7** [comment]
不太理解你的需求，看截图，规则已经成功命中了。

后面就是你的策略问题了。

**Comment by Kaiser-DMr** [comment]
规则流量是走向我选择的节点，但是IP地址还是显示 国内，如果要改变IP地址是不是还要加规则？

**Comment by blackmatrix7** [comment]
你可以先排查下，可能是规则收集的不全，我自己不用小红书，只是简单的抓个包收集，可能会有遗漏。

也可能显示的IP地址本身就做了缓存。
