### ISSUE TITLE
建议将域名hotapi-va.isnssdk.com添加至TikTok分流规则

### ISSUE THREAD

**Issue by jqyisbest** [blackmatrix7/ios_rule_script#682]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：TikTok分流规则

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/

异常规则：TikTok相关分流

问题描述：发现TikTok每次启动都会访问api.snapkit.com、hotapi-va.isnssdk.com，而这两个域名未能命中TikTok分流规则中的任何一条

抓包截图：(相关抓包工具的截图。)
![image](https://user-images.githubusercontent.com/16437320/185718101-e3fb9248-b99a-4b10-b7dd-c09c704b2591.png)

调整方案：(你希望规则做哪些调整，及其原因。)
域名hotapi-va.isnssdk.com与TikTok已知域名后缀snssdk.com有较高相似度
建议将域名hotapi-va.isnssdk.com加入TikTok分流规则：DOMAIN-SUFFIX,isnssdk.com

**Comment by blackmatrix7** [comment]
感谢提供，已加入。
