### ISSUE TITLE
Qx新版特性

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#683]
Qx商店更新正式版1.0.31

添加了新的分流规则：
- 分流规则增加类型 host-wildcard 进行通配符（* 与 ?）匹配，例如「host-wildcard, *.goo?le.com, proxy」
- 当启用分流匹配优化时，host-wildcard 优先级仅高于 host-keyword

支持了 ip-asn 分流
- ip-asn, 6185, proxy

可以精简一下分流总数了👏👏👏

**Comment by blackmatrix7** [comment]
host-wildcard  一直都支持，ip-asn 已加入支持。

但是目前没有把ip-cidr合并到ip-asn的功能，所以暂时规则数量并不会减少。
