### ISSUE TITLE
希望可以增减向日葵的规则

### ISSUE THREAD

**Issue by wakaka123wakaka** [blackmatrix7/ios_rule_script#685]
![image](https://user-images.githubusercontent.com/34087959/185746369-0c603e30-e8a5-4b59-8fee-f79cb78715c8.png)

**Comment by blackmatrix7** [comment]
向日葵抓包会比较复杂，近期也没精力去做这个事情，所以短时间内不会添加。

如果你有相关的规则，欢迎分享。

**Comment by wakaka123wakaka** [comment]
今天刚抓的向日葵的域名和ip
oray.com
112.124.7.153
ray.net
121.40.200.192
47.98.162.90
121.41.32.171
47.99.222.1
58.211.78.138
14.215.177.39
121.40.99.129
212.129.230.34
121.40.118.44
47.98.207.12
60.163.191.16
47.110.217.173
orayimg.com
27.128.222.203/24
60.163.191.40
180.113.2.229
47.99.203.77
47.110.134.164
121.199.72.21
14.215.177.38
oray.net
47.97.156.111
47.97.126.85
yundunwaf1.com
yundunwaf2.com
124.236.18.225
alikunlun.com

**Comment by Fu1in** [comment]
+1，希望增加向日葵的规则，或者已经有了吗，我好像没找到
