### ISSUE TITLE
已添加 https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/BaiDuTieBa

### ISSUE THREAD

**Issue by mayochow** [blackmatrix7/ios_rule_script#688]
已添加 https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/BaiDuTieBa

_Originally posted by @blackmatrix7 in https://github.com/blackmatrix7/ios_rule_script/issues/672#issuecomment-1220180201_

**Comment by mayochow** [comment]
非常感谢，不过经测试，分流规则选代理的时候还是会显示大陆ip,估计是遗漏了贴吧的其他域名地址，还请大神修复。

**Comment by blackmatrix7** [comment]
又添加了一些规则，精力有限，如果还不行，麻烦一起找下什么原因吧。
