### ISSUE TITLE
分流规则误杀

### ISSUE THREAD

**Issue by kid-oh** [blackmatrix7/ios_rule_script#69]
res-master-m-sausage.xd.com
去广告里的这个规则会导致一些taptap网游无法登录

**Comment by blackmatrix7** [comment]
感谢反馈，晚上会更新一下，把这条规则排除掉。

**Comment by blackmatrix7** [comment]
我仔细看了下，没找到这条规则，你是在哪个文件看到的？

**Comment by kid-oh** [comment]
这个我找了一下好像也没有，会不会是正则之类的，反正启用你的去广告规则（包括lite）后，发现网络请求里这个地址被reject了，然后停用规则就正常了，单独把这个地址写成规则也证明了确实会影响，像@NobyDa的去广告就没有这个问题。

**Comment by blackmatrix7** [comment]
找不到规则的话，理论上不会出现这样的情况。你用的是实时版吗？

**Comment by kid-oh** [comment]
对的是实时版，刚刚测试了一下稳定版还是一样

**Comment by kid-oh** [comment]
Domain.list的没问题，就advertising.list不行

**Comment by blackmatrix7** [comment]
你把游戏名发我试试吧

**Comment by kid-oh** [comment]
香肠派对，哈哈哈哈

**Comment by blackmatrix7** [comment]
DOMAIN-KEYWORD,usage 这条规则会导致的误杀，NoByda那里也有，可能是没有MITM的关系，所以没有生效。现在更新去掉了。
