### ISSUE TITLE
大家好，我想问一下，如果我想让safari里面的所有请求都走代理，应该用什么规则呀？

### ISSUE THREAD

**Issue by asdfj2381k** [blackmatrix7/ios_rule_script#690]
如题，谢谢。

谢谢。

**Comment by asdfj2381k** [comment]
手机是iPhone, 工具是surge5

**Comment by loyio** [comment]
直接开全局吗
或者你的意思是指定App分流，这个在Mac上Surge可以，但在ios好像不行

**Comment by asdfj2381k** [comment]
@loyio  我的意思就是 指定APP分流。   因为safari也算一个APP呀

可是在iOS上我不知道safari的user-agent是什么。
