### ISSUE TITLE
饿了么脚本获取Cookie失效

### ISSUE THREAD

**Issue by loyio** [blackmatrix7/ios_rule_script#692]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：饿了么

APP版本：V10.11.33

客户端名称：Surge

客户端版本：5.0.2

问题描述：饿了么脚本获取Cookie失效

复现方式：

1. 导入饿了么Module
2. 然后打开饿了么app，点击超级吃货卡
3. 没有提示获取Cookie成功

我在h5端和app端都进行了测试，发现在正常操作中并没有请求
```
^https?:\/\/h5\.ele\.me\/restapi\/biz\.svip_scene\/svip\/engine\/queryTrafficSupply
```
这个api，怀疑是api进行了更改

设备是iPad Pro

已使用空白配置文件验证：是/否

**Comment by guanzhikuan** [comment]
+1,使用quanx,手机上获取cookie 也没有任何提示

**Comment by blackmatrix7** [comment]
已修复，不过配置有些变化，请阅读README。
