### ISSUE TITLE
rule/Surge/Apple/Apple.list  部分错误

### ISSUE THREAD

**Issue by asdfj2381k** [blackmatrix7/ios_rule_script#701]
![image](https://user-images.githubusercontent.com/56584082/187817504-c60ba183-1818-4b02-b048-ce42d5ab07eb.png)

**Comment by blackmatrix7** [comment]
谢谢反馈，考虑到DOMAIN-KEYWORD比较容易误匹配，所以不做修正，直接移除。

稍后更新。

**Comment by asdfj2381k** [comment]
@blackmatrix7  这种错误肯定不在少数。   建议可以找一些测试工具，批量测试一下是否还存在更多的错误规则。

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/189292768-6d6eb11e-1fc1-4744-b857-98b572378084.png)

**Comment by asdfj2381k** [comment]
我建议去掉这些误伤可能性比较高的规则
![image](https://user-images.githubusercontent.com/56584082/189292998-02f5965b-b5b1-4eba-b42d-dca86861a831.png)

**Comment by asdfj2381k** [comment]
PROCESS-NAME这个规则目前只能对mac os的surge生效

对iOS surge不管用

**Comment by asdfj2381k** [comment]
@blackmatrix7   错误这么多，应该是某个来源引起的， 建议把该来源去掉。
