### ISSUE TITLE
易观分析以及国双数据洞察官网无法打开

### ISSUE THREAD

**Issue by rule-airport** [blackmatrix7/ios_rule_script#702]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list

异常规则：DOMAIN-SUFFIX,analysys.cn，DOMAIN-SUFFIX,gridsum.com
                  

问题描述：易观和国双官方无法打开，无法查看他们写的行业报告等相关信息。

抓包截图：![image](https://user-images.githubusercontent.com/101653181/188265170-00b36e01-edc6-4835-8a13-2133f053b0eb.png)
![image](https://user-images.githubusercontent.com/101653181/188265250-5473accd-97f6-448f-aa8b-22d14d510b6e.png)

调整方案：希望去掉该规则，让我们可以正常访问该网页，同时这个规则在多个软件中皆有，例如 Surge，Clash等，希望都可以进行相关的调整。谢谢。

附：两个网站的链接：
- 国双：https://www.gridsum.com  
- 易观：https://www.analysys.cn

**Comment by blackmatrix7** [comment]
谢谢反馈，已在Lite版本中移除，稍后更新。
