### ISSUE TITLE
饿了么最新版无法获取CK

### ISSUE THREAD

**Issue by h605290713** [blackmatrix7/ios_rule_script#705]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：饿了么

APP版本：最新版

客户端名称：饿了么

客户端版本：

问题描述：打开饿了么app提示获取ck成功,但是并没有获取到CK,BoxJS看不到CK ,运行脚本也提示未获取CK

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
Surge 需要关闭 MITM over HTTP/2  才能获取到Cookie。

**Comment by a1564471347** [comment]
> Surge 需要关闭 MITM over HTTP/2 才能获取到Cookie。

关闭了还是不行

**Comment by blackmatrix7** [comment]
精力有限，无法及时适配最新版，只能适配我自己使用的版本。

个人使用习惯是APP能正常使用就不会更新，所以最新版的适配需要自己动手解决一下了。
