### ISSUE TITLE
QQ 空间相关域名 .qzone.qq.com 误封

### ISSUE THREAD

**Issue by chenyiping1995** [blackmatrix7/ios_rule_script#710]
规则名称：
Advertising_Domain

规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.txt

异常规则：
84481行, `.qzone.qq.com`

问题描述：
QQ空间明显不应当判定为是广告链接。

抓包截图：(相关抓包工具的截图。)
![image](https://user-images.githubusercontent.com/16564295/189255787-71c977f0-cbbe-4da8-811a-3a3c3193c344.png)

调整方案：(你希望规则做哪些调整，及其原因。)
请予从该规则中移除该域名。

**Comment by justdoiting** [comment]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml

同样存在QQ空间域名

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
