### ISSUE TITLE
b站首页推荐无法加载，同时报错

### ISSUE THREAD

**Issue by Paris0-0** [blackmatrix7/ios_rule_script#72]
2020/11/16 16:38:20:710  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'obj.data.cards')
2020/11/16 16:38:41:967  <console>    [JS Console]: [ERROR] [BiliBili]
开屏广告处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['show']['stime'] = 1915027200')
2020/11/16 16:41:29:856  <console>    [JS Console]: [ERROR] [BiliBili]
开屏广告处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['show']['stime'] = 1915027200')
2020/11/16 16:43:05:116  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['sections_v2'][3]['items']')
2020/11/16 16:43:07:120  <console>    [JS Console]: [ERROR] [BiliBili]
我的页面处理出现异常：TypeError: undefined is not an object (evaluating 'obj['data']['sections_v2'][3]['items']')
2020/11/16 16:43:18:331  <console>    [JS Console]: [ERROR] [BiliBili]
追番去广告出现异常：TypeError: undefined is not an object (evaluating 'obj.data.cards')

**Comment by Boys-So** [comment]
加载广告没有，不要用puls的就行了

**Comment by Paris0-0** [comment]
> 加载广告没有，不要用puls的就行了

啊，b站都是plus啊

**Comment by Boys-So** [comment]
禁用试下看看

**Comment by Paris0-0** [comment]
禁用了就好了，再打开推荐还是加载不出来

**Comment by Boys-So** [comment]
你用qx还是？

**Comment by Paris0-0** [comment]
是的

**Comment by Boys-So** [comment]
加个te

**Comment by Paris0-0** [comment]
额是什么

**Comment by Boys-So** [comment]
Telegram

**Comment by Paris0-0** [comment]
ParisO_O

**Comment by Boys-So** [comment]
这么聊太麻烦了，又不能传照片

**Comment by Boys-So** [comment]
你没有，额😓，你烦(qiang)多久了

**Comment by Paris0-0** [comment]
这是用户名啊，搜不到么

**Comment by Paris0-0** [comment]
tg基本就看看通知用的比较少

**Comment by Boys-So** [comment]
Te账号是多少？我搜下你

**Comment by Paris0-0** [comment]
ParisO_O

**Comment by blackmatrix7** [comment]
目前已知只有QuanX有问题，等有空了仔细看看。

**Comment by Paris0-0** [comment]
好的
