### ISSUE TITLE
哔哩哔哩UP主推荐广告可以去除吗？

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#722]
不知道哪个版本出来的功能
当前版本：6.90.0

![BCFFBF0A-B2E7-4C6C-B4CC-6EDDFD596553](https://user-images.githubusercontent.com/49463634/191162599-b59be948-89a5-4ab7-b0cf-0cf4837486da.jpeg)

**Comment by blackmatrix7** [comment]
一直都有，只是暂时没精力去维护B站的脚本。

应该有其他大佬实现了这个功能，你可以搜看看。

暂时不会再维护B站脚本。
