### ISSUE TITLE
增加AdvertisingLite规则的数据来源

### ISSUE THREAD

**Issue by PingZi-Wing** [blackmatrix7/ios_rule_script#723]
反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite

客户端名称：Clash for Windows 

客户端版本：0.20.3

使用方式：AdvertisingLite.yaml、AdvertisingLite_Domain.yaml 共同使用。

问题描述：

对比了AdvertisingLite和Advertising的数据源，发现相比lite，Advertising不仅多了Hijacking、Privacy，还另外新增了一条去应用广告规则来源https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list  这个来源的规则能去除爱奇艺uwp版里面的视频广告。希望能把这个去应用广告规则也加入到AdvertisingLite规则里面。

**Comment by blackmatrix7** [comment]
加入到AdvertisingTest中，稍晚些更新。
