### ISSUE TITLE
在China规则中移除sm.ms

### ISSUE THREAD

**Issue by PingZi-Wing** [blackmatrix7/ios_rule_script#725]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：China

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/China

异常规则：  - DOMAIN-SUFFIX,sm.ms

问题描述：sm.ms在国内走直连大面积访问不畅，而且严格意义上也不算国内网站吧

抓包截图：无
调整方案：希望在China规则中移除sm.ms，靠漏网之鱼来控制最终走向

**Comment by blackmatrix7** [comment]
已移除，晚些时候更新。
