### ISSUE TITLE
无法获取贴吧cookie 无脚本运行记录

### ISSUE THREAD

**Issue by Allenj305** [blackmatrix7/ios_rule_script#726]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：贴吧_获取Cookie

APP版本：圈X1.0.32-756

客户端名称：

客户端版本：

问题描述：

复现方式：

1. ………
2. ………………

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
之前缺失了一个MITM hostname，你更新重写后再试试，如果还是不行，再跟我说下

特别是贴吧的版本

**Comment by laincat** [comment]
iPhone 14 Pro Max
iOS 16.0.2
Surge TF
贴吧 v12.26.5

好像是 iOS 16 才出现这样不能获取 cookie 的？

**Comment by tutuh** [comment]
ios16.02 最新版本的贴吧，qx能获取，surge不行！
surge日志：
19:36:22.177006 [INFO] [百度贴吧]
获取百度贴吧Cookies(请勿泄露):
undefined

19:36:22.177167 [INFO] [百度贴吧]
SCRIPT COMPLETED: 0.003 S.

19:36:22.177365 [Script Completed]
----------------------------
19:36:22.177693 [INFO] [百度贴吧]
SCRIPT COMPLETED: 0.003 S.

**Comment by tutuh** [comment]
surge mitm里面关了h2就能正常获取了
