### ISSUE TITLE
将IP-CIDR 规则添加no-resolve

### ISSUE THREAD

**Issue by linger040831** [blackmatrix7/ios_rule_script#727]
规则名称：本地局域网地址

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Lan

异常规则：https://github.com/blackmatrix7/ios_rule_script/blob/f6333009c2374ffb54dc5e328098b0815ac65ca2/rule/Clash/Lan/Lan.yaml#L129  

问题描述：运营商dns会把raw.github解析成0.0.0.0，如果把局域网规则放在最前面会先匹配到局域网规则里的0.0.0.0，导致没有正确的走代理

抓包截图：
![image](https://user-images.githubusercontent.com/84896599/191414594-273b7414-dd0a-42c7-ae68-185cee12bf12.png)

调整方案：在IP-CIDR 规则后加上no-resolve

**Comment by blackmatrix7** [comment]
按资料新版Clash是可以支持自行在规则源文件中配置no-resolve的，你可以试试。

issue我先关闭了，如果不行你再重新打开。

**Comment by linger040831** [comment]
谢谢老哥，之前问过别人了，可以直接加。
