### ISSUE TITLE
知乎助手疑似失效

### ISSUE THREAD

**Issue by jqyisbest** [blackmatrix7/ios_rule_script#729]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：知乎助手

APP版本：7.X和8.X均试了

客户端名称：小火箭

客户端版本：最新

问题描述：加载知乎助手plus模块后知乎app提示无网络，并会尝试切换Wi-Fi/蜂窝网络

复现方式：加载知乎助手plus模块，打开知乎随便刷点啥

1. ………
2. ………………

已使用空白配置文件验证：是

**Comment by z306334796** [comment]
我现在遇到的问题不是功能失效，是每次进入知乎APP都会陷入一个代理软件自动断开重连的循环，十分影响使用体验。PS我使用的是Quan X 。

**Comment by Paris0-0** [comment]
Quantumult X，好像一两个月前开始就有问题了，有时候有广告有时候没有，就是回答列表和回答里的广告时有时无，降级老版本也一样

**Comment by blackmatrix7** [comment]
没办法复现这个问题。

请先使用空白配置文件验证，如果还存在此问题，空白配置文件连带执行日志一起发出来看下。

**Comment by Paris0-0** [comment]
已解决，geoip顺序问题导致几个reject没生效
