### ISSUE TITLE
iPhone iCloud图片无法正常同步

### ISSUE THREAD

**Issue by bowzhung** [blackmatrix7/ios_rule_script#734]
规则名称：AllInOne

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf

异常规则：iCloud

问题描述：iPhone iCloud图片无法正常同步

抓包截图：无

调整方案：希望能关注下这个问题，这个问题可以说相当严重了吧

**Comment by bowzhung** [comment]
![1664343973198](https://user-images.githubusercontent.com/107580414/192698155-2e8b753e-2436-4b6c-9c6e-e17a56838906.png)


![1664344246137](https://user-images.githubusercontent.com/107580414/192698286-01c1f5f0-21d6-47d4-8fca-6422b80e009f.png)

**Comment by bowzhung** [comment]
希望可以拿掉iCloud相关，毕竟IOS本身的广告真的很干净了

**Comment by blackmatrix7** [comment]
没有发现iCloud的无法同步的问题。

这个是API Cloud，不是AP iCloud。

暂时没有发现需要处理的地方。
