### ISSUE TITLE
AdGuard 规则的最后一行均为单个字符 z

### ISSUE THREAD

**Issue by hellodword** [blackmatrix7/ios_rule_script#736]
规则名称：
[所有 AdGuard](https://github.com/blackmatrix7/ios_rule_script/tree/370ce1cbd66dc3c777bd50838ee02e0307d719eb/rule/AdGuard)

规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/370ce1cbd66dc3c777bd50838ee02e0307d719eb/rule/AdGuard

异常规则：

问题描述：
每个规则的最后一行均为 `z`，阅读 [官方语法文档](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) 没有找到能对应的，是错误还是有特定的含义？

https://github.com/blackmatrix7/ios_rule_script/blob/370ce1cbd66dc3c777bd50838ee02e0307d719eb/rule/AdGuard/AdvertisingMiTV/AdvertisingMiTV.txt#L48-L49

**Comment by blackmatrix7** [comment]
这是Bug，已修复，晚些时候更新。
