### ISSUE TITLE
谷歌翻译api错误配置于chinamax规则下

### ISSUE THREAD

**Issue by MirrorCubeSquare** [blackmatrix7/ios_rule_script#737]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Chinamax

规则链接：[ChinaMaxNoIP](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/ChinaMaxNoIP)

异常规则：  - DOMAIN,translate.googleapis.com
wwww.googletagmanager.com

问题描述：translate.googleapis.com 以及wwww.googletagmanager.com是谷歌外网的翻译api（by划词翻译）.cn才是国内
Chinamax导致划词翻译无法调用谷歌翻译（log显示走了chinamax规则，但是红字超时，表现为实质被墙）
抓包截图：(相关抓包工具的截图。)暂无，自己已经使用手动规则复写强制使用代理后正常

调整方案：去除这两条规则，交由GEOIP判断或是将这两个地址加入墙外

**Comment by MirrorCubeSquare** [comment]
补充
https://zhuanlan.zhihu.com/p/569824272
现在谷歌翻译没国内了，默认墙

**Comment by PingZi-Wing** [comment]
还有Direct规则列表也需要同步更改。

**Comment by blackmatrix7** [comment]
已移除，晚些时候更新。
