### ISSUE TITLE
未能完成该操作，无效的自变量

### ISSUE THREAD

**Issue by PowerDi** [blackmatrix7/ios_rule_script#74]
突然更新广告订阅时的提示，版本号1.0.16  如需要进一步信息可提供

**Comment by blackmatrix7** [comment]
需要提供更多信息，如果只是偶尔出现可以不理会。

**Comment by PowerDi** [comment]
可否简单说下需要什么日志，我这边可以去提取。确实是偶尔出现的，大概大半天时间。

**Comment by PowerDi** [comment]
另外还想请教一下 qx虽然是统计电量的机制问题，但开启后会不会有什么因素导致耗电量增加？（规则多，脚本） 发现待机和使用过程中电量下降很明显

**Comment by blackmatrix7** [comment]
“无效的自变量”更多的还是QuanX的问题，不是规则问题。
电量方面不太清楚，这个你应该去咨询下APP的作者。我个人认为脚本不频繁触发执行应该是不会额外耗电的，规则这个不好说。
