### ISSUE TITLE
圈叉分流下App store分流失效

### ISSUE THREAD

**Issue by TangJianM** [blackmatrix7/ios_rule_script#740]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：App store

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AppStore/AppStore.list

异常规则：rule/QuantumultX/AppStore

问题描述：App store分流规则圈叉使用后App store并不走相应策略，使用Apple分流规则才走相应策略

抓包截图：![image](https://user-images.githubusercontent.com/85019976/193491970-7d0b5a68-bc13-45d9-aabe-4fde5e1f5b50.png)![image](https://user-images.githubusercontent.com/85019976/193491986-c5a2d8ae-3aae-498f-97e0-249792e8f0e7.png)![image](https://user-images.githubusercontent.com/85019976/193491994-1bb57283-6499-4aff-98e6-503746c74049.png)

调整方案：希望能尽快解决，谢谢大佬!

**Comment by blackmatrix7** [comment]
这个 应该是规则的优先级问题，你可以在设置中修改。
