### ISSUE TITLE
Advertising规则屏蔽YouTube app搜索备选项

### ISSUE THREAD

**Issue by Captpricelsy** [blackmatrix7/ios_rule_script#742]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：rule/Quantumult X/Advertising

问题描述：设置相关策略组之后YouTube app搜索备选项获取被拦截，影响搜索体验，不影响搜索结果

抓包截图：![image](https://user-images.githubusercontent.com/50443946/193531903-d383b4c7-714b-4524-aec2-a16588baa38a.png)
![image](https://user-images.githubusercontent.com/50443946/193531964-54cb917c-fc1b-4246-82cd-afa91f4ac35c.png)
调整方案：去掉此规则

**Comment by blackmatrix7** [comment]
已移除，晚些时候更新。
