### ISSUE TITLE
dedao（得到app）在开启quan x的情况下部分内容显示异常

### ISSUE THREAD

**Issue by zwjtano** [blackmatrix7/ios_rule_script#743]
规则名称：ios_rule_script/rule QuantumultX Dedao

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/Dedao

问题描述：开启quan X，在不添加规则的情况下得到app部分内容显示系统异常，图片无法正常加载，添加规则走直连之后也是一样

[抓包截图：]([url](
![df512c324ed6d7794663ba88f76e249](https://user-images.githubusercontent.com/64340982/194533693-97101428-2a3e-4d79-9761-f1e09efac33b.jpg)
![89f807e0aaa66f32d47f47a44ac3f84](https://user-images.githubusercontent.com/64340982/194533686-b188b460-75d8-49b7-90f0-44704dfb356b.jpg)))

调整方案：希望能调整分流规则让全部得到app的流量直连

**Comment by PingZi-Wing** [comment]
我没用得到，这问题描述有点迷，不添加规则的情况下显示异常，那跟black规则有啥关系？添加规则走直连还是不行，建议看下网络活动记录，看是不是被屏蔽、或者被分流到海外、或者dns解析失败

**Comment by blackmatrix7** [comment]
建议看下抓包记录，判断是否有网络请求被拦截。
