### ISSUE TITLE
bilibili正则有误

### ISSUE THREAD

**Issue by srk24** [blackmatrix7/ios_rule_script#75]
^https?:\/\/ap(i|p)\.bilibili\.com\/((x\/v2|pgc)\/(search\/defaultword|season\/rank\/cn)|(pgc/season/rank/cn|x/v2/(search/(defaultword|hot|recommend|resource)))) - reject

比如^https?://app\.bilibili\.com/x/v\d/(search/(defaultword|square))这个搜索查询内的去除，你这样写是无法实现了。原谅我也是正则苦手，无法提出有效的建议。

**Comment by srk24** [comment]
^https?://api\.vc\.bilibili\.com/search_svr/v\d/Search/recommend_words - reject
这条可以屏蔽动态界面的搜索中的 - 大家都在搜

**Comment by srk24** [comment]
希望可以提供一个单独的去splash的js，神机那边引入你的js，但是一整个js包含内容太多了，无法自己修改界面了（指其他界面）

**Comment by blackmatrix7** [comment]
感谢提供过滤正则。
目前B站去广告复写的正则只是从现有复写脚本复制过来，不是我自己写的，所以我不太清楚它们具体是屏蔽哪些广告，只是看起来似乎有效果而已。
后续有空我会重新梳理里面的正则。

**Comment by blackmatrix7** [comment]
> 一个单独的去splash的js，神机那边引入你的js，但是一整个js包含

你说的无法自己修改界面是指什么？

**Comment by srk24** [comment]
> > 一个单独的去splash的js，神机那边引入你的js，但是一整个js包含
> 
> 你说的无法自己修改界面是指什么？

~~比如说那个js里面判断了个人界面的response，然后修改了，导致我自定义的js无法成功加载~~
我想错了，不会影响我自己的js。不过仍然建议把splash那部分单独拿出来，这样就不用一下加载那么庞大的js，不过如果你不介意，我等这两天休息的时间我尝试去做一下？

**Comment by blackmatrix7** [comment]
> > > 一个单独的去splash的js，神机那边引入你的js，但是一整个js包含
> > 
> > 
> > 你说的无法自己修改界面是指什么？
> 
> ~比如说那个js里面判断了个人界面的response，然后修改了，导致我自定义的js无法成功加载~
> 我想错了，不会影响我自己的js。不过仍然建议把splash那部分单独拿出来，这样就不用一下加载那么庞大的js，不过如果你不介意，我等这两天休息的时间我尝试去做一下？

目前没有拆分JS的想法。一方面是一个JS可以降低维护的工作量；另外一方面是多个JS必定含有一些重复的内容，APP加载这些JS需要重复加载这部分重复内容。
如果你有拆分的需求，可以自己实现一下，把Switch部分独立出来就可以。
