### ISSUE TITLE
希望增加linkedin.com 的分流规则

### ISSUE THREAD

**Issue by FRAOTIAC** [blackmatrix7/ios_rule_script#750]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Linkedin

规则链接：www.linkedin.com
问题描述：目前规则中不包含linkedin.com， GEOIP会将其识别为直连
调整方案：增加这一条规则

**Comment by topsite** [comment]
> 

www.linkedin.cn:443
RuleSet :: chinamax包括这个规则的啊，再说这个网站本身就应该是直连啊。

**Comment by FRAOTIAC** [comment]
> > 
> 
> [www.linkedin.cn:443](http://www.linkedin.cn:443) RuleSet :: chinamax包括这个规则的啊，再说这个网站本身就应该是直连啊。

你引用的这个链接是linkedin.cn, 即领英中国。而我指的是linkedin.com，即国际版领英。领英中国确实可以直连，但是这个网站不能找工作没啥用。所以我说建议添加一条linkedin.com的规则，不要识别成直连。

**Comment by websokit** [comment]
直接在QX里增加一条规则就行了

**Comment by blackmatrix7** [comment]
已加入，晚些时候更新。
