### ISSUE TITLE
wechat-clash规则中存在一个错误

### ISSUE THREAD

**Issue by studentluo** [blackmatrix7/ios_rule_script#752]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：WeChat

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml

异常规则：  - DOMAIN-KEYWORD,43.156.222.

问题描述：这条规则不工作，至少在我的clash meta核上不工作，同样应该属于  - IP-CIDR

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
例如   - IP-CIDR,43.156.222.216/32

**Comment by blackmatrix7** [comment]
因为上游规则 https://raw.githubusercontent.com/NobyDa/Script/master/Surge/WeChat.list

就是这样写的，程序没办法知晓上游规则的编写意图，也没办法对IP进行补充。

所以这个问题无法修复。

**Comment by Flora-air** [comment]
> 

我也遇到了这个问题
https://github.com/blackmatrix7/ios_rule_script/issues/939
