### ISSUE TITLE
新增美团外卖开屏广告

### ISSUE THREAD

**Issue by 1amfine2333** [blackmatrix7/ios_rule_script#762]
规则名称：AllInOne.plugin

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/Loon/AllInOne/AllInOne.plugin

异常规则：增加新的去除美团外卖开屏广告规则

问题描述：增加新的去除美团外卖开屏广告规则

抓包截图：抓到的最新的美团外卖开屏的广告链接

https://img.meituan.net/bizad/bizad_brandCpt_1666332415061127.jpg

调整方案：

  >^https://img.meituan.net/bizad/

**Comment by blackmatrix7** [comment]
谢谢提供。

不过直接过滤JPG文件的链接可能会有副作用，例如[https://img.meituan.net/bizad/](https://img.meituan.net/bizad/bizad_brandCpt_1666332415061127.jpg) 这个地址不一定只用来显示启动广告。

建议找到真正获取启动广告的请求再屏蔽。
