### ISSUE TITLE
Rewrite Ad lite 

### ISSUE THREAD

**Issue by pilioabc** [blackmatrix7/ios_rule_script#766]
Weixin 公众号视频会被误杀

**Comment by pilioabc** [comment]
![Uploading 3A601A64-4D54-4639-8280-8764B5D37D76.png…]()

**Comment by pilioabc** [comment]
![EA26C891-6A87-435F-B7B8-25222DF14186](https://user-images.githubusercontent.com/54693354/198054143-e82611c2-3d02-4fc1-ad3f-d4ddde1dff33.png)

**Comment by blackmatrix7** [comment]
能否给个文章的链接？
