### ISSUE TITLE
Game 文件夹内多条规则被再次移除

### ISSUE THREAD

**Issue by uLcdia** [blackmatrix7/ios_rule_script#769]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
**[Assassin'sCreed-Odyssey]
[Assassin'sCreed-Origins]
[GameDownload]
[TencentLoLMobile]**
规则链接：
**https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Game/Assassin'sCreed-Odyssey
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Game/Assassin'sCreed-Origins
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Game/GameDownload
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Game/TencentLoLMobile**
异常规则：
**规则被移除**
问题描述：
**原issue:https://github.com/blackmatrix7/ios_rule_script/issues/755
在 https://github.com/blackmatrix7/ios_rule_script/tree/d8ee33fe6f440d460be434e3f54fdf3c31800926/rule/Clash/Game 中被添加
在 https://github.com/blackmatrix7/ios_rule_script/tree/a744fb9099c287c1222b90163275837933aa0f9d/rule/Clash/Game 中被移除**
抓包截图：(相关抓包工具的截图。)
无
调整方案：(你希望规则做哪些调整，及其原因。)
**重新添加规则，检查规则被删除的原因**

**Comment by blackmatrix7** [comment]
谢谢反馈，这应该是Bug。

需要一些时间排查。

**Comment by blackmatrix7** [comment]
已修复。
