### ISSUE TITLE
能否恢复porn规则

### ISSUE THREAD

**Issue by qzdf** [blackmatrix7/ios_rule_script#770]
首先感谢作者的整理仓库。

之前有porn分流规则，今天更新规则的时候发现404了。
不知道是什么原因作者将其删除了，能否恢复？

下面这个是v2ray社区geosite中的porn分类，可以供作者参考
https://github.com/v2fly/domain-list-community/blob/master/data/category-porn

谢谢。

**Comment by blackmatrix7** [comment]
十分抱歉，没办法提供，因为程序是自动爬取的。

如果提供此类规则，很容易变成一个自动更新的成人网站列表。

这不利于项目健康发展，如果有此类需求，建议使用其他仓库的规则。
