### ISSUE TITLE
知乎小程序页面无法打开

### ISSUE THREAD

**Issue by Samiya321** [blackmatrix7/ios_rule_script#773]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：AdvertisingScript

APP版本：知乎

客户端名称：知乎小程序

客户端版本：最新

问题描述：https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rewrite/Surge/AdvertisingScript/AdvertisingScript.sgmodule）
里的一条Rule DOMAIN,sugar.zhihu.com,REJECT 会导致知乎小程序无法打开具体内容，注释掉就好了

如图所示：
![Clipboard 2022年11月2日 02 37](https://user-images.githubusercontent.com/36912982/199311802-723175d1-b8c8-490b-a9b7-c4e4e3cb1d33.png)
![Clipboard 2022年11月2日 02 37](https://user-images.githubusercontent.com/36912982/199311836-f212477c-b094-41a6-83e5-41b63c06d7a9.png)

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
已移除。
