### ISSUE TITLE
adobe规则收集了windows更新域名

### ISSUE THREAD

**Issue by luan0318** [blackmatrix7/ios_rule_script#778]
DOMAIN-SUFFIX,ctldl.windowsupdate.com
![E4107A49-BD83-464B-BE83-DE3AC47DFF0A](https://user-images.githubusercontent.com/10363547/200184223-eef005bd-0143-4434-bcfc-0eb793e5e3aa.png)
![5FAE72A7-4C8F-4216-8701-A58B87752B05](https://user-images.githubusercontent.com/10363547/200184232-f21a2695-7890-48ae-85ff-393f9a8b49fd.png)

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，晚些时候更新。
