### ISSUE TITLE
微信视频/语音通话规则

### ISSUE THREAD

**Issue by 0730aa** [blackmatrix7/ios_rule_script#779]
![Screenshot_20221108_103317](https://user-images.githubusercontent.com/97997625/200461032-6df300a5-a5d1-48b5-9307-eec8c5172113.jpg)
这个微信规则有没有 微信视频通话的规则？
如果没有后期有望增加吗

**Comment by Rakau** [comment]
可以自己抓包提交

**Comment by blackmatrix7** [comment]
最近加班实在比较多，暂时没有精力增加规则。

抱歉，同样欢迎共享规则。
