### ISSUE TITLE
最新更新中quanx rewrite的Advertising.conf报错

### ISSUE THREAD

**Issue by JerryJules** [blackmatrix7/ios_rule_script#78]
更新出现红字报错
invalid line ^https?:\/\/kaola-haitao\.oss\.kaolacdn.com\/.+?_\d{3 url reject

**Comment by blackmatrix7** [comment]
今天改动比较多，晚上再仔细看下为什么这个规则有问题，现在先暂时不要更新。

**Comment by blackmatrix7** [comment]
已经修复
