### ISSUE TITLE
方案建议：China_Domain规则精简

### ISSUE THREAD

**Issue by LimeAroma** [blackmatrix7/ios_rule_script#786]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：China_Domain

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Loon/China/China_Domain.list

异常规则：无

问题描述：无

抓包截图：无

调整方案：已经存在.cn规则，其他.cn域名规则可以精简掉

**Comment by blackmatrix7** [comment]
最近事情比较多，需要晚些时候改下代码。

**Comment by blackmatrix7** [comment]
谢谢反馈，已修改生成器移除重复规则。
