### ISSUE TITLE
请求将 accuweather.com 移出 China 规则

### ISSUE THREAD

**Issue by xiakele** [blackmatrix7/ios_rule_script#787]
规则名称：China

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/China

异常规则：350行 `DOMAIN-SUFFIX,accuweather.com`

问题描述：用中国 ip 访问 accuweather.com 会跳转到 m.weathercn.com ，无法访问源站

调整方案：将 accuweather.com 移出 China 规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，晚些更新。
