### ISSUE TITLE
抖音规则补充

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#789]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Douyin

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/DouYin/DouYin.list

异常规则：补充规则
host-suffix, amemv.com
host-suffix, awemeughun.com
host-suffix, douyincdn.com
host-suffix, douyinvod.com
host-suffix, douyinpic.com
host-suffix, douyinstatic.com
host-suffix, idouyinvod.com
host-suffix, byteactivity.com
host-suffix, bytecdn.cn
host-suffix, bytecdn.com
host-suffix, byteeffecttos.com
host-suffix, bytegecko.com
host-suffix, bytegoofy.com
host-suffix, byteimg.com
host-suffix, bytescm.com
host-suffix, bytedance.com
host-suffix, bytemastatic.com
host-suffix, bytetos.com
host-suffix, byteacctimg.com
host-suffix, bytednsdoc.com
host-suffix, ecombdapi.com
host-suffix, ecombdimg.com
host-suffix, ecombdstatic.com
host-suffix, ibytedapm.com
host-suffix, umeng.com
host-suffix, xycdn.com
host-suffix, zijieapi.com
host-suffix, zjcdn.com

问题描述：

抓包截图：

调整方案：补充规则

**Comment by blackmatrix7** [comment]
host-suffix, douyincdn.com
host-suffix, douyinvod.com
host-suffix, douyinpic.com
host-suffix, douyinstatic.com
host-suffix, idouyinvod.com

加入了以上规则，部分规则可能需要再讨论下。
比如umeng.com明显不是抖音的域名

**Comment by tkzc11** [comment]
我认为有byte和zijie（字节）的规则也应该加入使用过程中有大量请求從我的iPhone傳送blackmatrix7 ***@***.***>於2022年11月17日 下午2:40寫道：﻿
Closed #789 as completed.
