### ISSUE TITLE
Bilibili无法观看带手机标识的视频

### ISSUE THREAD

**Issue by char1eslu** [blackmatrix7/ios_rule_script#79]
surge使用module后，去广告效果良好，但无法观看视频推荐面带手机标识的视频，此类视频类似抖音那种的短视频

**Comment by blackmatrix7** [comment]
没注意看到过这种视频，方便给个链接吗？

**Comment by char1eslu** [comment]
[cid:1ABB350D-60E3-4B2D-88F0-E98C09DA2789-L0-001][cid:4C6E39A8-BE31-4407-8EFE-2E3A60F9FCF1-L0-001]就类似这种哈，左下角有这种标识的，打开就是黑色，只能左上角返回，下滑和右上角点不了或无用

On Nov 21, 2020, at 00:08, blackmatrix7 <notifications@github.com> wrote:

﻿

没注意看到过这种视频，方便给个链接吗？

**Comment by blackmatrix7** [comment]
图片没有正常显示

**Comment by char1eslu** [comment]
![image](https://user-images.githubusercontent.com/20885743/99823403-50bfd900-2b8f-11eb-8e31-a0095e459804.jpeg)![image](https://user-images.githubusercontent.com/20885743/99823427-561d2380-2b8f-11eb-82d6-9d0680c8509b.png)

啊，抱歉，现在这样不知行不行

**Comment by blackmatrix7** [comment]
我第一次看到这种视频，你是什么版本的，还是说需要打开什么开关，或者这是灰度测试？

**Comment by char1eslu** [comment]
![image](https://user-images.githubusercontent.com/20885743/99824061-202c6f00-2b90-11eb-8b82-ab0dcc7ffa01.png)

商店版本呢，我检查设置好像也没有哎，此类视频就类似于抖音视频那种，短视频，向上滑切换的

**Comment by blackmatrix7** [comment]
我已经升级到最新版本，刷了一会推荐，还是没看到你说的这类视频。似乎它是区分账号进行推荐的，现在这个情况不太好处理，我刷不出这类视频，不太好确认那条规则造成误杀。只能等我自己是账号什么时候能刷出此类视频再排查了。

**Comment by char1eslu** [comment]
嗯嗯，好的呢，谢谢啦

**Comment by MisterGlasses** [comment]
我也遇到了 大佬看下
`https://api.vc.bilibili.com/link_setting/v1/link_setting/bilibili_uid?access_key=0cfde707b0de57fe2677d8ccaf1aecb1&actionKey=appkey&appkey=27eb53fc9058f8c3&build=10370&device=phone&mobi_app=iphone&platform=ios&s_locale=zh-Hans_CN&sign=3e2120551fa6f77bd2c6e206f5237d3f&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.14.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1606442146 `
![690C9AF0-10B3-4A7A-B1BD-BF2FDA040F58](https://user-images.githubusercontent.com/27768847/100402282-d6172200-3096-11eb-90dd-799180e4f37a.png)

**Comment by blackmatrix7** [comment]
> 我也遇到了 大佬看下
> 
> `https://api.vc.bilibili.com/link_setting/v1/link_setting/bilibili_uid?access_key=0cfde707b0de57fe2677d8ccaf1aecb1&actionKey=appkey&appkey=27eb53fc9058f8c3&build=10370&device=phone&mobi_app=iphone&platform=ios&s_locale=zh-Hans_CN&sign=3e2120551fa6f77bd2c6e206f5237d3f&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.14.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1606442146 `
> 
> ![690C9AF0-10B3-4A7A-B1BD-BF2FDA040F58](https://user-images.githubusercontent.com/27768847/100402282-d6172200-3096-11eb-90dd-799180e4f37a.png)
> 
> 
你这个是抓包的结果吗？视频请求的是这个地址的数据？

**Comment by MisterGlasses** [comment]
> > 我也遇到了 大佬看下
> > `https://api.vc.bilibili.com/link_setting/v1/link_setting/bilibili_uid?access_key=0cfde707b0de57fe2677d8ccaf1aecb1&actionKey=appkey&appkey=27eb53fc9058f8c3&build=10370&device=phone&mobi_app=iphone&platform=ios&s_locale=zh-Hans_CN&sign=3e2120551fa6f77bd2c6e206f5237d3f&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.14.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1606442146 `
> > ![690C9AF0-10B3-4A7A-B1BD-BF2FDA040F58](https://user-images.githubusercontent.com/27768847/100402282-d6172200-3096-11eb-90dd-799180e4f37a.png)
> 
> 你这个是抓包的结果吗？视频请求的是这个地址的数据？

我试着抓包了 但不清楚是不是这个 此外我自己尝试改了bilibili域名的dns 无法解决黑屏问题 把qx的复写功能单独关闭 就能解决 应该是复写导致的 每次黑屏时 qx访问记录里总有如上图所示的Socket Closed by remote peer

**Comment by blackmatrix7** [comment]
> > > 我也遇到了 大佬看下
> 
> > > `https://api.vc.bilibili.com/link_setting/v1/link_setting/bilibili_uid?access_key=0cfde707b0de57fe2677d8ccaf1aecb1&actionKey=appkey&appkey=27eb53fc9058f8c3&build=10370&device=phone&mobi_app=iphone&platform=ios&s_locale=zh-Hans_CN&sign=3e2120551fa6f77bd2c6e206f5237d3f&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.14.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1606442146 `
> 
> > > ![690C9AF0-10B3-4A7A-B1BD-BF2FDA040F58](https://user-images.githubusercontent.com/27768847/100402282-d6172200-3096-11eb-90dd-799180e4f37a.png)
> 
> > 
> 
> > 你这个是抓包的结果吗？视频请求的是这个地址的数据？
> 
> 
> 
> 我试着抓包了 但不清楚是不是这个 此外我自己尝试改了bilibili域名的dns 无法解决黑屏问题 把qx的复写功能单独关闭 就能解决 应该是复写导致的 每次黑屏时 qx访问记录里总有如上图所示的Socket Closed by remote peer 

因为B站不会给我的账号推送仿抖音这类型的视频，所以我很难知道是什么规则导致视频被拦截。
只能靠你们抓包告诉我哪个规则我再去掉，或者等我借到个可以刷出此类视频的账号…

**Comment by MisterGlasses** [comment]
> > > > 我也遇到了 大佬看下
> > 
> > 
> > > > `https://api.vc.bilibili.com/link_setting/v1/link_setting/bilibili_uid?access_key=0cfde707b0de57fe2677d8ccaf1aecb1&actionKey=appkey&appkey=27eb53fc9058f8c3&build=10370&device=phone&mobi_app=iphone&platform=ios&s_locale=zh-Hans_CN&sign=3e2120551fa6f77bd2c6e206f5237d3f&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.14.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1606442146 `
> > 
> > 
> > > > ![690C9AF0-10B3-4A7A-B1BD-BF2FDA040F58](https://user-images.githubusercontent.com/27768847/100402282-d6172200-3096-11eb-90dd-799180e4f37a.png)
> > 
> > 
> > > 
> > 
> > 
> > > 你这个是抓包的结果吗？视频请求的是这个地址的数据？
> > 
> > 
> > 我试着抓包了 但不清楚是不是这个 此外我自己尝试改了bilibili域名的dns 无法解决黑屏问题 把qx的复写功能单独关闭 就能解决 应该是复写导致的 每次黑屏时 qx访问记录里总有如上图所示的Socket Closed by remote peer
> 
> 因为B站不会给我的账号推送仿抖音这类型的视频，所以我很难知道是什么规则导致视频被拦截。
> 只能靠你们抓包告诉我哪个规则我再去掉，或者等我借到个可以刷出此类视频的账号…

我正在挨个测试规则 如果查不出来我再提供账号 老哥可以留个联系方式

**Comment by blackmatrix7** [comment]
> > > > > 我也遇到了 大佬看下
> 
> > > 
> 
> > > 
> 
> > > > > `https://api.vc.bilibili.com/link_setting/v1/link_setting/bilibili_uid?access_key=0cfde707b0de57fe2677d8ccaf1aecb1&actionKey=appkey&appkey=27eb53fc9058f8c3&build=10370&device=phone&mobi_app=iphone&platform=ios&s_locale=zh-Hans_CN&sign=3e2120551fa6f77bd2c6e206f5237d3f&statistics=%7B%22appId%22%3A1%2C%22version%22%3A%226.14.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D&ts=1606442146 `
> 
> > > 
> 
> > > 
> 
> > > > > ![690C9AF0-10B3-4A7A-B1BD-BF2FDA040F58](https://user-images.githubusercontent.com/27768847/100402282-d6172200-3096-11eb-90dd-799180e4f37a.png)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你这个是抓包的结果吗？视频请求的是这个地址的数据？
> 
> > > 
> 
> > > 
> 
> > > 我试着抓包了 但不清楚是不是这个 此外我自己尝试改了bilibili域名的dns 无法解决黑屏问题 把qx的复写功能单独关闭 就能解决 应该是复写导致的 每次黑屏时 qx访问记录里总有如上图所示的Socket Closed by remote peer
> 
> > 
> 
> > 因为B站不会给我的账号推送仿抖音这类型的视频，所以我很难知道是什么规则导致视频被拦截。
> 
> > 只能靠你们抓包告诉我哪个规则我再去掉，或者等我借到个可以刷出此类视频的账号…
> 
> 
> 
> 我正在挨个测试规则 如果查不出来我再提供账号 老哥可以留个联系方式
麻烦你先抓包看看，不行的话周日晚上我再借你账号试试，最近事情太多了，腾不出时间来。

**Comment by MisterGlasses** [comment]
使用排除法 大概率是因为这一条 但还需要大佬查证
`# 推荐去广告
^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/bilibili/bilibili_plus.js `
![122ACAFB-FD36-4DFF-AD3B-1CA36F20D7D3](https://user-images.githubusercontent.com/27768847/100451729-dd6c1900-30f2-11eb-91b6-f34012f436b3.png)
![67A9FD85-0749-41B7-93F3-4309F9D5A3C1](https://user-images.githubusercontent.com/27768847/100451737-e0670980-30f2-11eb-8619-6a5cf840187e.png)
![42F019FE-D119-4085-A5F4-8DE036DB4B50](https://user-images.githubusercontent.com/27768847/100451743-e3fa9080-30f2-11eb-9df5-a18634f3e9cb.png)

**Comment by MisterGlasses** [comment]
> 使用排除法 大概率是因为这一条 但还需要大佬查证
> `# 推荐去广告 ^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/bilibili/bilibili_plus.js `
> ![122ACAFB-FD36-4DFF-AD3B-1CA36F20D7D3](https://user-images.githubusercontent.com/27768847/100451729-dd6c1900-30f2-11eb-91b6-f34012f436b3.png)
> ![67A9FD85-0749-41B7-93F3-4309F9D5A3C1](https://user-images.githubusercontent.com/27768847/100451737-e0670980-30f2-11eb-8619-6a5cf840187e.png)
> ![42F019FE-D119-4085-A5F4-8DE036DB4B50](https://user-images.githubusercontent.com/27768847/100451743-e3fa9080-30f2-11eb-9df5-a18634f3e9cb.png)

用资源解析器屏蔽了这一条 刷了一个小时这种类型的视频 正常

**Comment by blackmatrix7** [comment]
太感谢了，帮我排查这么久。脚本的话，我试着重写一下看看效果。

**Comment by blackmatrix7** [comment]
> > 使用排除法 大概率是因为这一条 但还需要大佬查证
> > `# 推荐去广告 ^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/bilibili/bilibili_plus.js `
> > ![122ACAFB-FD36-4DFF-AD3B-1CA36F20D7D3](https://user-images.githubusercontent.com/27768847/100451729-dd6c1900-30f2-11eb-91b6-f34012f436b3.png)
> > ![67A9FD85-0749-41B7-93F3-4309F9D5A3C1](https://user-images.githubusercontent.com/27768847/100451737-e0670980-30f2-11eb-8619-6a5cf840187e.png)
> > ![42F019FE-D119-4085-A5F4-8DE036DB4B50](https://user-images.githubusercontent.com/27768847/100451743-e3fa9080-30f2-11eb-9df5-a18634f3e9cb.png)
> 
> 用资源解析器屏蔽了这一条 刷了一个小时这种类型的视频 正常

太感谢了，帮我排查这么久。脚本的话，我试着重写一下看看效果。

**Comment by MisterGlasses** [comment]
> > > 使用排除法 大概率是因为这一条 但还需要大佬查证
> > > `# 推荐去广告 ^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/bilibili/bilibili_plus.js `
> > > ![122ACAFB-FD36-4DFF-AD3B-1CA36F20D7D3](https://user-images.githubusercontent.com/27768847/100451729-dd6c1900-30f2-11eb-91b6-f34012f436b3.png)
> > > ![67A9FD85-0749-41B7-93F3-4309F9D5A3C1](https://user-images.githubusercontent.com/27768847/100451737-e0670980-30f2-11eb-8619-6a5cf840187e.png)
> > > ![42F019FE-D119-4085-A5F4-8DE036DB4B50](https://user-images.githubusercontent.com/27768847/100451743-e3fa9080-30f2-11eb-9df5-a18634f3e9cb.png)
> > 
> > 
> > 用资源解析器屏蔽了这一条 刷了一个小时这种类型的视频 正常
> 
> 太感谢了，帮我排查这么久。脚本的话，我试着重写一下看看效果。

麻烦了 到时候我再协助测试

**Comment by blackmatrix7** [comment]
> > > > 使用排除法 大概率是因为这一条 但还需要大佬查证
> > > > `# 推荐去广告 ^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/bilibili/bilibili_plus.js `
> > > > ![122ACAFB-FD36-4DFF-AD3B-1CA36F20D7D3](https://user-images.githubusercontent.com/27768847/100451729-dd6c1900-30f2-11eb-91b6-f34012f436b3.png)
> > > > ![67A9FD85-0749-41B7-93F3-4309F9D5A3C1](https://user-images.githubusercontent.com/27768847/100451737-e0670980-30f2-11eb-8619-6a5cf840187e.png)
> > > > ![42F019FE-D119-4085-A5F4-8DE036DB4B50](https://user-images.githubusercontent.com/27768847/100451743-e3fa9080-30f2-11eb-9df5-a18634f3e9cb.png)
> > > 
> > > 
> > > 用资源解析器屏蔽了这一条 刷了一个小时这种类型的视频 正常
> > 
> > 
> > 太感谢了，帮我排查这么久。脚本的话，我试着重写一下看看效果。
> 
> 麻烦了 到时候我再协助测试

能否把https://app.bilibili.com/x/v2/feed/index这个url的response发我一下？

**Comment by MisterGlasses** [comment]
在启用规则的情况下还是禁用规则的情况下？

**Comment by blackmatrix7** [comment]
> 在启用规则的情况下还是禁用规则的情况下？

禁用的情况下，我看看它原始的返回结果是什么？就是带那个手机标志的视频时。

**Comment by MisterGlasses** [comment]
> > 在启用规则的情况下还是禁用规则的情况下？
> 
> 禁用的情况下，我看看它原始的返回结果是什么？就是带那个手机标志的视频时。

启用规则时
HTTP/1.1 200 OK
Date: Sun, 29 Nov 2020 09:16:22 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Bili-Status-Code: 0
Bili-Trace-Id: 4bf07f2c9e5fc366
X-Cache-Webcdn: BYPASS from hw-bj4-webcdn-14
Content-Encoding: identity
禁用规则时没有这个链接的记录 只有类似这种的记录`http://***.mcdn.bilivideo.cn:480/upgcxcode/06/49/259224906/259224906_nb2-1-30232.m4s?expires=1606648902&platform=iphone&ssig=2P5p7QJrQ987FVyxv-B6Sw&oi=2574709911&trid=6a9eeade159f425aa0537a76b2150a88U&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=1001128&mid=39805540&orderid=0,2&logo=A0000001 `
响应头如下
HTTP/1.1 206 Partial Content
Content-Type: video/mp4
Content-Length: 667597
connection: close
Date: Sun, 29 Nov 2020 09:21:43 GMT
Content-Range: bytes 0-667596/667597
Last-Modified: Thu, 26 Nov 2020 09:51:49 GMT
Server: bvs/1.5.1

**Comment by blackmatrix7** [comment]
> > > 在启用规则的情况下还是禁用规则的情况下？
> > 
> > 
> > 禁用的情况下，我看看它原始的返回结果是什么？就是带那个手机标志的视频时。
> 
> 启用规则时
> HTTP/1.1 200 OK
> Date: Sun, 29 Nov 2020 09:16:22 GMT
> Content-Type: application/json; charset=utf-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Bili-Status-Code: 0
> Bili-Trace-Id: 4bf07f2c9e5fc366
> X-Cache-Webcdn: BYPASS from hw-bj4-webcdn-14
> Content-Encoding: identity
> 禁用规则时没有这个链接的记录 只有类似这种的记录`http://***.mcdn.bilivideo.cn:480/upgcxcode/06/49/259224906/259224906_nb2-1-30232.m4s?expires=1606648902&platform=iphone&ssig=2P5p7QJrQ987FVyxv-B6Sw&oi=2574709911&trid=6a9eeade159f425aa0537a76b2150a88U&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=1001128&mid=39805540&orderid=0,2&logo=A0000001 `
> 响应头如下
> HTTP/1.1 206 Partial Content
> Content-Type: video/mp4
> Content-Length: 667597
> connection: close
> Date: Sun, 29 Nov 2020 09:21:43 GMT
> Content-Range: bytes 0-667596/667597
> Last-Modified: Thu, 26 Nov 2020 09:51:49 GMT
> Server: bvs/1.5.1

你用的QuanX吗？需要把调试打开，然后看看调试记录里，搜索feed之类的关键字，看响应部分，有Response。

**Comment by MisterGlasses** [comment]
> > > > 在启用规则的情况下还是禁用规则的情况下？
> > > 
> > > 
> > > 禁用的情况下，我看看它原始的返回结果是什么？就是带那个手机标志的视频时。
> > 
> > 
> > 启用规则时
> > HTTP/1.1 200 OK
> > Date: Sun, 29 Nov 2020 09:16:22 GMT
> > Content-Type: application/json; charset=utf-8
> > Transfer-Encoding: chunked
> > Connection: keep-alive
> > Bili-Status-Code: 0
> > Bili-Trace-Id: 4bf07f2c9e5fc366
> > X-Cache-Webcdn: BYPASS from hw-bj4-webcdn-14
> > Content-Encoding: identity
> > 禁用规则时没有这个链接的记录 只有类似这种的记录`http://***.mcdn.bilivideo.cn:480/upgcxcode/06/49/259224906/259224906_nb2-1-30232.m4s?expires=1606648902&platform=iphone&ssig=2P5p7QJrQ987FVyxv-B6Sw&oi=2574709911&trid=6a9eeade159f425aa0537a76b2150a88U&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=1001128&mid=39805540&orderid=0,2&logo=A0000001 `
> > 响应头如下
> > HTTP/1.1 206 Partial Content
> > Content-Type: video/mp4
> > Content-Length: 667597
> > connection: close
> > Date: Sun, 29 Nov 2020 09:21:43 GMT
> > Content-Range: bytes 0-667596/667597
> > Last-Modified: Thu, 26 Nov 2020 09:51:49 GMT
> > Server: bvs/1.5.1
> 
> 你用的QuanX吗？需要把调试打开，然后看看调试记录里，搜索feed之类的关键字，看响应部分，有Response。

开qx调试的情况下 禁用规则 搜feed没有记录 只有上边提到的记录

**Comment by blackmatrix7** [comment]
> > > > > 在启用规则的情况下还是禁用规则的情况下？
> > > > 
> > > > 
> > > > 禁用的情况下，我看看它原始的返回结果是什么？就是带那个手机标志的视频时。
> > > 
> > > 
> > > 启用规则时
> > > HTTP/1.1 200 OK
> > > Date: Sun, 29 Nov 2020 09:16:22 GMT
> > > Content-Type: application/json; charset=utf-8
> > > Transfer-Encoding: chunked
> > > Connection: keep-alive
> > > Bili-Status-Code: 0
> > > Bili-Trace-Id: 4bf07f2c9e5fc366
> > > X-Cache-Webcdn: BYPASS from hw-bj4-webcdn-14
> > > Content-Encoding: identity
> > > 禁用规则时没有这个链接的记录 只有类似这种的记录`http://***.mcdn.bilivideo.cn:480/upgcxcode/06/49/259224906/259224906_nb2-1-30232.m4s?expires=1606648902&platform=iphone&ssig=2P5p7QJrQ987FVyxv-B6Sw&oi=2574709911&trid=6a9eeade159f425aa0537a76b2150a88U&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=1001128&mid=39805540&orderid=0,2&logo=A0000001 `
> > > 响应头如下
> > > HTTP/1.1 206 Partial Content
> > > Content-Type: video/mp4
> > > Content-Length: 667597
> > > connection: close
> > > Date: Sun, 29 Nov 2020 09:21:43 GMT
> > > Content-Range: bytes 0-667596/667597
> > > Last-Modified: Thu, 26 Nov 2020 09:51:49 GMT
> > > Server: bvs/1.5.1
> > 
> > 
> > 你用的QuanX吗？需要把调试打开，然后看看调试记录里，搜索feed之类的关键字，看响应部分，有Response。
> 
> 开qx调试的情况下 禁用规则 搜feed没有记录 只有上边提到的记录

你有telegram吗？留个号给我，我加你吧，这样沟通太慢了。

**Comment by MisterGlasses** [comment]
> > > > > > 在启用规则的情况下还是禁用规则的情况下？
> > > > > 
> > > > > 
> > > > > 禁用的情况下，我看看它原始的返回结果是什么？就是带那个手机标志的视频时。
> > > > 
> > > > 
> > > > 启用规则时
> > > > HTTP/1.1 200 OK
> > > > Date: Sun, 29 Nov 2020 09:16:22 GMT
> > > > Content-Type: application/json; charset=utf-8
> > > > Transfer-Encoding: chunked
> > > > Connection: keep-alive
> > > > Bili-Status-Code: 0
> > > > Bili-Trace-Id: 4bf07f2c9e5fc366
> > > > X-Cache-Webcdn: BYPASS from hw-bj4-webcdn-14
> > > > Content-Encoding: identity
> > > > 禁用规则时没有这个链接的记录 只有类似这种的记录`http://***.mcdn.bilivideo.cn:480/upgcxcode/06/49/259224906/259224906_nb2-1-30232.m4s?expires=1606648902&platform=iphone&ssig=2P5p7QJrQ987FVyxv-B6Sw&oi=2574709911&trid=6a9eeade159f425aa0537a76b2150a88U&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=1001128&mid=39805540&orderid=0,2&logo=A0000001 `
> > > > 响应头如下
> > > > HTTP/1.1 206 Partial Content
> > > > Content-Type: video/mp4
> > > > Content-Length: 667597
> > > > connection: close
> > > > Date: Sun, 29 Nov 2020 09:21:43 GMT
> > > > Content-Range: bytes 0-667596/667597
> > > > Last-Modified: Thu, 26 Nov 2020 09:51:49 GMT
> > > > Server: bvs/1.5.1
> > > 
> > > 
> > > 你用的QuanX吗？需要把调试打开，然后看看调试记录里，搜索feed之类的关键字，看响应部分，有Response。
> > 
> > 
> > 开qx调试的情况下 禁用规则 搜feed没有记录 只有上边提到的记录
> 
> 你有telegram吗？留个号给我，我加你吧，这样沟通太慢了。

有QQ871569275
