### ISSUE TITLE
去广告分流导致Tim无法加载头像

### ISSUE THREAD

**Issue by 42vio** [blackmatrix7/ios_rule_script#792]
https://github.com/blackmatrix7/ios_rule_script/commits/master/rule/QuantumultX/Advertising/Advertising.list

q.qlogo.cn 被reject，无法加载 Tim/QQ 中的联系人头像。

**Comment by XINGYUZHMM** [comment]
![image](https://user-images.githubusercontent.com/112518475/203077530-23e79067-b4f1-4de1-b8be-37968fa8290d.png)
to同样情况

**Comment by 5uperv1sed** [comment]
我qq头像也都加载不出来，加了个本地分流规则暂时解决了，坐等大佬修复

**Comment by Sagittarius16th** [comment]
➕1⃣️

**Comment by blackmatrix7** [comment]
目前没有在规则文件里搜索到这条，推测上游已经移除掉了。

不过还是在过滤器里加入了这条，防止再次出现。

晚些时候更新。
