### ISSUE TITLE
修改任天堂规则一句规则

### ISSUE THREAD

**Issue by Rakau** [blackmatrix7/ios_rule_script#793]
规则名称：Nintendo

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Nintendo/Nintendo.yaml

问题描述： 漏了

抓包截图：(相关抓包工具的截图。)

调整方案：    - IP-CIDR,35.224.0.0/12改- IP-CIDR,35.223.0.0/12

**Comment by blackmatrix7** [comment]
谢谢反馈，已修改，晚些时候更新。
