### ISSUE TITLE
知乎助手清理数据报错

### ISSUE THREAD

**Issue by Tangfffyx** [blackmatrix7/ios_rule_script#796]
脚本名称：知乎助手

APP版本：知乎 8.33

客户端名称：qx

客户端版本：最新

问题描述：boxjs 里手动执行知乎助手清理数据报错（内容为：SyntaxError: Unexpected token ':'. Parse error.），请问有没有知乎助手的数据值（key）提供以供在 boxjs 里清理知乎助手持久化数据。

已使用空白配置文件验证：否

**Comment by blackmatrix7** [comment]
已知问题，直接执行脚本可以清理，但是在boxjs中不行。

近期事情较多，没有修复的计划。

知乎助手使用以下key：zhihu_blocked_users、zhihu_current_userinfo、zhihu_keyword_block
