### ISSUE TITLE
头条去广告

### ISSUE THREAD

**Issue by zjcfynn** [blackmatrix7/ios_rule_script#8]
头条去广告能不能加强一下、目前用的头条最新版、被我刷出来了暗黑模式、但就是广告太多了。麻烦了

**Comment by blackmatrix7** [comment]
你可能搞错了，头条那个不是用来去广告的。是我个人使用的，用来过滤不想看到的信息，不建议你使用，会误杀很多正常内容。头条应该有个Pro版没有广告吧？

**Comment by zjcfynn** [comment]
就是目前普通版有暗黑模式而pro版没有，就有了这个需求

**Comment by blackmatrix7** [comment]
近期没有为头条去广告的计划，建议等下头条Pro的更新，看看是否会加入暗黑模式。
