### ISSUE TITLE
bilibili是否可以去掉视频下方推荐的广告和评论中通知横条

### ISSUE THREAD

**Issue by NightAsker** [blackmatrix7/ios_rule_script#80]
感谢大佬写的bilibili去广告脚本，很好用，不知道去掉视频下方推荐的广告和评论中通知横条（我抓包的时候发现这些信息好像都被加密了），如下面图片中红色框中的广告
<img width="407" alt="image" src="https://user-images.githubusercontent.com/64188869/99867598-c8285380-2bf5-11eb-9e75-78299219995f.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/64188869/99867607-d8d8c980-2bf5-11eb-846b-6c5e73584ddd.png">

**Comment by blackmatrix7** [comment]
第一个广告去不掉。
第二个广告没遇到过，麻烦给个明确的可以触发这个广告的视频或方法。

**Comment by blackmatrix7** [comment]
如果没有进一步反馈，我就先关闭了。
