### ISSUE TITLE
game.subway.uu.cc域名拦截导致游戏加载失败

### ISSUE THREAD

**Issue by WeeekWin** [blackmatrix7/ios_rule_script#804]
------

规则名称：Advertising

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list

异常规则：game.subway.uu.cc  reject

问题描述：无法加载地铁跑酷游戏

调整方案：取消拦截 或者在Host添加direct

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
