### ISSUE TITLE
Emby 匹配规则过于宽泛，易错误命中

### ISSUE THREAD

**Issue by Xm798** [blackmatrix7/ios_rule_script#807]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：

Emby

规则链接：

https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Emby/Emby.list

异常规则：

DOMAIN-KEYWORD,emby

问题描述：

许多个人自建的 Emby 服务器也会使用 Emby 作为子域名，在已有绝大多数公益服规则的情况下，无需再使用关键词匹配。使用关键词匹配 emby 容易造成大范围的错误命中。

调整方案：

移除该规则

**Comment by Xm798** [comment]
@justdoiting 抄送一下规则上游作者

**Comment by justdoiting** [comment]
同意，DOMAIN-KEYWORD,xeton.dev 这条规则也建议移除

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
