### ISSUE TITLE
域名国内无法访问

### ISSUE THREAD

**Issue by Atroc-X** [blackmatrix7/ios_rule_script#812]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：China_Domain.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_Domain.list

异常规则：forums.liyuans.com

问题描述：国内无法直连访问，截图为国内外dns解析结果。

抓包截图：(
![image](https://user-images.githubusercontent.com/93807457/204807837-f70db63a-9f3b-4541-b762-7c801556d82e.png)
)

调整方案：(移去China_Domain加入Global_Domain)

**Comment by blackmatrix7** [comment]
谢谢反馈，问题已复现，已经移除规则。
