### ISSUE TITLE
quanX知乎助手会失效

### ISSUE THREAD

**Issue by Y2hhbw** [blackmatrix7/ios_rule_script#82]
分流zhihu.list放在最前
复写zhihu_plus.qxrewrite放在最前

有时会出现去广告失效
quanx日志如下：
[ERROR] [知乎助手]
知乎推荐列表去广告出现异常：TypeError: undefined is not an object (evaluating 'element['common_card']['feed_content']['source_line']['elements']')
2020/11/25 07:18:56:315  <console>    [JS Console]: [ERROR] [知乎助手]
知乎推荐列表去广告出现异常：TypeError: undefined is not an object (evaluating 'element['common_card']['feed_content']['source_line']['elements']')

去广告成功的情况下看一些问题时，点进去会出现加载失败 需要点击重新加载才会出现界面

**Comment by blackmatrix7** [comment]
第一个是已知问题，等有空了处理。
第二个有人也反馈过，但是我没办法复现。推测可能和拦截预加载有关系，你试试Lite版本会不会也出现这个问题？

**Comment by Y2hhbw** [comment]
好的我了解了，谢谢解答

**Comment by blackmatrix7** [comment]
已经做了更新，你试试是否解决异常第一个问题。
第二个问题需要想办法复现。

**Comment by Y2hhbw** [comment]
好的，谢谢大佬，我继续体验几天看看
