### ISSUE TITLE
clash规则里domain类型链接错误，需改为yaml后缀

### ISSUE THREAD

**Issue by XINGYUZHMM** [blackmatrix7/ios_rule_script#820]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：clash所有domain类型rule

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.txt

异常规则：clash规则里domain默认用的是txt后缀的连接，里面的格式无法用于clash
![image](https://user-images.githubusercontent.com/112518475/206688543-17eff21b-b33f-440a-ace1-d06183b1982e.png)

![image](https://user-images.githubusercontent.com/112518475/206675034-a5077100-68ab-4e18-9928-d3215e8f8cad.png)

问题描述：原来没注意有yaml格式的连接，建议把clash里的domain相关都改成yaml后缀的连接。
![image](https://user-images.githubusercontent.com/112518475/206675006-739767c4-7d87-47d7-aec3-7133c95aa2eb.png)

**Comment by blackmatrix7** [comment]
你好

txt格式是给Stash用的，不是给Clash用的。

Clash用yaml格式。
