### ISSUE TITLE
整合B站GRPC去广告

### ISSUE THREAD

**Issue by NyaMisty** [blackmatrix7/ios_rule_script#821]
#404 中提到的脚本现已经重新开始维护，在不是rm的另一个分支：
https://github.com/yjqiang/surge_scripts/tree/main

**Comment by blackmatrix7** [comment]
仓库主要满足个人需求。

目前B站国际版已基本满足个人使用需求，所以暂时没有继续维护B站去广告脚本的动力。

抱歉了。
