### ISSUE TITLE
规则异常

### ISSUE THREAD

**Issue by linger040831** [blackmatrix7/ios_rule_script#823]
规则名称：
Global
规则链接：
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Global
异常规则：
  - DOMAIN,xz.pphimalayanrt.com

问题描述：
这个应该是steam国内的cdn
抓包截图：(相关抓包工具的截图。)
<img width="383" alt="image" src="https://user-images.githubusercontent.com/84896599/206961004-03ee99fd-3deb-4553-a49b-4786dc6b650b.png">

调整方案：(你希望规则做哪些调整，及其原因。)
在steamcn里添加  - DOMAIN,xz.pphimalayanrt.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已修正，晚些时候更新。
