### ISSUE TITLE
规则误杀反馈

### ISSUE THREAD

**Issue by RuCu6** [blackmatrix7/ios_rule_script#826]
host-suffix, api.jr.mi.com

存在误杀情况  小米贷款，金融无法使用
![AD65D1F9-F30E-4F1C-B44B-0BF87033DC82](https://user-images.githubusercontent.com/49463634/207799774-edaca8b1-e51a-42bc-b199-d31ca5572809.png)

**Comment by RuCu6** [comment]
![3E4C377D-DC70-4E0E-A964-B84B5D70BE37](https://user-images.githubusercontent.com/49463634/207799913-16d655eb-7c51-4ce6-a286-5d01b2722c2e.jpeg)

**Comment by blackmatrix7** [comment]
已修复
