### ISSUE TITLE
Facebook规则优化

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#827]
规则名称：Facebook

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/Facebook/Facebook.list

异常规则：https://raw.githubusercontent.com/tkzc11/QX-Rules/main/Meta.list

问题描述：用asn代替部分规则

抓包截图：(相关抓包工具的截图。)

调整方案：优化规则

**Comment by blackmatrix7** [comment]
新增了你提供的数据源，晚些时候会更新。

对于CIDR和ASN合并，目前仅对CIDR的IP段范围较小时才会查询归属的ASN，然后进行合并去重。

否则如果对所有CIDR范围内的每个IP地址都查询ASN，规则生成时间会非常非常长，难以接受。

同时，只有CIDR范围内的所有IP，都归属于同个ASN时，才会去重，否则还需要对CIDR地址进行拆分，会非常繁琐，这部分后续可能会优化。
