### ISSUE TITLE
[WARNING] [什么值得买] 获取好文列表失败

### ISSUE THREAD

**Issue by hunter8605** [blackmatrix7/ios_rule_script#83]
[WARNING] [什么值得买]
获取好文列表失败，执行异常：TypeError: null is not an object (evaluating 'articleList.forEach')

提示如下，app版本:iphone 9.8.16

**Comment by blackmatrix7** [comment]
已知问题，目前做修改并且在测试中，确认没有问题后会更新上来。

**Comment by hunter8605** [comment]
> 已知问题，目前已做修改并且在测试中，确认没有问题后会更新上来。

好的，感谢。
