### ISSUE TITLE
loli.net 被拦截导致 SMMS 图床异常

### ISSUE THREAD

**Issue by Xm798** [blackmatrix7/ios_rule_script#831]
规则名称：[Advertising_Domain.list](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising_Domain.list)

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising_Domain.list

异常规则：`.loli.net`

问题描述：SMMS 图床使用该域名，错误拦截导致 SMMS 的图片全部无法显示

调整方案：移除该规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
