### ISSUE TITLE
Global 规则中包含icloud.com.cn

### ISSUE THREAD

**Issue by logxe** [blackmatrix7/ios_rule_script#832]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Global

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list

异常规则：HOST-SUFFIX,icloud.com.cn,Global

问题描述：不知icloud.com.cn加入Global是否有其它考量，会导致gateway.icloud.com.cn及iCloud邮箱(解析均为国内IP)走代理

抓包截图：![image](https://user-images.githubusercontent.com/1756224/210503031-626e1e45-0acb-41aa-9af2-0c59c849fb2e.png)

调整方案：建议加入China中或从Global中移除

**Comment by openviso** [comment]
也我也遇到课这个情况 ，暂时的处理办法时在引用China是使用out=iCloud

**Comment by blackmatrix7** [comment]
这个前几天已移除了，一直没空处理issue。

**Comment by uclort** [comment]
@blackmatrix7 一直用的 release 分支，发现 release 还没有移除，上次更新是去年 12 月了，以后是不是不太推荐 release 分支了。

**Comment by logxe** [comment]
> @blackmatrix7 一直用的 release 分支，发现 release 还没有移除，上次更新是去年 12 月了，以后是不是不太推荐 release 分支了。

可以试试[Proxy](https://github.com/blackmatrix7/ios_rule_script/tree/release/rule/QuantumultX/Proxy)规则，感觉这个范围小一点
