### ISSUE TITLE
1688登录页面IP被划分到Advertising_Domain、AdvertisingLite_Domain

### ISSUE THREAD

**Issue by EchoJotaro** [blackmatrix7/ios_rule_script#836]
规则名称：Advertising_Domain、AdvertisingLite_Domain

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Advertising/Advertising_Domain.list
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/AdvertisingLite/AdvertisingLite_Domain.list

异常规则：`'+.pass.1688.com'`

问题描述：1688登录时会解析到该地址，导致无法正常登录账号。

抓包截图：![b676766527291f60b7e08fbb5dbade7](https://user-images.githubusercontent.com/58978590/212456751-aadfdaee-b411-4866-8bd5-761d819b077e.png)

调整方案：建议对该域名直连。

**Comment by blackmatrix7** [comment]
新年好！这个已经移除一段时间了，一直没空回复，不好意思。

**Comment by EchoJotaro** [comment]
新年好！十分感谢！
