### ISSUE TITLE
希望添加winget的分流规则

### ISSUE THREAD

**Issue by goynhe** [blackmatrix7/ios_rule_script#839]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Global
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list
https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml
异常规则：
cdn.winget.microsoft.com
问题描述：
winget的cdn下载较慢
已使用DoH,非dns污染原因
抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)
使用Windows Package Manager时,需要访问cdn.winget.microsoft.com这个域名,国内直接访问这个cdn速度较慢,建议把这个域名添加到Global中

**Comment by goynhe** [comment]
可以考虑添加一条DOMAIN-SUFFIX, winget.microsoft.com
不是每次使用winget都需要访问这个域名, 检查更新时会用到

**Comment by blackmatrix7** [comment]
单独一条规则，建议手动添加一下，或者使用Microsoft的规则。
