### ISSUE TITLE
滴滴出行task脚本运行卡在第一步

### ISSUE THREAD

**Issue by r0ckmifan** [blackmatrix7/ios_rule_script#84]
[图1](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/28c81e56-2b10-4eb0-8be9-10d83f13f658.png) [图2](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/2f55bba4-8a98-4dee-af50-848200d470b8.png)
除了没获取lid以外，其他Token，ActivityId和ChannelId两个都获取了，使用圈X商店最新版。

**Comment by blackmatrix7** [comment]
出现图二的时候，执行日志了应该有异常信息，麻烦提供给我下。
这几天会有新版的更新。

**Comment by r0ckmifan** [comment]
就是图一所显示的，没有错误，我试了一下，发现关闭圈叉vpn，task再去执行（此时的只有一个绿色的播放按钮）就可以了，不知道什么地方冲突了。

**Comment by blackmatrix7** [comment]
这样的话，你看下是不是有去广告等复写规则把请求拦截了？

**Comment by r0ckmifan** [comment]
我用这也是您的分流规则，然后我试了把分流规则，重写规则全部禁用了也还是不行。

**Comment by blackmatrix7** [comment]
你方便把配置文件脱敏后提供我一份吗？我下载个商店版本测试。

**Comment by r0ckmifan** [comment]
https://share.weiyun.com/zFK9DaI2
我删减了其他的，保留了您的，您试试，分流规则不变都是用您的。

**Comment by blackmatrix7** [comment]
滴滴出行的脚本我试着更新了一下，你看看是否可用

**Comment by r0ckmifan** [comment]
忘记回了，更新后正常了，一直在使用。
