### ISSUE TITLE
Advertising重写规则重复

### ISSUE THREAD

**Issue by goynhe** [blackmatrix7/ios_rule_script#848]
规则名称：
AdvertisingLite和Advertising
规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AdvertisingLite/AdvertisingLite.conf
重复规则：
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ url reject
^https?:\/\/bdsp-x\.jd\.com\/adx\/ url reject
问题描述：
个人认为可以只保留第一条规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已处理，稍后更新。

由于是抓取上游规则自动生成，此类问题无法彻底杜绝，只能尽量减少。
