### ISSUE TITLE
希望加入limbopro仓库的视频站去广告规则

### ISSUE THREAD

**Issue by BaileyZyp** [blackmatrix7/ios_rule_script#85]
分流：https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list
重写：https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.conf

不过是Quanx的规则希望作者可以转换成Surge的，谢谢！

**Comment by blackmatrix7** [comment]
可以加入，不过可能要过几天，目前在对程序进行重构，重构完成后再增加这些新的数据源。

**Comment by blackmatrix7** [comment]
分流规则已加入
复写规则不会加入，几方面原因：

1. 有的复写规则正则写得太过随意，如：
o333o url reject
yb463.app url reject
这类的规则误杀可能会很严重。

2.有的正则进行转义，而有的又不进行转义，如:
https://i.imgur.com/AwTXfrw.gif url reject-img

3.有些把广告链接重定向到自己网站，以增加网站访问量的私货
^https://\b.*wixsite\b.*?feijibei url 302 https://bit.ly/39oJwJE
^https:?/\/.*wine-api.* url 302 https://bit.ly/39oJwJE
https://\b.*\bnaifei\b.*/\?sid=\w{1,6} url 302 https://limbopro.xyz
http.*yabo729.\b.* url 302 https://limbopro.xyz
http.*yabo.\b.* url 302 https://limbopro.xyz

第1点可以通过黑名单排除掉，第二点可以进行一些正则的替换修正，第三点我无法认同此类做法。

**Comment by blackmatrix7** [comment]
分流规则加入了，复写规则没有加入。复写规则里太多私货，还有劫持流量到他自己网站的。
