### ISSUE TITLE
希望可以将Apple ID的规则独立出来

### ISSUE THREAD

**Issue by ArriettyQAQ** [blackmatrix7/ios_rule_script#854]
继上次提交的[需要补充Apple的域名地址 #846](https://github.com/blackmatrix7/ios_rule_script/issues/846)

希望可以将Apple ID的规则独立出来，有时候节点不畅时，将Apple ID的服务直连可能会更好一些。

此时直连Apple ID可以避免线路太慢导致下载App和兑换App等场景时一直转圈加载的问题。

**Comment by blackmatrix7** [comment]
已独立出来，稍后会更新。
