### ISSUE TITLE
什么值得买无法正常签到

### ISSUE THREAD

**Issue by fuckboss** [blackmatrix7/ios_rule_script#856]
脚本名称：什么值得买

APP版本：ios 10.4.20

客户端名称：什么值得买

客户端版本：ios 10.4.20

问题描述：任务脚本正常，提示签到成功，可以看到前面一天的签到天数，且提示签到成功，但并未进行签到

![image](https://user-images.githubusercontent.com/63834315/217590490-682d09a6-9066-41f4-b2b9-30ba7c27f386.png)![image](https://user-images.githubusercontent.com/63834315/217590589-2e2faca6-2f92-489c-8ad2-385eefe3033d.png)
![image](https://user-images.githubusercontent.com/63834315/217590734-1e4ec024-21ab-485a-9c55-96143714a80d.png)

**Comment by fuckboss** [comment]
![image](https://user-images.githubusercontent.com/63834315/217591350-7c67fa64-ae52-4236-b516-52b93525f946.png)

**Comment by blackmatrix7** [comment]
Cookie是从App中获取的吗？

**Comment by fuckboss** [comment]
> Cookie是从App中获取的吗？
> 
> 查看下BoxJS订阅的配置，是否关闭了签到功能。

直接添加的请求任务，并未配置jsbox

**Comment by blackmatrix7** [comment]
脚本目前默认是不开启签到的，需要在BoxJS中打开这个功能。

现在改了一下，应该好了。

**Comment by fuckboss** [comment]
已恢复，谢谢
