### ISSUE TITLE
“哲也同学”模块疑似引用了一个不存在的资源

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#859]
相关模块：
https://github.com/blackmatrix7/ios_rule_script/blob/master/script/zheye/zheye.sgmodule

资源位置：
\# 暂不清楚作用
data="https://git.codecolor.cool/matrix/rule/raw/branch/master/blank/blank_dict.json"
该资源通过直连、不同国家节点代理连接，均无法获取到本地

**Comment by blackmatrix7** [comment]
谢谢反馈，已删除。
