### ISSUE TITLE
ios rule_script/rule/Loon/Proxy/Domain.list乱了套了，baidu都在里面

### ISSUE THREAD

**Issue by Catnipll** [blackmatrix7/ios_rule_script#86]
百度在里面：
![屏幕截图 2020-11-30 182316](https://user-images.githubusercontent.com/64342866/100598225-696f8200-3339-11eb-88ee-6af45aa21fb4.png)
QQ在里面：
![屏幕截图 2020-11-30 182347](https://user-images.githubusercontent.com/64342866/100598242-6d9b9f80-3339-11eb-9568-0c5d5a78038a.png)

问题：
一直用大佬的这个规则集命中的代理，结果直接今天QQ邮箱都进不去，一看规则走的是代理，很纳闷，排查了半天，才想到订阅的规则，爬上来一看这个里面彻底乱了，百度、QQ都在里面，请求大佬修复，感谢大佬的付出，感恩~

**Comment by blackmatrix7** [comment]
感谢及时反馈。之前就有过某个数据源出问题，我这里同步更新后也会问题的担忧，没想到还是出现了。

晚上我先排查下哪个数据源出问题，把它去掉再更新一次。最近在对程序进行重构，重构完成后会加入分流规则间互斥，用于缓解这类情况。

**Comment by Catnipll** [comment]
> 感谢及时反馈。之前就有过某个数据源出问题，我这里同步更新后也会问题的担忧，没想到还是出现了。
> 
> 晚上我先排查下哪个数据源出问题，把它去掉再更新一次。最近在对程序进行重构，重构完成后会加入分流规则间互斥，用于缓解这类情况。

感谢大佬的无私奉献！！！爱您！！！！

**Comment by blackmatrix7** [comment]
> > 感谢及时反馈。之前就有过某个数据源出问题，我这里同步更新后也会问题的担忧，没想到还是出现了。
> > 晚上我先排查下哪个数据源出问题，把它去掉再更新一次。最近在对程序进行重构，重构完成后会加入分流规则间互斥，用于缓解这类情况。
> 
> 感谢大佬的无私奉献！！！爱您！！！！

已经去掉了。不知道哪个数据源出错，后面又修改好了。

**Comment by Catnipll** [comment]
> > > 感谢及时反馈。之前就有过某个数据源出问题，我这里同步更新后也会问题的担忧，没想到还是出现了。
> > > 晚上我先排查下哪个数据源出问题，把它去掉再更新一次。最近在对程序进行重构，重构完成后会加入分流规则间互斥，用于缓解这类情况。
> > 
> > 
> > 感谢大佬的无私奉献！！！爱您！！！！
> 
> 已经去掉了。不知道哪个数据源出错，后面又修改好了。

收到~感恩~大佬您辛苦了~~~~~
