### ISSUE TITLE
AllInOne重写规则中zheye链接404

### ISSUE THREAD

**Issue by y1zhou** [blackmatrix7/ios_rule_script#862]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf

APP版本：

客户端名称：Quantumult X

客户端版本：1.2.0-777

问题描述：script/zheye/zheye.js status code 404

复现方式：

1. 在重写规则中添加 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AllInOne/AllInOne.conf 
2. 更新所有远程配置

已使用空白配置文件验证：是

**Comment by blackmatrix7** [comment]
状态早上更换的链接，等今天凌晨重写生成规则即可。
