### ISSUE TITLE
clash规则里的规则链接-各类分支直接复制Domain的连接报错

### ISSUE THREAD

**Issue by fhdjasklf** [blackmatrix7/ios_rule_script#865]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：CLash下的各类有Domain的规则

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.txt

异常规则：

问题描述：如果直接在README页面复制Domain的话是.txt结尾的格式，在clash内启动会报错

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。).txt看别的issue是给stash用的，但是这个规则写的是for clash，希望可以在说明页各个分支更改一下后缀或者在说明页加上一下说明嘛，辛苦啦

**Comment by blackmatrix7** [comment]
原先是有独立的Stash规则，但是重复的内容过多，后面做了合并。

说明会进行修改，只目前优先级不是很高，近期不会变动。
