### ISSUE TITLE
Surge for macOS下，Apple系请求的分流几乎全部失效

### ISSUE THREAD

**Issue by Nyim1s** [blackmatrix7/ios_rule_script#868]
规则名称：
Apple

规则链接：
`https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list`

异常规则：
全部

问题描述：
配置文件中，apple.list在global.list和global_domain.list之前，但是从dashboard上看到Apple系请求依然被匹配到global.list和global_domain.list

**Comment by blackmatrix7** [comment]
请仔细阅读README，规则需要搭配DOMAIN-SET使用。

https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Apple/Apple_Domain.list
