### ISSUE TITLE
去广告规则导致 PayPal 网页版显示异常

### ISSUE THREAD

**Issue by mwhds97** [blackmatrix7/ios_rule_script#869]
规则名称：Advertising

异常规则：
paypalobjects.com
www.paypalobjects.com

问题描述：
如图所示
![image](https://user-images.githubusercontent.com/32876945/219352028-4df829ea-fe4b-4327-b872-0140e31c15a4.png)

调整方案：加入过滤器

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入过滤器，等待明日凌晨的自动更新。
