### ISSUE TITLE
chinaips的ip少了很多

### ISSUE THREAD

**Issue by linger040831** [blackmatrix7/ios_rule_script#871]
规则名称：ChinaIPs/ChinaMax

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/ChinaIPs
                  https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/ChinaMax

异常规则：ChinaIPs/ChinaMax

问题描述：从1.x.x.x开始的规则明显少于https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt 

抓包截图：
![image](https://user-images.githubusercontent.com/84896599/219598782-181a8b3c-cfc8-4d48-a0ab-cac19d47111f.png)
![image](https://user-images.githubusercontent.com/84896599/219598792-507dccc5-e9c0-44ee-8971-bf0830e17b21.png)

调整方案：规则与https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt 同步

**Comment by blackmatrix7** [comment]
谢谢反馈。

这个问题分两部分来看：

一部分是之前增加了IP-ASN和IP-CIDR类型规则的合并，而Clash没有IP-ASN规则，所以会缺失合并后被移除的规则，这部分已经将Clash的规则独立出来，以解决这个问题。

另外一个部分是IP-CIDR类型会将有包含关系的规则进行合并，以及合并一些连续的IP-CIDR地址为新的IP-CIDR地址。

这部分从日志上看，合并去除了约48万条的规则，这也是造成数据差距巨大的原因。

目前没有收到其他反馈说ChinaIPs的规则无法命中，如果你有无法命中的确切IP地址，而在Hackl0us中是可以匹配的，麻烦提供给我一下，便于排查合并之后是否存在问题。

再次感谢。

**Comment by linger040831** [comment]
昨天steam下载游戏时会有1.183.x.x 和1.182.x.x的ip段
<img width="480" alt="image" src="https://user-images.githubusercontent.com/84896599/219871972-10d3634e-d4c2-4b1c-9d0a-e93c6c2ceba2.png">
查到的是内蒙古的ip
忘记截图了，所以没法看具体ip

**Comment by blackmatrix7** [comment]
谢谢反馈，粗略看了一下，合并后规则的确不存在了，具体原因需要等这段时间忙完后再排查。

临时解决方案为关闭这几个IP类型规则的IP-CIDR合并功能，今日凌晨更新应该就会生效。

可能会导致规则数量暴增。

**Comment by blackmatrix7** [comment]
已经禁用IP-CIDR合并，最近比较忙，Bug后续空了再排查。
