### ISSUE TITLE
完善Hulu规则

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#873]
规则名称：Hulu

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/Hulu/Hulu.list

异常规则：host, live-mediashield-ava-hulustream-com.akamaized.net, Hulu

调整方案：添加规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已经补充进去。

稍后会进行更新。
