### ISSUE TITLE
iOS百度地图、iOS Edge、iOS nicegram规则补充以及调整

### ISSUE THREAD

**Issue by xxb5656** [blackmatrix7/ios_rule_script#874]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Advertising

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Shadowrocket/Advertising

异常规则：DOMAIN-SUFFIX,map-mobile-opnimg.cdn.bcebos.com,REJECT

问题描述：该域名为iOS百度地图-我的-更多-中的各项功能icon，REJECT会导致图标不能显示，影响观感。
![IMG](https://user-images.githubusercontent.com/47763861/219823142-bbf958a4-6436-48f7-bf6b-cf0b78e3d522.PNG)

抓包截图：(相关抓包工具的截图。)

调整方案：DOMAIN-SUFFIX,map-mobile-opnimg.cdn.bcebos.com,DIRECT

--------------------------------------------------------------------------------------------------------------

规则名称：Microsoft

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Shadowrocket/Microsoft/Microsoft.list

异常规则：microsoftapp.net

问题描述：该域名为iOS edge最新版的新增分流域名，未收录

抓包截图：(相关抓包工具的截图。)

调整方案：DOMAIN-SUFFIX,microsoftapp.net,PROXY

--------------------------------------------------------------------------------------------------------------

规则名称：Telegram

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Shadowrocket/Telegram

异常规则：mbrx.app

问题描述：该域名为iOS nicegram的域名，未收录。不少人上tg的都是用nicegram，建议收录到Telegram中

抓包截图：(相关抓包工具的截图。)

调整方案：DOMAIN-SUFFIX,mbrx.app,PROXY

**Comment by blackmatrix7** [comment]
十分感谢，很详细的反馈，已经加入到附加规则和过滤器中，稍后会进行更新。
