### ISSUE TITLE
Akamai的ASN被包含在ChinaIPs,ChinaMax中

### ISSUE THREAD

**Issue by Xm798** [blackmatrix7/ios_rule_script#876]
规则名称：ChinaMAX

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/ChinaMax/ChinaMax.list

异常规则：IP-ASN,20940,no-resolve

问题描述：Lark 连接的部分位于香港的 CDN 域名被划分在 ChinaMax 中，定位到规则 `IP-ASN,20940`，但是经查询，这是 Akamai 阿卡迈的 ASN，没有足够的证据表明它是大陆 IP，且直连访问会导致 Lark 频繁连接缓慢或失败。

抓包截图：

<img width="1259" alt="CleanShot 2023-02-20 at 21 33 20@2x" src="https://user-images.githubusercontent.com/48074861/220122526-df2c62b5-4bcc-44e9-ba97-8e5b6fef0d3c.png">

<img width="327" alt="CleanShot 2023-02-20 at 21 33 00@2x" src="https://user-images.githubusercontent.com/48074861/220122477-bd75cb50-1a68-40a4-8db5-a9793d486c59.png">

调整方案：移除

**Comment by Xm798** [comment]
进一步定位发现，ChinaASN， ChinaIPs 等规则中也存在此条规则。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
