### ISSUE TITLE
Paypal 被包含在 ChinaMax 中

### ISSUE THREAD

**Issue by Xm798** [blackmatrix7/ios_rule_script#877]
规则名称：ChinaMax

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ChinaMax/ChinaMax.list

异常规则：

HOST-SUFFIX,paypal-mktg.com,ChinaMax
HOST-SUFFIX,paypal.com,ChinaMax
HOST-SUFFIX,paypal.me,ChinaMax
HOST-SUFFIX,paypalobjects.com,ChinaMax

问题描述：

PayPal 非国内网站，会导致访问卡顿。

调整方案：

移除

**Comment by Xm798** [comment]
补充：问题存在于 QuanX 中，但是 Surge 的对应规则不存在该问题。其余软件未排查。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除。
