### ISSUE TITLE
Apple list问题

### ISSUE THREAD

**Issue by JOJOforshaun** [blackmatrix7/ios_rule_script#878]
![11B81A3B-F111-4443-8D34-A7677F38E9BE](https://user-images.githubusercontent.com/63553362/220373206-82fea52d-5cde-4900-989e-2339b45856f3.png)

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list

domain和suffix去哪了？

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Surge/Apple 

请仔细阅读README
