### ISSUE TITLE
「Direct」增加两条规则

### ISSUE THREAD

**Issue by LimeAroma** [blackmatrix7/ios_rule_script#879]
规则名称：Direct

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Loon/Direct/Direct.list

问题描述：去广告规则中包含meiqia.com域名会导致app「日淘任意门」中的机器人客服页面收发信息异常。

经测试，增加以下两条直连规则后恢复正常：
DOMAIN,eco-push-api-client.meiqia.com
DOMAIN,new-api.meiqia.com

调整方案：增加以下规则
DOMAIN,eco-push-api-client.meiqia.com
DOMAIN,new-api.meiqia.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加。
