### ISSUE TITLE
有否考虑新增一个搜索引擎的集合规则？

### ISSUE THREAD

**Issue by tomektse** [blackmatrix7/ios_rule_script#883]
如题，新版bing整合了chatgpt吸引了很多人，既然有bing的分流，又有Google的，可以集和其他诸如yandex、naver等等做成一个search类的大合集？

**Comment by Bitcion** [comment]
bing规则太难整了，网页版还好办
移动端又不一样

**Comment by blackmatrix7** [comment]
最近事情太多，暂时不考虑手动新增资源。
