### ISSUE TITLE
精简版去广告规则拦截ylog.huya.com导致打开直播间加载缓慢

### ISSUE THREAD

**Issue by moondie** [blackmatrix7/ios_rule_script#884]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：AdvertisingLite

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml

异常规则：ylog.huya.com

问题描述：虎牙打开直播间时，视频流加载很久，看clash日志发现一连串ylog.huya.com的REJECT记录，手动把‘ylog.huya.com，DIRECT’放到rules最前面之后就没问问题了。

调整方案：删去拦截ylog.huya.com的条目。

**Comment by blackmatrix7** [comment]
已移除，已更新。
