### ISSUE TITLE
小火箭版苹果服务不齐全

### ISSUE THREAD

**Issue by iigood** [blackmatrix7/ios_rule_script#886]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Apple.list

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple.list

异常规则：all

问题描述：小火箭版本的苹果服务貌似收集的不齐全，最基本的apple.com都没有，我用rule-set导入后选直连，还是走了兜底。大部分的请求

抓包截图：(相关抓包工具的截图。)

调整方案：目前的解决方案是用圈X的规则，但作为强迫症我还是希望可以出一个小火箭专用的Apple.list
![4C450540-9820-4C31-B65E-1122AAAC92B5](https://user-images.githubusercontent.com/124248142/222398639-194486aa-6487-4f65-be44-d1ebfde09740.png)

**Comment by blackmatrix7** [comment]
配置建议

Apple.list、Apple_Domain.list 共同使用。
Apple_Resolve.list、Apple_Domain.list 共同使用。
