### ISSUE TITLE
pikpak规则无法命中，缺少类似HOST-SUFFIX,mypikpak.com,PikPak这样的

### ISSUE THREAD

**Issue by zakizou** [blackmatrix7/ios_rule_script#887]
pikpak规则无法命中，手动写入HOST-SUFFIX,mypikpak.com,xxx,命中规则

**Comment by blackmatrix7** [comment]
存在HOST-KEYWORD,mypikpak,PikPak，HOST-SUFFIX,mypikpak.com会被合并掉。

做了一下调整，晚些时候更新。

**Comment by xpn282** [comment]
pikpakdrive.com

这个也是属于PikPak的域名吧，我看网络记录有这个出现
