### ISSUE TITLE
手机网页版的百度首页图片加载异常

### ISSUE THREAD

**Issue by harry0071** [blackmatrix7/ios_rule_script#889]
规则名称：去广告精简版

规则链接：https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/AdGuard/AdvertisingLite/AdvertisingLite.txt

异常规则：||t10.baidu.com^ 、||t11.baidu.com^   、||t12.baidu.com^

问题描述：上面3条异常规则会导致 http://m.baidu.com 的图片加载异常

调整方案：希望能够正常显示http://m.baidu.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入过滤器，晚些时候更新。
