### ISSUE TITLE
微信通话不可用

### ISSUE THREAD

**Issue by jeffok** [blackmatrix7/ios_rule_script#894]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
WeChat.list

规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list

异常规则：

问题描述：
在使用微信通话时不能正常进行，微信其它的功能正常

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by myd986** [comment]
不是作者，但你是不是没开`fallback_udp_policy=direct`？
如果使用的节点不支持UDP，又没有让UDP回落到直连可能会出现这种情况。

**Comment by blackmatrix7** [comment]
规则只是IP和地址的合集，并不会影响APP的功能，通常是对应的策略或节点问题导致。
