### ISSUE TITLE
quanx去广告重写m.ctrip.com连接阻断

### ISSUE THREAD

**Issue by anon1984encn** [blackmatrix7/ios_rule_script#895]
规则名称：quanx/rewrite/advertisinglite.conf

规则链接：

异常规则：携程app m.ctrip.com

问题描述：连接阻断

抓包截图：(相关抓包工具的截图。)
![DF2C979F-913F-45E3-A5A5-07DEE45F97E5](https://user-images.githubusercontent.com/100828799/224455478-617a36e0-55ea-4d7a-b331-366cb68a0afd.jpeg)

调整方案：可以麻烦看一下这个规则是否有问题吗？谢谢

**Comment by blackmatrix7** [comment]
没有找到这条规则，可能上游已移除了。
