### ISSUE TITLE
Global.list中ddns相关域名

### ISSUE THREAD

**Issue by myd986** [blackmatrix7/ios_rule_script#896]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Quantumule X/Global.list
规则链接：
[Global.list](https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/QuantumultX/Global/Global.list)
异常规则：
ddns.net等
问题描述：
ddns相关域名很多用于家庭自建服务器等无固定IP的情况，归类为Global会导致访问延迟急剧增大，是不合理的，应该交给直连。
抓包截图：(相关抓包工具的截图。)
<img width="789" alt="image" src="https://user-images.githubusercontent.com/49913958/225205010-088b3cf3-cd1e-4184-baa4-e76d65a0b285.png">

调整方案：(你希望规则做哪些调整，及其原因。)
排除Global中DDNS相关域名，原因上文以表。

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，晚些时候更新。
