### ISSUE TITLE
关于目前火热的各类AI的分流规则添加

### ISSUE THREAD

**Issue by Space-Loon** [blackmatrix7/ios_rule_script#897]
当下chatgpt、Newbing 等AI很火热，希望能够增加这类规则的分流。

**Comment by easonnnone** [comment]
我也希望作者能够添加进来。

**Comment by blackmatrix7** [comment]
最近比较忙，暂时没有时间去整理这些规则。

**Comment by bricle** [comment]
DOMAIN-SUFFIX,openai.com
DOMAIN-SUFFIX,chat.openai.com
DOMAIN-SUFFIX,challenges.cloudflare.com
DOMAIN-SUFFIX,auth0.openai.com
DOMAIN-SUFFIX,platform.openai.com
# Add ai.com
DOMAIN-SUFFIX,ai.com
