### ISSUE TITLE
Akamaized.net不应在ChinaMax规则中

### ISSUE THREAD

**Issue by wydy** [blackmatrix7/ios_rule_script#899]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：ChinaMax

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/*/ChinaMax/ChinaMax_Domain.list

异常规则：.akamaized.net

问题描述：不是所有akamaized.net域名都可以直连，此前已经有人提到过这个问题，只是似乎时间久远导致再次出现
先前的Issue：https://github.com/blackmatrix7/ios_rule_script/issues/134#issue-776159525

调整方案：移除本条规则

**Comment by blackmatrix7** [comment]
谢谢反馈，又重新检查了一遍，现在确认已过滤掉，稍后更新。
