### ISSUE TITLE
您好，使用surge的smzdm签到脚本，在捕获手机app的登陆cookie时，提示“获取账号密码时请求数据不合法”

### ISSUE THREAD

**Issue by MasterCh1ef** [blackmatrix7/ios_rule_script#9]
如题

**Comment by blackmatrix7** [comment]
之前我测试时候，什么值得买的新版，存在请求头声明不规范的问题。它声明请求体进行了gzip压缩，实际并未进行gzip压缩。这种情况下，Surge在解压请求体时会失败，导致无法获取到账号密码。

你看下日志，是否是这个问题导致。如果是，有几个解决办法：

1. 降级到 什么值得买 iPhone 9.6.17，用这个版本获取一次请求体后再升级回去，只要不修改密码就不影响使用。
2.手动执行脚本，写入账号密码数据
$persistentStore.write("你的账号", "smzdm_account");

**Comment by blackmatrix7** [comment]
> 如题

之前我测试时候，什么值得买的新版，存在请求头声明不规范的问题。它声明请求体进行了gzip压缩，实际并未进行gzip压缩。这种情况下，Surge在解压请求体时会失败，导致无法获取到账号密码。

你看下日志，是否是这个问题导致。如果是，有几个解决办法：

降级到 什么值得买 iPhone 9.6.17，用这个版本获取一次请求体后再升级回去，只要不修改密码就不影响使用。
2.手动执行脚本，写入账号密码数据
$persistentStore.write("你的账号", "smzdm_account");
$persistentStore.write("你的密码", "smzdm_password");

**Comment by MasterCh1ef** [comment]
好的，谢谢😄
