### ISSUE TITLE
surge上模块更新失败

### ISSUE THREAD

**Issue by fiiir** [blackmatrix7/ios_rule_script#90]
Advertising MITM
Global MITM
Whitelist MITM
报错为“配置文件必须以[Section]形式开头”

**Comment by blackmatrix7** [comment]
![image](https://user-images.githubusercontent.com/27717518/101107810-184be080-360e-11eb-993a-cc59ac2cc5f8.png)

试了下可以，因为我把地址改了。你需要重新删除模块再安装。
