### ISSUE TITLE
广告过滤误杀，导致网站图片显示异常

### ISSUE THREAD

**Issue by harry0071** [blackmatrix7/ios_rule_script#901]
规则名称：去广告(/rule/AdGuard/Advertising)

规则链接：https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/AdGuard/Advertising/Advertising.txt

异常规则：||baikebcs.bdimg.com^  、||img2.autoimg.cn^ 

问题描述：①||baikebcs.bdimg.com^ 这条规则导致手机网页版的百度百科图片显示异常，具体请看→ https://github.com/privacy-protection-tools/anti-AD/issues/770

②||img2.autoimg.cn^ 这条规则导致 http://hssp.tv 这个网站的图片显示异常

调整方案：希望能够正常显示图片

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，晚些时候更新。
