### ISSUE TITLE
Discovery规则补充

### ISSUE THREAD

**Issue by tkzc11** [blackmatrix7/ios_rule_script#903]
规则名称：DiscoveryPlus

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/DiscoveryPlus/DiscoveryPlus.list

规则：host, discovery-us.conax.cloud, Discovery+
host, dplus-northamerica.media-edge.prod-vod.h264.io, Discovery+

调整方案：补充规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已补充，晚些时候更新。
