### ISSUE TITLE
同时使用Google和YouTube的策略会导致YouTube规则不起效

### ISSUE THREAD

**Issue by joawen** [blackmatrix7/ios_rule_script#905]
规则名称：YouTube.list，Google.list

规则链接：
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list

异常规则：
DOMAIN-KEYWORD,google

问题描述：
YouTube规则主要用于选择观看地区，但是由于googlevideo.com存在Google的规则集中，如Google选择节点地区不同于YouTube，会导致YouTube的视频因地区问题无法播放。

抓包截图：(相关抓包工具的截图。)
<img width="1277" alt="截屏2023-03-29 11 04 03" src="https://user-images.githubusercontent.com/52378454/228416033-cbfd7cbe-e7d6-4e06-8dab-4b9cbf1fe1ad.png">

调整方案：(你希望规则做哪些调整，及其原因。)

**Comment by blackmatrix7** [comment]
尝试将YouTube规则置于Google规则之前试试
