### ISSUE TITLE
追加trackerslist

### ISSUE THREAD

**Issue by radiation-chan** [blackmatrix7/ios_rule_script#906]
规则名称：PrivateTracker

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/PrivateTracker/PrivateTracker.yaml

调整方案：希望能追加 https://trackerslist.com/all.txt 和 https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt 两个trackerslist。

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后更新。
