### ISSUE TITLE
HttpDNS规则补充

### ISSUE THREAD

**Issue by svngxr** [blackmatrix7/ios_rule_script#908]
部分App使用了内置的HttpDNS进行域名查询,会绕过本地 DNS,导致用户域名分流与过滤规则失效
目前没有clash和Quantumult X
可以补充HttpDNS规则,或者合并到Advertising规则下
非常感谢
规则
https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/sgmodule/HTTPDNS.Block.sgmodule
来自于
https://github.com/VirgilClyne/GetSomeFries/wiki/🚫-HTTPDNS#使用说明

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后更新。
