### ISSUE TITLE
gstatic.com依然在ChinaMax里

### ISSUE THREAD

**Issue by goodffd** [blackmatrix7/ios_rule_script#909]
[ #537](https://github.com/blackmatrix7/ios_rule_script/issues/537)反馈已移除，但目前最新的列表里依然存在gstatic
chinamax规则的来源之一：https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt 这个里面就存在gstatic问题

**Comment by blackmatrix7** [comment]
谢谢反馈，忘了为ChinaMax配置过滤器，已移除，稍后更新。
