### ISSUE TITLE
为什么quanx使用会出现刚进去有效过一会失效的情况

### ISSUE THREAD

**Issue by suminor** [blackmatrix7/ios_rule_script#91]

**Comment by blackmatrix7** [comment]
你的描述太简单了

**Comment by suminor** [comment]
> 你的描述太简单了

就是只有杀死后台以后进到b站去广告才有效 个人中心也很简洁 切换到别的app然后再切回来 就失效了 个人中心就全部回来了

**Comment by blackmatrix7** [comment]
你看下是不是有其他的复写会导致VPN重启之类的。

贴个日志上来看看。

**Comment by suminor** [comment]
2020/12/04 18:12:26:447  <warning>    [QTXDomainResolver] server
119.28.28.28 replied with 0 AAAA record for s3.hdslb.com, waiting for other
results.
2020/12/04 18:12:26:458  <warning>    [QTXDomainResolver] server 223.5.5.5
replied with 0 AAAA record for s3.hdslb.com, waiting for other results.
2020/12/04 18:12:26:490  <warning>    [QTXDomainResolver] server
117.50.10.10 replied with 0 AAAA record for hm.baidu.com, waiting for other
results.
2020/12/04 18:12:26:501  <info>       [QTXTCPPath] New connection-11941(
s1.hdslb.com:443) (active 30)
2020/12/04 18:12:26:507  <warning>    [QTXDomainResolver] server
114.114.114.114 replied with 0 AAAA record for hm.baidu.com, waiting for
other results.
2020/12/04 18:12:26:511  <warning>    [QTXDomainResolver] server
114.114.114.114 replied with 0 AAAA record for s3.hdslb.com, waiting for
other results.
2020/12/04 18:12:26:646  <warning>    [QTXDomainResolver] server
117.50.10.10 replied with 0 AAAA record for s3.hdslb.com, waiting for other
results.
2020/12/04 18:12:26:841  <info>       [QTXTCPPath] New connection-11942(
www.recaptcha.net:443) (active 31)
2020/12/04 18:12:26:979  <info>       [QTXTCPPath] New connection-11943(
api.bilibili.com:443) (active 32)
2020/12/04 18:12:27:059  <info>       [QTXTCPPath] New connection-11944(
api.bilibili.com:443) (active 33)
2020/12/04 18:12:27:481  <warning>    [QTXDomainResolver] server
221.179.38.7 replied with 0 AAAA record for www.recaptcha.net, waiting for
other results.
2020/12/04 18:12:27:496  <warning>    [QTXDomainResolver] server
2409:8057:2000::8 replied with 0 AAAA record for www.recaptcha.net, waiting
for other results.
2020/12/04 18:12:27:497  <warning>    [QTXDomainResolver] server
119.29.29.29 replied with 0 AAAA record for www.recaptcha.net, waiting for
other results.
2020/12/04 18:12:27:497  <warning>    [QTXDomainResolver] server
2409:8057:2000:4::8 replied with 0 AAAA record for www.recaptcha.net,
waiting for other results.
2020/12/04 18:12:27:497  <warning>    [QTXDomainResolver] server 223.5.5.5
replied with 0 AAAA record for www.recaptcha.net, waiting for other results.
2020/12/04 18:12:27:498  <warning>    [QTXDomainResolver] server
119.28.28.28 replied with 0 AAAA record for www.recaptcha.net, waiting for
other results.
2020/12/04 18:12:27:498  <warning>    [QTXDomainResolver] server
117.50.10.10 replied with 0 AAAA record for www.recaptcha.net, waiting for
other results.
2020/12/04 18:12:27:519  <warning>    [QTXDomainResolver] server
114.114.114.114 replied with 0 AAAA record for www.recaptcha.net, waiting
for other results.
2020/12/04 18:12:29:040  <info>       [QTXTCPPath] New connection-11945(
api.bilibili.com:443) (active 33)
2020/12/04 18:12:29:058  <info>       [QTXTCPPath] New connection-11946(
data.bilibili.com:443) (active 34)
2020/12/04 18:12:29:708  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:31:435  <info>       [QTXTCPPath] New connection-11947(
s3.hdslb.com:443) (active 22)
2020/12/04 18:12:33:515  <info>       [QTXTCPPath] New connection-11948(
data.bilibili.com:443) (active 20)
2020/12/04 18:12:33:775  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:35:989  <info>       [QTXTCPPath] New connection-11949(
api.bilibili.com:443) (active 20)
2020/12/04 18:12:37:094  <info>       [QTXTCPPath] New connection-11950(
data.bilibili.com:443) (active 21)
2020/12/04 18:12:37:781  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:40:881  <info>       [QTXTCPPath] New connection-11951(
data.bilibili.com:443) (active 20)
2020/12/04 18:12:41:781  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:43:165  <info>       [QTXTCPPath] New connection-11952(
catdot.dianping.com:443) (active 20)
2020/12/04 18:12:43:223  <warning>    [QTXDomainResolver] server
2409:8057:2000::8 replied with 0 AAAA record for catdot.dianping.com,
waiting for other results.
2020/12/04 18:12:43:227  <warning>    [QTXDomainResolver] server
2409:8057:2000:4::8 replied with 0 AAAA record for catdot.dianping.com,
waiting for other results.
2020/12/04 18:12:43:227  <warning>    [QTXDomainResolver] server
221.179.38.7 replied with 0 AAAA record for catdot.dianping.com, waiting
for other results.
2020/12/04 18:12:43:257  <warning>    [QTXDomainResolver] server
119.28.28.28 replied with 0 AAAA record for catdot.dianping.com, waiting
for other results.
2020/12/04 18:12:43:261  <warning>    [QTXDomainResolver] server 223.5.5.5
replied with 0 AAAA record for catdot.dianping.com, waiting for other
results.
2020/12/04 18:12:43:313  <warning>    [QTXDomainResolver] server
119.29.29.29 replied with 0 AAAA record for catdot.dianping.com, waiting
for other results.
2020/12/04 18:12:43:314  <warning>    [QTXDomainResolver] server
114.114.114.114 replied with 0 AAAA record for catdot.dianping.com, waiting
for other results.
2020/12/04 18:12:43:315  <warning>    [QTXDomainResolver] server
117.50.10.10 replied with 0 AAAA record for catdot.dianping.com, waiting
for other results.
2020/12/04 18:12:44:499  <info>       [QTXTCPPath] New connection-11953(
data.bilibili.com:443) (active 21)
2020/12/04 18:12:45:776  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:48:097  <info>       [QTXTCPPath] New connection-11954(
data.bilibili.com:443) (active 20)
2020/12/04 18:12:49:771  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:51:503  <info>       [QTXTCPPath] New connection-11955(
data.bilibili.com:443) (active 20)
2020/12/04 18:12:52:447  <info>       [QTXTCPPath] New connection-11956(
api.bilibili.com:443) (active 21)
2020/12/04 18:12:52:753  <info>       [QTXTCPPath] New connection-11957(
api.bilibili.com:443) (active 22)
2020/12/04 18:12:53:788  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:55:026  <info>       [QTXTCPPath] New connection-11958(
data.bilibili.com:443) (active 22)
2020/12/04 18:12:56:946  <info>       [QTXTCPPath] New connection-11959(
s1.hdslb.com:443) (active 20)
2020/12/04 18:12:57:778  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:12:58:683  <info>       [QTXTCPPath] New connection-11960(
data.bilibili.com:443) (active 19)
2020/12/04 18:13:01:769  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:05:774  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:09:783  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:13:786  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:17:788  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:21:779  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:25:787  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.
2020/12/04 18:13:29:779  <warning>    [QTXPacketTunnelProvider] Memory
pressure condition has changed to level 4.


blackmatrix7 <notifications@github.com>于2020年12月4日 周五18:06写道：

**Comment by blackmatrix7** [comment]
你要把出问题时候日志贴上来，不是没有问题时候的日志。

**Comment by blackmatrix7** [comment]
你建一分空白文件，只用B站去广告的复写试试吧。

**Comment by blackmatrix7** [comment]
如果没有进一步反馈，我就先关闭了。

**Comment by suminor** [comment]
我使用了空白的配置测试了 也是一样 你可以自己试试 打开b站app 看一会视频 再返回各人中心 然后个人中心就还原了

blackmatrix7 <notifications@github.com>于2020年12月4日 周五23:56写道：

**Comment by blackmatrix7** [comment]
问题已复现，暂时无法修复。调试脚本执行情况，发现在脚本已经顺利执行且修改响应体，但是QuanX似乎没有把修改后的响应体传给B站App，所以暂时无解。
