### ISSUE TITLE
请求对Nvidia规则优化

### ISSUE THREAD

**Issue by svngxr** [blackmatrix7/ios_rule_script#911]
已使用Global和China规则,Final为代理
希望Global规则里为developer.download.nvidia.com添加代理(或者是download.nvidia.com)
现有规则会使用China规则里的nvidia.com导致developer.download.nvidia.com直连
使得下载链接在nvidia.com.cn(代理)和nvidia.com(直连)之间反复跳转导致下载无法进行
<img width="444" alt="1 (1)" src="https://user-images.githubusercontent.com/125230647/230595191-e97eee47-506f-4c5a-a28c-63c6bbd8ed79.png">

<img width="447" alt="1 (2)" src="https://user-images.githubusercontent.com/125230647/230595201-56f784d3-9f80-44b3-8386-cdea0b57ab7e.png">
感谢修复

**Comment by blackmatrix7** [comment]
谢谢反馈，已处理。
