### ISSUE TITLE
Advertising规则会导致淘宝部分正常商品页面无法打开

### ISSUE THREAD

**Issue by freeme2019** [blackmatrix7/ios_rule_script#913]
规则名称：Advertising

规则链接：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Advertising

异常规则：click.tz.simba.taobao.com

问题描述：浏览网页版淘宝首页时，点击部分商品链接显示无法访问，例如
http://click.mz.simba.taobao.com/necpm?spm=a21bo.jianhua.201876.5&eadt=149&p=&s=673271209&k=2042&e=T4zwT5fE6uHedKumL82gkhshM8myGjAQP8feSmnN6WmGJMjave%2FTQ5pc92zaMG0JuIBvQJ2SMc2U%2FLR8wbciHlt%2Fb%2FWJCCRiI2Z00C9OdgBqPLx1AoZNmOSaBjkNrk25KTmhck5vlFrGYudIJtDa9Oubu7IrWe5336%2F1b95PlMuC8WiuYNa64s3R4rhpI7kfkYtU3zm4HZdKuioDpde1tJGaVQNQDGjQh9D0QsT6hCmvLOxyRZooKazll%2B3pglN6HnQM0HujsJwSUy3AQsl2Ux1YFRPT46RNO1ZSWzvaH2qlygYZ3PPLrxl%2FT6Xiewb9bH4gMX4dCs8XHGGTp4RhwQmxS74NnZsGDFLayhpOxF3IR7%2BRduKux6bNhw%2BoC2g9QdcvTecevC4bmFSRc1O3kamlAtpDjjFsxn0GG6%2BcdlKPBsaFk8kocGEsuPXycvqM3NHqzDzKW38%2F83%2FfZUO8lkX9%2FT3OX5PO%2F7nEZcDbLRc3u1Z2JAdML1lwoRLCmra7uEqqFgxkdafH4U0dDOTY084PKZa7FaXLk8xLuyhVjydNrJVDfUpQhElRg8RiindoT%2Bsp0p74aYGjKvU43g48GPNTrMVp%2FZ4kvv1Dj2Y2cwFviiKHN2M1DzseSHffMbOSToUmO08Vbscy5%2Bfd7EbWF4wNI3AI1A7%2B6fcfv5ChZXGN9eBzXJC%2BkopxoHiKM03G9Uf2Oiz1uFArGaLRkleP1XT1BX2ExJfpedhz8ZF9hTmNMyunm%2F%2FZGzIcb%2FgzXu5VIrITZ98YA4finnLpuPLsv1KWsZAubYqjWE4HfWV2LI%2BywkW62aLuBF8osO6UX26YbkfJmpf7AqBr42qseGX3%2BPHQG5sR34O9gTcAX34LE%2BZyKs5kKvSmQ3MkjmLc90eMx%2Fp%2BEPCt4oLokVtkkqCneEjKtt6EmvBWAhbzp11Yjx7tQBd2883SEWSBrHQrLwnxQhmGwg%2BCBIgwo9vkC%2BStoDiREtdpcMk6AEzwWDy3sHT7iyvT%2BKOnYBnqKScmmKLnT9nMgrFeNuk%2B0x8R7ImFy9qccnw6a%2BZXMb3KYrqedB6y12CYTkhnUswGZIOBXPDl%2FRjbDbgFm0nHBnY%2BsY4O3HLeCcUppA5H%2BEI1FioRZXS5CpBq40pg37j%2F5P4OdN%2BgokrcT3rzyXK8z3w636r3N2svPTtisylkEKM6IIZQfKto8UZb%2FKbd0ZVn9qfsOU8d3QtJsicTww%2FvAkTbAhhlx0H9vkD%2FucxS9L2llWDy1jvLazQxkZSd5i6RHIrhovqOlWf2p%2Bw5Tx1hRNP%2Fs%2B2HqQyQridzc%2FFNYsVySVFt9bSFErMrRk4U3CprougVYdSjDLDFGIqftSy9SSTLqF2Unat88Feybr4MZpl4PmlJPVdCvyq1hZK3u5%2FjnrouB4JzrTkn8kY0XClOtdk5wB1mmxtEzlgH3EjWo%2F1Ww%2BnCZN56vNj5itHKpyB25bYOlV4BDZCGngESGnh5JhUSiwil5fnhlcTN9ycJ%2FGxzC5cf3ycJ2Wr9ys5hsx05UP%2FFvw5vEk4OGpW%2Fp41hzWdsZyImCsthT52F8J%2BEaBA5Px%2FrZ%2BCQt7c239HG3a7KlNIjeUHzkC1S8jy9z%2FH3QG1Zhw2zfYEveLMyT0DArKpNnDZJivN1cH4hDQqSPYWzGGRGEfy4Df3ArSUdti2HyhdncIOt4akcHi6xbGYrQg9CDzj1Tzfcut%2BWYDicUQz4h8vstARGrTkn8kY0XCmKOnhGbRoc0qFPk6DNZ%2BnNV%2BClfCsm7ZaggCQJ7YVAVndJbmjyKp%2BYjxu0%2F5mQfZObi6oMoG59ppe1RozutRzIYt10%2F7qZYR2vTyBKsaLY1bRGriZHc3irM2WTPQVwRJAKOyDT3ksIMFqe450MWPvpQb%2FhwdqIGnnB4tRNfJDZP2hjkAFIk7CHJcxk7D4uOmvKNAiAiNKMpFSBsITzkCPG%2FZ2MxVBDdeYga5TRQ4PfkeDMbDTAVowwd5N4qk%2BaA0zlACpSFqQ1qVs6ab7kSiA%2BSQgg4wzGysEJBhFYGXHkvw%3D%3D&scm=1007.40986.275655.0&pvid=85cc639b-6325-4716-9b8d-484387730f05&item_type=ad&xxc=ad_ct

抓包截图：(相关抓包工具的截图。)

调整方案：Advertising 规则包含了click.mz.simba.taobao.com会导致这个问题

**Comment by blackmatrix7** [comment]
谢谢反馈，已处理。

**Comment by Accademia** [comment]
> 谢谢反馈，已处理。

click.simba.taobao.com

也是与本帖同样的问题
