### ISSUE TITLE
Wechat 规则会导致淘宝内支付宝收银台无法弹出

### ISSUE THREAD

**Issue by whitezong** [blackmatrix7/ios_rule_script#915]
wechat分组内有一条是：
DOMAIN-KEYWORD,203.209.245.
若微信代理到国外会导致淘宝内支付宝收银台无法弹出，淘宝点击提交订单提示网络错误。
经查看，每次淘宝提交订单后到了付款环节，都会请求203.209.245.77:443, TCP, #3640 🇨🇳 - 10:03:15 - 🇸🇬 SGP 07 - 553 B
怀疑是此条规则冲突导致。
![IMG_0313](https://user-images.githubusercontent.com/125643951/230820976-4d19fc3a-f9c1-4fa6-87e2-4f03c9f66a0a.png)

**Comment by whitezong** [comment]
希望能在 Wechat List 内移除本段。

**Comment by blackmatrix7** [comment]
因为我不是规则实际维护者，不太清楚DOMAIN-KEYWORD,203.209.245.对应哪些IP地址。

如果直接移除怕影响wechat的效果。

建议手动增加一个规则解决这个问题。
