### ISSUE TITLE
知乎屏蔽关键词好像用不了了，打开显示网络错误

### ISSUE THREAD

**Issue by yxFeb3** [blackmatrix7/ios_rule_script#916]
APP版本：8.59.0
![image](https://user-images.githubusercontent.com/88957527/231347905-5e0c838f-10de-4bcc-94c4-3a557901ecb5.png)

**Comment by blackmatrix7** [comment]
实测 8.59.0 (13716) 无异常

建议检查日志和boxjs配置。

**Comment by yxFeb3** [comment]
感谢回复，之前不知道需要在boxjs中配置。再次感谢！
