### ISSUE TITLE
对promotion.aliyun.com的屏蔽会造成在阿里云页面无法显示商品价格

### ISSUE THREAD

**Issue by likecreep** [blackmatrix7/ios_rule_script#918]
规则名称：Advertising_Domain

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising_Domain.list

异常规则：promotion.aliyun.com

问题描述：会导致在阿里云购买商品，比如域名或者服务器时，无法获取到商品价格

调整方案：删除该规则

**Comment by blackmatrix7** [comment]
谢谢反馈，已经移除了，一直没事件处理issue。
