### ISSUE TITLE
可否给quantumultx的规则也添加no-reslove

### ISSUE THREAD

**Issue by 7ongOrz** [blackmatrix7/ios_rule_script#919]
我看其他软件都加上了no-reslove，圈x还没有，可以适配一下圈x的么，感谢！

**Comment by svngxr** [comment]
Quantumult X应该默认就有no-reslove，无需手动添加的

**Comment by 7ongOrz** [comment]
> Quantumult X应该默认就有no-reslove，无需手动添加的

刚试了一下，加了也触发了dns查询，估计不起作用

**Comment by partyspy** [comment]
Same Request
