### ISSUE TITLE
知乎模块不生效

### ISSUE THREAD

**Issue by carlchou00** [blackmatrix7/ios_rule_script#923]
请问下知乎模块为什么不生效呢？
------

脚本名称：
https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zheye

APP版本：
小火箭

客户端名称：
知乎

客户端版本：
8.4.0

**Comment by blackmatrix7** [comment]
小火箭目前没有正式的支持，需要自行解决，或者提供详细的日志。
