### ISSUE TITLE
有关Apple Music的PROCESS-NAME,music 规则中music首字母需大写Music方可起作用

### ISSUE THREAD

**Issue by isLundy** [blackmatrix7/ios_rule_script#924]
规则名称：AppleMusic

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/AppleMusic/AppleMusic.list

异常规则：PROCESS-NAME,music

问题描述：PROCESS-NAME,music 规则中 music 的首字母 “m“ 是大写才可以，小写不起作用!

抓包截图：(相关抓包工具的截图。)
<img width="1960" alt="截屏2023-04-19 21 50 36" src="https://user-images.githubusercontent.com/33220975/233098684-e71ba1c4-3cea-473e-be3c-f5bbe9776c99.png">

调整方案：希望将 PROCESS-NAME,music 改成 PROCESS-NAME,Music

感谢作者的付出～❤️

**Comment by isLundy** [comment]
附加规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Apple/Apple.list

**Comment by blackmatrix7** [comment]
谢谢反馈，已修复，晚些时候更新。
