### ISSUE TITLE
对Direct规则的建议

### ISSUE THREAD

**Issue by svngxr** [blackmatrix7/ios_rule_script#925]
Direct中有
host,fonts.googleapis.com,DIRECT
host,fonts.gstatic.com,DIRECT
似乎不能算是Direct修正规则,因为fonts的域名虽然国内可以访问但敏感时期并不稳定
数据来源中也只有[sve1r](https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Unbreak.list)的规则把fonts的域名计入Direct规则,而其他的数据来源都没有把fonts的域名计入Direct规则
建议从Direct规则中删除fonts的域名

**Comment by PingZi-Wing** [comment]
+1

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，晚些时候更新。
