### ISSUE TITLE
请求添加 appstorrent.ru 到 China_Domain.list

### ISSUE THREAD

**Issue by isLundy** [blackmatrix7/ios_rule_script#926]
规则名称：China

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/China/China_Domain.list

异常规则：

问题描述：

抓包截图：

调整方案：希望增加 appstorrent.ru 到 China_Domain.list 中

感谢作者的辛勤付出～❤️

**Comment by blackmatrix7** [comment]
从域名和解析的结果上看，都不像是国内的，能否详细说下添加的原因？
