### ISSUE TITLE
Clash .txt 规则中，关于 .test.com 这种域名匹配方式，匹配不全的问题

### ISSUE THREAD

**Issue by jklolixxs** [blackmatrix7/ios_rule_script#930]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：所有的Clash .txt 文件

规则链接：所有的Clash .txt 文件

异常规则：在clash中，.test.com 和 *.test.com 一样，不会匹配到 test.com 本身，这会造成比较严重的影响

问题描述：在clash中，.test.com 和 *.test.com 一样，不会匹配到 test.com 本身，这会造成比较严重的影响

抓包截图：(相关抓包工具的截图。)

调整方案：(你希望规则做哪些调整，及其原因。)  希望可以改一下，改成和 .yaml规则一样的格式 +.test.com ，这样就可以解决匹配不到 .test.com 本身的问题了

**Comment by blackmatrix7** [comment]
txt是给stash使用的，从官方给的规则示例来看，没有看到*.的写法。

这是APP 官方给的示例

https://fastly.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/proxy.txt

**Comment by InspoOnU** [comment]
> txt是给stash使用的，从官方给的规则示例来看，没有看到*.的写法。
> 
> 这是APP 官方给的示例
> 
> https://fastly.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/proxy.txt

考虑添加Text格式的Clash规则吗？规则数多的时候Text格式性能更好，而且目前这个txt确实容易让人误会
参考：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider#format

**Comment by Infatuation-Fei** [comment]
> txt是给stash使用的，从官方给的规则示例来看，没有看到*.的写法。
> 
> 这是APP 官方给的示例
> 
> https://fastly.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/proxy.txt

现在Clash也支持text格式的规则集，是否可以考虑添加一下给clash用的text规则集

**Comment by blackmatrix7** [comment]
增加了一个For_Clash.txt，请使用这个。
