### ISSUE TITLE
希望能增加 Duolingo 的独立规则

### ISSUE THREAD

**Issue by bearcolin** [blackmatrix7/ios_rule_script#932]
Duolingo 除了大陆地区功能残废以外，目前还在美国等少部分地区已经开通了 Duolingo Max ，最好是能有独立规则。感谢！

**Comment by ZzzM** [comment]
我的 Quantumult X 目前用的这些规则：

HOST-SUFFIX,duolingo.com,Duolingo
HOST-KEYWORD,duolingo,Duolingo
USER-AGENT,Duolingo*,Duolingo

**Comment by dylenala** [comment]
> 我的 Quantumult X 目前用的这些规则：
> 
> HOST-SUFFIX,duolingo.com,Duolingo HOST-KEYWORD,duolingo,Duolingo USER-AGENT,Duolingo*,Duolingo

手机端上用 代理+规则 可以访问国际版，但是在电脑浏览器上多领国好像有额外的判定方法，用了全局代理也能判定你是大陆用户，赶你回国区。。。

**Comment by lile0319** [comment]
谢谢！我已经收到您发来的邮件，我会尽快阅读，第一时间回复您的邮件。
