### ISSUE TITLE
Lan规则命中raw.githubusercontent.com

### ISSUE THREAD

**Issue by justdoiting** [blackmatrix7/ios_rule_script#933]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Lan

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml

异常规则：raw.githubusercontent.com

问题描述：clash日志显示Lan规则匹配了raw.githubusercontent.com

抓包截图：(相关抓包工具的截图。)
![image](https://user-images.githubusercontent.com/109136320/236420814-6c1ab942-cd04-44d3-8252-651d23c6864d.png)

调整方案：(你希望规则做哪些调整，及其原因。)
移除raw.githubusercontent.com

**Comment by blackmatrix7** [comment]
这个是DNS解析的问题，解析到本地回环地址127.0.0.1了。

不是规则的问题，检查下hosts或者dns设置。

**Comment by justdoiting** [comment]
> 这个是DNS解析的问题，解析到本地回环地址127.0.0.1了。
> 
> 不是规则的问题，检查下hosts或者dns设置。

![image](https://user-images.githubusercontent.com/109136320/236422818-ea12e24d-f939-4899-8fac-9f2d4255a835.png)
删除了就解决了
