### ISSUE TITLE
rule/Clash/WeChat/WeChat.list第21行应该改为 IP-CIDR,43.156.222.0/24

### ISSUE THREAD

**Issue by Flora-air** [blackmatrix7/ios_rule_script#939]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：
Wechat.list

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/WeChat/WeChat.list

异常规则：
DOMAIN-KEYWORD,43.156.222.,DIRECT

问题描述：
在我配置远程规则的时候遇到的，在clash的log中一直显示43.156.222.154（WeChat的出站连接ip）没有match任何规则，然后就去问ChatGPT
<img width="671" alt="image" src="https://github.com/blackmatrix7/ios_rule_script/assets/62434508/a76da5aa-f9b6-49bb-91c9-458cf37911c2">

抓包截图：(相关抓包工具的截图。)
更改之后，可以正常分流了
<img width="663" alt="image" src="https://github.com/blackmatrix7/ios_rule_script/assets/62434508/ff4ae116-a242-4060-8a20-ed1c5a62ac89">

调整方案：(你希望规则做哪些调整，及其原因。)
IP-CIDR,43.156.222.0/24

**Comment by Flora-air** [comment]
翻到了以前的一个issue
在上游规则https://raw.githubusercontent.com/NobyDa/Script/master/Surge/WeChat.list 中，有一个提示🔔（# 请注意，该规则集除 Surge 之外不应该使用 (由于双栈问题且考虑到规则数量，部分子规则写法仅与Surge兼容)）
（猜测是由于clash和surge的编写规则并不通用）

**Comment by Flora-air** [comment]
在surge的规则中 [<DOMAIN-KEYWORD：简单的字符串搜索，只要域名包含子串就会匹配。>](4.3.1 域名规则url https://manual.nssurge.com/book/understanding-surge/cn/#%E8%A7%84%E5%88%99)

在clash的规则中[<DOMAIN-KEYWORD：域名关键字匹配>](url规则编辑 https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html)

而IP-CIDR：IP 段匹配 因此使用IP-CIDR,43.156.222.0/24可能是更符合clash的分流规则

**Comment by Flora-air** [comment]
事情的起因是在Mac上我想从QuantumultX转移到ClashForWindows（[Clash.for.Windows-0.20.23](https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.23/Clash.for.Windows-0.20.23.dmg)以下简称clash）上，一直困扰我没有转移的是WeChat的分流规则，因为weixin转移到wechat之后乱跳ip可能容易封号、添加新好友的时候提示对方为非大陆ip 谨慎防诈之类的，搞定了clash远程配置配置文件之后，在本地尝试对WeChat分流进行reject来测试，发现仍然能正常发送消息，和43.156.222.这个ip段下出站连接的log显示的是match()➡️Final（漏网之鱼），所以就测试了一下。

值的一提的是quantumultx上的[wechat.list](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list)规则是没有问题的，虽然reject之后wechat还能连接发消息，但是把wechat后台划掉之后再打开就真的reject掉了。但是在Mac Clash上就会出现把[wechat.list](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list)规则reject之后还能登陆的离谱的地方，因此做了这个修改[wechat.list](https://raw.githubusercontent.com/Flora-air/ios_rule_script/master/rule/Clash/WeChat/WeChat.list)

**Comment by blackmatrix7** [comment]
谢谢反馈，已处理，稍后更新。
