### ISSUE TITLE
Scholar 万方数据 规则缺失反馈

### ISSUE THREAD

**Issue by Skimige** [blackmatrix7/ios_rule_script#940]
规则名称：Scholar

规则链接：https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Scholar/Scholar.yaml

异常规则：wanfangdata.com.cn

调整方案：添加此 DOMAIN-SUFFIX

**Comment by blackmatrix7** [comment]
谢谢反馈，已添加，稍后更新。
