### ISSUE TITLE
OpenAI 新增检测规则

### ISSUE THREAD

**Issue by missuo** [blackmatrix7/ios_rule_script#947]
在 Developer 中添加 **sentry.io**

**Comment by sch-lda** [comment]
建议直接作为跟踪器Reject了😆

**Comment by missuo** [comment]
> 建议直接作为跟踪器Reject了😆

也可以哈哈哈哈！

**Comment by Moraxyc** [comment]
建议添加这个到openai规则列表

o33249.ingest.sentry.io

**Comment by blackmatrix7** [comment]
谢谢反馈，已补充，稍后更新。
