### ISSUE TITLE
AdGuardSDNSFilter里匹配类型错误

### ISSUE THREAD

**Issue by ameyukisora** [blackmatrix7/ios_rule_script#956]
广告过滤规则语法里的类似于`||example.com^`应该对应clash规则的`DOMAIN-SUFFIX,example.com`而不是`DOMAIN,example.com`，同理AdGuardSDNSFilter_Domain.yaml的
```yaml
payload:
  - 'example.com'
```
也应改为
```yaml
payload:
  - '+.example.com'
```

**Comment by blackmatrix7** [comment]
谢谢反馈，已修正，稍后更新。
