### ISSUE TITLE
关于surge的Chinaip.list建议

### ISSUE THREAD

**Issue by yfue** [blackmatrix7/ios_rule_script#96]
你好，麻烦看看surge的Chinaip.list能不能不写规则类型只写ip，这样或许可以用于DOMAIN-SET类型，减少开销

**Comment by yfue** [comment]
这个不咋好操作😿，先关了

**Comment by blackmatrix7** [comment]
这个可以实现，之前对domain类型的规则，会做一个自动判断，规则数量超过1000条，转为domain-set，对ip类型的规则再做一下判断就可以。

就是不知道domain-set里，能混domain和ip类型的规则吗？

**Comment by yfue** [comment]
这个没有遇到过，试一下。但是按照描述应该是可以的

**Comment by blackmatrix7** [comment]
> 这个没有遇到过，试一下。但是按照描述应该是可以的

我查了下文档，似乎没有提到DOMAIN-SET可以支持IP，你有相关的资料我看看吗？

**Comment by yfue** [comment]
surge作者给的答复是DOMAIN-SET 实际匹配的是主机名，对于使用 IP 直接进行的请求可以匹配。考虑了一下这个不好实现

**Comment by blackmatrix7** [comment]
我实际验证了下，Surge中将IP-CIDR类型写入DOMAIN-SET并不会生效，所以我又把今天半夜自动生成的Domain.list文件删除了，后面在有实际测试能证明有效前都不会再加入。

如果你需要这个文件，可以访问这两个地址，分别对应Surge和Loon。

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/6c5ae782240fb734e6130690a1bd6fc797098ebc/rule/Surge/ChinaIPs/Domain.list

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/6c5ae782240fb734e6130690a1bd6fc797098ebc/rule/Loon/ChinaIPs/Domain.list

不过这两个文件并不会自动更新了。

**Comment by yfue** [comment]
真的麻烦你了，感谢你做的一切🙏🙏
