### ISSUE TITLE
国内云被加入到Global里面了

### ISSUE THREAD

**Issue by MichaelPan1026** [blackmatrix7/ios_rule_script#960]
规则名称：
Global

规则链接：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Global/Global.list
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Global/Global_Classical.yaml
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Global/Global_Domain.txt
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Global/Global_Domain.yaml

异常规则：
```
  - DOMAIN-SUFFIX,st.dl.bscstorage.net
  - DOMAIN-SUFFIX,st.dl.eccdnx.com
  - DOMAIN-SUFFIX,st.dl.pinyuncloud.com

```

问题描述：
国内云被加入到Global里面了

调整方案：去除

**Comment by blackmatrix7** [comment]
谢谢反馈，已移除，稍后更新。
