### ISSUE TITLE
Apple News规则不全，少两条规则。

### ISSUE THREAD

**Issue by li2282231** [blackmatrix7/ios_rule_script#962]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Apple News

规则链接：Apple News

异常规则：Apple News

问题描述：目前现有的Apple News规则不全面，我这边测试地图App可以成功去掉高德地图，可以正常开启Apple News，但是显示有问题，有些新闻内容不显示，显示成Content No Longer Available，另外Apple News小组件也无法加载。

抓包截图：我通过merlin clash查看得知，打开Apple News后会加载两项域名，而这两项域名目前的规则里没有包含。
                  即：DOMAIN-SUFFIX,apple.com和IP-CIDR,17.0.0.0/8
                  我设置这两个域名走代理以后，就可以正常访问Apple News了，另外小组件也显示正常。
调整方案：希望加入这两项域名到目前的规则里面，以便可以正常使用Apple News。

**Comment by li2282231** [comment]
修正一个问题，经过我的测试，apple.com这条规则不需要；但IP-CIDR,17.0.0.0/8是一定要走代理，不然Apple News打开后无任何新闻显示，至少我这边的网络环境下是这样的。

**Comment by li2282231** [comment]
发现设置IP-CIDR,17.0.0.0/8强制走代理有一个很大的副作用，就是会阻挡Mac和iPhone的接续互通，即无法通过Mac打电话，而且iPhone正在进行的通话也无法无缝衔接到Mac上；但是IP-CIDR,17.0.0.0/8不设置走代理Apple News则无法浏览，二者似乎冲突，请问各路大神有办法既能正常浏览Apple News也能正常用Mac打电话么？

**Comment by blackmatrix7** [comment]
如果副作用太大，则不建议直接加入，建议手动维护下配置文件的规则。
