### ISSUE TITLE
Mail 规则缺少 Yahoo 的 smtp 规则

### ISSUE THREAD

**Issue by yuehun1224** [blackmatrix7/ios_rule_script#973]
规则名称： Mail

规则链接： https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Mail/Mail.list

异常规则：

问题描述： 缺少 Yahoo 的 smtp 规则。

抓包截图：(相关抓包工具的截图。)

调整方案： 增加规则 DOMAIN,apple.smtp.mail.yahoo.com

同时，为了整洁和更好的匹配，建议将其 imap 规则也改为 DOMAIN,apple.imap.mail.yahoo.com

**Comment by blackmatrix7** [comment]
谢谢反馈，已补充和调整，稍后更新。
