### ISSUE TITLE
183.131.48.0这个IP为何会在Global规则里？

### ISSUE THREAD

**Issue by LzNOHentai** [blackmatrix7/ios_rule_script#975]
部分国内域名偶尔会解析到这个IP，海外节点似乎连不上。经过查询这个IP也是属于国内的，不明白为何会在Global规则里。
https://dnslytics.com/ip/183.131.48.0-183.131.63.255

**Comment by blackmatrix7** [comment]
你好，规则里没有搜索到这个IP，可能是上游已移除。

如果还是出现，麻烦把触发的具体规则发我一下。

**Comment by LzNOHentai** [comment]
> 你好，规则里没有搜索到这个IP，可能是上游已移除。
> 
> 如果还是出现，麻烦把触发的具体规则发我一下。
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Global/Global_Classical.yaml

- IP-CIDR,183.131.48.0/20
