### ISSUE TITLE
no-resolve相关

### ISSUE THREAD

**Issue by svngxr** [blackmatrix7/ios_rule_script#979]
在Clash for Windows的版本高于0.20.23后，使用类似
  - RULE-SET, Direct, DIRECT, no-resolve
的规则中no-resolve参数似乎不再生效，导致IP-CIDR类规则无法添加no-resolve，使用外部规则集会造成多余的本地DNS请求：
rules:
  - RULE-SET, Direct, DIRECT, no-resolve
  - RULE-SET, Advertising, REJECT, no-resolve
  - RULE-SET, Global, 🌏 Global, no-resolve
  - RULE-SET, China, DIRECT, no-resolve
  - GEOIP, CN, DIRECT
  - MATCH, Final
使用类似的规则在log中可以观察到大量的本地DNS请求，即便已经启用fake-ip

https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list 就是IP-CIDR类带有no-resolve的，但不是yaml格式无法添加到clash中

能否在Clash相关的规则中创建一个版本，将IP-CIDR类的规则统一添加添加no-resolve

非常感谢

**Comment by fiiir** [comment]
经过本地抽样排查，发现在用clash规则中，AdvertisingTest.yaml 和 BiliBili.yaml 同样存在该问题

经过对 /master/rule/Clash/*/*.yaml 抽样（不包含*_Classical.yaml、不包含*_Domain.yaml）排查，猜测 /master/rule/Clash/ 下提到的所有Clash规则均存在该问题
即：上述提到的yaml文件，所有 IP-CIDR类 和 IP-CIDR6类 规则都不含有“, no-resolve”后缀，会触发大量不必要的“dns解析请求”

----------------

建议沿用Surge规则文件命名规则，生成两个不同的yaml
一个内容无“, no-resolve”后缀
一个内容含“, no-resolve”后缀

即：现有 /master/rule/Clash/*/*.yaml（不包含*_Classical.yaml、不包含*_Domain.yaml）
改名为 /master/rule/Clash/*/*_Resolve.yaml（不包含*_Classical.yaml、不包含*_Domain.yaml）

重新生成/master/rule/Clash/*/*.yaml，
对 IP-CIDR类 和 IP-CIDR6类 规则，加上“, no-resolve”后缀

这样的好处是：正在使用中的clash规则，下次更新本地规则文件时，都会更新为有“, no-resolve”后缀的版本，影响最小

**Comment by blackmatrix7** [comment]
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Classical_No_Resolve.yaml

为了不影响之前的文件，默认还是不带no-resolve的，然后独立了一个带no-resolve的链接。
