### ISSUE TITLE
关于圈X的google.list与proxy.list

### ISSUE THREAD

**Issue by yfue** [blackmatrix7/ios_rule_script#98]
你好，今天在用圈X时google.list与proxy.list使用不同的策略组，但是google相关的链接还是走了proxy的策略，初步判断是proxy.list内与Google相关的策略优先级高于google的；这个问题能不能解决，第一次弄圈X，麻烦了

**Comment by blackmatrix7** [comment]
我的理解是规则文件间没有优先级，优先级和你配置文件中不同规则文件的排序有关系。更具体的你可以到相关的群组问一下，我这里无法提供任何关于科学上网之类软件的使用支持。
