### ISSUE TITLE
OpenAI规则在QuantumultX中被其他规则屏蔽

### ISSUE THREAD

**Issue by smilingpoplar** [blackmatrix7/ios_rule_script#980]
规则名称：OpenAI

规则链接：https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/QuantumultX/OpenAI/OpenAI.list

问题描述：
在QuantumultX中，HOST-SUFFIX优先级高于HOST-KEYWORD，当remote规则中存在openai的HOST-SUFFIX规则时，本规则即使放最前面也失效。

调整方案：
加上规则`DOMAIN-SUFFIX,openai.com,OpenAI`

**Comment by svngxr** [comment]
可可以考虑关闭filter match optimization

**Comment by smilingpoplar** [comment]
> 可可以考虑关闭filter match optimization

改这quantx设置也是种办法
