### ISSUE TITLE
建议亚马逊分CN和非CN

### ISSUE THREAD

**Issue by lmkyl** [blackmatrix7/ios_rule_script#984]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

规则仅是特定服务域名和IP地址的集合，请使用**中华人民共和国合法的网络出入口信道**访问相关服务。

------

反馈前请先确认：

1. 请勿涉及政治、成人等敏感或非法内容
2. 分流规则的更新需要等待次日凌晨生效
3. 仅接受规则引起异常的反馈
4. 已自行抓包明确引起异常的规则
5. 不规范填写的Issue可能不会得到任何回复

规则名称：Amazon

规则链接：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Amazon/Amazon.list

异常规则：

问题描述：Proxy模式下Amazon客户端无法访问国内内容，Direct模式下无法访问国外

抓包截图：似乎无需抓包

调整方案：将CN和非CN独立为各自的list，CN选择Direct，非CN选择Proxy

**Comment by LzNOHentai** [comment]
同意，不过现行规则里CN相关少了一条域名：ssl-images-amazon.cn
如果手动分流的话记得加进去。

**Comment by blackmatrix7** [comment]
已处理，晚些时候更新。
