### ISSUE TITLE
大佬可以更新下stash的blued规则吗

### ISSUE THREAD

**Issue by locharliea92** [blackmatrix7/ios_rule_script#986]
![image](https://github.com/blackmatrix7/ios_rule_script/assets/61534482/92177dfd-67a1-478a-be9c-de1fc2c4f1f5) 旧的匹配不上了 最新软件又多了两个域名都走的兜底 blued.cdn-gw-dv.net，blued.gw-dv.net这两个

**Comment by blackmatrix7** [comment]
谢谢反馈，已加入，晚些时候更新。
