### ISSUE TITLE
大佬，是否可以增加claude分流规则

### ISSUE THREAD

**Issue by FAIING** [blackmatrix7/ios_rule_script#989]
最近claude出来了，用了一些懒人分流规则，打不开claude，必须要选择特定的节点，看大佬能不能写个claude分流规则

**Comment by hunduncn** [comment]
同球

**Comment by Stevenzc888** [comment]
复议

**Comment by curtisrecords** [comment]
![image](https://github.com/blackmatrix7/ios_rule_script/assets/71839629/c62c1717-5f9b-4842-88f7-cfd91459a56d)
已经有了

**Comment by XCJYO** [comment]
> ![image](https://user-images.githubusercontent.com/71839629/257675245-c62c1717-5f9b-4842-88f7-cfd91459a56d.png) 已经有了

大佬,这种是怎么做出来的?访问claude会建立很多链接,如何判断每个链接要走什么规则?要用什么工具抓取?

**Comment by blackmatrix7** [comment]
> > ![image](https://user-images.githubusercontent.com/71839629/257675245-c62c1717-5f9b-4842-88f7-cfd91459a56d.png) 已经有了
> 
> 大佬,这种是怎么做出来的?访问claude会建立很多链接,如何判断每个链接要走什么规则?要用什么工具抓取?

实不相瞒，浏览器F12里找的域名。

我并不用这个AI，所以不能确保是抓全了。

只能有问题再反馈，我再补充。

**Comment by XCJYO** [comment]
懂了,多谢,我还以为有某种工具可以直接保证抓全了

**Comment by lanytcc** [comment]
2024/10/31
@blackmatrix7 缺一个`claudeusercontent.com`
