### ISSUE TITLE
rewrite/Advertising 数据来源补充

### ISSUE THREAD

**Issue by svngxr** [blackmatrix7/ios_rule_script#992]
第一个主要是微信小程序和一些常用app
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/cleanup.snippet

第二个莫离的合集
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/cleanup.snippet

第三个奇心的合集
https://raw.githubusercontent.com/zwf234/rules/master/QuantumultX/tailadv.conf

第四个是墨鱼的微信小程序
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Applet.conf

可以考虑为rewrite/Advertising增加以上数据来源
非常感谢

**Comment by blackmatrix7** [comment]
第一个和第二个是一样的，可能是写错了。

全部都已经加入了，不过只会抓取reject类型的规则，而不会抓取脚本类型的规则。

主要考虑到脚本的内容不可控，可能会有安全风险（当然，不是指上面的脚本有问题，而是尽量规避此类的风险）。

如果需要脚本处理，请自行添加。

稍后更新。
