### ISSUE TITLE
哲也同学，兴趣页没有过滤视频

### ISSUE THREAD

**Issue by Sheldontao** [blackmatrix7/ios_rule_script#996]
不提供任何关于客户端的配置、使用等帮助，此类问题请通过搜索引擎解决，相关Issues将直接关闭甚至删除。

------

反馈前请先确认：

1. 已使用空白配置文件复现此问题
2. 在issues中找不到类似问题
3. 请勿涉及任何非法内容
4. 不规范填写的Issue可能不会得到任何回复

脚本名称：哲也同学

APP版本：8.4.0(8126)

客户端名称：qx

客户端版本：1.3.0-781

问题描述：

因为知乎已沦落为一个social media，所以不想看首页推荐了，发现app版本还保留了不同兴趣页面，但是发现（比如这里—科学页）页面仍然有食品广告，虽然都是很久之前的（21年左右）

![image](https://github.com/blackmatrix7/ios_rule_script/assets/36765652/c9f01fad-60ca-4324-add8-92c5c6d75f98)

Js：

State:			Released
Request:		None
Description:		 	
❚  script-response-body
❚  https://www.zhihu.com/appview/v2/answer/3099268397?no_image=false&X-SUGER=SURGQT0yQ0RCQzE2Ni0zRUZELTRBNjItNERFMi0xNDQxQzhDMUUyNzg7VURJRD1BTUJmdU1wcVBCTkxCVUhCVEdTWmltaDlrM0czS1RVa3U2Zz07RElTSz0xMjc4NzA5ODAwOTY7TUVNTz04MTQ0MTQyMzM2O01PREVMPUQ1M2dBUDtTQlRTPTE2OTA4NTY2MzA7U1VUUz0xNjkwNDc3NTY1LjQ1MjMzODtETj04NjdFNTdCRDA2MkM3MTY5OTk1REMwM0NDMDU0MUMxOTtPUD3kuK3lm73np7vliqg7Q09VTlRSWT1ISztMQU5HPWVuLUhLO1RaPTI4ODAwO01BQ0hJTkU9aVBob25lMTMsMjtBTElTQlRTPTE2OTA4NTY2MzAuNTkwMTk4O0FMSVNVVFM9MTYxNjI3ODIxMS41NTY1OTEyMDg7Q0FJRD0yODRlZmUyN2VkMjY5ZGFiZmU2Njg2ZTk3NTFmMWJiMl8yMDIzMDMzMHxjZjdkOTZiMzU5MDc0NWEwOTc2YWJlYjJlNGZlMmU5OV8yMDIyMDExMTtYLUFELUlQVjQ9MTIwLjE5Ny4xNTYuMzE%3D&X-AD=canvas_version%3Av%3D5.1%3Bsetting%3Acad%3D0&follow_guide=1&is_enable_double_click_voteup=1&show_section_comment=true&preload=prefetch&entry=preload-topstory&omni=1&ab_signature=CiRBTUJmdU1wcVBCTkxCVUhCVEdTWmltaDlrM0czS1RVa3U2Zz0SIDg1ODQzNDNhZDRiMjJjYzViZGYxNDAwZTQ2YWU5MGVhGg8IAhIFOC40LjAaBDgxMjY%3D
❚  ^https?:\/\/www\.zhihu\.com\/appview\/v2\/answer\/.*(entry=(?!(preload-topstory|preload-search|preload-subscription)))? 
❚  https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
Logs:			 	
❚  [INFO] [哲也同学]
SCRIPT COMPLETED: 0.012 S.

已使用空白配置文件验证：是/否

**Comment by blackmatrix7** [comment]
仔细看了下，这个不是广告视频。

需要在boxjs中禁止视频内容。
