### ISSUE TITLE
Clash的规则类型能否加增domain类型

### ISSUE THREAD

**Issue by mobilefish** [blackmatrix7/ios_rule_script#997]
Clash的规则类型能否加增domain类型，例如：behavior: "domain"， 个人感觉clash在使用behavior: "domain"后，内存占用率会低一些。

例如：
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"

**Comment by blackmatrix7** [comment]
一直都是有的

https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Proxy/Proxy_Domain.yaml

部分规则如果没有，是因为domain类型的规则数量过少，不足以单独开一个文件。
